### ISSUE TITLE
Exclamation mark in search make people think there is a bug

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1008]
In the past couple of weeks we received feedback from 2 users who thought something was wrong with the search, after their performing a search with an exclamation mark. Below are the copy of the messages.

I remember some users also reporting related issues on the Wall, but I don't have the links to the Wall messages right now.

---

**1) Interesting bug!**

> Hi all, 
> 
> It seems that searching for "not again!" produces an error, but typing "not again" goes through just fine.

**2) errore**

> Too often, an error occured while performing the search to me. What is wrong?

// After asking more details:

> When I want search the following fraze, if it exists, I receive a "Search error". Now the fraze:
> 
> Achte nicht bloß auf das, was andere tun, 
> sondern auch auf das, was sie unterlassen!

**Comment by ckjpn** [comment]
If there is a setting in Sphinx Search to allow disabling the ! and ? special purposes, perhaps it would be a good idea to do so, since the Tatoeba Project is all about sentences and people would expect that the search engine would allow these to be used as expected, and similar to how Google works.

* Why get rid of ! *
The ! function is exactly the same as using - (minus), in Sphinx, I'm fairly certain.

* Why get rid of ? *
The the single character ? wildcard is probably very seldom used, and even if used is likely used mostly by people who are geeky enough to easily be able to download the data and do such searches offline.
It's also possible to sort of simulate this function with the "or".
So instead of "whe?ever", you could search for "whenever|wherever" if you wanted to. Or instead of "??eve?", you could search for "clever|eleven|peeves|uneven".


The * wildcard is unlikely to cause any problems, so I think it would be OK to leave it as is.


If it's not possible to change this with a setting in Sphinx, then perhaps you could just filter out the ! and the ? before searches are made.

**Comment by alanfgh** [comment]
Rather than remove the option of a single-letter wildcard altogether, I would support using another punctuation symbol that does not have a special meaning in Sphinx keyword search. From a quick look at the documentation and a little experimentation, it seems that % or _ would work. You could convert it to a ? (after stripping existing ? characters, of course) before sending it to Sphinx.

Of course, we would have to remember to update the "Advanced search" wiki page.

**Comment by ckjpn** [comment]
The percent sign (%) is used in some sentences, so I don't think it would be a good choice.

**Comment by jiru** [comment]
The percent sign is already used as an alias of the question mark in Sphinx. In other words, whe?ever and whe%ever yield the same results. As CK said, the exclamation mark is also an alias of the minus sign. So I think a reasonable option would be to just strip question and exclamation marks from the search queries.

**Comment by sacredceltic** [comment]
+1

**Comment by alanfgh** [comment]
> The percent sign (%) is used in some sentences, so I don't think it would
be a good choice.

At the moment, no one can conduct a search that finds sentences that
contain the percent sign, and no one has complained about that. If we
wanted to make literal percent signs findable, we'd have to make more
substantial changes.

**Comment by ckjpn** [comment]
>I think a reasonable option would be to just strip question and exclamation marks from the search queries.

I agree with jiru on this.  LIke alanfgh says, no one has complained about the lack of being able to search with the % sign, so using it for how the use of ? is currently explained in the Wiki is reasonable, I think.

**Comment by jiru** [comment]
I solved this bug in #1445. The exclamation mark is now simply ignored when used in an inappropriate place, such as the end of the query.
