### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by boracasli4** [Tatoeba/tatoeba2#1025]
I'm writing my complaint about your behaviours here since I can't email you. Why am I blocked? Why do you block me everytime I register? Please answer. I wouldn't register again if you didn't block my previous account.

By the way, you even delete well-written sentences by non-natives. Deleting others' sentences for no reason doesn't make you better administrators. Please understand and tell me when you will accept me on Tatoeba again?

There are many people who contribute sentences in many languages on Tatoeba, but I'm the only one among them who always gets blocked by you. Learning languages is my passion. You don't even delete badly-written sentences, but you delete every sentence I own, regardless of being well-written or not.

I'm no longer a 12-year old. You should understand this. I'm almost eighteen. I didn't violate the terms of service when I was between fifteen and seventeen

I don't care if you take this complaint down or not, but please stop insulting me and other people. Tatoeba was, is and will be better with more contributors, not with more authoritarian administrators. We're always treated as we were slaves by the bourgeois.

Was my only fault contributing in many languages or being a language addict? I'll stop writing to you if you allow me again to contribute sentences. Thank you if you will reply.

**Comment by trang** [comment]
@boracasli4, the GitHub issues is not the right place for this complaint. You should instead write to community-admins@tatoeba.org. If you care at all, here are our guidelines for submitting issues:
https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-issues

I will answer your questions this time only.

> Why am I blocked? Why do you block me everytime I register?

Your past behavior has led us to conclude that you were causing too much trouble within the project and within the community. 

1. Many people reported that your contributions contained too many mistakes or didn't make any sense. It would have been fine if you would have shown that you could improve, but there was no real sign of improvement. You were being uncooperative too many times.
2. You have been insulting people.
3. You have been spamming a lot.

All of this made many members of the community very, very annoyed.

I think you have a valid point however, by saying that suspending you over and over again, and deleting your sentences, is counter-productive. I don't like it either, but the other solutions that we currently have do not look much more appealing.

> Please understand and tell me when you will accept me on Tatoeba again?

Probably not before at least another 2-3 years. At this point it doesn't matter if you suddenly become a saint and a role model for the next generation of Taylor Swift's fans. Your past and recent behavior showed us that we cannot trust you.

We will have to design and implement the necessary features so that bad contributions and bad behavior does not have too much of a negative impact on the project and on the community. We are busy with many other topics though, that's why it will probably take at least a few years. I hope you can be patient.

> please stop insulting me and other people

If people from Tatoeba have been insulting you, feel free to report them to community-admins@tatoeba.org. As far as I know, you were, for the major part, the one insulting other Tatoeba members.

**Comment by boracasli4** [comment]
By the way, will you block me on Twitter? (@boracasli)

**Comment by boracasli4** [comment]
First of all, I would like to get blocked by you on Twitter

**Comment by boracasli4** [comment]
Please block me on twitter
