### ISSUE TITLE
User can send private message to him/her self

### ISSUE THREAD

**Issue by achaitanyasai** [Tatoeba/tatoeba2#1033]
It seems like an user can send a private message to him/her self. Is this intentional. If it's not, I would like to work on this.

**Comment by trang** [comment]
@achaitanyasai, can you explain what is the problem of sending a private message to yourself? If there is no actual problem, I would just close this issue because you might be removing a behavior that other people rely on.

I personally don't send PM to myself on Tatoeba, but I sometimes send emails to myself. So I can imagine that some people may want to send PM's to themselves, for whatever reason.

In case you would like to report more issues in the future, we have guidelines for submitting issues:
https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-issues
