### ISSUE TITLE
use "googleoff: index" tag to mark parts of the page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#107]
From sysko and CK:

Note that we may actually want to have the logs part indexed

For very simple reason that people may find it by typing the wrong version in google. So that we will appear on that typo keywords

Otherwise you are right that not indexing the other ¨menu¨ etc.  part of pages may be good idea.

On 2013年09月16日 07:13, CK wrote:
> 1.   If you use this code, then google won't index the part of the page with the already corrected errors. (the Logs - If you put the "logs" part of the page between these tags)
>
> 
>
> <p>This (X)HTML content will NOT be indexed by Google.</p>
>
> <!--googleon: index>
>
>
>
> 2. If you put these tags around everything, but just the main sentence and its translations, then Google Custom Search would be very effective.
>
> https://www.google.com/cse/publicurl?cx=006161583699950568705:ib23smm3ntq
>
>
>
> 3. This shouldn't affect what's in the TITLE and META Data getting indexed.

**Comment by RyckRichards** [comment]
Requested by  Guybrush88 on the 1st Tatoeba day (2015-06-06):
► https://tatoeba.org/eng/wall/show_message/23017#message_23017

**Comment by ckjpn** [comment]
This is set to "priority:low", but should be very easy to do.

**Comment by jiru** [comment]
I’m not sure it’s a good idea to generally prevent indexing of other parts than sentence pages. It seems you’re making the assumption that people won’t be searching for this, but I don’t think it’s true. What if I want to find back a particular comment of my own, for instance?

Besides, it seems to me that Google is smart enough to focus the search on the sentence rather than the other parts of the page (likely because it’s in the title and description). I’ve been trying to look up keywords like comments, tags, logs, good practices on that Google Custom Search link, and they all return relevant results. (About "good practices": note that Tatoeba only contain two sentences including the words "good practices", so only the first results are relevant.)

As always, I would like to know what’s the original problem that pushed you to suggest that enhancement.

**Comment by trang** [comment]
I'm planning to close this issue because it is unclear what problem we would solve by doing this and what parts of which pages we should exclude from Google indexation.
