### ISSUE TITLE
Arabic (Modern Standard) (arb)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1079]
- Language name: Arabic (Modern Standard)
- Language info: https://en.wikipedia.org/wiki/Modern_Standard_Arabic
- ISO 639-3 code: arb
- Public List:https://tatoeba.org/eng/sentences_lists/show/5866
- Icon: http://imgur.com/YGZ7XZF
- Requested by: https://tatoeba.org/eng/user/profile/cueyayotl
# 

[for dev.tatoeba.org]
CALL add_new_language('arb', 4231);

[for tatoeba.org]
CALL add_new_language('arb', 5866);

http://dev.tatoeba.org/eng/sentences_lists/show/4231

**Comment by damascene** [comment]
Could you please explain what is the reason behind creating this language? and how does it differ from the original Arabic (ara)?

**Comment by damascene** [comment]
See discussion in bug #1084

**Comment by trang** [comment]
@damascene we are currently considering removing `ara` to replace it with `arb`. You can see the discussion in the comments on the commit: https://github.com/Tatoeba/tatoeba2/commit/66c544d483915f3591a2ccbf46af4cd66dc9bc03#comments

**Comment by trang** [comment]
There's an alternative we could consider, and that's the only viable one I can think of, which is that for macrolanguages (like Arabic), we establish a new rule saying that when a language is considered to be part of a macrolanguage, then we only support the macrolanguage. The individual languages that members of the macrolanguage are handled with tags.

Concretely, in the case of Arabic, this means we would only have one Arabic language (code `ara`), and all the sentences that we currently have in the following languages would be moved to `ara` and tagged with their corresponding ISO code:
* [Algerian Arabic](https://tatoeba.org/eng/sentences/show_all_in/arq/none/none/indifferent) - tag `arg`
* [Egyptian Arabic](https://tatoeba.org/eng/sentences/show_all_in/arz/none/none/indifferent) - tag `arz`
* [Iraqi Arabic](https://tatoeba.org/eng/sentences/show_all_in/acm/none/none/indifferent) - tag `acm`
* [North Levantine Arabic](https://tatoeba.org/eng/sentences/show_all_in/apc/none/none/indifferent) - tag `apc`
* [Moroccan Arabic](https://tatoeba.org/eng/sentences/show_all_in/ary/none/none/indifferent) - tag `ary`

And any request to add a [language that is a member of the Arabic macrolanguage](http://www-01.sil.org/iso639-3/documentation.asp?id=ara) will be rejected. So Gulf Arabic would be rejected and Standard Modern Arabic would be rejected as well. The sentences will have to be added under the language "Arabic" (ara).

But in order to do this, we would need to make sure that each individual language that is part of a macrolanguage doesn't really need a category in its own. For instance in the case of Arabic:
- When someone wants to contribute let's say in Algerian Arabic, will they be fine contributing under the Arabic language, or will they protest because they consider Algerian Arabic is a different language from Arabic?
- When someone searches sentences in Arabic, is it fine that they find not only sentences in Standard Modern Arabic, but also sentences in the other Arabic languages? Or is it going to create confusion to have all these languages mixed together?

We would have to figure out the answers not only for Arabic but for all the macrolanguages that are listed in the ISO 639-3 classification.

**Comment by damascene** [comment]
I looked at some of those so called languages, which are just slangs. I do not think you should add them to the Arabic (ara) as I see there are few sentences in them. They are definitely slangs for the ara and people should not find them when searching in Arabic.

They are not real languages and they do not have any grammars and I think there are very few books (if any) are written in them beside they are not used in official communications.

So what you are doing by allowing such languages is just making Tatoeba messy. these language are not recognized by any official Arabic institute or country.

I suggest you add one language that is called **Arabic Slang** or **Arabic Spoken** and you can use the tags in it as you suggested and to group all those local slangs or dialects in it.

**Comment by trang** [comment]
Adding a language called "Arabic Slang" or "Arabic Spoken" is not a viable solution and doesn't make Tatoeba less messy. If we start doing this, what would stop us from having "English Slang", "German Slang", "Spanish Slang", etc?

If the sentences in Algerian Arabic, Egyptian Arabic, etc, cannot be merged into "Arabic", then they'll remain where they currently are.

**Comment by trang** [comment]
@RyckRichards, since the decision is not to add `arb` as a new language, but to replace `ara` with `arb`, I'm going to revert your commit (https://github.com/Tatoeba/tatoeba2/commit/66c544d483915f3591a2ccbf46af4cd66dc9bc03).

**Comment by damascene** [comment]
@trang Could you please do not modify Arabic language? Keep it as it's unless non Arabs are the ones who are going to do the decisions for us.

**Comment by trang** [comment]
@damascene, only the code will be modified from `ara` to `arb`. The name will remain as `Arabic`. The sentences that are currently under Arabic will remain under Arabic.

**Comment by damascene** [comment]
@trang I know, I prefer you stick to the 639-2 codes https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes which state (ar - ara)
Apparently there is much debate on the 639-3
http://linguistics.stackexchange.com/questions/17232/why-the-iso-639-3-has-many-languages-for-arabic-while-it-has-one-for-english

I even contacted SIL and the responded with the normal answer that Arabs can not understand each other if they speak in their own languages which is far from true. They did not response to my replay.

**Comment by trang** [comment]
@damascene, we've never followed the ISO 639-2 classification, therefore sticking to it is not the right way to say it. We're not going to mix 639-2 and 639-3. If we're following half of a standard and half of another, then we might as well create our own standard (which is not happening anytime soon).

The reason why Arabic is currently under the code `ara` in Tatoeba is simply because back when we decided to use ISO 639-3, several years ago, we didn't know exactly which code to take. So this is the result of our lack of knowledge back then, not the result of a deliberate choice that we made. And as long as we keep the code `ara`, we will be inconsistent.

That being said, I'm not going to modify the code itself right now because it leads to some breaking changes I'd like to take more time to evaluate. But you have to understand that sooner or later, if we choose to continue to stick with ISO 639-3 and if the SIL does not decide to change their classification for Arabic, we will change the code `ara` to `arb`.

There will be a lot of debate on any language classification you will find out there. So the fact that the ISO 639-3 is being criticized by some people is not going to be a strong argument for us to switch to another classification.

**Comment by loolmeh** [comment]
> That being said, I'm not going to modify the code itself right now because it leads to some breaking changes I'd like to take more time to evaluate. But you have to understand that sooner or later, if we choose to continue to stick with ISO 639-3 and if the SIL does not decide to change their classification for Arabic, we will change the code ara to arb.

SIL is within mainstream linguistics on this, it's not a minority position. No need for appeasement here.
