### ISSUE TITLE
Chinese (Jin) (cjy)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1089]
* Language name: Chinese (Jin)
* Language info: https://en.wikipedia.org/wiki/Jin_Chinese
* ISO 639-3 code: cjy
* Public List: https://tatoeba.org/eng/sentences_lists/show/5982
* Icon: http://imgur.com/hBs1Nfk
* Requested by: https://tatoeba.org/eng/user/profile/cueyayotl

=========================================

[for dev.tatoeba.org]
CALL add_new_language('cjy', 4238);

[for tatoeba.org]
CALL add_new_language('cjy', 5982);

http://dev.tatoeba.org/eng/sentences_lists/show/4238

**Comment by trang** [comment]
Are we sure we want to name this `Chinese (Jin)` rather than `Jin Chinese`? 
Also, from the [SIL's page](http://www-01.sil.org/iso639-3/documentation.asp?id=cjy), the name is `Jinyu Chinese`, why do we choose `Jin` instead?

**Comment by cueyayotl** [comment]
Well, as for Chinese languages, I strongly suggest they be in the "Chinese (xxx)" format. If we manage to get native speakers of Jin Chinese, they will more likely not be looking for their variety of Chinese, but rather, just Chinese (probably even thinking that only Mandarin is allowed). When they find Chinese, but notice an option for "Chinese (Jin)" [or "Chinese (Hakka)", "Chinese (Min Nan)", etc.], it would probably be only then that they realize that their 方言 (fāngyán, literally "dialect") is also permitted on Tatoeba.

As for "Jin" rather than "Jinyu", the "-yu" just means "language" and seems to me somewhat redundant. This issue is always present in translations of East Asian geographical terms: do you call the Japanese mountain "Mt. Fujisan" or "Mt. Fuji" ("-san" means mountain in Japanese); it was called Mt. Fujisan in English for a long time until the last few decades. As there will always be people who make the case for either "Jin" or "Jinyu", and argue against the other, I suppose it would be okay to use either.
