### ISSUE TITLE
Add Sort by Last Updated for Lists

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1100]
This would be useful, but perhaps not worth doing if it is difficult to do.

## The Feature

* Have the option to sort lists in the order that the most recent addition was added.

## The Reasons

* This would allow people to access this URL, for example, to see which members have been most recently adding audio files.

https://tatoeba.org/eng/sentences_lists/of_user/CK/audio

* This would also help members see which public lists are being updated and push the old public lists not being updated to the bottom of the list.

* Perhaps, this would also help members find their own recently-used private lists, and with a reverse sort, be able to find which lists of theirs that they may want to consider deleting.

**Comment by dispyfree** [comment]
I see two different solutions to this problem:

1) explicitly keeping track of this information and storing it in a special field in the database. This will be more cumbersome as it must be kept up to date manually.
 
2) using virtual fields with CakePHP (introduced in CakePHP 1.3). This is very easy to implement; virtual fields can even be created on the fly. As it is computationally expensive to query the information each time, it is probably advisable to only include this information if the user actually sorts by it. 
Having said that, using the on-the-fly method, sorting will actually influence the fields which are shown in the table. 

What would you prefer?

**Comment by trang** [comment]
I think virtual fields won't work there. If I understand properly, virtual fields are based on fields from the same model. In our case, we have the data for the lists in `sentences_lists`, and the date of when sentences are added in `sentences_sentences_lists`.

As for the update of the new field, it could be handled by a MySQL trigger, no?

**Comment by dispyfree** [comment]
Virtual fields are basically arbitrary SQL expressions - that includes subqueries.

MySQL triggers are an option too - so adding a new field for that information and updating it using triggers is the preferred option? As long as this field is not indexed, the trigger should virtually have no overhead.

**Comment by trang** [comment]
> so adding a new field for that information and updating it using triggers is the preferred option?

Yes. I have no preferences regarding the trigger, but we for sure want to avoid subqueries and joins as much as possible, for performance reasons.

**Comment by trang** [comment]
Changes to do on the UI:

![lists](https://cloud.githubusercontent.com/assets/221850/15226698/17dbe11a-1884-11e6-8e1c-48be3c3ffdae.png)


1. We have to add a link that the user can click to sort the sentences. For the label, we can use `Last updated`. Technically, we should not only take into account sentences that are added but also sentences that are removed. If the latest sentence was added 2 months ago, but then 2 days ago a sentence was removed from the list, then the date of "last updated" is 2 days ago and not 2 months ago.

2. Because we have a new sort option that is also a date, the date that is currently displayed may become ambiguous. So we will need to move it next to "created by", to make it more obvious that it's the date of creation and not the date of last update: `created by {user}, {date}.`.
Then we can add next to it: `Last updated: {date}`, or we can use the previous "creation date" column to display the "last updated" date. Not sure what is best.

**Comment by ckjpn** [comment]
> or we can use the previous "creation date" column to display the "last updated" date. Not sure what is best.

I'm not sure which is better, either, but in the current creation date column seem like it might be good, since people could scan down that column more easily to see the "last updated" info.

Perhaps like this.

"Last updated on 2016-03-22"
or
"Updated: 2016-03-22"

I like the shorter version better myself.

**Comment by trang** [comment]
Let's align it like this:

![screenshot_2](https://cloud.githubusercontent.com/assets/221850/15268129/eda05b86-19d4-11e6-8472-a4ac7bbf401f.png)

**Comment by ckjpn** [comment]
I assume that you are only going to put the date and not label it. However, it you are planning to add a label, instead of "Created date", it would be better to say "Date created:"


Date created: 2016-01-13  (probably not needed since the date is right next to the "Created by ...." message.

Last updated: 2016-05-14

**Comment by dispyfree** [comment]
![updated_result](https://cloud.githubusercontent.com/assets/1538146/15376890/757d5168-1d8a-11e6-8ec7-4a1a82d8dfe6.png)
[patch.txt](https://github.com/Tatoeba/tatoeba2/files/271520/patch.txt)

I wanted to avoid repetitive clutter, therefore I didn't include a label for "created" (as suggested by @ckjpn ) and put the "last updated" as a col caption on top.

**Comment by dispyfree** [comment]
There's a new pull request to fix the git structure:
https://github.com/Tatoeba/tatoeba2/pull/1208

**Comment by ckjpn** [comment]
Perhaps it would be better to change the default sort for the "last updated" to direction:desc.

http://dev.tatoeba.org/eng/sentences_lists/index/page:1/sort:modified/direction:desc

**Comment by ckjpn** [comment]
Perhaps as long as you are working on lists, you might want to change "All Lists" to "All Public Lists" on this page http://dev.tatoeba.org/eng/sentences_lists/index/page:1/sort:modified/direction:desc.

Note that currently this doesn't seem to even show unlisted lists by the currently logged-in member.

**Comment by dispyfree** [comment]
@ckjpn  I incorporated your suggestions:
https://github.com/dispyfree/tatoeba2/commit/dd31275f5baf66ac6c30f4796dfca68710d91bdb

(should I open up yet another pull request? I don't want to flood the system just for those minor changes ;-D )

**Comment by trang** [comment]
@dispyfree you always open a pull request, even if it's for ultra minor changes. That's how we roll :)

However, because you make a pull request:

1. I'm okay with having the initial sort on "last updated / direction:desc" so you can submit that change.
2. I however don't think we should change the label "All public lists" to "All lists". The reason why it's labelled "All public lists" is because it lists only public lists. If we label it "All lists", then it would also have to include lists that are "unlisted" or "private" and are from the current user. But since there's already a category "My lists" for those lists, there's no need to include them as well in "All lists".

**Comment by dispyfree** [comment]
@trang
2. Actually it's currently "All lists", it's my patch that changes that into "All public lists". 

I'll make another pull request - you gotta do something for your github stats ;-)

**Comment by trang** [comment]
2. Oh, my bad, I read it the other way around.

Thanks for the pull request :)
