### ISSUE TITLE
Searching for "$" generates an error message

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1126]
When I tried to search for "$", it just returned this message:

> Search error

> An error occured while performing the search. If the problem persists, please let us know.

https://dev.tatoeba.org/eng/sentences/search?query=%24&from=eng&to=und
https://dev.tatoeba.org/eng/sentences/search?query=%24&from=und&to=und

I
![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/14944089/1d7e7082-0fc0-11e6-8790-60a57205de81.png)

**Comment by RyckRichards** [comment]
Maybe it's somewhat related to #1119

**Comment by ventice** [comment]
Taking.

**Comment by ventice** [comment]
Actually, there are two different issues here:
1. `$` isn't escaped which leads to error mentioned in the description (can be checked by escaping it in query itself by putting backslash in front of it, i.e. looking for `\$`)
2. When searching for escaped `$` (or `/`) only, no results are returned even though no error occurs. This is in my opinion because language indices do not include punctuation.

**Comment by ventice** [comment]
After fixing 1. it appeared that my guess concerning 2. was true. Only underbars (`_`) are currently indexed. When I added `$, /,` to `charset_table` in `common_index` index in my local *sphinx.conf* file I was able to search for standalone `/` and `$` symbols (not those included in strings like **$100** because this fix makes punctuation part of indexed word and star syntax is not enabled in sphinx by default to search for substrings using `*` operator).
In any case, I am not sure I can update sphinx_conf to include dollars and slashes as part of charset without approval of some empowered tatoeba representative (:

**Comment by trang** [comment]
#### Regarding escaping `$`

Since `$` can be used after a word to find sentences ending with that word, escaping `$` would make this feature unavailable, wouldn't it?

####  Regarding indexing `$` and `/`

From a strictly UX point of view, I'm in favor of it. I think it should be possible to search for `$` alone and have all the sentences containing `$`. I also think that if I'm searching for `$100`, I shouldn't get sentences with `100%`. Same if I search for `1/4`, I don't want results with `1.4`.
So indexing these symbols would make sense to me, but we would need to evaluate the impacts.

One thing to consider, in the case of `$`, is how to avoid ambiguity for searches like `100$`. Did the user want to search sentences that end with 100? Or did the user want to search sentences that contain `100$`? Currently, the search returns [sentences that end with 100](https://tatoeba.org/eng/sentences/search?query=100%24&from=und&to=und).

In case we realize it's too much trouble to allow users to search these symbols, then we would need to display a more accurate message, something like `"$" is not a valid search.`.

**Comment by ventice** [comment]
> Since `$` can be used after a word to find sentences ending with that word, escaping `$` would make this feature unavailable, wouldn't it?
Yes, this feature disables `$` as special symbol.

This is what I personally think about symbols, punctuation and searches.
### 1. Search hints
Since (in my understanding) tatoeba's primary role is providing of usage examples, search features are *must* because during language the words position and relation to other words matter, so users will be really interested in positional and combinatoric types of searches. So, looks like necessity of advanced search is out of doubt.
### 2. Punctuation
Punctuation **may** be of some interest, but in my opinion its use cases are limited. Additionally, since our contributors are expected to be native speakers, so experts of spoken language, the punctuation of their sentences is expected to be less credible, so it will be incorrect to position tatoeba as database of exemplary punctuation. So, that's why search by punctuation seems to be doubtful feature.
### 3. Special symbols
Some special symbols may be considered as acronyms. For instance, `$` may be considered analogue of the word "dollar", the `%` sign - the analogue of the word "percent", and etc. Users may be tempted to look for these symbols and it has nothing to do with punctuation. Anyhow, we must be aware that these symbols provide some complexity in reading the sentence making language with alphabets look like languages with hieroglyphs. For instance, the sentence "I've got $100." reads as "I've got hundred dollars", so decoding of "$100" to "hundred dollars" is some analogue of transcription. In this case, the symbols "$100" lacked some linguistic data that the student may need to acquire from other sources. In general, I think that sentence with "$" and "100" is example of bad sentence in terms of language study. The "transliterated" version is better version of this sentence.
Anyhow, the reality is that we already have lots of sentences with symbols and making them searchable will be a good feature.

### 4. Summary
Provided arguments mentioned above, we can conclude the following:
1. Searching for punctuation can be dropped
2. Searching hints must be supported
3. Searching for acronym symbols is nice to have

These requirements can be achieved by two ways:
1. Introduction of our own searching hints grammar. Some simple translator is to be written to translate our own convention (that is to be well documented) to sphinx queries
2. Full support of sphinx queries. In this case users are responsible for escaping special symbols used in sphinx as search hints. We only need to include those symbols in charset_table (on language basis) so that they are searchable when escaped by users.

First solution decouples us from sphinx search engine and gives us more control over our search engine (so, once we change it, we will only need to rewrite the translator and not teach thousands of ours users and their scripts the new syntax). So, any corporate website and service would take this solution. Second solution is simpler and more geek-friendly. I think it is more acceptable for open source site like tatoeba.

So, if we take this solution, we have to roll back my previous commit with this one, and close all the issues where users try to do advanced searches without being geeks - if you want to looks for anything but words, be so kind to escape special symbols.

The decision is up to you (:

**Comment by trang** [comment]
Solution 2 sounds fine to me. Considering our resources, it'll take years anyway to accomplish solution 1. We can use a more modest solution meanwhile :P

**Comment by trang** [comment]
@ventice, to clarify the expections of this issue, there are two cases we need to solve.

1) The user searches for `$`

We should display: `Invalid search. Check out our documentation about the search features.`
Where `search features` links to http://en.wiki.tatoeba.org/articles/show/text-search

2) The user searches `\$`

We should return sentences containing `$`.
