### ISSUE TITLE
Add a "Help" menu in the top navigation bar.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1145]
## The Problem

New members don't notice the links at the bottom of the page, such as the Quick Start Guide, FAQ and Wiki.

Before registering, maybe it is no problem having these important links at the bottom of the page as they are on the non-logged-in "home" page.

However, once a member has registered, these links are in a less visible place at the bottom of the page and often seem to go unnoticed.

## The Solution

Put a "Help" menu in the top nav bar and include the following.

Quick Start Guide
Rules and Guidelines
FAQ
Tatoeba Wiki Home Page   (or call the link "More ...")

All of these would be the direct links to those pages on the Wiki.

This not only makes it much more obvious, but is where people usually expect to find this kind of information.

![screen shot 2016-05-13 at 15 09 47](https://cloud.githubusercontent.com/assets/7934273/15239474/c7a84996-191d-11e6-80d2-0cca5fe9a367.png)

I think I've already mentioned in another issue that we really should have the top menu bar of the Wiki and the main site the same so that when new members do click to anything on the Wiki they feel they are on the same website and can also easily find their way back to what they were doing.

I think TRANG mentioned that sysko is the only one who knows how to change the menu bar on the wiki, so maybe this won't be easy to change.

**Comment by billoliver** [comment]
I think we should work on our information architecture and build a sitemap. This would solve those kinds of problem.

**Comment by ckjpn** [comment]
Step 1, though, would be to make it easy to find the documentation we already have, so adding the "Help" in the top nav bar where people would see it, would help quite a lot.

**Comment by trang** [comment]
My opinion on this topic: https://github.com/Tatoeba/tatoeba2/issues/28#issuecomment-195798798

In short: I don't consider that it is an actual problem that new members don't notice the help links. The problem to me is that new members need to read the help in the first place, and what we need to work on is to figure out why they need to read the help, and how can we change the UI so that they don't need to anymore.

If we ever put a help section in the top menu, then we have to commit to reorganize our help content in a way that is actually helpful. It is not something we can commit to, at least not that I can commit to. If some people want to work on improving our documentation and we end up with something good, then sure, we can consider having a help section that is more noticeable. But meanwhile I consider the help section to be okay where it is, and I would much rather invest efforts in building a better UI and improving the flows of the website.

**Comment by ckjpn** [comment]
> how can we change the UI so that they don't need to anymore.

Unless you put some of the basic rules and guidelines on every page, you'll always need a "help" and "quick start guide", so people know that they shouldn't add annotations into sentences and shouldn't do things like copy material from copyrighted sources.

People are more likely to read the "Help" if it's in the top nav bar, because they'll see it's there.

However, it's your website and if you don't think that's important, it's up to you.

**Comment by trang** [comment]
> Unless you put some of the basic rules and guidelines on every page, you'll always need a "help" and "quick start guide", so people know that they shouldn't add annotations into sentences and shouldn't do things like copy material from copyrighted sources.

I disagree with this. At least for the 2 points you mentioned (people adding annotations and people adding copyrighted content), we don't have to put guidelines on every page.

We can for instance have a script that tries to guess if a user is adding annotations (by detecting if there are parenthesis maybe), and show a warning to the user while they type their sentence.

We can detect when new users copy-pastes a sentence instead of typing it entirely, and when they do that, we display a warning to mention that they shouldn't submit the sentence if they copy-pasted it from a non CC-BY source.

I don't think it's unimportant that users understand how Tatoeba works, but we can do better than making the Help link more noticeable and hope for them to read our documentation.

Unless there are more objections I'll be closing this issue this weekend.

**Comment by ckjpn** [comment]
You already know that I think this is important, but if nobody else thinks so, I'll try to remember to quite mentioning this.  Perhaps I just notice that problem more because I'm on the site almost every day.
