### ISSUE TITLE
Change wording of option "Hide random sentence on homepage"

### ISSUE THREAD

**Issue by declanmalone** [Tatoeba/tatoeba2#1156]
Just two places where I noticed this:
1. In options, there's a checkbox beside "Hide random sentence on the homepage". It would be better written as "Show random ..." and be ticked by default.
2. In advanced search, "Is approved" is easier to understand than "Is unapproved", especially since the default is a double-negative "is not unapproved"

**Comment by trang** [comment]
1. By default the random sentence is displayed, this is why the option says "Hide random sentence" (the option is to hide, not to show).

2. It would be incorrect to say that the sentences are "approved". The current system only handles the situation where certain sentences do not comply to our standards or to our rules, and therefore are unapproved. A sentence that is "not unapproved" is not necessarily approved.
I agree with you though that it is harder to understand, and if you have an idea of a better (and accurate) wording, let me know. Otherwise I let you close this issue :)

**Comment by declanmalone** [comment]
On 21 May 2016 at 21:57, Trang <notifications@github.com> wrote:

>
>    1.
>
>    By default the random sentence is displayed, this is why the option
>    says "Hide random sentence" (the option is to hide, not to show).
>
>
Yes, both the the text and the default state of the button would have to be
changed in tandem.


>
>    1.
>
>    It would be incorrect to say that the sentences are "approved". The
>    current system only handles the situation where certain sentences do not
>    comply to our standards or to our rules, and therefore are unapproved. A
>    sentence that is "not unapproved" is not necessarily approved.
>    I agree with you though that it is harder to understand, and if you
>    have an idea of a better (and accurate) wording, let me know. Otherwise I
>    let you close this issue :)
>
>
I don't actually understand what "not approved" means on the site. I
haven't gotten around to reading all the parts of the documentation, so
there are still some areas that I don't quite understand.

As for the other point you raised, about posting on the wall, I will copy
the "issue" there.

Thanks & Regards,
Declan

**Comment by ckjpn** [comment]
1.

I don't see any problem with changing this the way it has been suggested.

I think the default setting for "email notifications" is "on", too.  However, I'm not sure, since I've opted out of that.

If all the options are listed as positive, then it's easier to see what's turned on and what's turned off.


2.

I agree with TRANG here that this shouldn't be changed.   We don't have any "approved" status for sentences.  However, we do have a status for sentences to warn users that the sentence is problematic -- a copyright infringement, or some other problem.

**Comment by declanmalone** [comment]
Thanks for the support on #1, CK.

On #2, how about "reviewed" as the opposite of "unapproved"? It doesn't necessarily mean that you approve of it, but that it has passed some basic checks that might disallow it.

On a related (but slightly off-topic) note, as a newcomer here, I don't have the benefit of knowing how these terms are used within your "in-group". Do you have any page that summarises what is meant by phrases such as "unapproved" or "collection" or "orphan" or whatever in one place? If you did, then some sort of explanatory link to that page would probably help clear up a lot of confusion that new users might have.

**Comment by ckjpn** [comment]
The term "reviewed" implies that the sentences have been reviewed, which is not the case.
The term "unapproved" means that the sentence was looked at and manually set to that status.

The term "collection" means "ratings" on tatoeba.org, so instead of sentences being rated, OK, unsure or not OK, they are added to "collections" by those names.  I've suggested that this terminology be changed to "ratings", but Trang seems to prefer the word "collections." 

Note we do have a Wiki with a lot of information.
http://en.wiki.tatoeba.org/articles/show/main
Perhaps someone could start a glossary there.

**Comment by declanmalone** [comment]
> The term "unapproved" means that the sentence was looked at and manually set to that status.

So to make sure I understand, the default state is neutral and tagging with "unapproved" moves it to a lower status? In that case wouldn't  a tag like "rejected" or "dubious" be a more appropriate?

> Note we do have a Wiki with a lot of information.
> http://en.wiki.tatoeba.org/articles/show/main
> Perhaps someone could start a glossary there.

I've read some of this, but not all. I will try to read it all.

**Comment by trang** [comment]
> Yes, both the the text and the default state of the button would have to be changed in tandem.

With CK's explanation I understand better the rationale behind this.

I didn't even think of it this way because to me it actually feels more intuitive to have options unselected by default: when all options are off, you have the default behavior, and every option that you turn on generates a derived behavior.

But it's true that the "Email notifications" are selected by default and I think as well that it makes more sense to have a positive label on a checkbox.


> Trang seems to prefer the word "collections." 

@ckjpn, I don't actually. I'm not changing the name because for the time being, the feature is still not completely defined. Since it can evolve into something that is more than just ratings, I'd rather wait until things are more settled.


> So to make sure I understand, the default state is neutral and tagging with "unapproved" moves it to a lower status? 

Yes.


> In that case wouldn't a tag like "rejected" or "dubious" be a more appropriate?

I think it will be difficult to find an appropriate wording because there is currently no official rules that define when a sentence should be marked as unapproved. I don't think we can really find a solution in the scope of this issue. The feature itself needs to be reworked anyway, so when we get the chance to improve it, we can discuss again about wording. Meanwhile, feel free to create a thread on the Wall to discuss this topic.


> > http://en.wiki.tatoeba.org/articles/show/main

> I've read some of this, but not all. I will try to read it all.

Our documentation is not everywhere up-to-date and is lacking a lot of information, so don't hesitate to ask questions on the Wall.


I'm going to change the title and wrap up this issue to make it clearer for developers who will want to solve on this.

**Comment by trang** [comment]
**Problem**

In the profile > "Settings", there is an option that currently says `Hide random sentence on the homepage`. This can be counter intuitive because turning on the options is associated to the absence of the random sentence. It would be more intuitive if **turning on** the option is associated to the **presence** of the random sentence.


**Solution**

* Remove the current option: `Hide random sentence on the homepage.` (which is unselected by default).
* And create a new option: `Show random sentence on the homepage.` (which will be **true by default**). The user will uncheck the option if they want to remove the random sentence from the homepage.
* Additionally, we may need a script that migrates users current settings to the new settings, so that those who already opted for hiding the sentence can keep their settings after the change.

**Comment by ckjpn** [comment]
>> Trang seems to prefer the word "collections."
> @ckjpn, I don't actually. I'm not changing the name because for the time being, the feature is still not completely defined. Since it can evolve into something that is more than just ratings, I'd rather wait until things are more settled.

Still,  "ratings" makes more sense the way it is now, and would be much less confusing to new members.

"Collections" and "lists" are basically the same meaning, so if you want to evolve the "ratings / collections" into something else, maybe it would make sense to do it as "lists".  A list is a collection of sentences.

It seems to me like it would be more clearly defined if you called the rating system "ratings."

**Comment by agrodet** [comment]
@trang Apart from the change of logic, I have a question about the following point 

> Additionally, we may need a script that migrates users current settings to the new settings, so that those who already opted for hiding the sentence can keep their settings after the change.

I'm not very aware of the CakePHP way of doing things, so I'd like to make sure of what you have in mind. It seems okay to me to add a `'show_random_sentence' => true` setting to the User Entity and running the following Cake command, after which we will just have to remove the `hide_random_sentence` from the User entity. 
```
$users = $this->Users->find();
foreach($users as $user) {
    $currentSetting = $user->settings['hide_random_sentence'];
    if ($currentSetting) {
        $user->set('settings', ['show_random_sentence' => '0']);
        $this->Users->save($user);
    }
}
```
Is that what you had in mind or am I missing something?

**Comment by trang** [comment]
@agrodet, you can ignore that actually. I was over-complicating things. There's no need to create a new setting attribute technically. You can just revert the condition upon which the checkbox is checked and revert the associated value for when it's checked or not checked.

**Comment by agrodet** [comment]
@trang I thought the same at first, but when I modified the code, I found it confusing that the settings would be named "Hide" while it would be used as "Show". Since it is used in a very few places, I finally thought it would be more beneficial, for future maintenance or developers for example, to actually rename it properly, as you suggested before. Of course, the same reasoning can be applied for the reverse argument. Since it is used in only one place, it is not so difficult to understand why the attribute would be used negatively.

What do you think? If reversing the attribute is enough, I'm okay with it, no problem to merge ^^

**Comment by trang** [comment]
Reversing the attribute is enough. We just want to reword a string in the end, it's a bit overkill to change the database and migrate data just for that.
