### ISSUE TITLE
In "advanced search", things aren't really sorted by "last created".

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1165]
## The Problem

Using the following search, the newest sentence (the highest numbered sentence) is not listed at the top.

https://tatoeba.org/eng/sentences/search?query=%22%5EI+wish%22&from=eng&to=und&orphans=no&unapproved=no&user=&tags=&has_audio=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created

![screen shot 2016-05-27 at 21 51 05](https://cloud.githubusercontent.com/assets/7934273/15608594/c4e2d44a-2455-11e6-9acd-a9924781f9dc.png)

This is the order of the sentences on the search results page.

5168841 - I wish I'd known how to speak French.
5168842 - I wish to speak with you in private.
5168843 - I wish I had the courage to do that.
5168844 - I wish you wouldn't drive so fast.
5168845 - I wish Tom would stop complaining.
5168846 - I wish Tom would make up his mind.
5168847 - I wish tomorrow would never come.
5168848 - I wish we could ask Tom to help.
5168849 - I wish I'd bought a size larger.
5168850 - I wish I had a voice like Tom's.
5168851 - I wish I could've talked to Tom.
5168852 - I wish I'd bought that bicycle.
5168853 - I wish you'd stop complaining.
5168854 - I wish summer would never end.
5168855 - I wish it was Valentine's Day.
5168856 - I wish Tom would stop smoking.
5168857 - I wish you a speedy recovery.
5168858 - I wish I lived in a big city.
5168860 - I wish I could go with Tom.
5168862 - I wish Tom understood me.
5168865 - I wish I had a pony.
5168866 - I wish I had a dog.
5168827 - I wish I had studied French when I was in high school.
5168828 - I wish I could play volleyball as well as Tom.
5168829 - I wish I had the courage to do what Tom did.
5168830 - I wish I had had the chance to learn French.
5168831 - I wish I'd bought a different color shirt.
5168832 - I wish to be alone for a couple of hours.
5168833 - I wish that I had never sent that email.
5168834 - I wish I could fall asleep that quickly.
5168836 - I wish I didn't have so many problems.
5168837 - I wish we'd told Tom to come as well.
5168838 - I wish we'd told Tom to come, too.

## Note

Perhaps the "last created" is not based on sentence numbers.  If that's the case, maybe this is because all of these sentences were imported. If that is the case, then it's not a problem with the advanced search.

**Comment by dispyfree** [comment]
It appears that this is due to the data and not an issue of the advanced search function. 
See here: 
`mysql> SELECT sent1.id AS id1, sent2.id AS id2 FROM sentences AS sent1, sentences AS sent2 WHERE sent1.id < sent2.id && sent2.created > sent1.created LIMIT 10;
+---------+---------+
| id1     | id2     |
+---------+---------+
| 5079544 | 5079545 |
| 5079544 | 5079546 |
| 5079544 | 5079547 |
| 5079544 | 5079548 |
| 5079544 | 5079549 |
| 5079544 | 5079550 |
| 5079544 | 5079551 |
| 5079544 | 5079552 |
| 5079544 | 5079553 |
| 5079544 | 5079554 |
+---------+---------+
10 rows in set (3.61 sec)
`

**Comment by trang** [comment]
@dispyfree, it's not really contradictory. If 10 sentences are added in the same second (i.e. these 10 sentences have the same datetime), and you order by datetime, there's no reason for the id to have any influence on the order. Just like if you order alphabetically by text, and 10 sentences have the same text value, there's no reason for the id to have an influence on the order.

I'm closing this, since there's no actual problem.

**Comment by dispyfree** [comment]
Quick follow-up: small quirk of MySQL, in particular:

> If omitted, the default precision is 0. (This differs from the standard SQL default of 6, for compatibility with previous MySQL versions.) 
(http://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html)

By default, MySQL does not store any fraction at all. I was somehow assuming that datetime was on microsecond level (default of 6) which would have made that event very unlikely.

**Comment by ckjpn** [comment]
It doesn't really matter to me, but if this sort was done by sentence ID number instead, then the sort would be correct, no matter how quickly sentences got added.
