### ISSUE TITLE
Vocabulary item: automatic sentence list

### ISSUE THREAD

**Issue by kamillel** [Tatoeba/tatoeba2#1166]
The purpose of this feature is to help users study vocabulary by providing them with a list of sentences for a given word.

For example: I am learning vocabulary lists but I want contextual sentences to understand how the words are really used

The first implementation will focus on the key functionalities: adding a vocabulary item, getting existing sentences automatically linked to it, and adding new sentences to an item.

With further developments, the users will be able to manage the links between one item and the sentences and ask for new sentences to be added (see [Trang's comment](https://github.com/Tatoeba/tatoeba2/issues/1148#issuecomment-221347302) on #1148).

**Use case 1: As a learner, I want to add a new vocabulary item**

_Access: My profile > 'My vocabulary items'_

![1_add_item](https://cloud.githubusercontent.com/assets/6699709/15633800/17188c10-25ae-11e6-9222-14ec8fd805d5.jpg)

As a user: I can add an item and specify the language (both fields are mandatory).
Once I added one, it appears below (disappears if I leave the page). 

**Use case 2: As a learner, I want to check the sentences linked to my items**

_Access: 'My vocabulary items' sidebar > 'All my vocabulary items'_

![2_item_list](https://cloud.githubusercontent.com/assets/6699709/15633831/755ba9ce-25ae-11e6-868f-6ddc773c1557.jpg)

As a user: Here, I can see all of my items with all their sentences. The items are ordered by date (from the one I added the more recently to the oldest one).
I can filter by language (from the sidebar).

Tatoeba is performing a search for each item and automatically displaying the matching sentences.

**Use case 3: As a native speaker, I want to add sentences to vocabulary items**
 
_Access: Contribute > Add sentences_

I used the 'Translation' behaviour but I integrated it to the 'Add sentences' pages. I feel like adding a new entry in the menu will add complexity and in both cases people are here to add sentences.

![3_add_sentence_search](https://cloud.githubusercontent.com/assets/6699709/15633834/79723bae-25ae-11e6-973a-42d0ce92426a.jpg)

As a user: I can search for vocabulary item, by selecting a language and/or typing a username.

![4_add_sentence_list](https://cloud.githubusercontent.com/assets/6699709/15633836/7b8ff9da-25ae-11e6-8900-ee07e1b1f650.jpg)

The items are ordered by the amount of linked sentences: from the item with the less sentences to the one with the more sentences.

As a user: once the results are displayed, I can add a sentence by clicking on the "+".
Same behaviour as adding a translation: the text area replaces the sentences (if any) and once I submitted it appears at the top of the linked sentences.

I can filter by language or user (from the sidebar).

**Comment by RyckRichards** [comment]
There will be a way for browsing requests?

Example: I am a native speaker of Portuguese and so, I would like to help
members by creating sentences they asked via this feature. How would I do
it?

**Comment by RyckRichards** [comment]
Another point that ”poped up" into my mind

Imagine that I just found Tatoeba and I want to give it a try. So I browse
for sentences in English that contain the word "Google". Let's suppose that
nobody created any sentence with this word

1) as a non-registered user, will I have to create an account if I want to
be notified whenever someone added a sentence or will I have a page like
"sorry. There is any sentence with the word "Google" for now. Would you
like to get notified when a Tatoeba user adds a sentence containing this
word? If so, write your email here"?

2) will native speakers get notified that someone requested sentences in
his/her native language? Maybe via email? There might be some users that
won't be willing to help and some that will. Will they have the option
(maybe on settings) to choose to be notified if they want to be notified
about a new word request?

**Comment by kamillel** [comment]
*Browsing requests*: 
Native speakers can access them by going to 'Contribute > Add sentences' (wireframes 3 and 4), I'll update the ticket to make it clearer.
We could also add an additional entry in 'Browse > By vocabulary item'.

*Notifications*
This first implementation only focuses on the basic features needed to start using the vocabulary items, requests & notifications won't be supported in this iteration. But I'm keeping the ideas for later! I don't if it's possible to support email notifications for non-registered users but optional notifications for registered users is interesting (some users would like to be able to send their requests to specific native users so that's something we need to work on).

**Comment by trang** [comment]
I have some final comments then I think we can mark this as accepted and start an implementation :)

1. There is a `#` icon next the vocabulary item. Is it clickable? Or is displayed to maintain the same pattern as sentence?

2. The user will probably want a button/link to perform a search for a certain vocabulary item, in order to see all the sentences for a certain item.

3. The user will probably want to know as well how many search results there are for each vocabulary item.

4. I'm thinking that in this first iteration, we should drop the display of linked sentences in "All my vocabulary items", and let the user click the search button to view "linked" items.
If we display the search results, it will require extra development effort for something that we will use only temporarily: once users can select their own sentences, we won't need to display search results anymore, we would display the user's selected sentences. And I'm also a bit concerned about the performances with displaying the search results: we would need to run 10 searches every time the page is displayed.

There's probably other small things, but we can deal with them during the implementation.

**Comment by kamillel** [comment]
1. The # is clickable and leads to a 'item page'
2. Could the search be automatically performed when the 'item page' is displayed? 
3. I added a line for it (item page)
4. I think the 'all items' page feels quite logical to have (there is on for the user's sentences /lists / favorites) but I agree with wasting development time and it would affect the performance too much. Could we keep it but use it as simple list? (screenshot below, like what is done for sentences or favorites)

**All my items**

![2_item_list](https://cloud.githubusercontent.com/assets/6699709/15941831/ca8e60de-2e79-11e6-894d-689665a825a8.jpg)

**Item page**
When I clicked on the # from the previous page I access the item page.
The search is automatically performed (if it's too confusing, we could add an button for the user to launch the search).

![2b_item_page](https://cloud.githubusercontent.com/assets/6699709/15941822/c26fcec4-2e79-11e6-8a0c-46aa73510dc4.jpg)

**Comment by trang** [comment]
> Could the search be automatically performed when the 'item page' is displayed?

Yes. The item page is virtually the same the search results page, except the sentences on the item page don't include translations.

At this point I think we've reached something stable enough for the first iteration :)

At least in my mind things are clear enough that I can start the implementation this weekend. We can discuss more about the details once we have an actual UI to play with.

**Comment by trang** [comment]
I completed a first implementation of this feature and it's currently testable on the dev website :)

### Things I did differently from the design

1. The `My vocabulary items` link int he profile doesn't redirect to the page to add new voacbulary, but the page that lists all the vocabulary of the user. It felt more intuitive that way.

2. Whenever a vocabulary item is added, the number of existing sentences for this vocabulary is displayed (`{n} sentences`) at the end of the item.

3. Instead of creating a "Vocabulary item" page, I simply added a redirection to the search page. I suspect that some people will ask that the sentences on the item's page can be translated, favorited, etc. Those features are provided on the search page so it saves me some time to simple redirect to the search page. This search page can be accessed by clicking on the `{n} sentences` link.

4. I didn't add the `#` icon because it would make sense only if there's a dedicated page for each vocabulary item. I also didn't find an equivalent icon in the Material icons.

5. I implemented the UI with with slightly different UI patterns, to be closer to what the UI will be like when we are done making it responsive.

6. The "Add sentences using vocabulary items" page doesn't list all the vocabulary, only the items that have less than 10 search results.

### Things that can be improved

1. Once a sentence is added for a vocabulary item, the number of sentences is not updated. I'm not sure how to handle this yet, and it probably won't be handled for the first iteration.

2. The sentence cannot be edited on the fly either (in case the user made a typo).

3. The user cannot go to the sentence's page of newly added sentences.

4. I didn't add yet the form "Add sentences using vocabulary items" on the "Add sentences page". I'm thinking instead of a whole form, we could have a simple link saying something like `Not inspired? Check out the list of vocabulary that needs sentences.` and this link would redirect to the "Add sentences using vocabulary items" page.

----

There's for sure still a whole bunch of small details to fix, that I didn't mention, but overall the feature should be usable as it is now.

**Comment by ckjpn** [comment]
>Whenever a vocabulary item is added, the number of existing sentences for this vocabulary is displayed ({n} sentences) at the end of the item.

If it doesn't requre extra time, then instead of 1,000 for items with more than 1,000, display the true number of sentences, otherwise maybe display 1,000+ or "more than 1,000".

https://dev.tatoeba.org/eng/vocabulary/of/CK
![screen shot 2016-06-19 at 11 43 01](https://cloud.githubusercontent.com/assets/7934273/16174874/480d4fac-3613-11e6-9e51-64f2a570cca1.png)

**Comment by ckjpn** [comment]
Currently, it's possible to contribute a blank "word" and a word in an unidentified language..  This should probably be corrected.

**Comment by ckjpn** [comment]
"Filter by language" doesn't work on "add_sentence", but does work on "vocabulary/of".

This works.
https://dev.tatoeba.org/eng/vocabulary/of/CK/jpn

This doesn't.
https://dev.tatoeba.org/eng/vocabulary/add_sentences/jpn

**Comment by ckjpn** [comment]
It would probably be a good idea to give a unique name to the 3 different "Vocabulary" pages.

Currently, all 3 have the same title.

```
<title>
        Vocabulary    </title>
```

For the "My vocabulary" lists, it might be good to include the username in the TITLE code, too, since members might possibly bookmark other members' lists as well.

Maybe the TITLE of the HTML page could be the same as the main title on the page, minus the item count.

https://dev.tatoeba.org/eng/vocabulary/of/CK

**Comment by ckjpn** [comment]
On the "Add vocabulary items" page, perhaps you should consider doing both of the following things.

1. Put a message or a language name in the select menu, so it's not blank when you first land on the page.

2. Make the input area look like a standard input box rather than just an underlined area.  This confused me the first time I saw it, so I assume others might not immediately understand that it's an input box if you leave it the way it is.

![screen shot 2016-06-20 at 21 43 04](https://cloud.githubusercontent.com/assets/7934273/16194655/95c89bb6-3730-11e6-8d39-0cb019d68e94.png)

**Comment by Guybrush88** [comment]
maybe a larger thing in the window used to add vocabulary items would improve things, translated strings (at least in Italian) appear truncated: http://i.imgur.com/zkXmglh.png
