### ISSUE TITLE
Internationalize date

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1219]
Requested by [Pfirsichbaeumchen](http://tatoeba.org/eng/wall/show_message/26614#message_26614).

The date is currently displayed in a format that is not very human friendly. 
For example: `2010-10-22 23:10`

We would ideally want something like: `October 22, 2010 at 23:10`. 
This string should be translatable.

**Comment by zachleigh** [comment]
How are you planning on doing this? I use Carbon (https://github.com/briannesbitt/Carbon) in other projects. Comes with a few dozen languages out of the box and looks like it would be easy to add more to.

**Comment by trang** [comment]
I haven't done much research on whether or not there's already a mechanism in CakePHP for this, and I haven't researched either about existing libs.

**Comment by AndiPersti** [comment]
[CakePHP changed from Carbon to Chronos since 3.2.0](https://book.cakephp.org/3/en/core-libraries/time.html).

Formatting the dates is pretty easy.

Full datetime strings as used for logs, comments, wall messages, ...:
![contributions](https://user-images.githubusercontent.com/6566321/68205820-80736180-ffcb-11e9-8f13-91cad16523c4.png)

![users](https://user-images.githubusercontent.com/6566321/68205836-86694280-ffcb-11e9-9028-e48d6a7c3fee.png)

![wall](https://user-images.githubusercontent.com/6566321/68205837-86694280-ffcb-11e9-942b-28fbdc8aff9d.png)

Just dates as used in the user profiles:
![profile1](https://user-images.githubusercontent.com/6566321/68206232-87e73a80-ffcc-11e9-9d2b-533c7818012f.png)
![profile2](https://user-images.githubusercontent.com/6566321/68206233-87e73a80-ffcc-11e9-81db-3f29f533153d.png)

What about tooltips? I guess they should still show the  ISO 8601 format for combined date and time (e.g. 2012-02-11 03:49:06).

Something to consider: There probably will not be enough room for displaying two nicely formatted datetime strings on one line if the modification date is also displayed for wall messages, comments, ... This problem already exists with the current version in some translations:
![comments1](https://user-images.githubusercontent.com/6566321/68207302-ec0afe00-ffce-11e9-94e7-db41b666e590.png)
![comments2](https://user-images.githubusercontent.com/6566321/68207303-eca39480-ffce-11e9-86e6-216ec59e0bc4.png)

**Comment by ckjpn** [comment]
I personally like the 2019-11-23 02:15 format better.

1. It good for sorting.
2. It is easy to compare dates and quickly see how many months has passed between 2 dates.
3. It is likely easier to understand across a lot of languages.

**Comment by trang** [comment]
@AndiPersti 

> What about tooltips? I guess they should still show the ISO 8601 format for combined date and time (e.g. 2012-02-11 03:49:06).

They should show the human-friendlier version (like `February 11, 2012 at 3:49 PM`). Do you see an advantage for keeping them in the ISO format?

> Something to consider: There probably will not be enough room for displaying two nicely formatted datetime strings on one line if the modification date is also displayed for wall messages, comments, ... This problem already exists with the current version in some translations:

That's okay, there's always the tooltip to show the full text.

@ckjpn

> I personally like the 2019-11-23 02:15 format better.
> 
> 1. It is good for quick and easy sorting by date.
> 2. It is easy to compare dates and quickly see how many months have passed between 2 dates.
> 3. It is likely easier to understand across a lot of languages.

This issue is about having the dates translated on the website UI. The format will not change in the database. Sorting and translating applies for when you're processing the CSV file and in the CSV files, the format will remain the same. As for making it easier to understand across many languages: having a date/time string that will be translated in every language language is the best thing we can do for that.

**Comment by AndiPersti** [comment]
> They should show the human-friendlier version (like `February 11, 2012 at 3:49 PM`). Do you see an advantage for keeping them in the ISO format?

No, I just wasn't sure whether they should be changed or not.

> That's okay, there's always the tooltip to show the full text.

And that's a good reason for changing them. :-)
