### ISSUE TITLE
I would suggest capitalizing "ID" in the "sort by ID" in lists.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1226]
![screen shot 2016-06-27 at 10 08 57](https://cloud.githubusercontent.com/assets/7934273/16366260/718c6fec-3c4f-11e6-8040-044b7c00fa15.png)

Maybe even add the word "number".

**Comment by ckjpn** [comment]
On second thought, perhaps "sentence number" would be better than "sentence ID".

It seems most members of the Tatoeba Project refer to it this way.

Also, this way you wouldn't have to capitalize it.

**Comment by halfdan** [comment]
Honestly I would just vote to remove sorting by "sentence id". There's no inherent value in sorting by a sequential id that I can think of.

**Comment by ckjpn** [comment]
I assume "date added" mean "newest first" and "sentence ID" means "oldest first"

Maybe that's the wording that should be used.

**Comment by trang** [comment]
It's true that ordering by sentence id doesn't make sense by itself, but it's indirectly a way to order by date of creation of the sentence (related issue: #660). We could keep the sort by `sentence id` feature but rename it to something like sort by `date of sentence creation`?

**Comment by alanfgh** [comment]
It took me some experimentation to figure out that "date added" meant "date added to list" rather than "date added to corpus" (== "sentence creation"). 

I suggest:

Sort by:  date added to list  |  date created

Internally, "date created" could sort by sentence ID, since we guarantee that any new ID is larger than any previous one.

**Comment by ckjpn** [comment]
> Sort by: date added to list | date created

This sounds good to me.
