### ISSUE TITLE
"birthday" value that lacks month, day, or year is not displayed at all

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1235]
On the dev site, I tried saving my birthday without the month, without the day, and without the year. Only when all three are saved is anything displayed. There are valid reasons for wanting to display partial dates:

- displaying the year lets people know my age, but keeps my birthday secret
- displaying the month and day lets people know my birthday, but keeps my age a secret

**Comment by zachleigh** [comment]
Ill take this one.      
   
The reason why we cant save partial dates is that the database table requires a DATETIME and partial/invalid dates don't save properly using the current code. I think if we changed the unspecified values to 00 it would work.    
    
Also, this column should really be a DATE column rather than a DATETIME. I think changing the column type will simply cut the timestamps and leave the date.

**Comment by zachleigh** [comment]
So I got this mostly working. It took a little more effort than I had expected...the real problem was with the php date function. When given a partial date, it falls back to a valid date rather than allowing an incomplete date. I wrote a little date parser which allows partial dates and displays them in the current format. However, the current date format (Y-m-d) makes the date strings awkward. Currently, they look like this:     
  - Full date (2005-06-15)
  - Only year (2005-00-00)
  - Month and day (0000-06-15)
  - Month and year (2005-06-00)
    
To me, these dates are strange and difficult to understand. I think dropping the zero strings makes them look much better:
  - Full date (2005-06-15)
  - Only year (2005)
  - Month and day (06-15)
  - Month and year (2005-06)     

But of course that breaks the convention a little. Thoughts?

**Comment by trang** [comment]
Ideally we should format the date to be more human-friendly: #1219.

Having the year alone, or year and month look more or less fine as 2005 and 2005-06. But the month and day is not very intuitive as 06-15.

Until we have translatable dates, I would go for question marks, like this: 
* 2005-??-??
* ????-06-15
* 2005-06-??

**Comment by trang** [comment]
@zachleigh, I've merged your PR with the printed zeros. Probably some users will report that it's confusing, but we'll see what they prefer to use instead of zeros. In the end this should be only a temporary state until we solve #1219.
