### ISSUE TITLE
The $ search function has quit working correctly.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1243]
## The Problem

This was reported on the Wall five days ago.

https://tatoeba.org/eng/wall/show_message/26665#message_26665

**Comment by ventice** [comment]
Taking this.

**Comment by ventice** [comment]
The reason is clear. It happens because of attempt to make the `$` sign searchable - when I added the rules `    regexp_filter           = \$(\w+) => $ \1` and `    regexp_filter           = (\w+)\$ => \1 $` to strip `$` off its numbers to make it available to indexer I stripped off also the query hint `$` from its word. Technically can be fixed if we strip `$` sign only off the digits. This will result in inability to use `$` as query hint for numbers only, but I guess, it is reasonable compromise - I can hardly imagine someone looking for sentences ending with given number.

**Comment by trang** [comment]
Sounds good.

**Comment by jiru** [comment]
@ventice I’m pretty late to the party, but have you tried adding the dollar sign to Sphinx’s [ngram_chars](http://sphinxsearch.com/docs/current.html#conf-blend-chars) option? It probably needs further testing, but it may be a more elegant approach to make the dollar sign (or any other sign that sticks to words) searchable. Some CJK signs like 。 or 、 are actually already searchable just because we didn’t bother removing them from ngram_chars.

**Comment by ventice** [comment]
@jiru Thanks. Will have a look.
