### ISSUE TITLE
Add column headers to exported csv files

### ISSUE THREAD

**Issue by jayrod** [Tatoeba/tatoeba2#1259]
If the headers for the csv exports were added to the first line other systems could use the csv.Dictreader function to easily iterate and parse the files. #401

**Comment by alanfgh** [comment]
Making this change would break most of the scripts that people have already written. Furthermore, I'm not sure it would accomplish much because I believe that people who are importing csv files from us already know what the contents are, based on the names and descriptions we provide.

Issue #401, which you referenced in your comment, is a closed issue regarding the updating of the "Downloads" page to link to compressed csv files, as opposed to the older uncompressed csv. I'm not sure why you mentioned that issue.

**Comment by ckjpn** [comment]
This would break the scripts I use to process the weekly downloads.  I could re-write my scripts, of course, but it would require that I spend more time on something I've already debugged and have working properly.

I'd suggest not doing this, unless a lot of people really need for this to be done.

My guess is that jayrod could easily insert the headers he wants whenever he uses the files.

**Comment by jayrod** [comment]
Yup agree with all. I merely suggested it as a change as it makes processing using the Dictreader very easy. I understand people already have processes in place. Consider it not needed and closed.
