### ISSUE TITLE
Perhaps the duplicate-merging script shouldn't move @change, @need native check and certain other tags to the existing good sentence.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1273]
## Problem

Often people leave a comment, then add the @change tag to a sentence.  And then, the sentence gets corrected and it matches an existing good sentence.  The merging script moves the irrelevant tag to the older sentence.

https://tatoeba.org/eng/sentences/show/2271891
### Tag

![screen shot 2016-07-27 at 15 10 38](https://cloud.githubusercontent.com/assets/7934273/17165703/48453c1a-540d-11e6-8c2a-5a03d0ebed50.png)
### Comment

![screen shot 2016-07-27 at 15 11 03](https://cloud.githubusercontent.com/assets/7934273/17165710/51e98d98-540d-11e6-869c-177367a2a774.png)
## One Possible Solution

Don't move certain tags aimed at correcting bad sentences when merging sentences.

Perhaps some necessary tags that should be moved won't be moved, but overall perhaps there would be fewer tagging errors this way.

**Comment by halfdan** [comment]
This seems to be rather rare and I would think that simply dropping all tags from the newer sentence should be fine.

**Comment by ckjpn** [comment]
It's not so rare.
Also, dropping other tags would mean a certain number of useful tags would potentially be dropped.

I don't know how the duplicate-merging script is written, but perhaps it wouldn't be too difficult to check to see if a tag is "@change", and then not move it if there is a match.

**Comment by trang** [comment]
This problem is unrelated to the deduplication script.  If the sentence is corrected, and the new text is not a duplicate sentence, the tag will remain as well.

Also, it's been established that corpus maintainers or advanced contributors remove these tags manually, because once the sentence is changed, one has to ensure that the change was correct as well.

There is of course a higher chance that if a sentence gets merged after it's modified, then it's a correct sentence. But it's not 100% certain. You still need a human to confirm it (by removing the tag).

Generally speaking, the `@change`/`@check` tags are very volatile and need more maintenance. It is not a problem if some sentence are incorrectly tagged with such tags, it's part of the process.

**Comment by ckjpn** [comment]
You are welcome to close this issue if you think it's not important.

However, I do find it irritating when I see a @change tag that was previously on an incorrect sentence now on sentences that I have previously proofread and added to List 907.  (This happens because the incorrect sentence was corrected and now matches the correct sentence.)
