### ISSUE TITLE
after adding a translation to a page with multiple sentences, the "Add to list" buttons on that page don't work

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1284]
I'm using this search, looking at page 3 of the results:

https://tatoeba.org/eng/sentences/search/page:3?query=&from=heb&to=und&orphans=no&unapproved=no&native=yes&user=&tags=&has_audio=&trans_filter=exclude&trans_to=eng&trans_link=direct&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

All the elements have loaded, and when I hover over the "Add to list" button for any sentence, it turns black, but clicking it doesn't do anything. If I open an individual sentence in another page, the "Add to list" button works normally there.

When I go to page 4 of the results, the "Add to list" buttons work normally. When I copy the URL into another tab and change the 4 to a 3, every thing works fine, too.

I was using Firefox on Windows 7 when I saw this problem. I didn't see it in Chrome on the same machine when I went to the same URL, but that difference in behavior may not have been related to the browser.

**Comment by ckjpn** [comment]
I can verify that this is a problem with Chrome, too.

The most recent time I had this problem was when I did this. However, it's happened to me before, too.

1.
I added a translation to this.
https://tatoeba.org/eng/sentences/show/5420490
The blood-stain cannot be removed.
=>
https://tatoeba.org/eng/sentences/show/5423588
The blood stain can't be removed.

2. I then tried to add Hybrid's sentence to my list of sentences not to use in my projects since a contracted version with the same meaning exists.

However, clicking the list button did not show the drop down list.

3. I reloaded the page, and was then able to add the sentence to the list.

**Comment by alanfgh** [comment]
I find that perhaps 50% of the time these days, the "Add to list" button is inactive from search result pages, even after all other elements on the page has loaded. On the other hand, when I then open the sentence from its own page, I have never had a problem adding it to a list from that new page. The other buttons above the sentence (translate, edit, favorite, delete, mark as OK, mark as unsure, mark as not OK) don't have the problem. There seems to be something unique about the "Add to list" button.

**Comment by ckjpn** [comment]
Check this behavior.

Maybe you can always add to the list before you make any translations.
Once you add a translation, then it doesn't work when on a page that lists more than one sentence.

I can't remember exactly, but I think this happened to me.

**Comment by alanfgh** [comment]
ckjpn's description matches all the observations I've made since he posted it. I changed the title of the issue ticket accordingly.

**Comment by alanfgh** [comment]
This occurs even when the page contains only a single sentence but is not the sentence page. That is, after adding a translation to a sentence on a page that contains any number N of search results, including N=1, no "Add to list" buttons on that page will work until the page is refreshed.

**Comment by trang** [comment]
@alexandresmirnov just a note about this issue: if you can find quick fix, that's great but in case the problem is too complicated to solve, we will just cancel the resolution of this issue.

I will be redesigning the sentences and at the same time, I will be migrating a lot of code, and this bug should no longer exist after the migration. So it is not worth investing too much effort fixing it in the current code.

**Comment by alexandresmirnov** [comment]
Understood!

**Comment by NM-30** [comment]
[On the Wall](https://tatoeba.org/eng/wall/show_message/27802#message_27802) I don't know if it's related, but whenever I try to add a certain sentence from https://tatoeba.org/eng/sentenc...por&to=por into a list, the "Add to List" icon doesn't work unless I translate a sentence or after I translated a sentence. It means

1 - Whenever translate a sentence from https://tatoeba.org/eng/sentenc...por&to=por , I have to translate another sentence in order to be able to add sentences to list again;

2 - Whenever I translate a sentence from https://tatoeba.org/eng/sentenc...por&to=por and close the tab/window/the browse, I have to reopen that again or clean the cache in order to be able to add sentences to any list.
