### ISSUE TITLE
Take care of ratings when a sentence has been edited and when the duplicate-merging script does its job.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1309]
## The Problems
- Ratings (currently called "collections" or "Reviewed by") remain even after a sentence has been edited.
  - Bad ratings remain when a sentence is corrected.
  - Possibly there are cases when good ratings remain when a good sentence was changed to something that isn't good.
- Ratings don't get moved (merged to) the original sentence when duplicates are being removed.  (I think.)
## Screenshot

https://tatoeba.org/eng/sentences/show/34312
This is a sentence that was edited since Jesse added a rating.

![screen shot 2016-09-11 at 08 10 22](https://cloud.githubusercontent.com/assets/7934273/18414082/3139f448-77f8-11e6-999b-5b3b629f874e.png)

**Comment by zachleigh** [comment]
The duplicate problem should be solved with pull request #1311. Duplicate handling now occurs at sentence creation.     

When a sentence is edited, it should be simple to reset the sentence rating.    
     
@trang Ill take this issue.

**Comment by trang** [comment]
@zachleigh actually we don't want to reset the sentence rating when it is edited. The problem if we reset it is that the user will have no idea that it has been modified and the sentence will disappear from their collection without their consent (cf. #1034).

There is an issue regarding handling outdated ratings: #747. The description is empty because I created the issue more like a reminder for myself. If you're interested to work on this issue let me know, I'll try to find a moment to write clearer requirements for it.

**Comment by zachleigh** [comment]
@tang That makes sense. I'll take the issue(s) :)

**Comment by ckjpn** [comment]
Here's another problem.

"Reviewed by" ratings don't get removed when sentences are deleted.

They stay on the page and also in the "my collections" lists.

![screen shot 2016-09-18 at 11 44 47](https://cloud.githubusercontent.com/assets/7934273/18612475/af556fa4-7d95-11e6-8d17-4a3fc75edb8d.png)

https://tatoeba.org/eng/sentences/show/4998387

**Comment by trang** [comment]
Closing this. I think this issue is no longer relevant.
Ratings are now marked as "outdated" when a sentence is edited.
