### ISSUE TITLE
Obscenity Filter for example sentences 

### ISSUE THREAD

**Issue by dispyfree** [Tatoeba/tatoeba2#1328]
# Problem

While tatoeba does have an "obscene" tag, it can only be used manually. Because tatoeba continues to be a great project for learning websites, it is routinely recommended to under age teens all over the world as a great learning resource. Even when not searching for obscene sentences directly (by using that kind of vocabulary), those sentences will come up  on any number of sites. This may include random sentences, recent activities, sentence requests, not translated sentences etc. All of those sites will (involuntarily) expose people to content they are often either not willing to see, which disgusts them or could even be detrimental to their development. 
I'm not talking about just censoring the sheer _usage_ of such vocabulary, but giving people a choice.
# Solution

I can think of two different solutions to this:
-  A setting in the profile: Just a simple checkbox you can tick/untick "I want to see content marked as obscene" . This is very easy to implement and does not degrade performance: a boolean could be added to the database table which is synced with the tags using a trigger. This only works for registered users. 
- A simple flag in the user's session. This does not require registration and works out of the box. 

Sentences should always be available when directly linked - this proposal covers things as result lists. Whenever a sentence is removed, a notice such as 
![obscenity](https://cloud.githubusercontent.com/assets/1538146/19039159/079f72dc-897f-11e6-80b7-e48d540268f6.png)

could be displayed. Clicking the link could toggle the flags (either in the session or in the user account) and reload the page. While I'd prefer the filter to default to not showing obscene content, displaying the very same message offering to _enable_ the filter is fine, too.  

You can find all sentences tagged with as obscene here: https://tatoeba.org/eng/tags/show_sentences_with_tag/3301
I believe myself to be quite tolerant, however this particular sentence made me bring up that proposal: 
https://tatoeba.org/eng/sentences/show/2994360

Thank you for your comments!

**Comment by sacredceltic** [comment]
Na und wer wird entscheiden was "obscene" ist oder nicht ?? Was ist "obscene" im Ryad oder Teheran (alles !) ist nicht im Paris oder Tokyo (nichts ist !). Heute können allen Kindern in der Welt porno-Videos anschauen. Was ist denn los mit einige Sätze ?

**Comment by dispyfree** [comment]
I put a (less technical) description on the wall:
https://tatoeba.org/eng/wall/show_message/27387#message_27387

@sacredceltic Having any measure is better than having no measure at all. There is a reason Google does not show you pornographic advertisement, even though you are very likely to use this very search engine to search for that kind of content. I think it's best to use English on github, so everybody knows what you are saying ;) 
I think the discussion should continue on the wall; I am used to github and just forgot to post it on the wall beforehand - sorry for that!

**Comment by sacredceltic** [comment]
>I think it's best to use English on github

Kaj mi opinias ke estas pli bone skribi en esperanto.

**Comment by ckjpn** [comment]
While this may be "out of scope" for the project, perhaps it might be a good idea to have a "white list" of sentences that get shown on the non-logged in main page, so visitors don't randomly get something that makes them decide to leave.

I know that you might not want to use only English sentences as the selection for this purpose,. 
 However, perhaps you may want to consider limiting the random sentences shown to non-logged in visitors to sentences on List 907, which would have the following advantages.

1. I've attempted to limit sentences to those usable by school children and various cultures.
2. I've attempted not to include any sentences with errors.
3. There are over 700,000 of these already which should be enough to get a feeling of randomness.
4. A majority of visitors can likely understand English better than they can understand a randomly-selected language's sentence.

If you are willing to future limit this selection to a little over 400,000, then you could only show sentences with audio, or use List 4000 (audio by me)  if there would perhaps be a chance that there are obscene sentences recorded by others.  However, this might mislead visitors into thinking all sentences have audio. I'm not sure if that's a problem or not.

**Comment by alanfgh** [comment]
Why don't we simply replace Tatoeba with List 907? The corpus would be far less messy.

**Comment by ckjpn** [comment]
>Why don't we simply replace Tatoeba with List 907? The corpus would be far less messy.

That's obviously not what I was suggesting.
I was suggesting one possible way to avoid having obscene sentences displayed to first-time visitors.

**Comment by alanfgh** [comment]
> I was suggesting one possible way to avoid having obscene sentences displayed to first-time visitors.

Yes, and the proposed cure was worse than the initial problem. I was horrified that an admin would suggest replacing a feature meant to highlight the diversity of Tatoeba with one that shows sentences in a single language, selected by a single user. I was also amazed that someone would suggest a whitelist approach rather than a blacklist. Given that the number of obscene sentences is small in proportion to the entire collection, identifying such sentences is far easier than marking all sentences that do not share that property.

We don't actually need to come to a 100% consensus on which sentences are obscene. If person A thinks that words 1, 2, and 3 are obscene, and person B thinks that words 1, 2, and 4 are obscene, but word 3 is okay, tagging sentences with word 3 or word 4 as obscene won't be a big deal. The set of people who want obscene sentences filtered out probably would be perfectly happy with if all sentences containing any of those words are filtered out. I don't think that the system would be too easy to abuse, either (though if mass tagging is implemented, that could change).

The real work (other than changing the code and user interface) would involve (a) agreeing on a common tag or set of tags (maybe it should include "vulgar" and "sexual" as well) and (b) identifying the problematic sentences (probably by doing searches for the obscene words).

**Comment by trang** [comment]
I marked this issue as "out of scope" a while ago but haven't had the chance to explain myself.

So here's the thing. I have a problem with making assumptions about what people want or do not want to see and I have a problem with being overprotective. Implementing an obscenity filter does both of these things.

A sentence can make someone feel uncomfortable while sparking curiosity for someone else. We cannot know. As far as I'm concerned, I can testify that my 12-year-old self was much more curious about obscene words than disgusted by them, and I don't think I'm an exception.

Even if there was a sentence that makes the majority of users feel uncomfortable or unsafe, then what? Seeing things we don't want to see, hearing things we don't want to hear, reading things we don't want to read... is just life. 

It's not like Tatoeba is made of 99% sexual and violent sentences. Being exposed to obscene sentences at a high frequency would be a problem, I agree. But in our case, it will only happen punctually and any normal human being should be able to handle it. For those who can't deal with it, I would argue they need to seek professional help because I can't imagine how they would navigate through life with such a fragile mind. Us trying to shield them from the reality of language isn't going to help much.

As for the risk that visitors decide to leave because of an inappropriate sentence, I must say I don't understand why this argument keeps being brought up. Why do we have to be paranoiac about what appears in the random sentence? I cannot imagine a rational person visiting for the first time Tatoeba, seeing an obscene sentence and just running away in shock.

I understand that we have an image to defend, we certainly don't want to look like a community of perverts. But who is going to judge us on just one sentence? At least they would check a few dozen more sentences, to evaluate what kind of content we have. Anybody with a little bit of common sense can understand that we will have some exotic content and will not give up on us at the sight of just one "bad" random sentence.

That doesn't mean we shouldn't provide ways to filter sentences. We definitely should, but we have to let each user choose for themselves what they want to filter out. We cannot and should not be making this choice for them. Whether it's obscene sentences, political sentences, sentences that are too long or too short, archaic sentences, sentences from non-native speakers; whatever it is, it should be up to the users, not up to us, to decide what they want or need to see.

From my perspective we have no real issue with obscenity. Our contributors are overall quite reasonable and are not flooding the corpus with adult content. Self-moderation and peer-moderation are our best filters, they worked well enough till now and I trust that they will keep working well enough for a long time.

I consider this issue closed. Our efforts should rather be directed towards improving the search criteria, or towards issues like #1609.
