### ISSUE TITLE
The Outdated Ratings Feature is not working correctly.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1350]
## Problem

Many ratings are marked outdated even though no changes have been made to seentences.

https://tatoeba.org/eng/collections/of/CK/outdated/page:6
![screen shot 2016-10-30 at 09 58 29](https://cloud.githubusercontent.com/assets/7934273/19833730/d9cda0ae-9e87-11e6-9b5f-19c8c5a2e81c.png)
## Notes

Several days ago, when I reviewed my page of outdated ratings, there were only 5 and I checked them and re-rated them, so my list was empty.

Apparently, Odexed saw an "outdated" on this page, even though I don't.
https://tatoeba.org/eng/sentences/show/2737383
![screen shot 2016-10-30 at 10 02 56](https://cloud.githubusercontent.com/assets/7934273/19833736/18f083a0-9e88-11e6-93d3-bb2506613952.png)

I do see an "outdated" on this page, though, even though the sentence has not been edited.
https://tatoeba.org/eng/sentences/show/2839853
![screen shot 2016-10-30 at 10 04 01](https://cloud.githubusercontent.com/assets/7934273/19833740/4cebd024-9e88-11e6-9289-429fadda12cc.png)

**Comment by ckjpn** [comment]
This may be related to this other issue.
https://github.com/Tatoeba/tatoeba2/issues/1354

Screenshots of outdated ratings and all OK ratings.
The numbers are nearly the same, which is definitely not correct.

![screen shot 2016-11-03 at 11 46 39](https://cloud.githubusercontent.com/assets/7934273/19954414/83443234-a1bb-11e6-8f1c-
c737548ed0c7.png)
![screen shot 2016-11-03 at 11 45 58](https://cloud.githubusercontent.com/assets/7934273/19954415/834a763a-a1bb-11e6-8626-1ceed5ad2ced.png)

**Comment by zachleigh** [comment]
I cant produce this locally. I wonder if this was the result of one of the sql scripts we ran when the feature was implemented. The pull request for the sql scripts is here: https://github.com/Tatoeba/tatoeba2/pull/1347

**Comment by ckjpn** [comment]
One problem is that the "outdated" gets added if someone adopts a sentence and there is no actual editing of the text.

https://tatoeba.org/eng/sentences/show/2722514



I just adopted all of these, too.

I did well on the test.
http://tatoeba.org/eng/sentences/show/5119610

Tom is one of the wealthiest people in the world.
http://tatoeba.org/eng/sentences/show/5096042

Tom roamed through the streets of Boston.
http://tatoeba.org/eng/sentences/show/4905275

I'm only telling you what I heard.
http://tatoeba.org/eng/sentences/show/3023013

What do you know about pandas?
http://tatoeba.org/eng/sentences/show/2722514

My goal is to be happy.
http://tatoeba.org/eng/sentences/show/2722502

I'd like to book a double room.
http://tatoeba.org/eng/sentences/show/2686468

I folded the towel in half.
http://tatoeba.org/eng/sentences/show/2611714

Horses sleep standing up.
http://tatoeba.org/eng/sentences/show/2550100

My friend wants to talk to you.
http://tatoeba.org/eng/sentences/show/2283333

This is just a hypothesis.
http://tatoeba.org/eng/sentences/show/2110836

Life is interesting.
http://tatoeba.org/eng/sentences/show/2110809

Nobody knows the future.
http://tatoeba.org/eng/sentences/show/1588344

**Comment by ckjpn** [comment]
I wonder if instead of the adopting that caused the "outdated", maybe these we "unadopted" since I rated them OK, and the "unadoption" caused the "outdated" to be added.

**Comment by zachleigh** [comment]
That would explain the ones that were marked as outdated after the sql script ran. The script compared the sentence modified date to the user_sentence modified date. Adopting a sentence changes the sentence modified date.   

That doesnt explain why adopting a sentence now is causing it to be marked as outdated because, at least as far as I can tell, the `adopt` method never hits the `makeDirty` method. Ill look into this.

**Comment by ckjpn** [comment]
I don't know if this helps, but I found a sentence that hasn't been changed that has 2 OK ratings.
One of the ratings says "outdate", the other one doesn't.

https://tatoeba.org/eng/sentences/show/5270063

![screen shot 2016-11-07 at 01 52 56](https://cloud.githubusercontent.com/assets/7934273/20039770/1b853a1a-a48d-11e6-8ef3-27d426aca659.png)

**Comment by trang** [comment]
There is no problem with the feature itself.

The problem comes from the script to detect existing outdated ratings is not completely accurate, since it relies on the `modified` date of the sentence, and this date could be the modification of the owner, or of the audio.

In addition to the queries mentioned in https://github.com/Tatoeba/tatoeba2/pull/1347#issuecomment-257113758, I executed the following:

```
mysql> UPDATE users_sentences
    ->     LEFT OUTER JOIN sentences ON(sentences.id=users_sentences.sentence_id)
    ->     SET `dirty` = false
    ->     WHERE sentences.hasaudio = 'shtooka'
    ->     AND users_sentences.correctness = 1
    ->     AND users_sentences.dirty = true;
Query OK, 890 rows affected (1.22 sec)
Rows matched: 890  Changed: 890  Warnings: 0
```

This makes sure all the sentences with audio are not marked dirty. 

The only users who have a high number of of outdated sentences are CK and PaulP (higher than 500).  We can see if there's a few more queries we can run, to unmark sentences outdated. But the rest will need to be verified manually by the users, because it will be too much work for the server if we make a script that checks against the logs rather than against the `modified` date of the sentence.

**Comment by ckjpn** [comment]
I wonder if it would be too much load on the server to check against logs once a week, or even once a month using a cron job.  This might help clean up any that get by the other script.

**Comment by ckjpn** [comment]
https://tatoeba.org/eng/sentences/show/875567
![screen shot 2016-11-07 at 11 05 34](https://cloud.githubusercontent.com/assets/7934273/20044219/3e967c10-a4da-11e6-86e8-f5d1d22696da.png)

I checked the exported data, and many sentence that show no difference between the creation date and the modification date in the "users_sentences.csv" file are marked as "outdated" on the website.

CK	875567	1	2016-01-26 01:06:38	2016-01-26 01:06:38

![screen shot 2016-11-07 at 11 09 22](https://cloud.githubusercontent.com/assets/7934273/20044258/ae64f0f8-a4da-11e6-9474-78b57378998d.png)

**Comment by trang** [comment]
The more accurate we want the outdated feature to be, and the more effort we have to spend on design and development. We can imagine a lot of things to ensure there's no incorrect "outdated", but I don't think it's worth the effort. Having ratings incorrectly marked outdated has a fairly low impact on the users.

Right now there are a lot of incorrect outdated ratings because they were generated from the script in #1347. This script won't be executed again, it was a one-time script. Once we manage to reduce the number, and the remaining of the outdated ratings are reviewed manually, we're done. It won't happen very often that a new rating is wrongly marked outdated.

**Comment by ckjpn** [comment]
Perhaps you could at least run a one-time script to undo the incorrect "outdated" ratings.

Couldn't you just compare the date of the rating and the modification date of the sentence, and then remove the "outdated" if the modification date of the sentence is before the "oudated" rating?

**Comment by sacredceltic** [comment]
Tout ceci ressemble fort à une énorme usine à gaz... Combien d'utilisateurs de la fonctionnalité, déjà ?

**Comment by ckjpn** [comment]
TRANG,

I am in the process of removing all of my incorrectly labeled "outdated" ratings.
There seem to have been 1166 of them.
Once this has been done, I should be able to go through and manually check any "outdated" ratings that were done.

I created the list of sentence numbers that needed changes made by comparing modification dates in the sentences_detailed file the users_sentences files using a Python script.

**Comment by trang** [comment]
@ckjpn 

> Couldn't you just compare the date of the rating and the modification date of the sentence,

This is what the initial script did. The date of modification can however be the modification of the language, of the audio, or of the owner. Therefore there was a lot of incorrect outdated ratings.

**Comment by ckjpn** [comment]
Would it be possible to check the logs that show on each sentence's page to see if a change has been made?

These logs don't seem to be affected by additions of audio files or modification of the language flags.

**Comment by trang** [comment]
As I've said before, it's possible, but I don't think it's worth it. 

If however you'd like to spend time working on a script to avoid manual verification, you can elaborate a script that creates a file that looks like this:

```
UPDATE users_sentences SET dirty = true WHERE user_id = 1396 AND sentence_id = 1;
UPDATE users_sentences SET dirty = true WHERE user_id = 1396 AND sentence_id = 2;
UPDATE users_sentences SET dirty = true WHERE user_id = 1396 AND sentence_id = 3;

// Assuming the ratings for sentences 1, 2 and 3 are outdated.
```

Then send it to me. I'll reset all your ratings to NOT be outdated, and I'll run the file so that it sets to outdated only the ratings of sentences mentioned in there.

**Comment by ckjpn** [comment]
I've already reset all the previously wrong ones.

If this is a reoccurring problem, I'll probably just ignore making changes in the future.

I already keep a list of sentences I use.  I do my filtering each week based on my list 907.

 I really only add the OK rating as a service to those who use the website, since otherwise they can't see which sentences I've proofread and okayed.   If a small percentage of these say "outdated", it's probably not that big a problem, since now I'm also tagging sentence with "List 907".

**Comment by ckjpn** [comment]
Perhaps one possibility that would lower the number of incorrect "outdated" tags would be to make it so that adding an audio file to a sentence doesn't change the modification date of that sentence. This would seem logical, since no actual change has been made to the text of the sentence.   Maybe there is some reason on the website for changing the modification date when adding an audio file, but it doesn't seem to make sense to me when using the sentences_detailed.csv file, since the implication is that the text of the sentence has been changed.
