### ISSUE TITLE
Make a downloadable file that includes all the outdated ratings.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1358]
In addition to the "users_sentences.csv" make an "outdated_ratings.csv" file.

username  + [tab] +  sentence number

OR

username  + [tab] +  sentence number   + [tab] +  rating number

The first way would be enough for me.  However, perhaps others would find it useful to also include the current rating.

**Comment by halfdan** [comment]
What's the use case for this?

**Comment by ckjpn** [comment]
It would make it possible to review what's outdated offline, and then use a script to reset all the ones that are still OK.

**Comment by halfdan** [comment]
Is there any reason you prefer to do this offline instead of having an admin page built for this?

**Comment by ckjpn** [comment]
It saves me time.

However, if this is too difficult to do, then this issue can be closed.

**Comment by trang** [comment]
Technically, you can find out which reviews are outdated by comparing the "Date last modified" of the sentence in `sentences_detailed.csv` and the "Date last modified" of the review in `users_sentences.csv`.

I'm closing this because I think this is a very specific need that does not justify changing our export script.
