### ISSUE TITLE
Change access to MP3 files from https:// to http://

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1374]
Change access to MP3 files from https:// to http:// if there is no security reason for this.

I've noticed that there is often a delay in getting the audio while Chrome is establishing a secure connection.  I assume the delay happens in other browsers as well.

What kinds of problems would occur if we used http instead of https?

If there are no security problems with this change, then making this change would speed up the site a bit.

**Comment by jiru** [comment]
There are several reason not to switch back to http.
* Leakage of session cookies when playing audio, allowing impersonation of members using man-in-the-middle attack. It is especially very easy to do if the attacker is on the same network (LAN or wireless), even for non security experts
* Similarly, leakage of what sentences I listen to and the URL of the page from where I click the audio button.

Anyway, because of these concerns, modern browsers like Firefox *will* block the download of the audio file if it is requested through http from an https page, and issue a warning about mixed content.

@ckjpn, please, please, follow the [guidelines](https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-issues) when submitting issues: *When creating new issues, the main thing we would like you to remember is to focus on describing the problem, not the solution.*

About the delay, it needs to be further investigated, but I rather think it is due to the Flash player. So I suggest we close this issue in favor of #941.

**Comment by ckjpn** [comment]
Here is it restated with the problem stated first.

## Problem.

I've noticed that there is often a delay in getting the audio while Chrome is establishing a secure connection. I assume the delay happens in other browsers as well.

## Possible Solution

Change access to MP3 files from https:// to http:// if there is no security reason for this.

If there are no security problems with this change, then making this change would speed up the site a bit.

## Question

What kinds of problems would occur if we used http instead of https?

**Comment by ckjpn** [comment]
I doubt if it's the Flash player, since Chrome clearly states in the "status" bar thing at the bottom of the page that it's waiting for a secure connection.

**Comment by trang** [comment]
Closing this as we will not switch back to http and the delay may be fixed with #1397.

@ckjpn if you are still experiencing delays when trying to play audio, please create a new issue.
