### ISSUE TITLE
Copyright notice in page footer - change needed

### ISSUE THREAD

**Issue by NiallTracey** [Tatoeba/tatoeba2#1392]
The current copyright notice on main pages is as follows:
"_Our sentences and translations can be used under the Creative Commons Attribution 2.0 license (CC-BY 2.0). 
If you love this content, please consider a donation_."

Reading this, I would understand this to include both text and audio "sentences", but I know that this is only intended to refer to text versions, and that audio files have separate licensing. This should be made clear, as at present I believe the wording would allow anyone to use any audio content on the site under the cc-by license.

**Comment by trang** [comment]
Thank you for reporting this.

The CC-BY license indeed doesn't apply to audio, only to the textual corpus. 

On the legal aspect, I don't think any serious business/project will rely purely on the statement in the footer to assume that all audio can be re-used CC-BY. 
The footer is a place where we have some constraints in terms of how much we write (we don't want to write a wall of text or something too complicated) and these constraints makes us write simplified statements that can turn out to be too ambiguous to be considered as legal material.

Do you have an idea of how the text can be rephrased? My only solution right now is to say "Our **textual** sentences and translations can be reused...", but that sounds plain weird.

@alanfgh, any suggestion here?

For the context, audio was initially not meant to be redistributed or reused elsewhere than on Tatoeba. As you can see, our "Downloads" page only lists files for the textual corpus: https://tatoeba.org/eng/downloads
You won't find anywhere on Tatoeba a page that explicitly says "Download audio".

Audio was added to Tatoeba from popular demand. Many users would tell us "oh it would be nice to have audio", and someday we introduced audio, but without really thinking about licenses. Time went by and we realized that some people would like very much to reuse the audio in Tatoeba, and some contributors may be glad that their audio are reused in other projects, but of course, we didn't want to force them to share their audio under CC-BY exclusively. Some contributor are not okay with work being reused in commercial projects.

As a result, we established that contributors who want to share their audio will mention it in their profile. But as of today, Tatoeba doesn't take the responsibility of facilitating the distribution of these audio. Either the contributors have their own webpage where they provide with a ZIP of all their audio, or they will send their audio on request via email, or they will contact Tatoeba and say "hey, someone contact me to ask if they could use my audio and I'm okay with it but I don't have the audio on my computer anymore, can you maybe send them for me?", or the requester will download manually each audio file they need one by one.

**Comment by alanfgh** [comment]
You could say:

Our sentences (exclusive of audio) and translations can be used under the Creative Commons Attribution...

or:

Our written sentences and translations...

**Comment by ckjpn** [comment]
Perhaps adding a "more info" link to http://en.wiki.tatoeba.org/articles/show/using-the-tatoeba-corpus would be a good idea.


Our written sentences and translations can be used under the Creative Commons Attribution 2.0 license (CC-BY 2.0).  ([More Info](http://en.wiki.tatoeba.org/articles/show/using-the-tatoeba-corpus))

**Comment by trang** [comment]
I'm thinking about turning `sentences and translations` into a link that redirects to the "Downloads" page, and on the downloads page we can have an extra section in the sidebar that explains about the audio.

**Comment by alanfgh** [comment]
I prefer CK's approach: "Our written sentences and translations can be used under the Creative Commons Attribution 2.0 license (CC-BY 2.0). (More info)" This makes a true statement (namely, that all our written sentences and translations can be used under CC-BY 2.0), then provides a "More info" link that allows you to find out that some audio can be used, too. By contrast, if they are assuming that "sentences and translations" includes all audio because we haven't qualified the original statement, then the more complete statement that they see later might feel like backtracking. It's the difference between an ad that tells you that there's a bonus beyond what the ad originally promised ("But wait! There's more!") and one that concludes with someone reading the "fine print" at a high speed ("Restrictions apply. Good only while supplies last...").

**Comment by trang** [comment]
1) Should we have parenthesis around `More info`?

> Our written sentences and translations can be used under the Creative Commons Attribution 2.0 license (CC-BY 2.0). [More info](https://tatoeba.org/eng/downloads)

or

> Our written sentences and translations can be used under the Creative Commons Attribution 2.0 license (CC-BY 2.0). ([More info](https://tatoeba.org/eng/downloads))

2) What do we write on the "Downloads" regarding the audio? This is my suggestion:

> **Audio have different licenses**
>
> Please be aware that the CC-BY 2.0 license applies to the content of the CSV files only. They do not apply to the audio files. The license of the audio varies depending on the contributor of the audio and is indicated on the page that lists the audio of the contributor.

**Comment by ckjpn** [comment]
2.

FROM:
 They do not apply to the audio files.
TO:
 It does not apply to the audio files.

**Comment by alanfgh** [comment]
(A) I don't have a strong preference about the presence of absence of
parentheses. I would probably write "information" instead of "info",
considering that this is a page about legal issues.

(B) I agree with CK's change ("They do not apply" -> "It does not apply").

(C) "Audio" is a non-count (mass) noun. I would change "Audio have
different licenses" to one of these:

"Audio is covered by other licenses"
"Audio is covered by a variety of licenses"
"Audio is covered by different licenses"
"Licenses covering audio"
"Licenses for audio"
"Audio licenses"

I lean toward "Licenses covering audio", but it's not a strong preference.

(D) "The license of the audio varies depending on the contributor of the
audio and is indicated on the page that lists the audio of the
contributor." ->

"The license covering an audio file is chosen by the contributor, and is
indicated on the page that lists the audio files that he or she has
contributed."
