### ISSUE TITLE
The duplicate-merging script has deleted both sentences, rather than just one sentence of a pair of duplicates.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1407]
I noticed this on one of my sentences, and posted a comment about it.

https://tatoeba.org/eng/sentences/show/5854702

Another member has posted an additional comment about this.

Perhaps until this bug gets resolved, it might be a good idea to stop Horus for running the script.

Maybe this is just a one-time happening, but if it isn't, Horus may be doing damage to the corpus.

**Comment by jiru** [comment]
Maybe this is happening when two instances of Horus are running at the same time because one is not completed while the next one starts already?

Maybe this has to do with manipulating audio while Horus is running?

I’d need more examples of such mistakes to find out the reason why Horus deleted both sentences.

**Comment by jiru** [comment]
In the past, I witnessed multiple instances of Horus running simultaneously during high load. My guess is that this was causing the problem. This shouldn’t happen any more so I’m closing this issue. Feel free to reopen if you see this problem again.
