### ISSUE TITLE
Some sentences get duplicated even with Horus 

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1469]
[Reported by PERCE_NIEGE](https://tatoeba.org/eng/sentences/show/1158299)

"Horus" (The Tatoeba's duplicate bot) was supposed to delete duplicate sentences and merge them by keeping the original sentence. However, it didn't happen on [here - original](https://tatoeba.org/eng/sentences/show/8745) and [here - duplicate](https://tatoeba.org/eng/sentences/show/1158299).

**Comment by alanfgh** [comment]
One of the sentences has a nonbreaking space before the exclamation mark, and the other has a regular space. There are many such pairs of duplicate sentences in French. In order to fix this situation, we would need not only code, but a policy decision, preferably made by a majority of French speakers who express a preference. We would need to choose between one of the following:

(1) For French sentences, change every nonbreaking space before final punctuation into a regular space, first for every existing sentence, and then whenever a sentence is added.
(2) Do the same as (1), but in the reverse direction.
(3) Change the deduplication algorithm so that the comparison between sentences is insensitive to the difference between nonbreaking spaces and regular spaces, so the decision as to which is preserved is based on the other criteria (such as which sentence is older).

Approach 3 would require more programming effort and more execution time (perhaps a lot more). Approach 1 or 2 would require one pass that would take a while, but after that, converting the nonbreaking space to a regular space, or vice versa, each time a sentence is added would be pretty quick. Trying to get agreement from the community on whether to choose between 1 and 2, and then making sure that someone with programming capabilities wanted to sign up for doing it would be the challenge.

**Comment by trang** [comment]
This issue has been reported in #770. I'll close this one.
