### ISSUE TITLE
Restore modifications and deletions of sentences

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1484]
When we used the CSV files to restore data that was lost between February and June, only addition of content was restored (i.e. new sentences, new comments, new tags, etc)

Modifications and deletions were not restored. We cannot restore it for all content (such as comments), but we can do it for sentences, since we have logs for sentences.

For example: https://tatoeba.org/eng/sentences/show/76450
The sentence was modified on Feb 20, but the sentence text is set to the original value.

Related Wall thread: https://tatoeba.org/eng/wall/show_message/28429#message_28429

**Comment by ckjpn** [comment]
See https://github.com/Tatoeba/tatoeba2/issues/1504 for a list of all such sentences and a Python script that can help find the most recent revision based on a comparison of the pre-crash export and the current export.

**Comment by trang** [comment]
I had a look at the file, and the content seems fine. I didn't look in details at the script though.

I guess we could go ahead and replace the text/owner of the sentences in the database by the text/owner of the sentences in the file. I should be able to take care of this next weekend. It would be nice if by then other people could verify the script, or/and the content of the generated file.

**File:** [sentences_detailed_ONES_NEEDING_REVERTED 2017-09-11.zip](https://github.com/Tatoeba/tatoeba2/files/1291096/sentences_detailed_ONES_NEEDING_REVERTED.2017-09-11.zip)
**Script:** [fix-sentences_detailed - version 2.zip](https://github.com/Tatoeba/tatoeba2/files/1291099/fix-sentences_detailed.-.version.2.zip)

**Comment by ckjpn** [comment]
Newer files are here.

http://iteslj.org/tatoeba/

**Comment by trang** [comment]
Modifications of sentences should be restored now.
I ran the following script: https://gist.github.com/trang/66835392f279653b1aa0c4647938bfdb

I noticed that some sentences had a modification that was not logged. I'm not sure if that modification was simply never logged, or if we lost the logs for it...

For instance https://tatoeba.org/eng/sentences/show/330

The text is now:
> „Ich habe Lust, Karten zu spielen.“ – „Ich auch.“

But in the logs we only see that it was created as:
> "Ich habe Lust, {Karten}{1} zu spielen." "Ich auch."

Anyway, @ckjpn If possible have a look if the replaced sentences are now okay. I'll close this issue and open new ones for potentially missing logs and for restoring deletions of sentences.

**Comment by trang** [comment]
Re-opening, I've reverted the modifications made by script.

There is a problem with sentences that have been modified recently.

For instance sentence 3333 has been modified lately by Aiji.
```
3318	fra	"Pierre qui roule n'amasse pas mousse" est un proverbe.	trotter	\N	\N	LAST GOOD Export 2017-06-10
3318	fra	« Pierre qui roule n'amasse pas mousse » est un proverbe.	trotter	\N	2017-10-06 03:15:28	CURRENT Export
```

If I replace the current text by the text from the generated file, I will erase the good version of the sentence.

**Comment by ckjpn** [comment]
The problem with the previous file of corrections was caused by the \N in the date fields.  Python couldn't correctly compare \N with a date.
I converted all the \N in the 5th and 6th fields to 0000-00-00 00:00:00 and then did the comparisons.

Note that in the current exported data that there is a problem with the modification date being \N when no modification has taken place, which was part of the problem.

For these corrections, I used the first export after the crash (2017-07-01), so that corrections made by Aiji and adopted by him correctly give him credit. Some were only adopted I think with no corrections needed.  He said on the Wall that some of the sentences he had previously adopted were being adopted by other members. It seems only fair to give these sentences to the person who adopted them first.


Attached are 3 files.

_about.txt

sentences_detailed_CORRECTIONS_NEEDED 2017-10-17.txt
-- the file you need to make revert the modifications

sentences_detailed_ONES_NEEDING_REVERTED_pairs 2017-10-17.csv
-- a file with both the line from the "last good export" and the "first export after the crash".

[sentences that need modifications reverted 2017-10-17.zip](https://github.com/Tatoeba/tatoeba2/files/1389290/sentences.that.need.modifications.reverted.2017-10-17.zip)

**Comment by trang** [comment]
Thanks for the fix @ckjpn.

I've applied the changes in the database. Please have a look :) Hopefully everything's fine this time.

**Comment by ckjpn** [comment]
There are 1,319 sentences in the latest export between 1 and 6139244 that were not in the 2017-06-10 export.  6139244 was the last sentence in the 2017-06-10 export.

Probably, it would be safest to not try to delete these, until after the duplicate-merging script has successfully run and merged translations, since some of these deletions might have been done by Horus.

The attached file contains these sentences numbers, if you want to glance through them.

[possibly deleted sentences that need to be re-deleted.zip](https://github.com/Tatoeba/tatoeba2/files/1406333/possibly.deleted.sentences.that.need.to.be.re-deleted.zip)

**Comment by ckjpn** [comment]
At least one sentence didn't get reverted to the pre-crash correction.

https://tatoeba.org/eng/sentences/show/5850144

**Comment by trang** [comment]
I've deleted sentences that were deleted pre-crash (1396 sentences).

For the record, these are the deleted sentences:
https://gist.github.com/trang/3a658ec28a8e76227c563ef5fff64b38

**Comment by jiru** [comment]
Can we close this issue?

**Comment by trang** [comment]
Yes.

I didn't close it because there was still links to restore. But that would be another issue.
