### ISSUE TITLE
Re-install wiki

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1501]

**Comment by ckjpn** [comment]
Temporarily, I'd suggest that you put this file into /app/View/Elements

I changed 3 pages within lines 45 to 63 to include direct links to the 3 links at the bottom of every page.
This way, new members and older members alike can find the documentation rather than not get anything.


[foot.zip](https://github.com/Tatoeba/tatoeba2/files/1403679/foot.zip)

                    __('Quick Start Guide'),
                    'http://web.archive.org/web/20170606014940/http://en.wiki.tatoeba.org/articles/show/quick-start'
                );
                ?>
            </li>
            <li>
                <?php
                echo $this->Html->link(
                    __('Tatoeba Wiki'),
                    'http://web.archive.org/web/20170606132808/http://en.wiki.tatoeba.org/articles/show/main'
                );
                ?>
            </li>
            <li>
                <?php
                echo $this->Html->link(
                    __('FAQ'),
                    'http://web.archive.org/web/20170606120047/http://en.wiki.tatoeba.org/articles/show/faq'
                );

**Comment by ckjpn** [comment]
I wonder if now might not be a good time to convert over to using Wikimedia.

https://www.mediawiki.org/wiki/Download

I haven't used it myself recently, but when I installed it a long time ago, it was very easy to do.

One advantage over the previous Tatoeba Wiki software would be that it uses a markup language that many, many people already know since Wikipedia is such a big part of the Web.


I suspect that the reason our wiki hasn't yet gone back online is that it's a difficult installation that maybe only sysko understands how to do.

**Comment by Ppjet6** [comment]
On 2017/10/20, ckjpn wrote:
> I wonder if now might not be a good time to convert over to using Wikimedia.
> 
> https://www.mediawiki.org/wiki/Download
> 
> I haven't used it myself recently, but when I installed it a long time ago, it was very easy to do.
> 
> One advantage over the previous Tatoeba Wiki software would be that it uses a markup language that many, many people already know since Wikipedia is such a big part of the Web.
> 
> 
> I suspect that the reason our wiki hasn't yet gone back online is that it's a difficult installation that maybe only sysko understands how to do.

No, the main reasons our wiki isn't back online yet are time and
motivation.

Also I remember people told me but I need to ping them again to know
where to find things.

-- 
Maxime “pep” Buquet

**Comment by Ppjet6** [comment]
I got something working!
I'll post on the wall asking for people to report if they find anything weird/broken.

**Comment by Ppjet6** [comment]
@ckjpn, assuming we have the necessary resources (people, time, etc.), I agree that we might want to look into a more commonly used solution. Setup + migration will be necessary.

Sysko's solution has a few quirks, (not much documentation, no logs, and possible vulnerabilities), but for the time being it works, so this is not on my priority list.

**Comment by ckjpn** [comment]
This can now be closed.
