### ISSUE TITLE
names of countries in the drop-down list in the profile are not internationalized

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#151]
tommy_san pointed out that the names of the countries in the drop-down list in a user's profile appear only in English.

**Comment by lagleki** [comment]
Why not add these strings to Transifex so that we can quickly localize them?

**Comment by jiru** [comment]
First, the list of countries is stored in database instead of the source code, so it needs a little bit of work to add them to Transifex. Second, the list is out of date: it includes countries that doesn’t exist anymore. And finally, countries names have already been translated into many languages by e.g. CLDR, so we’d better use their data instead.
