### ISSUE TITLE
License selection for new sentences

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1553]
On the page "Add sentences", in addition to the "Language" and "Sentence" fields, we will need a 3rd field as dropdown where people can select a license.

<img width="517" alt="license-new-sentences" src="https://user-images.githubusercontent.com/221850/40888835-70318d40-675d-11e8-9807-a0ee152030da.png">

**Comment by jiru** [comment]
I wonder if it's a good idea to put a license dropdown here, because:
1. I think most people won't need to switch license when adding new sentences. Most people are likely to stick to a single license for all their sentences.
2. It will confuse people who don't know what a license is. What should I select here? What’s the meaning of CC-BY? That could be especially negative for new contributors.

How about having a text like "Your sentence will be published under the CC-BY license ([learn more](https://tatoeba.org/somewhere))" close to the submit button? The "learn more" link could bring the user to a page that explains licensing, allows to change the default license under which sentences are published etc.

**Comment by trang** [comment]
I wouldn't make early assumptions as for how many people will be switching licenses. Besides, the way we implement the feature will have an impact. If we don't manage to make it intuitive and clear enough, then people will less likely switch between licenses.

But you're correct, people who don't know about licenses and don't know about CC-BY will be confused if they just see a dropdown listing some accronyms they never saw before.


For your suggestion, I think that with only "learn more" some people may not even realize they can choose another license.

So we could have:
Your sentence will be published under the [CC-BY]() license. [[Learn more]()] [[Change license]()]

Or:
Your sentence will be published under the [CC-BY]() license. [[Change license]()]


We can also just keep the dropdown and have a question mark icon next to it. Clicking on this question mark icon would lead to a page explaining the licenses.

**Comment by jiru** [comment]
Thanks for your comment. I eventually kept your initial design, because I’m not sure about what to do, and we can rearrange things later on. This is functional already.

Currently, when adding sentences through other pages (like /vocabulary/add_sentences),  the value of the license is read from the "default_license" user setting, which is yet to be made editable and defaults to 'CC BY 2.0 FR'.

**Comment by trang** [comment]
Tricky situation reported by [Ricardo on the Wall](https://tatoeba.org/eng/wall/show_message/29537#message_29537):
* User A adds `Sentence A` with CC-BY.
* User B later adds `Sentence A` with CC0. 

With our current system, user B wouldn't be able to add their sentence at all and `Sentence A` will not be reusable under CC0.
