### ISSUE TITLE
UI Enhancement - Make the dropdown user menu match the right column on the profile page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1580]
It would be nice if "Audio" and other items in the right-hand column were also on the dropdown menu.  This should be easy to add.

<img width="975" alt="screen shot 2018-06-22 at 12 16 11" src="https://user-images.githubusercontent.com/7934273/41756329-fbc7a50c-7616-11e8-883b-74b1d97e6cd8.png">

**Comment by ckjpn** [comment]
Another matter that is related, but not all that important maybe is that you might want to reconsider the order this items appear, putting the high priority items used by almost all members at the top.

Some members don't likely use "My vocabulary", "My collection", "My lists", "(My) Audio" and maybe others.
Perhaps these should be moved lower on the list.

**Comment by jiru** [comment]
> This should be easy to add.

Yes. However it would be useless for members who don’t have any audio, which is the vast majority. I think this menu is way too long already. Any idea about how to shorten it? We could remove some entries that are not very frequently used, and/or only start showing entries if they bring to a page with contents. For example, "My sentences" wouldn’t show up unless the user has at least one sentence, same for "My audio" etc.

**Comment by ckjpn** [comment]
I can see how the menu might be too long for mobile devices, since tatoeba.org hasn't yet been optimized for mobile use.  However, once it is, using Bootstrap or some other similar option, then the longer menu is likely not to be a big problem.

**Comment by trang** [comment]
I reordered the items on the profile page so that they match the dropdown in the menu. The "Audio" and "Transcriptions" have been moved below the "Logs" and there is darker separator to sort of hint that those two items are not part of the dropdown.

I think that's the best we can do for now.

What items we should add or remove from the dropdown, and in what order they should be, is still too subjective at this point.

Listing only items that have content for the user is a good idea to explore, but would be much higher effort than settling down on an arbitrary list.
