### ISSUE TITLE
Allow to play audio on the new design

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1592]
Considering that
1. the majority of the visitors, who are guests, are seeing [sentences with the Material design](https://i.gyazo.com/df924e72badea27efdf90b67b45c2031.png) (except on the sentence page)
2. the audio database has grown into something quite big, and is still growing

We should consider adding a button to play audio on the new Material design.

**Comment by Poulpisator** [comment]
[Yes](https://tatoeba.org/fra/wall/show_message/28536#message_28536) indeed! :)

**Comment by ckjpn** [comment]
I think that until this is done, it would be a good idea to change the default for non-logged in visitors to be the same as for logged-in visitors who have "Display sentences with the new design. Note that you will not have all the features from the old design." unchecked.

I assume that this would be a very easy change to make.
This would likely give visitors a more positive experience.

See how useless a search like this is if you are not logged in.


https://tatoeba.org/sentences/search?trans_filter=limit&trans_link=direct&from=eng&to=fra&list=907&has_audio=yes&trans_to=fra&sort=random
Show a randomly-selected set of English-French pairs in which the English has audio.



Someone who was was testing my page "How to Use the Tatoeba Corpus to Study English"  pointed this out to me the other day.

http://www.manythings.org/tatoeba/eng/

**Comment by ckjpn** [comment]
Once more, I'd like to suggest giving non-logged-in visitors the full working design rather than the experimental new design.

It would be a lot easier to introduce tatoeba.org to new people if they could get a fuller experience without needing to log in.

It somehow seems wrong to me to have an experimental "new design" being the default for the website, requiring visitors to log in to get the fully functional design.

**Comment by trang** [comment]
The old design comes with the issue that people do not understand what are the "grey translations". Perhaps they don't even notice there are two types of translations.

If we were to make the old design the default one for unauthenticated users, then we would need to at least take care of #1874 before.

The amount of effort it would take to integrate audio on the new design is not significantly higher than the effort it would take to revert to the old design for unauthenticated users, so in my opinion, it would make more sense to work on integrating audio on the new design.

**Comment by ckjpn** [comment]
Sorry.  I had assumed that since it was possible to get the full version as a setting for members that it would be easy to just make that same setting for non-logged-in members.

I also didn't realize that it would be hard to insert this little bit of code that I suggested.
I'm not that familiar with CakePHP.

https://github.com/Tatoeba/tatoeba2/issues/1874#issuecomment-507538977

**Comment by trang** [comment]
You're misunderstanding it. It would not be too difficult to add audio to the new design just like it would not be too difficult to make indirect translations more explicit on the old design and revert to it for non-authenticated users.

**Comment by ckjpn** [comment]
I still would love to be able to send my students to a search like this and let them easily listen to the audio the same way logged-in members can.

https://tatoeba.org/eng/sentences/search?from=eng&trans_to=und&query=found+out&to=jpn&sort=words&has_audio=yes

I was just thinking that if it's going to take a long time before this issue is resolved, then reverting back to the pre-new layout would be useful right away.  This issue is already over a year old and the new layout for non-logged-in visitors has been a problem even longer than that.

If reverting back to the usable version isn't something that can be done in less than an hour, I can understand why you're not willing to do so.

**Comment by trang** [comment]
There's nothing insulting in what you wrote CK, but you know, repeating over three comments that you think it would be really good to get this done, isn't going to get this done any faster.

I completely agree that it would be good to have the audio feature on the search results for guests, and I have confirmed to you that it would not be too hard do (very likely less than an hour). But please keep in mind that just because something is quick to do doesn't mean it will be done ASAP.

**Comment by ckjpn** [comment]
There is something to be said for making the website work better for visitors who arrive on the website today.

According to Google Analytics, in the past week we had over 31,000 new users (86% of the visitors).
We had a 13.4% for returning visitors.

For the whole past month, it was 139,000+ visitors and 11.3% for returning visitors.

While, of course, a certain number of new visitors just accidentally come to the website and would likely never come back, a certain number of these might return and become contributing members  if they had a positive experience when they visited the website.

I guess that is what I'm really trying to point out.  It might be worth an hour of your time.

**Comment by alanfgh** [comment]
CK, you're being a nudnik. Look it up. Trang agrees that this would be a good change, but she has other things to do, both on Tatoeba and in her own life. One of the things you're forcing her to do is reply to your repeated requests. You have no idea what a drain on her time and energy that represents. Give it a rest.
