### ISSUE TITLE
Setting controlling number of sentences per page is ignored

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1597]
My settings specify that I want to see 20 sentences per page. However, when I go to a page (for example: https://tatoeba.org/eng/sentences/of_user/AlanF_US ), I see 100 sentences on it. Changing the setting (for instance, to display 10 sentences per page) has no effect.

**Comment by jiru** [comment]
Yes, this page always shows 100 sentences per page regardless of that setting. I think it makes sense on that page to show more sentences than the default 10, because the list is quite compact. It is however in contradiction with the setting.

**Comment by alanfgh** [comment]
@jiru wrote: 

> I think it makes sense on that page to show more sentences than the default 10, because the list is quite compact.

Screen real estate is not the only consideration. I want to choose how many sentences are displayed on any page because it's hard to keep track of my progress when there are too many. For instance, I might want to go through a contributor's list of sentences in order to correct them, but when more than 20 are displayed on a page, I lose track of where I am.

**Comment by agrodet** [comment]
I share Alan's opinion.
@jiru Is it okay to take care of this or do you have any worries about the modification? I haven't checked in detail but I think it is just a matter of modifying the following line. 

https://github.com/Tatoeba/tatoeba2/blob/3f71e6d5c206a194cf7f426f9403a0f92af9d053/src/Controller/SentencesController.php#L917

**Comment by jiru** [comment]
@agrodet yes this the correct place to tune the number of sentences.

I often use this page to have an overview of the sentences of a user. It this case I prefer to see a lot of sentences at once because I'm quickly going through them (as opposed to stopping on each of them to think about it).

I think my problem is less about that particular page than about having a unique user setting that controls the number of sentences per page everywhere. I have the feeling that the number of sentences per page depends on the use case, not the user. Besides, I believe that having it "hidden" in the user settings makes it underused or unbeknown to most people. There must be some way to better allow people to control this.

So yeah, @agrodet I think you can go ahead.

**Comment by alanfgh** [comment]
@agrodet, thanks for fixing this. @jiru, I agree that it would be better to be able to set the number of sentences per page by use case rather than in general. However, at least @agrodet's change lets the user control the behavior, which is an improvement, and we can think about adding more fine-grained control in the future.
