### ISSUE TITLE
Copy button overlaps with red sentences warning sign

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1598]
When a sentence is in red and you activate the copy button (and do not use the new design), the [warning sign overlaps with the copy button](https://tatoeba.org/sentences/search?query=&from=und&to=und&orphans=no&unapproved=yes&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=yes&trans_has_audio=&sort=words).
![screenshot-2018-7-4 recherche avancee tatoeba](https://user-images.githubusercontent.com/5107734/42293399-81780f20-7f9f-11e8-90b3-db97e325e4a3.png)

**Comment by agrodet** [comment]
I had a look at the CSS, always fun... Probably things have changed since your post since I can see the icon correctly displayed on the main sentence (Firefox). However, the translations still has the issue. Anyway, an `overflow:hidden` later, here's what I obtained. Excuse the content of the sentences, I felt creative...

With the list icon:
![image](https://user-images.githubusercontent.com/42261966/74521926-9515ad00-4f5d-11ea-9035-b9892959d71d.png)

Without the list icon:
![image](https://user-images.githubusercontent.com/42261966/74521972-a65eb980-4f5d-11ea-809d-fc09b50b2fe2.png)

Also, I found one or two other CSS rules that, I think, could be improved / modified. If these screenshots are okay, maybe I could open a PR to modify some CSS rules. 

We can see that the red icon is slightly higher than the other icons. This can be arranged on the main sentence, but not on the translations, because the height of one div is too small, nearly over 16px. So if we align the red buttons, they will actually be cropped (like they are now on the main site, I think?). One solution would be to slightly increase the div height to be able to align the red icons with the two other. (Also, the list and audio icons currently exceeds the div bottom so that could look better).

Please tell me what you think.

**Comment by trang** [comment]
It's good enough.

We don't have that many red sentences and the old sentence design is meant to disappear fairly soon (max two months, I hope). I won't bargain for 2 pixels of misalignment :P
