### ISSUE TITLE
Gheg Albanian (aln)

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1600]
- Language name: Gheg Albanian
- Language info: https://en.wikipedia.org/wiki/Gheg_Albanian
- ISO 639-3 code: aln
- Public List: https://tatoeba.org/ita/sentences_lists/show/7907
- Icon: probably the Albanian flag with the ISO code in it? (suggestions about this are welcome)
- Requested by: https://tatoeba.org/ita/user/profile/aln

**Comment by RyckRichards** [comment]
@cueyayotl

**Comment by cueyayotl** [comment]
Thank you Guybrush88, but let me be the guy to open the lang-request issues :)

- Language name: Gheg Albanian
- Language info: https://en.wikipedia.org/wiki/Gheg_Albanian
- ISO 639-3 code: aln
- Public List: https://tatoeba.org/eng/sentences_lists/show/7907
- Icon: https://i.imgur.com/SqXsJTm.png
- Requested by: https://tatoeba.org/eng/user/profile/aln

[for tatoeba.org]
CALL add_new_language('aln', 7907);

**Comment by cueyayotl** [comment]
I'm thinking that it would be more wise to add this language as "Albanian (Gheg)", rather than "Gheg Albanian", so that it is more easily searchable for new users in the future.

**Comment by RyckRichards** [comment]
taking it

**Comment by jiru** [comment]
> I'm thinking that it would be more wise to add this language as "Albanian (Gheg)", rather than "Gheg Albanian", so that it is more easily searchable for new users in the future.

I agree about the search, however we already have a language called "Albanian", which means we will have two languages known as Albanian, named like this:
* Albanian
* Albanian (Gheg)

Now, I’m confused: it’s not really obvious what "Albanian" alone means. I suggest we add something between parenthesis to the existing "Albanian" too.

According to the [article about Albanian language on Wikipedia](https://en.wikipedia.org/wiki/Albanian_language), our existing Albanian (ISO code sqi) is a macrolanguage (like "Chinese"). It includes Gheg Albanian among with other varieties. So it’s unclear to which dialect it refers. Maybe we should ask "aln" (the user who requested inclusion of Gheg Albanian) about the status of the current Albanian corpus and how to better name Albanian.

**Comment by jiru** [comment]
Yes, it makes sense. If we say our current Albanian (SQI) encompass various non-Gheg Albanians, then it’s probably fine like this.

Off-topic: this makes me think that maybe we want to have a standard place on Tatoeba to gather this kind of information about each language. We could have a standard page for each language that describes it. Because now, the only thing we have to describe each language is a name and an ISO code. Such page could be also used to gather useful information and stats about the language, like who’s native speaker, who’s corpus maintainer, and how to contact them (#1200), how many contributors, who’s the most active etc.

**Comment by RyckRichards** [comment]
+1
