### ISSUE TITLE
More suitable fonts to improve accessibility

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1630]
Using this article as a starting source http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf and a bit of research I did on other sources, it seems that good fonts for people with reading issues can be mostly Arial and Verdana (which seem to be the most recommended ones wherever I looked at). Switching to one of these fonts instead of the current ones might significally improve the possibility for everyone to read anything that appears on Tatoeba.

**Comment by Guybrush88** [comment]
here are other links for suggestions:
https://www.dyslexicadvantage.org/the-best-fonts-for-dyslexia/
https://bdatech.org/what-technology/typefaces-for-dyslexia/
https://www.dyslexic.com/fonts/

**Comment by trang** [comment]
In the current approach of how we define fonts, we don't exactly force people to a specific font. We defined "Noto Sans" as our default font, but people would need to download and install this font in order to see Tatoeba with Noto Sans. If they don't have it, they will see the text with the default sans-serif font that is defined in their browser (usually Arial).

Whether or not we keep this issue opens depends on whether we believe that we should use an embedded webfont. This ensures everyone sees Tatoeba with the same font, even if they don't have it installed, and we can make sure it's an accessible font.

As far as I'm concerned, I feel we don't have to change the way things are now. I don't know how Noto Sans works for dyslexic people, but I suppose if it doesn't work for them they won't have it installed. I also assume that browsers have by default an accessible sans-serif font defined in the settings. If that's indeed the case, dyslexic people should be already seeing Tatoeba with an accessible font.

**Comment by Poulpisator** [comment]
Yes, they usually have well parametrized browsers and may even use plugins specially built for dyslexia, or to at least ease the reading process. It is also worth noting that Noto Sans and Arial are quite similar. Noto Sans is slightly more skewed on some letters and more round on points so the impact on reading would be, I guess, negligible (since the two letters the most different are probably t and f). 

Funny thing that a font display problem was reported [on the wall](https://tatoeba.org/fra/wall/show_message/29594#message_29594) just three days ago.

**Comment by trang** [comment]
Closing this issue then.
