### ISSUE TITLE
Probably not everything was restored after the last big crash

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1631]
I was browsing random sentences, and I stumbled upon this one: https://tatoeba.org/ita/sentences/show/6103416

Currently, only indirect sentences appear under this sentence, even if it appears to be linked to this sentence: https://tatoeba.org/ita/sentences/show/6103407

The problem is that the English sentence does not exist anymore, but the logs (both in the English sentence and every linked sentence) don't show any deletion of such sentence.

**Comment by jiru** [comment]
It should be possible to find all sentences affected using the following algorithm:
1. Find all the ids of sentences having an "insert sentence" entry in the log table.
2. Find all the ids of sentences having a "delete sentence" entry in the log table.
3. Find ids of set 1 not in set 2.
4. Find ids of set 3 not in the sentences table.

**Comment by trang** [comment]
Related issue: #1561

**Comment by trang** [comment]
Following the algorithm I came to this list: https://gist.github.com/trang/0aefcd7bc0e2a9279c4eaf496390e0ed

However this was not enough. Some sentences in there have really been deleted as duplicates, but they have no delete log because back then we didn't log deletion of duplicates.

I filtered the list to keep only the ID's of sentences that exist in the `sentences_detailed.csv` from 2017-06-10, that led to 292 sentences: https://gist.github.com/trang/b6172f7f72800c83e41dd8ea3c1963fb

I restored them yesterday. [Sentence #6103416](https://tatoeba.org/eng/sentences/show/6103416) now show up with its previously missing translations.

The reason why those sentences were missing was because I made a mistake when restoring the sentences back then (in some SQL query I used `JOIN` instead of `LEFT JOIN`) and orphan sentences got left behind.

Some additional things to do:
- Update the `based_on_id` field for these sentences. Running `bin/cake sentence_derivation` feels a bit overkill. Would there be another way?
- Re-index the sentences. I'm not too familiar with how the delta index works. Would it be enough to add the (sentence_id, lang) in the `reindex_flags` table?

**Comment by jiru** [comment]
> Update the based_on_id field for these sentences. Running bin/cake sentence_derivation feels a bit overkill. Would there be another way?

I don’t think it’s overkill because you only need to run it once. Running that shell will only update the based_on_id field that are NULL (since 56c361c822b3e6aa34dfe14bee9e26a3daa2cabb), so should be safe to run. I am not sure the shell is still working though.

> Re-index the sentences. I'm not too familiar with how the delta index works. Would it be enough to add the (sentence_id, lang) in the reindex_flags table?

Yes.

**Comment by trang** [comment]
The sentence_derivation shell is broken. I have created an issue for it: #1936.

Indexes have been re-created (#1929) so no need to fill up the `reindex_flags` table anymore.

Closing.

**Comment by jiru** [comment]
On August 3, 2019 1:11:15 PM UTC, Trang <notifications@github.com> wrote:
>
>Indexes have been re-created (#1929)

Not exactly. In #1929 I only recreated indexes that had updated MVAs. There happened to be about a dozen of them only (basically the most actives languages currently). So, consider recreating all the indexes just to be sure.

**Comment by trang** [comment]
> So, consider recreating all the indexes just to be sure.

Noted. Just to confirm, that would be done by:

- Disabling the cron jobs.
- `bin/cake sphinx_indexes main`
- Re-enabling the cron jobs.

Is that correct or is there other things?

**Comment by jiru** [comment]
On August 3, 2019 5:54:46 PM UTC, Trang <notifications@github.com> wrote:
>Is that correct or is there other things?

Yes that's correct. Consider running the cake command inside a `screen` session if your connection is unstable.

Also, the cake command won't start indexation if another indexation is running. It uses a lock file to prevent parallel runs that could otherwise overload the server. Because of this, you need to wait for any running reindexation to finish first, and in theory there is no need to disable the cron jobs because they won't start while your manual reindexation is running.
