### ISSUE TITLE
User should be redirected to last existing page when trying to go to a page that is too high

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1637]
I was unadopting some sentences, and, when I unadopted all the sentences in a single page (everything after page one, which doesn't trigger this) and refreshed the page, I got an error message telling me that the page doesn't actually exist. What I expected was being redirected to the previous existing page.

STEPS TO REPRODUCE
1. Go to the "Translate sentences of" page
2. Unadopt all the sentences in a given page (but not page one, it doesn't trigger this behavior)
3. Refresh the page

**Comment by Poulpisator** [comment]
This happens on any research (orphan, tagged, etc.) when being on the last page and cleaning / removing all the sentences of that last page, refreshing leaves us on the last page, that really does not exist anymore since there are not enough sentences to reach this page.

It was mentioned before somewhere but I can't find where. At that time, I suggested that when a page whose index is too big is accessed, it would redirect to the last page displaying result.
