### ISSUE TITLE
Yucatec Maya (yua)

### ISSUE THREAD

**Issue by tulakalbeyo** [Tatoeba/tatoeba2#1645]
* Language name: Maya Yucateco
* Language info: https://en.wikipedia.org/wiki/Yucatec_Maya_language
* ISO 639-3 code: yua
* Public List: https://tatoeba.org/eng/sentences_lists/show/8047
* Icon: https://i.imgur.com/qH2Wtwm.png
* Requested by: https://tatoeba.org/eng/user/profile/tulakalbeyo

[for tatoeba.org]
CALL add_new_language('yua', 8047);

**Comment by trang** [comment]
@tulakalbeyo Note that language requests are usually be created by @cueyayotl. You need to contact him as explained in the [wiki article](https://en.wiki.tatoeba.org/articles/show/new-language-request). He creates the issue in GitHub after evaluating if the request is valid.

I'll keep this issue open. We'll wait for his confirmation regarding this language request.

**Comment by cueyayotl** [comment]
Thank you for tagging me. As per adding a language, it is one of our rules that we must have a native speaker of that language (if not an extinct language) in order to be able to add it. As much as I would LOVE to have Yucatec Maya on Tatoeba, it doesn't seem to me that user tulakalbeyo is native, as he reveals himself to be from Tijuana, Mexico. Unless he can find a native Yucatec Maya speaker to join the Tatoeba Project as well, or otherwise demonstrate that he is a native speaker himself, I unfortunately cannot approve this language request, at least for now.

**Comment by jiru** [comment]
Note that according to the [Wikipedia article](https://en.wikipedia.org/wiki/Yucatec_Maya_language) you mentioned:

> To native speakers, the proper name is Maya and it is known only as Maya. The qualifier "Yucatec" is a tag linguists use to distinguish it from other Mayan languages (such as K'iche' and Itza'). Thus the use of the term Yucatec Maya to refer to the language is scientific jargon or nomenclature.[4]

So I wonder if the name "Maya Yucateco" is appropriate.

**Comment by cueyayotl** [comment]
Those who speak the language simply call it Màaya T'àan (or Maya talk). We here at the Tatoeba project DO use "scientific jargon", or more specifically, the terms used by ISO classification standards and the Summer Institute of Linguistics (SIL), much to the chagrin of some of our contributors or would-be-contributors. If this language is ever added, we WOULD call it:
Maya (Yucatec)

**Comment by tulakalbeyo** [comment]
that's right, the common endonym for the language is **maya t'aan**. my bad.

**Comment by RyckRichards** [comment]
@cueyayotl @sabretou should we close this issue?

**Comment by RyckRichards** [comment]
Nonong asked to have this language added. He gave us (the Language Team) the following:

Yucatec Maya (yua).

https://tatoeba.org/eng/sentences_lists/show/166719

https://geofictionist.fandom.com/wiki/File:Yucatec_Maya_(yua)_30x20.jpg

https://en.m.wikipedia.org/wiki/Republic_of_Yucat%C3%A1n

https://en.wikipedia.org/wiki/Yucatec_Maya_language

Should I open a new thread or can I work on this one?

**Comment by sabretou** [comment]
Let's go ahead in this one. I don't know if the flag of the Republic of Yucatan will be acceptable for this flag, however. I don't see it has having any connection to the Yucatec Maya language in particular. Perhaps it is best to go with a Mexico flag with the language code.

**Comment by soliloquist-tatoeba** [comment]
Info about Nonong's flag proposal:
https://en.wikipedia.org/wiki/Flag_of_Yucat%C3%A1n#Modern_usage

Compare:
https://en.wikipedia.org/wiki/Yucatec_Maya_language#/media/File:Yucatec_map.svg
https://en.wikipedia.org/wiki/Republic_of_Yucat%C3%A1n#/media/File:Mapa_Mexico_1847.PNG

@cueyayotl , @tulakalbeyo

I guess you are both from Mexico. What is your opinion on this? Is the proposed flag widely accepted and used by the native speakers as a cultural and historical symbol? Or is it rather considered controversial and extremist? Should we use the Mexican flag with the language code instead?

**Comment by nonongvik** [comment]
I like the Flag of Yucatán, but an alternative could be some Mayan glyph, like the one originally proposed by @tulakalbeyo at the top of this discussion.  The glyph should have some relevance.  I still like the Flag of Yucatán, though.  I think that it looks pretty.

**Comment by nonongvik** [comment]
Maybe, the Mexican flag with the language code is a good option, too.  We have not ascertained whether the Flag of Yucatán is really too controversial or not.  A Mayan glyph would allude to a prior script, but Yucatec Maya now uses Latin letters.

**Comment by sabretou** [comment]
@nonongvik Regarding the Yucatán flag, my concern is not so much about whether it is controversy, as whether it is relevant. I cannot see any connection between the Republic of Yucatán and the indigenous language of Yucatec Maya, other than they both reference Yucatán in their names.

(I have further reservations too, based on my reading of the [Republic of Yucatán page](https://en.wikipedia.org/wiki/Republic_of_Yucat%C3%A1n), but I should not air them if I am not knowledgeable, so I will keep them to myself).

I am okay with either the glyph by itself, or with the flag of Mexico accompanied with a language code.

**Comment by nonongvik** [comment]
Here’s some information on the Mayan fish glyph of @tulakalbeyo:

<<
There are three elements we need to recognize in order to read this glyph:

the main glyph, which resembles a fish (we’ll call this part of the glyph element “A”);
the oval and hook shapes on the right, which resemble a fish’s tail but are actually a separate glyph (let’s call this element “B”);
the two dots that resemble a colon near the fish’s mouth (element “C”).
The main glyph, A, represents the syllable sound “ka”.  Element B, near the fish’s tail, represents the syllable sound “ua” (also written “wa”).  So far, the glyph is pronounced “ka-ua” since the Maya read their glyphs left-to-right and top-to-bottom.  Next, we need to take into account element C near the fish’s mouth.  Anyone who reads music will recognize element C as a repeat sign, which can be placed at the end of a bar of music to indicate that a portion of the piece should be repeated.  Surprisingly, that’s exactly the function it serves here, too.  It tells the reader to repeat the sound of the symbol next to it.  Here, that’s element A, “ka”.  So, when each element is read in the correct order, left-to-right and top-to-bottom, the glyph reads “ka-ka-ua.”

Just one further insight is needed to pronounce this glyph properly: the Maya were known to drop the last vowel of a spoken word.  Therefore, this glyph should be read without the final “a” sound at the end.  Without that last “a,” the glyph reads “ka-ka-u,” or as we currently spell it, cacao, the main ingredient for chocolate.
>>
https://www.ancient.eu/article/789/how-to-read-a-maya-glyph/

**Comment by nonongvik** [comment]
@tulakalbeyo’s Mayan fish glyph:
  Icon: https://i.imgur.com/qH2Wtwm.png

**Comment by nonongvik** [comment]
<<  The Olmecs undoubtedly passed their cacao knowledge on to the Central American Mayans who not only consumed chocolate, they revered it. The Mayan written history mentions chocolate drinks being used in celebrations and to finalize important transactions. >>

https://www.history.com/topics/ancient-americas/history-of-chocolate

**Comment by nonongvik** [comment]
I suppose that the “cacao fish” glyph is relevant, as chocolate is a central theme amongst Mayans.

**Comment by nonongvik** [comment]
tulakalbeyo‘s list:

https://tatoeba.org/eng/sentences_lists/show/8047

**Comment by soliloquist-tatoeba** [comment]
I had contacted the admin of the most-followed Yucatec-Maya-related page on FaceBook, [Belize Yucatec Maya](https://www.facebook.com/Belizeyucatecmaya/). 

I invited them to Tatoeba and informed them about this discussion. Since Belize isn't in Mexico, I asked them to join the discussion if they had a specific symbol or something that could be used to represent their language other than the Mexican flag. They thanked and said that they would check it out, but apparently, it didn't interest them much. 

However, the admin of another FB page ([Lengua Maya Yucateca](https://www.facebook.com/mayayucateca)) I contacted said that we could use some historical/cultural element such as 'the pheasant and deer', 'Chichen Itza' or 'Kukulcan' as the icon.

After their feedback, I tried to create a custom flag, placing the Kukulcan pyramid (which is in Chichen Itza, Yucatán) over the flag of Mexico. They liked and approved it. 

![Yucatec Maya Flag](https://user-images.githubusercontent.com/47579687/90322918-f2b5a100-df62-11ea-91f0-87d572ee1cae.png)


The icon version: ![Yucatec Maya Icon](https://user-images.githubusercontent.com/47579687/90323047-8dfb4600-df64-11ea-840a-ca136c88a4c9.png)


I think we can use it as the icon. A similar design with the Parthenon temple was previously used for Ancient Greek. ![Ancient Greek Icon]( https://user-images.githubusercontent.com/7658430/43933615-064ab17e-9c21-11e8-8026-0c146a87081e.png)

**Comment by sabretou** [comment]
This flag is pretty good, Soliloquist! We can go ahead with this and the list by tulakalbeyo.

**Comment by RyckRichards** [comment]
Great. Going to work on it right now. 
@jiru @trang Should I open another Ticket to add this language?

**Comment by RyckRichards** [comment]
Language name: Yucatec Maya
Language info: https://en.wikipedia.org/wiki/Yucatec_Maya_language
ISO 639-3 code: yua
Public List: https://tatoeba.org/eng/sentences_lists/show/8047
Icon: https://imgur.com/a/nJ2IvMv
Requested by: https://tatoeba.org/eng/user/profile/tulakalbeyo

**Comment by trang** [comment]
@RyckRichards No need to create a new ticket ticket. You can simply refer to this ticket for your PR.
