### ISSUE TITLE
Difficulty to select/find the desired language

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1651]
## Problems
1.  We have now more than 300 languages and that's already too much to be handled via a regular dropdown. It's a very long list, and if you're using Tatoeba on a mobile device, you may have to scroll forever until you find your desired language.
2. Some users don't find their language because of the name. For instance, someone looking for sentences in Egyptian Arabic would scroll down to languages starting with "E", but they may stop at languages starting with "A" because they expect the language to be listed somewhere below "Arabic". As a result we have changed the names of some languages so that they could be grouped and people could find them more easily. But this was, in my opinion, a bad decision and led to inconsistent names (cf. #936).

## Solution

We need to replace the regular dropdown by searchable one.

We could possibly use AngularJS Material's autocomplete:
https://material.angularjs.org/latest/demo/autocomplete

**Comment by Guybrush88** [comment]
Currently, with this new dropdown menu, when a user deletes the default option in the search's language, he/she sees the languages he/she chose in his/her profile and then every other language. My suggestion is: maybe the dropdown, at least for registered users, should be limited to the languages that a user chose in his/her profile when no specific language is selected, since it's likely that this user would stick only to such languages when searching for sentences, and, for all the other languages, he/she would have to type them manually to get them in the dropdown menu, since they're less likely to be used for custom searches

**Comment by jiru** [comment]
> Currently, the dropdown accepts any characters, including punctuation symbols that do not appear in any existing language name and are highly unlikely to appear in any in the future. Since these are probably mistyped, they should simply be ignored.

By “ignored”, do you mean ignored from the search or prevented to be typed into the field?

Note we have some languages that include symbols, like Karachay-Balkar or K'iche'. Besides, since the language names are translated into many languages, there is a possibility that a translation includes symbols too. For example, it’s common in Japanese to separate borrowed multi-words using a "middle dot" (・) because Japanese does not use word separators: “Scottish Gaelic” → “スコットランド・ゲール語”. Finnish [uses colon](https://github.com/Tatoeba/tatoeba2/blob/0541827868d462aae175e6e3c151f50bf80808be/app/Locale/fin/LC_MESSAGES/languages.po#L260) to append grammatical endings to some words.

**Comment by trang** [comment]
@Guybrush88 For your suggestion I replied [on the Wall](https://tatoeba.org/eng/wall/show_message/29739#message_29739).

@alanfgh Do you feel it is still necessary to ignore special characters now that the dropdown doesn't keep values that are not from the list of options? 

When interacting with a text input, it feels strange (to me at least) to enter a key and have nothing happening. It feels as if the text input is broken and doesn't work properly. I think that if we ignore some characters, we would need to display a visual feedback to compensate for the lack of response from the input (for instance show some tooltip saying "character not allowed"). But that would be a bit overkill here.

While I understand the rationale behind ignoring "useless" characters, I think it would be a better approach to let the user enter whatever character they want and adjust the search results in case they mistype something. This is basically related to the problem that sabretou brought up when asking for a spellcheck.

For the tab issue, I added a replacement of tabs by spaces. Again because it feels weird to simply delete the tab.

**Comment by alanfgh** [comment]
> By “ignored”, do you mean ignored from the search or prevented to be typed into the field?

I meant that they shouldn't be typed into the field. But if @trang thinks that will confuse users, I'm willing to trust her judgment.

However, @trang, if we are going to write tabs to the field, I would rather not have them replaced by spaces, since it's easier to delete a tab (with one backspace or delete operation) than a series of spaces. It also seems more consistent, since the tab was added with a single keypress in the first place.

**Comment by trang** [comment]
@alanfgh One tab is replaced by a single space.

**Comment by alanfgh** [comment]
@trang, that sounds fine to me.
