### ISSUE TITLE
Tachawit (shy)

### ISSUE THREAD

**Issue by cueyayotl** [Tatoeba/tatoeba2#1683]
- Language name: Tachawit
- Language info: https://en.wikipedia.org/wiki/Shawiya_language
- ISO 639-3 code: shy
- Public List: https://tatoeba.org/eng/sentences_lists/show/8414
- Icon: https://i.imgur.com/yOU43Zz.png
- Requested by: https://tatoeba.org/eng/user/profile/Kahina_n_awras

[for tatoeba.org]
CALL add_new_language('shy', 8414);

**Comment by cueyayotl** [comment]
CORRECTION: Tachawit
Somehow I was thinking of Tarifit, another Berber language we added earlier, and mixed it with this one.

**Comment by RyckRichards** [comment]
Fixed!

**Comment by belkacem77** [comment]
Language native name: Tacawit. 
Flag used par Shawiya https://commons.wikimedia.org/wiki/File:Chaouia_flag.svg

**Comment by cueyayotl** [comment]
We may need to hold off on adding the attached language icon before proper research is done into the political affiliations of this flag. If this language is able to be added soon, we may need to use this flag as a temporary:
![shy1](https://user-images.githubusercontent.com/7318754/46651248-a8767280-cbc9-11e8-8fe0-4ec98c1a4897.png)

**Comment by S-Amiri** [comment]
If you use the suggested icon, people will be confused, the chosen icon
looks like the berber's one. Not all people know the chawi's iso code. But
all chawis know the Chawi flag. The chawi flag is not attached with any
political organization. You can do your research.

Slimane Amiri /
Maṣi Selyan At Ɛmer

**Comment by belkacem77** [comment]
@cueyayotl 
It's the flag used publically for Shawiya as well as the Mozabit, the tergui and the Kabyle one in Algeria.
These flags represents the regions.
By the way, the ber flag is not the one used on tatoeba. You can search deeply. The ber flag is the same used in Libya, Tunisia, Algeria, Mali, Niger, Canarian iles, Maritania, and Siwa (Egypt). 
Take a look on Google and will find all what you are searching for.

**Comment by RyckRichards** [comment]
@cueyayotl is Tacawit or Tac**h**awit ?

**Comment by belkacem77** [comment]
@RyckRichards Tacawit

I'm a Kabyle, speaks and writes Kabyle which also a berber language as well as Shawiya language.

The berber languages share the same alphabet and rules. The difference in flexions (nouns, adjectives and verbs), vocabulary and phonlogy. So the right syntax is Tacawit not Tachawit.

**Comment by belkacem77** [comment]
For the flags, believe me, you are taking the opposite path of the social reality by following Amastan.

**Comment by cueyayotl** [comment]
Tachawit; we go by Ethnologue's standards here on Tatoeba. If there is an issue, then please contact them; they've definitely made changes in the past. For now, we use what they have on their site.
https://www.ethnologue.com/language/shy

**Comment by RyckRichards** [comment]
> Tachawit; we go by Ethnologue's standards here on Tatoeba. They have 'Tacawit' listed as an alternative name; if anyone believes that 'Tacawit' should be the main name, and 'Tachawit' an alternative (or deleted altogether), then please contact them; they've definitely made changes in the past. For now, we must use what they have on their site as the main name.
> https://www.ethnologue.com/language/shy

Thanks!

**Comment by belkacem77** [comment]
I am sorry I think there is a misunderstanding. Tacawit is the native name of Tachawit (English Name).

**Comment by trang** [comment]
@cueyayotl Can you confirm which flag to use?

This one is the one that is currently in the pull request: ![shy1](https://user-images.githubusercontent.com/7318754/46651248-a8767280-cbc9-11e8-8fe0-4ec98c1a4897.png)

This one is the one that is mentioned in the description: ![shy](https://i.imgur.com/yOU43Zz.png)

**Comment by S-Amiri** [comment]
@cueyayotl
Just ask people chawi or see in Google and Wikipedia, you will find the right flag, the real.

**Comment by trang** [comment]
Since this is dragging for a bit too long and I'd like to merge the pull request this week, we will go ahead with the flag originally suggested by Kahina_n_awras.

@sabretou I leave it to you to make the proper restyling of this icon and send the final version to @RyckRichards so he can update his pull request.

**Comment by cueyayotl** [comment]
Sorry, I work 15 hours a day and have been too busy to read everything that has happened, but looking into it ... using the yellow flag as a language icon may be problematic, as shown in this article:
http://www.inumiden.com/lorsque-la-presence-du-drapeau-chaoui-agace-certains-congressistes-du-cma/
The flag has been associated with the MAC political movement, which has its relations with the MAK political movement. I don't think it is the right icon to use. We should just use the white icon with ISO 639-3 code on the side. In fact, it is starting to look like the right thing to do for ALL Berber languages, including Tahaggart Tamahaq (ISO 639-3 THV), which has been requested a couple of days ago. If users of Berber languages want to identify with a flag or other icon, they are more than welcome to use it as their profile picture.

**Comment by S-Amiri** [comment]
@cueyayotl
Hello, it's not logical to delete a flag just because an organization or association uses it, the flag Chandran is adopted by the Chandran even before the birth of this party or movements, I do not understand your reasoning. If we follow your reason, then we'll have to remove all the flags. I find that you are too influenced by fears that do not exist. The realities of the terrain must be taken into account. The Chandran peoples has its own language and flag, It is the socio-linguistic and cultural reality of Chandran,  It is the socio-linguistic and cultural reality of Chawi people. 
The yellow flag is part of their identity. How can you deny it??!!! Because you

**Comment by trang** [comment]
Considering all things, I think we'll have to go with a more "neutral" temporary icon: just the ISO code on white (or grey) background.

1) It seems questionable to use a derivate of the Berber flag as a temporary icon for Tachawit. Strictly speaking, under the ISO 639-3 standard, Tachawit is defined as an individual language that doesn't belong to any macrolanguage. So by using the Berber icon with 'SHY' on the side, we are contradicting the standard (since it implies that Tachawit belongs to the Berber family). Obviously, just having Berber as a language in Tatoeba contradicts the standard, but we agreed to keep Berber because it was added before we decided to support only ISO 639-3 languages. We never agreed however on which languages are considered "sub-languages" of Berber, nor if there is any sub-language. So to remain consistent we shouldn't do anything that assumes that Tachawit belongs to the Berber family, at least not until we properly discussed it.

2) It is unreasonable to block the addition of a language just because we feel unsure about a flag. There's going to be more cases where we're going to be unsure. Perhaps the uncertainty won't even come from us but from the requester themselves (they may have no idea what image can best represent the requested language). In such cases, we need a compromise so that the language request doesn't fall into a limbo. I think the best compromise we can come up with is to establish that we have a default language icon (similarly to how we have a default user profile picture) and that this icon is meant to be temporary. The user should of course understand that "temporary" could mean several months, maybe years, depending how much effort we can/must to invest into designing an appropriate icon.

If it is indeed true that the Chawi flag was adopted by the Chawi people even before the birth of the political movement, I can understand it may seem ridiculous that we "reject" this flag. But I hope the speakers of Tachawit don't take this as a rejection, rather as a safety measure for Tatoeba. 

Whenever we add a new language, we are stepping into a new territory. We won't always know the cultural/social/political/historical background of the language we're adding. Cueyayotl has stated that he feels the Chawi flag may carry too much political weight and Tatoeba may not be able to endorse it, so we will go along with his opinion.

We are going to use a default language icon here and this doesn't mean we reject the Chawi flag. It is nothing but a statement that we simply don't know enough and we need more time. We only know for sure that there is a lot of political tension. We still haven't come to a conclusion if we made a mistake with the Kabyle flag and we don't want to be too hasty with the Chawi flag.

@sabretou Sorry for the change of instructions, but we're gonna have to work on defining what our default language icons will look like.

**Comment by sabretou** [comment]
I will be designing a standard black-on-white text icon for SHY for the time being, so we can move forward with adding this language. It will be replaced once we've settled on what our default icon design should look like.

**Comment by cueyayotl** [comment]
@trang >>Strictly speaking, under the ISO 639-3 standard, Tachawit is defined as an individual language that doesn't belong to any macrolanguage.

There are ISO 639-3 codes for both macrolanguages and languages. Just because a tongue has been assigned an ISO 639-3 doesn't mean it is not a macrolanguage. Consider ARA (Arabic), GRN (Guarani), KUR (Kurdish), NAH (Nahuatl), PUS (Pashto), etc. which we have on Tatoeba... anyone could request an individual language included in these Macrolanguages anyday, as is the case with NCH, NGU, NLV, which are individual languages in the NAH (Nahuatl) macrolanguage.

>>So to remain consistent we shouldn't do anything that assumes that Tachawit belongs to the Berber family, at least not until we properly discussed it.

Tachawit DOES belong to the Berber language family, though:
https://www.ethnologue.com/subgroups/berber
So in that sense, there is no issue.

@sabretou, welcome to our team! Regarding your question about the horizontal text on flags, I write them manually. Not being an artist, I usually just type the letters and shrink them to the proper size and use the resulting blurry image to guide my design of the letters. Of course you may look through some of the language icons I've created and use the letters I've design to use on future icons. My general guidelines are to create a white rectangle in the rightmost 20x10 area to write the letters. The top of the letters should be 1 pixel from the bounds of the white rectangle, the bottom should be 2 pixels away from the edge, and the sides of the letters should be 2 pixels away from either edge... of course these are MY own rules anyway :) for most of the flags I make, I add a gradient effect on Photoshop to make it appear (shinier), and I reduce the brightness of the edges by -25 (see my new Guaraní, Amharic and Hawaiian icons for examples).

@S-Amiri, we are not deleting a flag, we are changing a language icon.
>>the Chawi flag is adopted by the Chawi people even before the birth of this party or movement

Which Chawi people? And, how many of them? Why is it that it is still sensitive among even the Chawi people? If you present us with valid arguments, we are willing to change our opinions; our minds are not set in stone. Facts before emotions.

>>We'll have to remove all the flags

We've removed the Portuguese flag as the icon of the Portuguese language, and replaced it with a mix of the Brazilian and Portuguese flags. I contribute in the Spanish language, but am from Mexico. I WISH we used the Mexican flag in place of the Spanish flag (after all we are the country with the most Spanish speakers). But, I love the SPANISH language and understand the importance of the Tatoeba Project, so even despite ME having the authority to change the Spanish language icon, I still do not, because there are far more important things. My profile picture is of a village, and I think it better represents myself than any flag could.
WE ARE NOT REMOVING THE MAK FLAG, you are always welcome to use the flag as your profile picture.

**Comment by trang** [comment]
Tachawit is now available on Tatoeba.

Just a few notes on @cueyayotl's comment:

Even though the Ethnologue is classifying Tachawit as belonging to the Berber family, the ISO 639-3 doesn't (yet?). That's why I said that strictly speaking, under the ISO 639-3 standard, Tachawit is considered as an individual language that doesn't belong to any macrolanguage. That is not to say we can never classify Tachawit under Berber within Tatoeba, but we cannot take this decision without more analysis. This is anyway more a question of what should we do with Berber and this should be discussed in #1673.

Even if a language belongs to a macrolanguage, we should probably think twice about using a derivative of the macrolanguage's icon. In most cases, the contributors will probably not mind and if they don't mind, we can of course use the macrolanguage's icon. In some cases however, the native speakers may have a strong sense of independence/detachment regarding their people and their culture and don't like to be associated as a sub-part of a bigger "empire".

For the record, what I have collected from Kahina's feedback (the requester of this language) is that her peers didn't want to contribute Tachawit sentences under the Berber language. I then suggested to her that they could always set their sentences as "other language" while waiting for Tachawit to be added and she was more appealed by this option. She was against the use of the Berber icon to represent her language, but was okay with the plain 3-letter ISO icon as a temporary solution.
