### ISSUE TITLE
Add export sentences to CSV

### ISSUE THREAD

**Issue by mozillakab** [Tatoeba/tatoeba2#1687]
If some one would export his own sentences to csv with possibility to apply a filter on his own sentences.

![2018-10-05 20_29_25-](https://user-images.githubusercontent.com/7033740/46556338-445c6180-c8de-11e8-9870-9d14d5816613.jpg)

**Comment by jiru** [comment]
Note that your ticket contains two distinct improvements: filter users’ sentences by text and export as CSV. It would be better to open different tickets for each thing.

About your design: as much as I think CSV export is useful, I doubt that the majority of members is going to use it. Because of this, I don’t think it’s a good idea to insert this new export element (button?) on the top of the page. Things that are not used a lot shouldn’t be placed in such a prominent position.

**Comment by belkacem77** [comment]
The export feature will be very usefull for academicians and other people working on one lang corpus. As Tatoeba can provide such a feature, people who don't have programming skills can easily take advantage from the corpus. I had to write some Python scripts to filter the kabyle data since I only needed that language within my processing tasks. So for academicians with only langusitics skills, such features would be helpfull. For the design, I recognize that I'm very bad :).

**Comment by trang** [comment]
It is now possible to download sentences in a specific language (#2163). On the [Downloads page](https://tatoeba.org/eng/downloads), there's a dropdown to select the language for some of the files.

I think this addresses the issue of this ticket so I will close. If that's not the case, feel free to reopen @mozillakab.
