### ISSUE TITLE
Add import free sentences without translation

### ISSUE THREAD

**Issue by mozillakab** [Tatoeba/tatoeba2#1688]
If someone would import a CSV  file sentences without translation

![2018-10-05 20_40_15-add sentences - tatoeba](https://user-images.githubusercontent.com/7033740/46556810-b5e8df80-c8df-11e8-861b-4f9eb48b007e.jpg)

**Comment by jiru** [comment]
Note that we already have a CSV import function, in another page, but access to this page is currently limited to admins and corpus.

About your design, I am not sure it would play well with the existing "Add new sentences" form, because it appends newly-added sentences at the same place as where you suggest to add the "File to import" and "browse button" area.

**Comment by agrodet** [comment]
With #1762 around, is that issue still relevant?

**Comment by trang** [comment]
No, this is basically some form of duplicate. I'm closing.
