### ISSUE TITLE
Link vocabulary to sentence to take advantage from seaching feature.

### ISSUE THREAD

**Issue by belkacem77** [Tatoeba/tatoeba2#1697]
**We'd like enhance the searching feature to extract more sentences.**

Due to flexion within the kabyle language (names and verbs) and some syntactic rules (use of the - char), the system can"t detect if the word is used or no.
Example: 
1- name:
"argaz" (man) is in the free state: "wagi d argaz". When we use it on annexed state, it becomes: "urgaz". "Yusa-d urgaz". Its plural is "irgazen" and the annexed state: irgazen, yirgazen. 
For the verbs, it's more complicated.  We can also consider the gender as a flexion 
for some words.
2- verb:
the verb "aru" has several flexions: aruɣ, turiḍ, nura.....
3- tokennization: In Kabyle language we use the '-' to connect words. We can get an expresion such: "Fkiɣ-as-t-id" which means "I gave it to him".

So the system will consider it as a word since tokenizzation is blank-based char. I'd like link the verb "efk" to the sentence  "Fkiɣ-as-t-id" to make it appear when doing search on the verb "efk."

![2018-10-09 10_07_35-vocabulary that needs sentences - tatoeba](https://user-images.githubusercontent.com/7033740/46659815-8c64d800-cbad-11e8-8dd4-04c64f8f1bb3.jpg)

**Comment by jiru** [comment]
The problem you’re describing is not limited to Kabyle and it’s called [stemming](https://en.wikipedia.org/wiki/Stemming). In Tatoeba, stemming is handled by the search engine Sphinx, which delegates this task to the [snowball library](http://snowballstem.org/). Currently, stemming is only supported in a limited number of languages, and Kabyle is not one of them. In languages with stemming support, searching for a word brings results including inflected variants too. For example, [searching for "improvement" in English](https://tatoeba.org/sentences/search?query=improvement&from=eng&to=und) brings sentences including variants like "improves", "improved", "improving"… That’s because snowball support stemming for English. So if you want to have stemming support for Kabyle in Tatoeba, it needs to be implemented it in the snowball library. You may implement it yourself if you can, or ask/pay someone else to do it for you.

As for the vocabulary feature, it can clearly be improved in many ways, but I think some members may also want to have exactly the flexed version of a word as vocabulary item. Maybe we need to add the option "include variants" for each vocabulary item.

> 3- tokennization: In Kabyle language we use the '-' to connect words. We can get an expresion such: "Fkiɣ-as-t-id" which means "I gave it to him".
> So the system will consider it as a word since tokenizzation is blank-based char.

That’s not true. The system also uses the minus character to tokenize words. See for example [searching for the word Yusa](https://tatoeba.org/sentences/search?query=Yusa&from=kab&to=und).

**Comment by belkacem77** [comment]
Yes I'm aware. I was working on it for a while to add a stemmer for the Kab language within snowball. I think I should return and work on it again. I will close this issue. Thanks.
