### ISSUE TITLE
Reduce bandwidth required to download sentence exports

### ISSUE THREAD

**Issue by Kentoseth** [Tatoeba/tatoeba2#1729]
This is a suggestion, mostly because I can do it.

Instead of having 1 giant sentences.csv file that people need to frequently download to update, you can add git-tracking and split the sentences.csv file by language.

This will conserve bandwidth and you can also use github to handle big file downloads if necessary.

**Comment by jiru** [comment]
@Kentoseth Thanks for you suggestion. Our sentences distribution system clearly needs to be improved, but what exactly is the problem you are trying to solve here? I’d like to know what is your use-case. What are the benefits of git-tracking *for you*? What are the benefits of splitting the sentences.csv file by language *for you*?

**Comment by jiru** [comment]
@Kentoseth Thanks for your suggestion. Our sentences distribution system clearly needs to be improved, but what exactly is the problem you are trying to solve here? I’d like to know what is your use-case. What are the benefits of git-tracking *for you*? What are the benefits of splitting the sentences.csv file by language *for you*?

**Comment by Kentoseth** [comment]
@jiru 

> but what exactly is the problem you are trying to solve here? I’d like to know what is your use-case. What are the benefits of git-tracking for you?

I don't have a specific use-case, but when I saw how big the sentences.csv tarball was, I thought I would suggest this solution so that it can conserve bandwidth. Example:

20 people download the 100MB tarball each week. This is 20GB of bandwidth a month. By using a version-controlled alternative for the large files, you can reduce bandwidth to a fraction of what is being consumed currently.

> What are the benefits of splitting the sentences.csv file by language for you?

This is also another bandwidth-conserving measure. I think most people are generally interested in translations between 2/3 languages only. Being able to download just English-French instead of having to download the entire CSV might save bandwidth too.

**Comment by jiru** [comment]
Thank you for your answer, this is very helpful.

**Comment by jeanm** [comment]
Having worked with Tatoeba raw data before, I also ended up downloading a massive file to only use maybe 5% of it. I guess the admins will have to see whether the bandwidth costs are high enough to warrant doing extra work.

If the costs are a problem, then instead of splitting the files yourselves or you could see if the good folks at [opus.nlpl.eu](http://opus.nlpl.eu/Tatoeba.php) would be willing to do this for you regularly. They already host some data, although there's no indication of how recent it is. You could then put a fairly prominent link to that page in your download section.

**Comment by alanfgh** [comment]
The size of sentences.csv is not only a problem for the site (server), but also for the user (client). It's problematic not only in terms of the bandwidth for a download, but everything else: disk space, the ability to load the file in a text editor, the ability to load the file from a script, and so on.

To paraphrase and extend what Kentoseth said, an individual user rarely wants sentences in more than two languages, and often just a single language. For instance, in the past, I've wanted to download English sentences in order to do searches locally that I couldn't do effectively on the site (for instance, find sentences with no terminal punctuation). However, I found that downloading the file and splitting it myself wasn't worth the effort. If I could download an English-only file, it would be a different story. However, if you start providing files that people find more worthwhile to download, people may perform more downloads (even if the files are smaller). That probably won't result in exceeding the original bandwidth from downloads of the unsplit sentences.csv, but it's a possibility worth taking into account.

**Comment by soliloquist-tatoeba** [comment]
> If the costs are a problem, then instead of splitting the files yourselves you could see if the good folks at [opus.nlpl.eu](http://opus.nlpl.eu/Tatoeba.php) would be willing to do this for you regularly. They already host Tatoeba data, although there's no indication of how recent it is. You could then put a fairly prominent link to that page in your download section.

The Tatoeba corpus on opus.nlpl.eu is pretty old (probably from around 2014). I emailed Mr. Tiedemann a few months ago to ask if he was planning to update the data. He said that it had been on his to-do list for a long time, but didn't have time to do it. I don't think he would be able to update it regularly, on a weekly or monthly basis.

**Comment by Kentoseth** [comment]
> He said that it had been on his to-do list for a long time, but didn't have time to do it. I don't think he would be able to update it regularly, on a weekly or monthly basis.

He shouldn't need to. Software can automate this process.

My proposal would be to address both the issues in a single solution:

1) Create some type of script that splits sentences into language<->language as found on http://opus.nlpl.eu/Tatoeba.php
2) Put this data under version control so that when updating the data, you don't need to download the entire datasets repeatedly.

Does anybody have a suggestion for a Python library (or even a few Bash commands) that I can use to split the sentences.csv file into smaller chunks? Right now the detailed sentences.csv is 720MB

**Comment by trang** [comment]
> Does anybody have a suggestion for a Python library (or even a few Bash commands) that I can use to split the sentences.csv file into smaller chunks?

Not a Python programmer here, but probably you'll find something in one of those results: https://www.google.com/search?q=python+split+csv+based+on+column

However, your proposal mentions:
> Create some type of script that splits sentences into language<->language as found on http://opus.nlpl.eu/Tatoeba.php

If your actual goal is to create sentence pairs, maybe [this](http://www.realworldnlpbook.com/blog/building-seq2seq-machine-translation-models-using-allennlp.html) can help you. Also I know that @ckjpn has a page where he lists [sentence pairs from English to other languages](http://www.manythings.org/anki/). I don't know what script he is using though.

I'm gonna ping @robbertbrak here as well because he contacted us on this topic last month. He wanted to implement a way to export sentences in a specific pair of languages. What you are suggesting here may be somewhat very close to what he wants to do.

But note that we have two independent problems:
1. On one hand there is the problem of updating your dataset without having to waste bandwidth and time. For that we could technically just track the entire `sentences.csv` in Git. That would be already useful people like [shaptoothed](https://tatoeba.org/eng/wall/messages_of_user/sharptoothed) who is making stats about the evolution of the corpus and needs all the sentences in all the languages. Ideally he shouldn't have to download everything all over again every time.
2. On the other hand there is the problem of extracting specific data from the corpus. And for that we already have an issue: #1609. It covers the more general problem that we lack of options for people to download only a subset of the corpus. Someone might want to download our data only once, but not all of it, just in a few languages (or from specific users, or from a specific period of time, etc). It's pretty much all or nothing right now. We have zero options... or almost zero. We have a subset for CC0 sentences, but that's it.

Then there is of course the combination of the two (which is probably your initial requirement): you want to download a subset of our data and update it over time. I guess this very likely the case for anyone who is making a language app from our corpus. They will target specific languages and they will want to update their data regularly to include all the corrections and improvements that have been made.

Anyway I would suggest to limit the scope of this issue to problem nº1 and evaluate if tracking our files in Git is a viable solution or not. I don't think it's a bad idea at all but I've never tracked large files in Git before and I don't know the limitations. I've only quickly found documentation [about large files in GitHub](https://help.github.com/en/categories/managing-large-files) but haven't read through it yet.

**Comment by soliloquist-tatoeba** [comment]
> 1. Create some type of script that splits sentences into language<->language as found on http://opus.nlpl.eu/Tatoeba.php

@Kentoseth 
There is a script for this purpose.

https://github.com/kmicklas/sentence-pairs

It has some problems handling apostrophes and quotation marks (dialogues), but it gets the job done for personal use. If anyone is interested in creating a script, improving this might be easier than starting from scratch.

**Comment by ckjpn** [comment]
One way to lower the bandwidth would be to put all the uncompressed files into a non-accessible folder, and only offer the compressed files for download.

The way I create bilingual pairs may not be so useful for tatoeba.org, but this is what I do with Python2 scripts I've written.

* I read in my list of native speakers, the List 907 sentence IDs, the sentences_detailed.csv, and the links.csv.
* I then create a very large file that links the all sentences by non-English sentences owned by native speakers that are linked with English sentences on List 907.
* After that file is created, I run another script that splits these into files with bilingual pairs.
* From those files, I create the following:
** http://www.manythings.org/bilingual
**  http://www.manythings.org/anki
** http://www.manythings.org/sentences/audioplayer/
* I use the big file to create this one, but I don't update this one as often.
** http://www.manythings.org/sentences/audio/

**Comment by Kentoseth** [comment]
Thanks for the Python suggestion @soliloquist-tatoeba 

Although a little bit late, I rewrote part of that Python script into a compiled, executable binary available here: https://github.com/Kentoseth/tatoeba-sentence-pairs

This should make sentence-pair extractions much quicker than the Python script.

You also automatically get JSON output, which can be used for pushing to some web-based view or even using a terminal viewer like this: https://github.com/saulpw/visidata

I will now think of the best way to automate the process of fetching the content-file and turning it into some version control.

**Comment by Kentoseth** [comment]
@ckjpn 

> One way to lower the bandwidth would be to put all the uncompressed files into a non-accessible folder, and only offer the compressed files for download.

I think the download file are already compressed. The files are around 100-300MB and when uncompressed they can go as big as 700MB

Your manythings.org project is cool. I tested it out recently :100:

**Comment by ckjpn** [comment]
@Kentoseth 
What I meant was to only make the compressed files available for downloading.
https://downloads.tatoeba.org/exports/

At this time both the .csv and the .tar.bz2 files are available.

If all the csv files were in another folder, not available for people to download, then people would only download the compressed files.  The .csv files could be in another publicly-accessible folder for those who might possibly not be able to use compressed files. However, my guess is that anyone who can figure out how to use these files can also figure out how to uncompress them after downloading them.

At this time the following files are only offered as non-compressed files.  I download the first 2 every week.

users.csv
users_sentences.csv
wwwjdic.csv

**Comment by soliloquist-tatoeba** [comment]
> The Tatoeba corpus on opus.nlpl.eu is pretty old (probably from around 2014). I emailed Mr. Tiedemann a few months ago to ask if he was planning to update the data. He said that it had been on his to-do list for a long time, but didn't have time to do it.

It has been updated. 

http://opus.nlpl.eu/Tatoeba-v20190709.php

**Comment by jiru** [comment]
For now, how about providing per-language csv exports in addition to the exiting global ones? I think this can be easily done by expanding the exiting SQL export script. I like this solution because it has a good benefit/effort ratio.

**Comment by trang** [comment]
Yes, it would be definitely a step forward.

**Comment by AndiPersti** [comment]
For per-language csv (well not really csv but tsv :-) ) exports this simple awk one-liner which splits the current `sentences.csv` into language-only files (`xxx_sentences.csv` and `unknown_sentences.csv`) runs in under a minute on my system (AMD Athlon(tm) II X4 640 Processor, 16GB RAM):

    $ time awk -F"\t" '{print >> ($2 == "\\N" || $2 == "" ? "unknown_sentences.csv" : $2 "_sentences.csv")}' sentences.csv
    
    real    0m47,528s
    user    0m46,146s
    sys     0m1,289s
    $ ls -1 | grep -cF _   # count all files excluding sentences.csv
    347    # '\N' and '' are both in unknown_sentences.csv
    $ cut -f 2 sentences.csv | sort | uniq | wc -l   # count all languages in sentences.csv
    348
    $ wc -l epo_sentences.csv   # count sentences in epo_sentences.csv
    611206 epo_sentences.csv
    $ cut -f 2 sentences.csv | grep -cF epo   # count sentences of language epo in sentences.csv
    611206

For compressing these files `bzip2 *_sentences.csv` would be sufficient:

    $ time bzip2 *_sentences.csv
    
    real    1m23,062s
    user    1m22,058s
    sys     0m0,481s
    $ ls -1 | grep -c 'bz2$'
    347

(Another point I find strange since the first time I've downloaded a file: Why are these tar archives if there is only one file in each?)

**Comment by trang** [comment]
> Another point I find strange since the first time I've downloaded a file: Why are these tar archives if there is only one file in each?

No idea. I can't think of a reason either...

**Comment by jiru** [comment]
Closing as solved by #2163.
