### ISSUE TITLE
Adding sentence to list doesn't work on pages with multiple sentences

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1743]
Reported by [soliloquist on the Wall](https://tatoeba.org/eng/wall/show_message/31166#message_31166):

> I think there's a bug with the add-to-list function on pages with numerous sentences (like list pages or "translate user's sentences" pages). On such pages, sentence selection goes wrong if a previously-selected sentence is selected again. Add-to-list command is erroneously sent to the previous sentence.
> 
> It might sound unclear so I've created a few example sentences to demonstrate.
> 
> https://dev.tatoeba.org/eng/activities/translate_sentences_of/testuser
> 
> Just add those sentences into some lists. Do it in order, not randomly. After getting done with the 3rd one, select the 1st or 2nd one again and try to add it into another list. You'll reproduce the bug.
> 
> This is present on both the main and the dev site.

**Comment by soliloquist-tatoeba** [comment]
Another description.

https://tatoeba.org/eng/wall/show_message/31535#message_31535

> [BUG]

- Add two sentences, A and B.
- Add A to a list L.
- While A is being adding (the waiting symbol is spinning), click on the "Add to a list" button => It looks like B was added to the list L (because L disappears from the dropdown), while the waiting symbol on A spins forever.
- Actually, A is correctly added to L (checked by opening L), and B cannot be added anymore unless going to the sentence page of B.

Expected behavior:
- Wherever I click during the addition of A to L, the dropdown menu of A, and its waiting symbol, should be the ones affected when the operation is over, not the one with the current focus.
