### ISSUE TITLE
No "(native)" information next to the username in sentences

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1747]
After the update of CakePHP, "(native)" doesn't appear anymore next to usernames within the sentence's page, even if, within the settings, this is selected to appear

**Comment by ckjpn** [comment]
This is almost a year old.

Perhaps it might a good idea to hide the setting until this gets fixed, to avoid confusion.

It should be a fairly simple matter to comment out the code for the setting, and uncomment it when this has been repaired.

**Comment by AndiPersti** [comment]
I've ported this feature to CakePHP 3 but I'm not sure about incorporating it into the new design:
![native](https://user-images.githubusercontent.com/6566321/72618649-dc4b5680-393b-11ea-825b-542ce18618d7.png)
If the subheader text is pretty long (long sentence number + long username + long translation text) there is not much space left for the native indicator.

Maybe wrap the text:
![native_wrapped](https://user-images.githubusercontent.com/6566321/72620371-72cd4700-393f-11ea-8480-246b52bb9752.png)

Any other ideas?

**Comment by ckjpn** [comment]
Here are some ideas that may take less space.  I'm not sure how practical these ideas are, but perhaps these ideas might trigger other ideas.

* Put native speakers' usernames in BOLD font.
* Color-code native speakers usernames with a different color.
* Increase the size of native speaker usernames, or decrease the size of non-native speakers.
* Remove the "Sentence Number" text in front of the sentence number "#18" would likely be enough to understand that it's a sentence number.
#18 belongs to corpus_maintainer (native)
* Possibly remove the "belongs to" text, combined to look something like this.
#18 corpus_maintainer (native)
... or ...
#18 (corpus_maintainer =  native)

**Comment by trang** [comment]
I suggest to add the indicator next to the sentence itself instead of next to the username. The indicator would have to be an icon (just like we have an indicator for unapproved sentences). You could use the [star](https://material.io/resources/icons/?icon=star&style=baseline) material icon and add a tooltip `This sentence belongs to a native speaker`. The text of the option in the Settings would need to be updated.

On mobile devices, the space to display the sentence and the owner will be even smaller, so it would be better to move this indicator away from the sentence header if we can.

**Comment by ckjpn** [comment]
Doing what TRANG suggests would perhaps also make it possible to also show which of the linked translations were by native speakers.  That would be useful information, too.

**Comment by AndiPersti** [comment]
For now, I've just ported the old implementation. I'm not sure if this implementation is also usable/adaptable for marking translations.

I suggest you open a new issue for that.
