### ISSUE TITLE
The link to "more information" about CC licenses is wrong.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1750]
it goes to the "downloads" page and not the page about licenses.

<img width="637" alt="screen shot 2019-01-23 at 1 13 48 pm" src="https://user-images.githubusercontent.com/7934273/51582759-e6956900-1f10-11e9-9373-b01ca5ecc20e.png">

**Comment by trang** [comment]
The Download pages contains information about licenses though... Can you specify what other page about licenses did you expect "More information" to link to?

**Comment by ckjpn** [comment]
I expected a link to something explaining the various licenses.
I think that's what most people clicking the link would expect to see.

**Comment by jiru** [comment]
The information about licenses is in the the right column of the downloads page. Let’s move it into a new page and point the `More information` link to that page.

**Comment by trang** [comment]
I'm thinking instead to remove this "More information" link, and put the link to the Downloads page on the words "Our data".

> [Our data](https://tatoeba.org/eng/downloads) is released under various Creative Commons licenses.

In the end the only information we have on the license is this block:

![image](https://user-images.githubusercontent.com/221850/62000926-1867d200-b0e4-11e9-914d-b3c6bebf1c1b.png)

It feels a bit overkill to have a separate page for that.

**Comment by jiru** [comment]
The license information apply to sentences as viewed on the website, as well as the exports. Hence, this information is not specific to the Downloads page. Since the footer appear on all the pages, I expect it to tell me about the license of the website content, not the exports.

For example, let’s say a visitor opens a sentence page (/sentences/show/xxx) from a Google search result. The visitor likes that sentence and its translations, and want to reuse it in a project. The visitor look for licensing information in the footer, clicks the "More information" link. But the visitor will surely be confused to be brought to a "Downloads" page as it’s not the expected information. Even if the visitor scrolls down and sees the license block, the text is about "these files", not the website content.

That’s why I was suggesting a separate page.

**Comment by trang** [comment]
Makes sense. Then let's link to the Terms of Use?
More specifically to this section: https://tatoeba.org/eng/terms_of_use#section-6
