### ISSUE TITLE
The numbers on the side of https://tatoeba.org/eng/audio/index are not updating properly

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1774]
It's been 4 days since I uploaded the last Spanish audio files, and the numbers still don't match.

<img width="1133" alt="screen shot 2019-02-05 at 14 11 12" src="https://user-images.githubusercontent.com/7934273/52254272-4bf54b00-2950-11e9-8cd9-9fe683a265c3.png">

**Comment by trang** [comment]
I ran the script to update the language stats so the numbers are okay now. But the issue itself is not fixed. We need to make sure that the stats are updated whenever audio is imported.

**Comment by jiru** [comment]
This can help: [CounterCache](https://book.cakephp.org/3.0/en/orm/behaviors/counter-cache.html).

**Comment by jiru** [comment]
@trang I have a feeling that it’s not a good idea to add a new lang field to the audios table, because it is against the principle of [single source of truth](https://en.wikipedia.org/wiki/Single_source_of_truth). Did you try writing unit tests for the `updateCount()` or `importFiles()` functions?

**Comment by trang** [comment]
I understand the concerns. I liked the convenience of letting the framework handle the count update but, if you think it's better, we can instead increment and decrement the count manually in `beforeSave()` and `afterDelete()` (unless you're thinking of another solution).

I didn't try writing unit test for `updateCount()` because I was not able to figure out how to rewrite the query with the CakePHP ORM. It's a custom SQL query which has not been migrated and it would not be in use here.
Nor did I try for `importFiles()` because ultimately the count update happens when assigning the audio or removing it, so I wrote the tests on that level.

**Comment by jiru** [comment]
I see. I mentioned writing a test in order to isolate the bug in a failing unit test, because from what I saw, the origin of the bug was still unclear. I wrote a unit test for `updateCount()` locally and I can see it is failing, so now I can confirm that this was causing the problem.

I agree that it’s simpler to let the framework handle the count, but not to the expense of adding unnecessary fields to the schema. I think it’s better to use signals to update the counter, so that we can put the logic and the tests in the Language model instead. I’m going to implement this now.
