### ISSUE TITLE
Show list information on sentence pages for public lists

### ISSUE THREAD

**Issue by soliloquist-tatoeba** [Tatoeba/tatoeba2#1800]
If a sentence belongs to a list, on the sentence page, only the creator of the list can see that information regardless of the privacy setting of the list. 

![index](https://user-images.githubusercontent.com/47579687/61997682-ecc9f500-b0ad-11e9-8e8a-4dd830183e10.png)
https://prnt.sc/mq613p

That's how it should be for private and hidden lists, but for public lists, anyone should be able to see it. Just like tags. It would help users to discover other sentences on the same subject.

**Comment by trang** [comment]
For this we will need to split the "public" option into two options:
1) The list is listed on the index page only.
2) The list is listed on the index page and on the sentence's page.

Some users may not want to have their lists listed on the sentence's page, but still listed on the index page:
https://tatoeba.org/eng/wall/show_message/25227#message_25227

**Comment by soliloquist-tatoeba** [comment]
Thanks for letting me know about the previous discussion. I personally don't see much point showing a list on the index page and hiding it on sentence pages, but apparently that's what some users want. Your suggestion will surely solve the issue.

**Comment by jiru** [comment]
I think that putting more options is generally a bad idea.

@soliloquist-tatoeba Just to make the context clear. Unlisted lists are a somewhat new feature (see #677). Before, all the lists were public and listed, but none of the lists were listed on the sentence page. As a result, lists didn’t have that much exposure and members created collaborative lists about topics they didn’t necessarily want to be displayed on the sentence page. Consider this [previously "collaborative" list](https://tatoeba.org/sentences_lists/show/992). There is a huge difference between showing *every visitor of the sentence page* the way *only you and some other members* are classifying sentences, and having the your list listed on the *much harder to find* "list of lists" page.

**Comment by soliloquist-tatoeba** [comment]
Thanks for the information.

> Consider this [previously "collaborative" list](https://tatoeba.org/sentences_lists/show/992). 

Yes, I know how messy that list is. Actually, there's always this risk for collaborative lists. They're very easy to be spoiled and removing sentences is the other problem. Many active users prefer private lists to avoid that. That's why I requested a limited-collaborative privacy setting for lists before: #1704

And yet I think this is more reason to show list information on sentence pages. This way, it becomes easier to notice if a list is spoiled or misused. Displaying misinformation (spoiled collaborative lists) on the index page isn't less harmful than on the sentence page, I believe.

>showing every visitor of the sentence page the way only you and some other members are classifying sentences

But this is how tags work, isn't it? There is no standardization except for a few ones like 'OK' and '@change', but they're visible to everyone. I don't see a huge difference between tag and list information in this regard.

**Comment by trang** [comment]
The main difference with tags is that tags were displayed on the sentence's page since the beginning. So everyone used tags knowing they would be displayed on the sentence's page.

For lists, that was not the case. Lists are never displayed on the sentence's page. For that we cannot assume that everyone will be okay with seeing their lists on the sentence's page, even if the lists are public, because they have been creating lists with the knowledge that they are not displayed on the sentence's page. 

Similarly to you, I didn't understand at first why it matters to have lists on the sentence's page, but after discussing it on the Wall back then, I realized it's a different privacy level. People have different sensitivity when it comes to privacy, it's not black or white, private or public. Having lists on the sentence's page makes the lists "ultra public" (and not just "public"). If you're not very sensitive to the privacy of your lists, then you probably won't care. But if you are very sensitive, then you will feel a bit cheated on if your lists go from "public" to "ultra public" without your agreement.

**Comment by bakananbanjin** [comment]
We could just change all public lists to private or unlisted, and members can reset their list, if they feel. I accidently changed it in my commit for the Issue #895 ( #2379 issue-#895 ), because i thought the same way that it could be beneficial to see all list with this sentences. 

> But if you are very sensitive, then you will feel a bit cheated on if your lists go from "public" to "ultra public" without your agreement.

My opinion is that we dont increase the visibility, just how easy it is to recall the information. Because the data is out there but to access them it is really inconvenient.

**Comment by trang** [comment]
> We could just change all public lists to private or unlisted, and members can reset their list, if they feel

We could but we shouldn't. That would be a breach of trust. We should never change users settings without their prior consent, unless there's some significantly harmful consequences if keep the settings as they are.

> My opinion is that we dont increase the visibility, just how easy it is to recall the information. Because the data is out there but to access them it is really inconvenient.

We do increase visibility. Displaying a piece of information in more places is increasing its visibility. Otherwise we don't have the same definition of visibility.

You could argue that almost no one will mind that their current public lists suddenly become visible on the sentence's page and therefore we don't need to care about the few people who might be bothered by this change. But we have no need to take such a forceful approach.

We can introduce a new option and let people transition to that new option at their own pace. If you wish, you can even try to implement this yourself as your next Kodoeba challenge :) I think it would be in your range of skills to implement it. We would just need to agree on the design of the solution first.

**Comment by bakananbanjin** [comment]
> We can introduce a new option and let people transition to that new option at their own pace. If you wish, you can even try to implement this yourself as your next Kodoeba challenge :) I think it would be in your range of skills to implement it. We would just need to agree on the design of the solution first.

I think it would be quite easy: two ways come to mind, 

1.just add an other visibility like you from 'private' 'unlisted' 'public' and then 'public_with_ListView' (or something like this) 
add an field at the List of visibility 
![image](https://user-images.githubusercontent.com/64922245/83892386-e1743b00-a74e-11ea-95b3-f34343fefd58.png)

2. you add an new boolean column in the db table sentences_lists and add a new select opinion field something like this with the right text
![image](https://user-images.githubusercontent.com/64922245/83892630-37e17980-a74f-11ea-9124-e045b526df7c.png)


In my opinion first has the least impact on the server and db structure. and should be done in just a few rows of code

if its ok for you i would implement it with #2373 for issue #895 because the features are interconnected

looking forward for a quick reply (until i hear different i focus on the first opinion)

**Comment by trang** [comment]
> 1.just add an other visibility like from 'private' 'unlisted' 'public' and then 'public_with_ListView' (or something like this) (any ideas how to call it?)

I think this solution would be better too.

Note that we also need to add some visual indicator on the page "My lists" to indicate the new type of visibility.

For lack of better idea, the new option could be labelled `Public and shown on sentence's page`. Or something like `Promoted`, but I'm afraid this sounds a bit too commercial.

Otherwise, we could redefine our vocabulary:
- `Private`: the list is only accessible to its creator (same as before).
- `Unlisted`: the list is accessible for anyone who has the link, but is not searchable (same as before).
- `Listed` or `Searchable`: the list appears on the list index but not on the sentence's page (new label, but corresponds to the old "Public" feature).
- `Public`: the list is listed/searchable and is shown on the sentence's page (old label, but corresponds to the new feature).

However, doing so could be confusing for those who are used to the old definition of "Public". Although having the option "Listed/Searchable" does give a hint that "Public" probably no longer means what it used to mean. But we would still need to introduce some tooltips to explain what exactly each option means.

> if its ok for you i would implement it with #2373 for issue #895 because the features are interconnected

It means that we keep #895 in hostage for a little bit longer but it's not an urgent feature. So I think it's okay if you prefer to solve both at once. I'll assign this issue to you :)

**Comment by AndiPersti** [comment]
I'm personally a bit worried about the added complexity but such is life when dealing with legacy code/decisions. :smile: 

But it looks like we are lucky. 

`sentences_lists` already has a currently unused boolean column named `is_public` (I guess this column was used before adding the visibility categories; there are 293 lists with that boolean set to true and the most recent creation date is `2016-01-11`).

Most of them have `visibility = public` and `editable_by = anyone` but there are a few other combinations:
````sql
MariaDB [tatoeba]> select visibility, editable_by, count(*) from sentences_lists where is_public = 1 group by visibility, editable_by;
+------------+-------------+----------+
| visibility | editable_by | count(*) |
+------------+-------------+----------+
| private    | creator     |        4 |
| private    | anyone      |        7 |
| unlisted   | creator     |        1 |
| public     | creator     |        3 |
| public     | anyone      |      277 |
| public     | no_one      |        1 |
+------------+-------------+----------+
````

So here's how I would solve this:

We set `is_public = 0` for all lists (there is no change in behavior because we don't use this column anywhere). Then we add a new setting in the user settings with a text like `Enable public lists to be visible everywhere. Without enabling this setting, public lists are only visible for everyone on the lists page and in the weekly exports.` (Maybe also add a sentence why this setting is necessary.)

On the list page nothing really changes and we can keep the options as they are. We probably should add a short note linking to the user settings. 

Everywhere else we check whether `is_public` is set in order to decide whether we display the list or not.

The biggest advantage would be that we don't need to find a good and concise explanation for having two public options that won't fill up too much space on the sidebar. And there is no change in the database (except resetting the column for 293 lists).

Did I miss anything?

**Comment by trang** [comment]
The column `is_public` was indeed used back when lists were only either collaborative or personal. Every list were in fact public, and `is_public` really only meant that they were editable by anyone (if I remember correctly).

I'm not sure if introducing an option in the Settings would be a good idea here, unless we somehow want to keep this feature a little bit more hidden (for instance if we're not yet completely confident it's a good feature).

If we want users to be actually aware of the new option, then we should display it in the options on the list page. Otherwise if someone never needs to change their settings, they would never know that there's the possibility to make lists visible on the sentence's page.

If we need to save space, we can convert the radio buttons into a dropdown list. We can even add a hint text for the selected option. This hint text would actually be useful even today because people may already misunderstand what each option really means. We can otherwise just add a help link/icon that either redirects to documentation that explains the difference between each visibility option, or that opens a dialog box with the explanation.

As for the wording, we could perhaps ask @alanfgh for a bit of help?

**Comment by bakananbanjin** [comment]
the wording problem still exists but after i tried to add a new value in the DB for a few hours i noticed that the visibility is an enum.... 
anyway after that it was 2 lines of code to change...
![image](https://user-images.githubusercontent.com/64922245/83921373-80645b80-a77e-11ea-8096-1c1b3dbdcc76.png)
if you hover over it it gives you the short tool tip and i added a small red new next to it. *which should be removed after a while
