### ISSUE TITLE
Caching works a little differently now than it used to.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1833]
Caching works a little differently now than it used to.

Perhaps this is one reason the site isn't getting as many contributions as we used to, since this likely not only slows down the perceived speed, but would likely slow down the whole site since people would be downloading more from the site.

I noticed it this way.

Before when I'd remove a sentence from a sentences page, using a JavaScript bookmarklet, and then returned to the page, it was still listed as being on the list on the side of the page, even though it wasn't.  I would have to reload the page if I wanted to verify that it wasn't on the list anymore.

Now, using the same method, when I go back to the page, the page completely reloads, clearly without the list name being shown.

Note that we have only had one day with over 2,000 new sentences since January 18, 2019.

http://tatoeba.ueuo.com/timeline/

Unless interest has dropped off drastically, it's likely that members are finding the website to be much slower.

**Comment by jiru** [comment]
I, too, noticed that pages are reloaded when clicking on the "back" button of my browser. It’s probably because CakePHP 3 has different defaults regarding caching headers. From a user’s point of view, I welcome this change because I am not showed invalid pages anymore, after logging in for example.

I don’t think this change makes the website any slower. Note that assets, which account for a great deal of the page loading time, are still being properly cached. So I don’t think it’s the reason.

Even if there is evidence that the website is slower that before, it doesn’t mean that’s the reason why we’re getting less contributions, because [correlation does not imply causation](https://en.wikipedia.org/wiki/Correlation_does_not_imply_causation).

**Comment by ckjpn** [comment]
It's OK with me if you close this.  I just thought you might want to be aware of the change and that it might possibly be part of why the website has seemed slow recently.
