### ISSUE TITLE
Vocabulary item feature is hard to discover

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1836]
In order for someone to discover the vocabulary item feature via the user interface, they need to follow this path:

Contribute
Add sentences
Sentences added (the heading for the bottom half of page)
Sentences wanted (clickable link that uses small capitals, unlike most links on Tatoeba)

At this point, they see a page that has the heading "Vocabulary that needs sentences", as well as a listing of items in different languages. They need to choose "Filter by language" in the right-hand sidebar in order to transform it to something that they can work with.

Now they need to choose between the following clickable links under "Vocabulary items" in the right-hand sidebar:
- My vocabulary items
- Add vocabulary items
- Sentences wanted

And whenever they go back to "Sentences wanted", the UI forgets the language that was selected, so the user needs to press "Filter by language" again.

This path is nonintuitive (if I want to request vocabulary, I'm not thinking that I want to add sentences), circuitous (many clicks required to get to the desired place), and inconsistent, especially with regard to terminology ("Sentences" vs. "Vocabulary items").

My suggestions:

(1) Use "vocabulary request" throughout:

"Vocabulary requests" (instead of "Vocabulary items")
"My vocabulary requests" (instead of "My vocabulary items")
"Add vocabulary requests" (instead of "Add vocabulary items")
"Existing vocabulary requests" (instead of "Sentences wanted")

(2) Add an item ("Add vocabulary request" or "Request vocabulary") to the "Contribute" menu that goes directly to vocabulary requests. Possibly remove the vocabulary-related part of the "Add sentences" page.

(3) Store and remember the value selected for "Filter by language" when it pertains to vocabulary requests.

**Comment by danail-georgiev** [comment]
This is an interesting proposition and I think that it is fairy straightforward to be implemented. 

However, I am not quite sure that the third point - storing the value from the Filtered language is something that should be done. As far as I see the filtered should be cleared every time when the page is left for some reason. 

@trang  and @alanfgh  Please advise if I should try to implement this and also what are the best names for the menus and the labels plus the value of the 3rd point.

**Comment by trang** [comment]
@danail-georgiev You can consider the 3rd point as a bonus more than a requirement for the scope of this issue. 

But just to explain the rationale behind it: by default you will see vocabulary requests in *every* language, even languages that you have no idea about. This is not exactly useful. Right now for instance, I see most that of the requests are for Portuguese. I don't speak Portuguese so I can't contribute example sentences for these items. I will have to select "French" (or "English") in the dropdown, but I will have to do that every time I come back to the page. That's why saving the last selected language and pre-selecting it for the next time you come back to the page makes sense.

For the wording of the new item in the "Contribute" menu, I would go with "Add vocabulary request" so that it stays consistent with the Vocabulary menu.

**Comment by alanfgh** [comment]
> Please advise if I should try to implement this and also what are the best names for the menus and the labels plus the value of the 3rd point.

@danail-georgiev , sure, I'd love it if you implemented this. From my point of view, I think this is the weakest part of the site in terms of usability, and any improvement would help. You ask what I think are the best names for the menus and the labels. My suggestions are listed in my initial post. Do you have any questions about other items, or about those suggestions?

**Comment by alanfgh** [comment]
Thanks for implementing this, @danail-georgiev !
