### ISSUE TITLE
It was possible to contribute an exact duplicate.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1837]
https://tatoeba.org/eng/sentences/show/7816804
I want to go and change into that shirt I bought yesterday.

It was possible to contribute an exact duplicate.
https://tatoeba.org/eng/sentences/show/7822631
I want to go and change into that shirt I bought yesterday.

**Comment by trang** [comment]
Possibly duplicate of #1647.

**Comment by ckjpn** [comment]
The way it was described in #1647 wasn't how this happened.
The way it was describe in #1647 has always been happening, and likely the best way to deal with this is cleaning up the problem with Horus.

**Comment by jiru** [comment]
@ckjpn Can you elaborate on how you contributed this duplicate?

**Comment by ckjpn** [comment]
> @ckjpn Can you elaborate on how you contributed this duplicate?

No.

**Comment by trang** [comment]
The hash was calculated before trimming the spaces. The sentence added by sharris123 had an extra space at the end and its hash was saved as `3atg62k` when it should have been `27gglud`.

**Comment by ckjpn** [comment]
This happened to me again today.

I accidentally contributed the same sentence Hybrid had, with the intention of adding a "the" and moving the audio to there.

https://tatoeba.org/eng/sentences/show/7930055

So, what happened was that Hybrid's sentence was deleted.

https://tatoeba.org/eng/sentences/show/7917428

**Comment by ckjpn** [comment]
Just to let you know, it happened again today.

https://tatoeba.org/sentences/show/8381346
https://tatoeba.org/sentences/show/8311762

I thought that I heard Tom snoring.

**Comment by AndiPersti** [comment]
There is also a similar problem when editing a sentence: Suppose there is a sentence `A simple sentence.` with hash `248lc35` stored in the database. After changing the sentence to <code>A&nbsp;&nbsp;simple sentence.</code> (two spaces between `A` and `simple`) we still store the original sentence text but the hash changed to `28i0a6u` because we currently only trim spaces at the beginning and at the end when saving an edited sentence.

Since there are 3 different code parts where hashes are created/modified (adding a sentence, editing a sentence, changing the language) I would restructure the hashing feature so that the hash is only calculated at one place after cleaning the sentence text.

Furthermore we also need a script/cake shell which recalculates the hashes for all sentences in the database because it seems there are a few wrong hashes stored.

All in all I'm not sure if this is really a good first issue.

**Comment by trang** [comment]
You're right, it's a bit more complex than what I had in mind initially. I removed the label.
