### ISSUE TITLE
Changing flag breaks audio

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1869]
Steps to reproduce:

1. Find a sentence with audio.
2. Go to the sentence page. Audio plays fine.
3. Change its flag.
4. Reload the page.
5. Try to play audio. Audio fails to play.

**Comment by alanfgh** [comment]
This makes sense because the path to the audio file includes the language of the sentence at the time it was linked to the audio. Note that we might have to check whether a sentence has audio when its flag is changed, and if so, move the file. Note that for sentences with audio, some operations, such as changing the text, are effectively restricted to admins (because they temporarily need to mark the sentence as not having audio while they make the change). Apparently, this is not true for changing the flag.

**Comment by ckjpn** [comment]
This isn't likely a big problem.  I'm not even sure that I would classify it as a bug.  It's definitely a low-priority thing, I think.

The only way it's appeared so far is when someone changed the flag to the wrong language.
It's pretty unlikely that someone who is recording sentences in their own native language would accidentally record a sentence in another language.

One possible fix would be to not allow changing the flag on sentences with audio.  In the unlikely case that it ever needs to be done, the changes could be made by someone with direct access to the server and database.
