### ISSUE TITLE
The activity timeline should be more flexible with deleted sentences

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1882]
Currently, the activity timeline (https://tatoeba.org/ita/contributions/activity_timeline/2019/05) keeps track of every single sentence that it's added. However, sentences that are eventually deleted are still kept in the count, and, in my opinion, they should be removed from it, since this could improve the accuracy of the overall contributions' stats.

If this isn't feasible, maybe we could have a distinction between the sentences that are contributed and the sentences that are deleted, so anyone who is interested in stats can see a clearer distinction between these two types of contributions

**Comment by jiru** [comment]
I think that removing a sentence is also a contribution and should be counted as such.

> If this isn't feasible, maybe we could have a distinction between the sentences that are contributed and the sentences that are deleted, so anyone who is interested in stats can see a clearer distinction between these two types of contributions

That seems like a good idea to me, but I think we need to think more about the problem you are trying to solve here, in order to come up with a good solution. Currently, the graph answers the question: how many contributions were done each day? Now, what other questions would you like the graph to answer?

**Comment by Guybrush88** [comment]
within the graph, I'd personally like to see a clearer distinction between the sentences that have been actually contributed and the sentences that are actually deleted, since they're different types of contribution, and, if a user needs some stats about the actual growth of the whole corpus, this would be a clearer distinction for this purpose (i.e.: there could be a mass deletion of sentences and even more new sentences are added on the same day, but the graph currently doesn't show an accurate chart of sentences' contributions during that day, so I don't find this an accurate stat)

**Comment by jiru** [comment]
I think it's a good idea, so I'd like to know why you want to see the number of deleted sentences per day, so that we can find a good way to display that information. Here is a non exhaustive list of questions I suggest you ask yourself. Do you want to see the actual number of deleted sentences? Or you just want to visually compare how much it represents compared to the number of added sentence on a given day? Or, since you're talking about the growth of the corpus, do you want to be able to compare the number of deleted sentences with the next/previous day?

**Comment by Guybrush88** [comment]
Do you want to see the actual number of deleted sentences? Or you just want to visually compare how much it represents compared to the number of added sentence on a given day?

Maybe we can have both, if feasible. I suggest a bar with a different color and, next to it, the number of deleted sentences, so we could have: on the far left the total number of sentences that have been added, next to it on the right a visual bar, to the right of this bar another bar (with a different color) representing the deleted sentences, to its right the total number of deleted sentences

Or, since you're talking about the growth of the corpus, do you want to be able to compare the number of deleted sentences with the next/previous day?

maybe a daily average would be fine for me, as it currently is for the total number of contributions
