### ISSUE TITLE
Vocabulary items count is wrong

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1886]
As reported by Seael on the wall:

> Something is wrong with the counting here: https://tatoeba.org/eng/vocabul...es/spa?page=32
> 
> Two examples (there are more):
> 
> 1) It says there are 8 sentences containing the word "cigüeñas" and when you click on the link, they are actually 12 sentences.
> 
> 2) The count becomes negative with the term "fascista". It says there are 8 sentences and, when you follow the link, it only shows 6.

https://tatoeba.org/ita/wall/show_message/31800#message_31800

**Comment by ckjpn** [comment]
Perhaps this is related.

https://github.com/Tatoeba/tatoeba2/issues/1388

**Comment by soliloquist-tatoeba** [comment]
A similar syncing problem affects lists, too. The counts of some lists on the index page are incorrect. I suspect that removing sentences from lists triggers the issue.


<img width="519" alt="tat" src="https://user-images.githubusercontent.com/47579687/57398650-35bd8c00-71d8-11e9-9fdb-468331634104.png">

**Comment by ckjpn** [comment]
Perhaps this one is related, too.  (It's been closed.)

https://github.com/Tatoeba/tatoeba2/issues/1278

**Comment by ckjpn** [comment]
The one soliloquist-tatoeba mentioned is already an issue reported in 2016.

https://github.com/Tatoeba/tatoeba2/issues/1277

**Comment by AndiPersti** [comment]
> 2. The count becomes negative with the term "fascista". It says there are 8 sentences and, when you follow the link, it only shows 6.

The link loads the result page with the default search options which exclude sentences which are orphan or unapproved.
"fascista" isn't on the vocabulary list anymore because there are [already 15 sentences](https://tatoeba.org/eng/sentences/search?query=fascista&from=spa&to=und&user=&orphans=&unapproved=&has_audio=&tags=&list=&native=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance&sort_reverse=) with that word. But if you exclude orphan and unapproved sentences from the search you get [13 sentences](https://tatoeba.org/eng/sentences/search?query=fascista&from=spa&to=und&user=&orphans=no&unapproved=no&has_audio=&tags=&list=&native=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance&sort_reverse=).

A current example is "trafficking": The vocabulary list says there are [9 sentences](https://tatoeba.org/eng/vocabulary/add_sentences/eng?page=136). But following the link [only shows 7](https://tatoeba.org/eng/sentences/search?query=%3D%22trafficking%22&from=eng). Reason: [2 sentences are orphaned](https://tatoeba.org/eng/sentences/search?query=%3D%22trafficking%22&from=eng&to=und&user=&orphans=yes&unapproved=&has_audio=&tags=&list=&native=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance&sort_reverse=).

So the solution is to either exclude orphan and unapproved sentences in the vocabulary count (harder) or link to the result page which includes orphan and unapproved sentences (easier).

**Comment by trang** [comment]
Let's go for the second option: link to the result page which includes orphan and unapproved sentences.

Regardless of what is easier to do, excluding orphan and unapproved sentences from the vocabulary count would require us to answer the question: do we think that orphan and unapproved sentences are completely useless to everyone who creates vocabulary items?

I personally cannot answer that question right now and until we can make a decision, I think we should take into account all the sentences in the vocabulary count. Orphan or not, unapproved or not.
