### ISSUE TITLE
I suggest putting "Audio" above "License" on the right side of the sentences' pages.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1888]
I think people are much more likely to be interested in who recorded a sentence than what license each sentence is.

The license information is more likely mainly of interest to those who download all the data, so perhaps that could even be put below the Logs.

<img width="1120" alt="Screen Shot 2019-05-11 at 11 04 04" src="https://user-images.githubusercontent.com/7934273/57563785-0cba1880-73dd-11e9-952e-746f9f3d19d8.png">

I still wish something could be done about the "green" link colors that are hard to read.
 (Reference: https://github.com/Tatoeba/tatoeba2/issues/1164)

I can fix this using Stylish on my own computer, but not on a mobile.
I'm doing a presentation on the Tatoeba Project at a conference at the end of this month, so wanted to make screen shots that look like the actual site, but I don't think they'll show up well in a PowerPoint presentation, so I'll likely do the screen shot with the Stylish improvements.

**Comment by jiru** [comment]
> I think people are much more likely to be interested in who recorded a sentence than what license each sentence is.

That’s all good, but your own opinion may not reflect the majority of the users. I don’t see an obvious answer to the question of which block is more important.

**Comment by trang** [comment]
I will close this issue. Feel free to re-open if you have a use case where it is necessary to have the audio info displayed before the license info. But otherwise we will keep the info blocks in the current order.

Note that recently a kind stranger fixed a bug where the tooltip was not mentioning the name of the user who recorded the audio (#1899). So now it's possible (again) to see who recorded the audio just by hovering over the audio icon and that's probably better than having the Audio above the License block.
