### ISSUE TITLE
Horus should probably not be moving "outdated ratings"

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1893]
When someone corrects an error and a sentence gets merged with the correct sentence, Horus is currently moving "not good" ratings to the correct sentence with an "outdated" comment.

Since members didn't really rate the good sentence that way, perhaps it would be a good idea to have Horus, the duplicate-merging script, not move such ratings.

https://tatoeba.org/eng/sentences/show/566994

<img width="1129" alt="Screen Shot 2019-05-22 at 10 10 32" src="https://user-images.githubusercontent.com/7934273/58140550-9fc73e00-7c7a-11e9-8c5a-5c018712ad40.png">

**Comment by jiru** [comment]
> Since members didn't really rate the good sentence that way

Isn’t that why the review is marked as outdated? Unless the review is reviewed, we have no way to know if the reviewer still wants to mark the sentence as "not OK". The reviewer may think that the change that induced merging makes it "OK", or maybe the reviewer has other reasons to keep its review as "not OK".

**Comment by trang** [comment]
I can somewhat see the rationale in not moving the rating. Since the new sentence doesn't carry the history of the old sentence, the user could be confused about what happened, wondering why is the rating "outdated" when the sentence hasn't even been edited.

On the other hand, leaving it on the old sentence makes it more complicated to update the rating. I would first have to go to the page of the deleted sentence, then remove my rating from there (if that's even possible), then go to the new sentence to apply my rating.

I think it's better to keep things as they are now. Most likely users won't really look at the history, they just look at the sentence. If it's correct now, they update the rating to OK, and that's it.

I'll close this but feel free to re-open if you have a scenario where keeping the rating on the old sentence would be better.
