### ISSUE TITLE
Sphinx search on VM results in warning message

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#191]
On a VM, I searched for the word "simplistic" with "Any" as the value for both "From" and "To". I got this:

:::
Notice (1024): Search query warning: index 'tur_index': query word(s) mismatch: simplistiç [APP/models/behaviors/sphinx.php, line 110]
:::

However, the search succeeded, finding two sentences in English that contained the word "simplistic". 

I was using lool0's early April VM.

**Comment by jiru** [comment]
It happens on the server as well (PHP messages are redirected in `app/tmp/logs/debug.log`). According to [this](http://sphinxsearch.com/forum/view.html?id=8699#42800), that warning is harmless. It shows up because each of our indexes uses different stemmization rules and thus return different matched words. We should however prevent that warning from spamming the logs.

**Comment by jiru** [comment]
These warnings seem to have been removed in newer versions of Sphinx.
