### ISSUE TITLE
It's hard to add languages you speak/know

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1916]
I was trying to add some more languages I know on my profile. I visited [my own profile](https://tatoeba.org/fra/user/profile/Ricardo14) to do so and clicked on "Add language".  I added Bavarian to the list but to add other languages, I had to click on "save" and do the progress all over again. It may make that new members don't add all the languages they know and the progres is kinda tricky since it's not obvious I have to repeat the process all over again. On many websites we can add all the languages we speak at once - including adding your proficiency.

**Comment by jiru** [comment]
I agree. We could allow to add languages right from the profile page, or change the "add a language" page into an "edit language list" page.

**Comment by jiru** [comment]
There is another related problem for new members. After they register, they see a banner asking them to fill languages in their profile. The banner includes a link to their profile page. So they land on their profile page, and from there, they have to figure out how to add languages by finding the "add a language" button. This step [proved to be somewhat difficult in a UX test](https://en.wiki.tatoeba.org/articles/show/ux-test-1), because the user discovers the profile page for the first time and the button is located down right.

So when this issue is fixed, we should probably also update the link in the welcome banner to bring users more directly to where they can add a new language.
