### ISSUE TITLE
Language in latest contributions is not updated

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#192]
On the VM, where autorecognition of sentence languages was not working, I added several languages in English, then manually changed them from "unknown" to "English". Later, when I went to "Home"/"Latest contributions", they were still listed as unknown (question marks). However, the ones that I marked as English from the start (instead of using autodetect) have the proper English icons next to them. I wonder if this is related to the problems that we see where:

- some sentences are being marked with "null" in a given field and others are marked with something else
- sentence counts differ depending on where they're calculated

**Comment by trang** [comment]
I'm updating the title of this issue because this is a problem that is unrelated to the fact that a sentence's language has not been recognize. It can be reproduced even when the language was recognized. It's just that the language in the "latest contributions" is not updated when the language of a recently added sentence is updated.

**Steps to reproduce**

1. Add a new sentence in any language.
2. Go to the homepage: the sentence is displayed in the "Latest contributions".
3. Go the the sentence's page and change the language into any other language.
4. Go back to the homepage: the language of the sentence hasn't changed in the "Latest contributions".

**Expected result**
The language of the sentence should be updated to the new language that was set for that sentence.
