### ISSUE TITLE
German ß is not treated like a regular letter when searching

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#1951]
Reported on the wall https://tatoeba.org/eng/wall/show_message/32566#message_32566

**Comment by Yorwba** [comment]
Looking at the way excluding a punctuation mark was handled [previously](https://github.com/Tatoeba/tatoeba2/commit/e8cf0d36be929112dfa84de98378e4e8f0b56e43) this seems to require modifying the searchable character range [ending at `U+DE`](https://github.com/Tatoeba/tatoeba2/blob/5fd1ded193f39d290dd1368c1eec22fb6c2d67cf/src/Shell/SphinxConfShell.php#L55) to also include ß `U+DF`. The case-folding part might be a bit tricky to implement, since ß, ss, SS and ẞ `U+1E9E` should all fold to the same value (though nobody uses that last one).

**Comment by alanfgh** [comment]
If worst comes to worst, simply folding ß to itself should be fine. I doubt anyone will demand conversion between ß and ss, and I doubt any of our users will use ẞ U+1E9E.

**Comment by jiru** [comment]
Yeah, folding ß to itself is a good start. If we are to make searching for ß find "ss" and vice-versa, note that it will make searching for ß only impossible as "ss" results will always be included, regardless of the use of the exact search operator *=*.

**Comment by Yorwba** [comment]
While I agree that folding ß to itself is probably best for Standard German, there are some other related languages with different orthographic rules, where replacing it with "ss" might be more appropriate. So I decided to ask about it  [on the wall, together with a few thousand other characters](https://tatoeba.org/eng/wall/show_message/33106#message_33106).

**Comment by alanfgh** [comment]
Let's go back to the context in which the issue was reported. A user complained that an exact phrase search in Standard German for "Fuß" was also pulling up other terms like "Fußballer". We can fix that issue easily by mapping ß to itself, either for Standard German or for all languages. Mapping a single character to a character pair, or vice versa, is bound to be more complicated. If we widen our scope to insist on following orthographic rules (quite possibly not followed in the real world) for other languages, in which no one has yet reported a problem, and then beyond that to a few thousand other characters, it's hard to imagine anything happening. In any case, you have a new issue ticket to keep track of the few thousand other characters. My vote is for simply folding ß to itself, either for Standard German or for every language, and then closing this ticket.

**Comment by alanfgh** [comment]
Nice!
