### ISSUE TITLE
Possibility to filter sentences by word count

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1954]
As suggested by MisterTrouser on the Wall:

> 
> Suggestion for a new filter: Word count.
> 
> Current situation:
> It's possible to sort by "fewest word count". However, that might give you the first 30 pages with sentences like "really?", "hurry!" or "silence!".
> 
> Suggestion:
> Add a new filter, where the word count can be set.
> 
> Reason / Good points:
> - Beginners could search short to mid-long sentences specifically through word count.
> 
> Regards

https://tatoeba.org/ita/wall/show_message/32611#message_32611

**Comment by riverxside** [comment]
Hi, can you add me to the project ? I 'd like to solve this issue.

**Comment by trang** [comment]
@riverxside You don't need to be added to the project to solve this issue :) You just can fork the repository and [create a pull request from your fork](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

**Comment by trang** [comment]
More recent wall thread on this topic: https://tatoeba.org/eng/wall/show_message/35723

**Comment by jiru** [comment]
Even more recent wall thread: https://tatoeba.org/fra/wall/show_message/36541

**Comment by ckjpn** [comment]
This title should be renamed ...

FROM:
Possibility to filter words by word count 
TO:
Possibility to filter sentences by word count

**Comment by Sobsz** [comment]
Bumping this, as I've recently had the need to search for longer sentences to translate. I currently use a workaround hinted at in the wiki, namely putting two common words in quotation marks with a number of asterisks between them (e.g. `"she * * * * * * * * * her`). However, this only helps establish a minimum length, not a maximum one, and it's rather restrictive.

An issue might arise due to some languages (e.g. Japanese) not having clear word separation. Possible solutions, in order of effort required:
- filter by character count instead
- filter by word count or character count, depending on the language (Manticore [seems to do this](https://tatoeba.org/en/sentences/search?from=jpn&query=%22%E7%A7%81+*+*+*+*+%E5%AF%9D%E3%82%8B%22) for wildcards)
- import a whole dang library for splitting words in the affected languages

**Comment by ckjpn** [comment]
Related Wall Post.

https://tatoeba.org/en/wall/show_message/39305#!#message_39305

Hi!

I don't know whether this has been asked before, but I was wondering whether it could be possible to search for example sentences of a specific length. For example, looking for sentences that are at least 4-word long and at most 9-word long.

Thanks in advance!
