### ISSUE TITLE
Download of the audio files

### ISSUE THREAD

**Issue by B-bit-maker** [Tatoeba/tatoeba2#2018]
Hello everybody,
I'd like to ask if it's possible to implement a way to download the audio files (maybe divided by language). I'm asking because I'm creating cards on Anki and downloading all the audio files one by one takes a lot of time, even if I automate the process (including the sleep time as well).
Thanks

**Comment by Yorwba** [comment]
Sounds like you already have an automated process for downloading audio, but the problem is that it takes too long.

I think that's likely due to reconnection overhead. For example, passing 100 files to `wget` at once, it will reuse a single HTTP connection and finishes pretty quickly:

```bash
wget $(grep -e 'manythings' sentences_with_audio.csv | tail -n100 | sed -e 's|^\(\S*\)\s.*$|https://audio.tatoeba.org/sentences/eng/\1.mp3|')
```
on my machine prints something like

```
----8<---- (100s of lines omitted)

2019-11-21 16:57:53 (27.8 MB/s) - ‘8322828.mp3’ saved [15256/15256]

--2019-11-21 16:57:53--  https://audio.tatoeba.org/sentences/eng/8322829.mp3
Reusing existing connection to audio.tatoeba.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 17209 (17K) [audio/mpeg]
Saving to: ‘8322829.mp3’

8322829.mp3        100%[=============>]  16.81K  --.-KB/s    in 0.002s  

2019-11-21 16:57:53 (10.9 MB/s) - ‘8322829.mp3’ saved [17209/17209]

FINISHED --2019-11-21 16:57:53--
Total wall clock time: 4.1s
Downloaded: 100 files, 1.4M in 0.05s (30.8 MB/s)
```

If you're seeing speeds slower than that, the problem is unlikely to be with tatoeba.org, but with the way you're downloading the files.

**Comment by B-bit-maker** [comment]
Downloading 2000+ files with wget won't cause the server any problems? When I write scripts in Python I usually use the sleep function to avoid that, do I need to use something similar with wget?

**Comment by Yorwba** [comment]
If the 100 files I downloaded to test are representative, 2000 files should be about 30 MB, which is still smaller than e.g. the `sentences_detailed.tar.bz2` file I download every week (like probably a bunch of other people). I think the server should be able to stomach the load of downloading those files once. If you intend to update them regularly, I recommend passing the `--timestamping` option to `wget`. That way, it won't download files that didn't change since the last time you ran the command, saving some bandwidth.

**Comment by B-bit-maker** [comment]
So, what matters is the total size of the downloaded data? I thought it was the number of requests made to the server.

**Comment by Yorwba** [comment]
What matters is that your download does not negatively affect anyone else. So long as you keep your requests sequential, I don't think there's a difference between many small files and one large one. To play it safe, you could use the `--wait` or `--limit-rate` to prevent yourself from hogging all the bandwidth continuously.

**Comment by B-bit-maker** [comment]
Ok. Thank you very much, you've been very helpful.
