### ISSUE TITLE
Make user sidebar menu collapsible

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/tatoeba2#2023]
The sidebar menu on a user page is pretty long. Thus the language filter element (and other similar filter elements) on some user pages (Sentences of, Audio of, Translate sentences of and Profile) is only accessible after scrolling down a bit. How about making the sidebar menu collapsible?

**Comment by Poulpisator** [comment]
Yes, please! And I also suggest to make it collapsed by default. If I check a user page, may it be its profile, its sentences, etc., it is more important to me to see information relative to this page than a list of links to other pages. 

I realized that there was an option to only show orphan sentences only because I saw the sentence untranslated in Transifex... (Yes, I know it's very recent and maybe I would have realized after a while. But maybe not)

**Comment by Poulpisator** [comment]
It doesn't seem intuitive that a click on the username will bring a whole new menu. Maybe "More of <user>'s contributions" or something like that would make it clearer. @alanfgh Any suggestion of a good, concise string?

I'm not sure my second point is due to the new code but I only realized it when I checked the new page. Please have a look at this image https://imgur.com/a/HX6OLYv (using Firefox)  
You can see that the page is not correctly resized on small windows (simply split my screen in two) and that all menus exceeds the limit of the Tatoeba background. That is the case of all menus of all pages. As I said, I don't know if it's linked to the new code but it impacts it, since the arrow of the new menu is not visible if you don't slide the page to the right (making my first point even more problematic).

**Comment by AndiPersti** [comment]
> It doesn't seem intuitive that a click on the username will bring a whole new menu. Maybe "More of 's contributions" or something like that would make it clearer. @alanfgh Any suggestion of a good, concise string?

Just some ideas:
- Use "xxx's Pages" or "More [info] about xxx" as the text
- Expand the menu automatically when the cursor hovers over the element (like in the top bar; won't work on mobile)
- Move the arrow to the front

> You can see that the page is not correctly resized on small windows (simply split my screen in two) and that all menus exceeds the limit of the Tatoeba background. That is the case of all menus of all pages. As I said, I don't know if it's linked to the new code but it impacts it, since the arrow of the new menu is not visible if you don't slide the page to the right (making my first point even more problematic).

As you've noticed yourself this happens on all pages with a sidebar so this should be a new issue.
(I guess this will be handled by the [Responsive UI project](https://github.com/Tatoeba/tatoeba2/projects/3). See also #1180 (especially phase 3).)

**Comment by Poulpisator** [comment]
Other things bothering me about this menu (not entirely related to this issue). 
- This menu is not displayed on the following pages: Vocabulary, Collection, Lists. Designly speaking, I think it should be.
- Except Audio, and Translate user's sentences, the other pages below Lists (Favorites, Comments, etc.) do not have any other menu so I see no reason to collapse this menu there.

**Comment by AndiPersti** [comment]
>This menu is not displayed on the following pages: Vocabulary, Collection, Lists. Designly speaking, I think it should be.

I agree that these pages need a more consistent design and have opened a new issue: #2074

**Comment by ckjpn** [comment]
I personally don't like this.

If you are going to stick with this, I'd suggest instead of duplicating the username as the title for these links, put "Links" or "Related Links" or something similar to make it obvious that visitors need to click this to find something.

<img width="1016" alt="Screen Shot 2020-01-20 at 9 01 14" src="https://user-images.githubusercontent.com/7934273/72690880-c4561b80-3b63-11ea-87e7-fc60cd41b7e4.png">

**Comment by trang** [comment]
> If you are going to stick with this

We are not. This will stay only until we redesign the user pages.

Turning the website into a responsive website will require to get rid of the sidebar, which means the design of the whole page needs to be reworked. And redesigning the whole page means redesigning all the user pages (#2074) in order to have something consistent.
