### ISSUE TITLE
UTF-8 characters in the CSS sometimes get interpreted as another encoding instead

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2039]
[Reported by Pandaa on the wall](https://tatoeba.org/eng/wall/show_message/33747#message_33747)

![](https://i.imgur.com/iRtGRrl.jpg)

The character before "Advanced Search" should be `▸ `. The `â–¸ ` visible in the screenshot is the result of decoding the UTF-8 bytes as any of several other encodings like Windows code page 1250.
I'm guessing that the browser is incorrectly using that encoding because it has not been declared explicitly by the point the `layout.css` file is being parsed.

[W3.org says the following about declaring the character encoding of CSS](https://www.w3.org/International/questions/qa-css-charset):
> You should always use UTF-8 as the character encoding of your style sheets and your HTML pages, and declare that encoding in your HTML. If you do that, there is no need to declare the encoding of your style sheet.
> Other approaches are only needed if your style sheet contains non-ASCII characters and, for some reason, you can't rely on the encoding of the HTML and the associated style sheet to be the same. In this case you should use `@charset` or HTTP headers to declare the encoding. (If your HTML and CSS files use the same encoding, the latest versions of major browsers will apply the encoding of the HTML file to the CSS stylesheet.)

There is no `@charset` declaration in `layout.css`, but the CSS uses the same encoding as the HTML. Under the assumption that someone who knows how to open the developer tools also keeps their browser up to date, I guess that makes it likely the HTML encoding was not declared properly.

There is a `<meta charset="utf-8">` tag in the HTML, but it comes after a long list of inline styles. [W3.org says that the declaration should be within the first 1024 bytes](https://www.w3.org/International/questions/qa-html-encoding-declarations):
> Always declare the encoding of your document using a meta element with a charset attribute, or using the http-equiv and content attributes (called a pragma directive). The declaration should fit completely within the first 1024 bytes at the start of the file, so it's best to put it immediately after the opening head tag.

Maybe that is the root cause.

**Comment by AndiPersti** [comment]
> There is a `<meta charset="utf-8">` tag in the HTML, but it comes after a long list of inline styles. [W3.org says that the declaration should be within the first 1024 bytes](https://www.w3.org/International/questions/qa-html-encoding-declarations):

But the meta tag comes directly after the opening head tag:

    $ curl -s https://tatoeba.org/eng | head -n 5
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8"/>    <title>
            Tatoeba: Collection of sentences and translations    </title>

And the inline styles are generated by [AngularJS Material at runtime](https://material.angularjs.org/latest/Theming/05_under_the_hood). So I'm not sure that this is the problem.

I'll ask Pandaa whether s/he can give us more information (OS, browser, ...).

**Comment by AndiPersti** [comment]
I've [checked `layout.css` with the W3C CSS validator](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Ftatoeba.org%2Fcache_css%2Flayout.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en) and while it shows a lot of warnings which can be ignored, it also shows the CSS it has validated. The important part is:

    .search-bar-extra a:before {
      content : 'â¸ ';
    } 

So it also doesn't use `utf-8`. 

It looks like we have to add `@charset "utf-8";` at the beginning of that file to be sure that it is interpreted with the correct encoding.

(Adding the charset declaration to `layout.css` and testing it with the W3C validator gives the correct result.)

**Comment by AndiPersti** [comment]
I think I've found another reason why `css` files aren't recognized as UTF-8.

In the `nginx` configuration we set `charset utf-8;` which works for `html` and `js` files:

    $ curl -s -i -I https://tatoeba.org/cache_js/layout.js | grep '^content-type'
    content-type: application/javascript; charset=utf-8
    $ curl -s -i -I https://tatoeba.org/index | grep '^content-type'
    content-type: text/html; charset=UTF-8

But that doesn't work for `css` files:

    $ curl -s -i -I https://tatoeba.org/cache_css/layout.css | grep '^content-type'
    content-type: text/css

The reason is that `nginx` only adds the charset to the MIME types defined in `charset_types` which by [default doesn't include `text/css`](http://nginx.org/en/docs/http/ngx_http_charset_module.html#charset_types) and we need to [add `text/css` ourselves](https://trac.nginx.org/nginx/ticket/312).

I've made this change on my private server and sent an unmodified `layout.css` from it to the W3C CSS validator and the validator recognized the UTF-8 character.

So there are two possible solutions:
1) Add `@charset "utf-8";` to the beginnig of `layout.css`
2) Add `charset_types text/html text/xml text/plain text/css application/javascript;` to the `nginx` configuration. (We don't need `application/rss+xml` and `text/vnd.wap.wml`, do we?)

W3C reoommends doing both:
> However, we recommend that if you need to use an HTTP declaration to set the correct encoding, you also include an @charset declaration inside the style sheet. This will ensure that the encoding is still known if the style sheet is used locally or moved, eg. for testing or editing.

What do you think?

**Comment by jiru** [comment]
I think putting `@charset` directives is the most robust way to solve the problem. However, I am not sure how to go about that because some of our CSS files, like `layout.css`, are generated using the asset_compress shell. We could insert a file containing only the charset directive at the beginning of the CSS file list in `config/asset_compress.ini`. Or maybe use the `filters[]` thing: create a filter that just inserts the charset directive.

**Comment by AndiPersti** [comment]
> We could insert a file containing only the charset directive at the beginning of the CSS file list in `config/asset_compress.ini`.

That's what I have planned to suggest in a PR but I was rather busy this week and hadn't had time yet.

> Or maybe use the `filters[]` thing: create a filter that just inserts the charset directive.

We could do that, but there is a recent suggestion to add a [generic filter which executes a given command](https://github.com/markstory/asset_compress/issues/344) which is exactly what we would need. But I'm not sure how soon it will be available.
