### ISSUE TITLE
Standardize the way sentences as displayed in the "new look."

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2080]
Wouldn't it be better to have the sentences displayed the same way in the various pages on the site? 
## This is one pattern.
<img width="592" alt="Screen Shot 2020-01-19 at 18 25 03" src="https://user-images.githubusercontent.com/7934273/72678510-faef5000-3ae9-11ea-99ac-cc9cbe0edd91.png">
<img width="580" alt="Screen Shot 2020-01-19 at 18 24 39" src="https://user-images.githubusercontent.com/7934273/72678511-faef5000-3ae9-11ea-9fa6-a31c00eb09d4.png">
<img width="581" alt="Screen Shot 2020-01-19 at 18 24 06" src="https://user-images.githubusercontent.com/7934273/72678512-fb87e680-3ae9-11ea-8adc-420f0c005904.png">

## Comments are almost the same, but not quite.
<img width="590" alt="Screen Shot 2020-01-19 at 18 23 26" src="https://user-images.githubusercontent.com/7934273/72678513-fb87e680-3ae9-11ea-9e84-75ebb9fb5dd0.png">

## These are different.
Add a sentence.
<img width="704" alt="Screen Shot 2020-01-19 at 18 28 23" src="https://user-images.githubusercontent.com/7934273/72678527-10fd1080-3aea-11ea-86f5-effd24b22623.png">

Each sentence's page.
<img width="585" alt="Screen Shot 2020-01-19 at 18 23 40" src="https://user-images.githubusercontent.com/7934273/72678528-10fd1080-3aea-11ea-8b29-43f8f73b13bb.png">

**Comment by trang** [comment]
The sentence in the comment is meant to be just a preview of the sentence and this won't change. The focus should be on the comment and not on the sentence.

The sentence on the "Add sentence" page is still using the old design because we would have to migrate the functionality from jQuery to AngularJS to be able to use the new design.

Same thing for the sentence on the homepage or the lists. The code would need to be rewritten with AngularJS.

As for the sentence page, it will remain with the old design until all the features are ported to the new design because it ensures that people who have the new design enabled can still access all the sentence features if they need to.
