### ISSUE TITLE
Mingrelian (xmf)

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#2087]
- Language name: Mingrelian
- Language info: https://en.wikipedia.org/wiki/Mingrelian_language
- ISO 639-3 code: xmf
- Public List: https://tatoeba.org/eng/sentences_lists/show/8696
- Icon: http://lingvisto.org/pics/mingrelia_flag_30x20.png
- Requested by: https://tatoeba.org/eng/user/profile/lovermann

[for tatoeba.org]
CALL add_new_language('xmf', 8696);

**Comment by lovermann** [comment]
If anybody has any questions about the flag, I would appreciate a discussion (here or on tatoeba.org). It was very hard to find mingrelian flag, because Samegrelo (historically correct name of the region, where mingrelians lived and live, former region of [Colchis](ukrainianconsular@gmail.com).) was never a independent state or country. That's why I've found this flag in wikipedia as mingrelian flag.

**Comment by Yorwba** [comment]
Regarding the flag: I thought we were switching to SVG for the flag images, so shouldn't we use [this file](https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_The_Principality_of_Mingrelia_%28Portolan_1560%29.svg) instead?

**Comment by lovermann** [comment]
> Regarding the flag: I thought we were switching to SVG for the flag images, so shouldn't we use [this file](https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_The_Principality_of_Mingrelia_%28Portolan_1560%29.svg) instead?

Sure, you can. I thought I should make small icon for it. But if you do it, I would be good!

**Comment by RyckRichards** [comment]
@Yorwba - I used the .svg flag in my PR - https://github.com/Tatoeba/tatoeba2/pull/2089/files :)

**Comment by Yorwba** [comment]
That's an SVG with embedded PNG, which isn't much different from using a PNG directly. In particular, it doesn't have the advantage of normal SVGs that they look sharp at all possible resolutions. If we wanted to scale the flags up for high-resolution screens, for example, the embedded PNG would look blurry.

**Comment by RyckRichards** [comment]
This is the one we have been using for all the flags. We called it "fake svg" but it was an easier way to implement this kind of language icon on Tatoeba.

**Comment by Yorwba** [comment]
It's a good solution for the transition period, but if there's a non-fake SVG available, that one should probably be used instead.

**Comment by RyckRichards** [comment]
That's the point. For most of flag the flags there isn't any svg available. (French flag is the only one which is not a "fake" one, I think. @trang knows about it better). 
I'm the one who converts ,png flags into .svg. since I'm not able to create .svg flags myself. :/

**Comment by trang** [comment]
The French flag is still a fake SVG. It was given as an example of usage of a real SVG in the merge request that migrated the flags to SVG (#1806), but we reverted it to a fake SVG because the real SVG was looking too different. Back then we still had the "shadow" and the saturation effect set on the image itself rather than in the CSS.

Now that we moved the shadow effect to the CSS and removed the saturation, we should at some point make a pass on which of the fake SVG's we can replace by a real SVG. There are a significant amount of them that are available on Wikimedia.

@RyckRichards For our case here, since a real SVG has been provided and it looks the same as the fake SVG, you can use it in your pull request.

**Comment by RyckRichards** [comment]
That's OK, Trang. I'm going to work on it :) I may have some questions about "sizing" the SVG flag

@sabretou perhaps we should have a look on https://tatoeba.org/eng/stats/sentences_by_language to check which flags we'll have to change
