### ISSUE TITLE
Play audio button does not work

### ISSUE THREAD

**Issue by Chi-teck** [Tatoeba/tatoeba2#2088]
When clicking the button the audio does not play and the following error appears in the browser console.

> layout.js?1579449934:41 TypeError: $event.stopPropagation is not a function
>     at SentenceAndTranslationsController.playAudio (sentence-and-translations.dir.js?1579448631:120)
>     at fn (eval at compile (layout.js?1579449934:1), <anonymous>:4:270)
>     at i (layout.js?1579449934:56)
>     at g.$eval (layout.js?1579449934:45)
>     at g.$apply (layout.js?1579449934:45)
>     at HTMLButtonElement.<anonymous> (layout.js?1579449934:56)
>     at HTMLButtonElement.dispatch (layout.js?1579449934:15)
>     at HTMLButtonElement.f.handle (layout.js?1579449934:14)

**Comment by AndiPersti** [comment]
Audio only doesn't work in the new design on the main sentence. Audio for translations works. For example on https://dev.tatoeba.org/eng/sentences/show/239 the German audio doesn't work while any audio on translations works.

The problem is in `src/Template/Element/sentence_buttons/audio.ctp` where `playAudio` still gets an URL instead of an event:
https://github.com/Tatoeba/tatoeba2/blob/3f71e6d5c206a194cf7f426f9403a0f92af9d053/src/Template/Element/sentence_buttons/audio.ctp#L21-L26
