### ISSUE TITLE
Having an easier way to send a PM

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2094]
On https://tatoeba.org/eng/private_messages/write we have to type the user our users' name(s) in order to send a PM.
It's not a big deal if it's a small one. But most of the times it can be tricky.
» Sometimes the usernames are very big;
» It may have capitalized letters and/or underscores and/or numbers
» We may want to send PM to a couple of users and it's not that clear for many users that they have to type (not conventional in many other websites)

![image](https://user-images.githubusercontent.com/7658430/73115492-40a28300-3f05-11ea-911d-fc27e380af51.png)

I'd suggest an "auto fill" / "autocomplete" as we have on Gmail, for example. We start typing a user / some usernames. It would display some users and we select them by clicking or something

![image](https://user-images.githubusercontent.com/7658430/73115653-c1fb1500-3f07-11ea-8b9f-bb7b6ca17e5e.png)

**Comment by trang** [comment]
Closing because too low priority to be ever implemented.

Note that in general any feature request regarding private messages will be out of scope. I know that there could be many things to improve in the private messages but we cannot afford it. It is too off-topic compared to the core activity of Tatoeba.

@RyckRichards When I have to write a private message to someone with a long username, I usually go to the profile page and copy the username. I know it's not as intuitive as an autocomplete but it's the only tip I can give you.

**Comment by RyckRichards** [comment]
I see your point, Trang! Thank you!
