### ISSUE TITLE
Improve issue browsing and categorization on GitHub

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2124]
With almost 300 issues, it's getting harder to browse issues. Let's face it, GitHub search is not so great. Sometimes I *know* an issue exists but I waste my time searching until I find it. Lately I ended up taking notes on paper to browse a database...

So my suggestion is simple : categorize issues by topic. Since projects are not really adequate for the task, what about labels? Right now, there are at least 3 important topics: search, tags, lists. But other exists, i.e. responsive ui, vocabulary, orphans. All of them have many issues. Having issues properly listed would help in several ways. 
- It would allow people interested in improving one functionality to easily find something they could do. 
- It would be easier to identify functionalities that are closely related, hence could or should be treated together. 
- It would make identifying duplicate issues more easily.

**Comment by jiru** [comment]
I never had a problem using Github search. Sometimes I have to search multiple times until I find what I want, but it has never been a problem to me. Maybe it’s because I have been contributing for a long time so I can use my own memory to find duplicates.

I understand the problem you are trying to solve, but your proposed solution brings a new problem. It means more burden because now we have to tag all existing and future issues by topic. Do you really think that it worth the extra effort? Besides, if such tags are only useful to you, it is likely that other contributors won’t keep tagging issues like you if you ever stop contributing, so it will become a new mess to sort out.

Maybe the real problem is that we have too many issues. I think the number of opened issues has been constantly growing for the past few years. Isn’t there anything we can do to make this number go down instead of up?

Note that I’m okay with adding new tags, I just wanna invite you to think twice.

**Comment by agrodet** [comment]
As a brief introduction, let me say that I don't ask tags absolutely, just a better way to classify issues. I hope discussing this issue does not become a waste of time so I'll develop my reasoning. 

Let me answer several of your questions quickly first.
I see your point. I understand the extra effort. I think it's worth it and I don't think that's an extra burden (more on that in the next paragraph). I don't think such tags are only useful to me since in my head they would be applied the same way they are now, like enhancement, unclear, etc., not by me or the author of the issue. Therefore, it won't become a mess. Of course, if there were 10 issues, it wouldn't be a problem but that's not the case. I thought about it more than twice ^^

Now, about your first paragraph. Let's do a mini UX test :P I want to help improving the tag functionality. My first reflex is therefore to search `is:issue is:open tag`. What are the results?
1. Improve issue browsing and categorization on GitHub
2. Make the different "info" md-icon more identifiable
3. Add a special tag to the sentences from the Tanaka Corpus
4. Add "Sort by" bottom 
5. Internal error when using advanced search with no words
It doesn't look so promising. I open 3. It's not really about the tag functionality but more about adding a specific tag. Not what I'm searching really. So from the top 5 results, no results I'm interesting in :'(

If I'm lucky, someone will tell me "No, but you didn't make a good search, look for `in:title tag`". Alright, now I understand I'm a newbie on GitHub. I've made progress in my life and that's a good thing. 

**Problem / Questions / Considerations (some of them being thought more thoroughly than others)**
1. Are we supposed to assume that everybody is GitHub fluent? (I was not until recently). 
2. Doing the research mentioned above may leave some results out. One could say that in that case, the issue title is not good enough (I'm not sure I agree with that). 
3. This search gives me a good set of results for tag, but less good for list, because list is a much more common word. We have "list of vocabulary", "audio list", etc. One could say that if the good results are included, I'm just being finicky (Not sure I agree with what either).
4. If I'm a new developer, I will have to go through all the issues to get an understanding of what each of them is about. Then I will have to make my own list of issues that I want or can tackle. I know we have a "good first issue" tag, but there are only a few, and maybe I want more. If the topic of the issue was tagged onto it, I could get a better or faster understanding of issues I want or should ignore. 
5. The "burden" of tagging will be only once. After that, it will be the usual routine. If it improves the global feeling of the developers group, will it not be worth it? I don't say it will improve, but I hope so. Since a lot was done recently, we haven't reached 300. The burden is a dozen of issues less a burden than it could have been! :D 
6. We have a "ui-strings" tag. 


>  Isn’t there anything we can do to make this number go down instead of up?

Develop an awesome bug-free website full of wonderful features so everybody is plainly satisfied and never needs to open an issue again, of course! :D

**Comment by trang** [comment]
> Lately I ended up taking notes on paper to browse a database...

I'd be interested to know what your notes look like, if that's not too personal.

You are the first developer who expressed the need to have a better way to browse issues by topic. From all the developers who contributed before, either they didn't have any difficulty finding issues in the topics they were interested in, or they were simply never interested in solving issues of a particular topic and were more interested in solving issues that were in the range of their skills while being as helpful as possible for the project.

So while I cannot say that adding additional labels for some topics will be useless but I also cannot say it will be useful. We don't really have that many contributors on the dev side to confirm this... I can only say we could try and I could technically give you "Triage" permission level to go ahead and add labels to our issues. But I'd like to suggest a more progressive approach.

- We can first start with a wiki page that lists topics and issues that would fit in each of these topics. As far as I know, you could create this wiki page yourself. We didn't restrict the write access to our GitHub wiki. 
- We can mention this wiki page in our guide for new developers and in the README of the repository even. 
- When we clearly see that people rely on this page to find issues to work on, we can integrate these topics as labels.

It's for sure more tedious to maintain such a page, but it would be less intrusive to have this intermediate step that basically serves as a proof of concept. Maybe we find out this page is enough and we don't need to create new labels. 

If you ask me, I prefer that we keep the amount of labels to the minimum necessary and in general you'll have an easier time convincing me to stop using labels than to create more labels. I think ~10 labels is a comfortable amount to work with. Up to ~20 labels is still okay but past that, I personally feel overwhelmed.

> If I'm a new developer, I will have to go through all the issues to get an understanding of what each of them is about.

If you felt obligated to go through all the issues as a new developer then maybe we need to rewrite a little bit our guide for contributing as a developer :) If a new developer is happy to actually read through all our issues, then that's fine. But otherwise, they can tell us what are their preferences in general and we can suggest issues based on what they prefer.

**Comment by agrodet** [comment]
The following is entirely personal, and actually I don't think that's a very usual way to do things, but anyway :P Also, I've always been admin / main developer of my GitHub projects so I always had a quasi-full understanding of what was going on, lacking, and expected. That may explain the "feeling" I expressed. If you have any advice on the personal level, I'm open. We never stop learning.

I felt obligated to go through all the issues because I wanted several things: contribute code in a very short time, have a global understanding of the general expectations (of issuers, not dev lead), and be the one to decide for myself.

There's nothing personal with my notes. They're very standard, I think. First I went through all the issues, as I mentioned, and when there was one I thought I wanted to or could tackle, I would put the issue number on my list. I soon realized that I couldn't remember all the details of each issue with only the number, so I quickly changed to "#Number - few keywords".  
I also took notes of issues where I should leave a comment, because I thought my opinion was worth giving (bad idea, design divergence, etc.) or go back later (more difficult to implement than I thought at first glance, etc.). 
Originally, I took notes on my phone, but then I realized that the list format was not adequate, because many issues were related to each other. I would have #n - Something about vocabulary and four lines below #m - Something else about vocabulary. So I thought about adopting paper so I could organize in clusters.  
Of course, I know that I will never touch most of the issues I noted. However, I crossed them out when I, or @AndiPersti or somebody else solved them, and that was a good feeling :) 

But that was not enough. Because I only listed issues to which I may eventually possibly bring a solution one day. But since I went through all the issues, I sometimes recall some past comments that are echoing a current discussion but if they're not in my notes, I sometimes take a lot of time to find them again. For example, lately I was trying to find where the "list icon and red icon overlap" thing was... Then I saw that @AndiPersti wrote a "ToDo" list of issues on his own repository and I thought I could do a huge clustering, once and for all. But before doing it myself for myself, I thought about asking here. And here we are.

**Comment by trang** [comment]
> I felt obligated to go through all the issues because I wanted several things: contribute code in a very short time, have a global understanding of the general expectations (of issuers, not dev lead), and be the one to decide for myself.

To contribute code in a short time seems contradictory with going through all the issues. If I wanted to contribute code in a short time, I'd just browse a bit randomly and pick the first issue that I find useful or interesting. Then I'd just ask for the information I need to come up with the best solution I can.

But to have a global understanding, as well as to be able to decide for yourself, that indeed requires to go through all the issues :)

> Then I saw that @AndiPersti wrote a "ToDo" list of issues on his own repository and I thought I could do a huge clustering, once and for all. But before doing it myself for myself, I thought about asking here. And here we are.

Did you plan to have a ticket for each topic, then reference the corresponding Tatoeba issues? It could be indeed a way to do it, instead of creating a wiki page... I'd say go ahead with that.

The thing is, this categorization might feel worth it for you, but it doesn't yet feel worth it for us, as project maintainers. If we can see that it actually helps many people besides you, then we will be convinced and we can integrate it into our routines of maintaining Tatoeba's issues in GitHub. Before that, I can tell you that in my case, if the label is not useful to me and there aren't enough people for whom it's actually useful, then laziness will prevail. Doesn't matter that it takes 5 seconds to add a label, laziness wins all the time.

**Comment by agrodet** [comment]
I'm okay if you want to close this.

**Comment by trang** [comment]
I will close it then. We can always bring back the topic during the weekly calls, whenever it becomes relevant.
