### ISSUE TITLE
Copy-paste and reviews may not be "experimental" anymore

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2130]
I open this issue to continue the discussion started on #2119, because I shouldn't pollute it anymore (my apologies). 

To summarize, the discussion is about the copy-paste function and the review function. I argue that they could by removed from the "Experimental options", and added to the "Main options".  
In my [comment](https://github.com/Tatoeba/tatoeba2/issues/2119#issuecomment-581327292) I suggested to remove them and make them full part of the site. I don't think that's a good idea. We should keep them as options, just as they are currently.  

@trang said 
> The copy-paste feature was classified as experimental because it was not guaranteed to work on enough browsers, if I remember properly.

I have tested it on last versions of: 
Microsoft 8.1: Firefox
Microsoft 10: Chrome, Internet Explorer, Edge
MacOS: Firefox, Opera, Safari
Android: Firefox
And if the access to the clipboard was allowed, obviously, all of them copied the sentence.

@trang said
> The reviews feature was classified as experimental because it was not mature enough. Some people were opposed to its release. Still, enough people considered it was useful even in this unfinished state, so it was released but as something experimental. This would allow to get some information on how this feature can be used in real life situations and not just in our minds, but the fact that it is experimental also meant that we could decide more easily to simply abandon it if it turns out to be a catastrophe for the project.

I clearly understand why some people would be against such a feature :D I'm not sure of what was "unmature" so I cannot really argue about that. However, I think that it is not a catastrophe for the project. I guess the difference of appreciation is maybe that you would like to get it as close as your ideal image before taking it out of the experimental section. I think it's okay for main options to evolve (or even temporarily disappear in extreme case of necessity). A similar question was asked by @alanfgh in #1591
> Isn't it true that any element of the interface could change or be removed in the future?

Also, I think that by moving the review function to the "Main options", people may be more curious of activating it than under a scary red warning :P If more people activate it, that could bring more feedback, maybe more catastrophe, hence some more insight into what ways of improvement we have. 

About the other two experimental functions, I do think that they are still experimental.

**Comment by trang** [comment]
This could be two separate issues :)

For copy-paste button: I'd suggest removing it from the experimental options (and putting it in the regular options) when it's implemented in the new sentence design.

For reviews: from what I remember there was still disagreement on what each of the options really mean. There was a concern that people will use it for such large range of situations that in the end, all those reviews end up as a meaningless data.

> If more people activate it, that could bring more feedback, maybe more catastrophe, hence some more insight into what ways of improvement we have.

Take into consideration that bringing more catastrophe that we cannot support isn't necessarily a good user experience. No one is happy complaining about things just to see that nothing will ever be done about it because we simply don't have the resources for it.

If you ask me personally, I am not ready to re-open this topic. Not at this time. I wouldn't be able to secure enough time and energy for this. Perhaps after the whole responsive UI migration is done.

**Comment by agrodet** [comment]
Thank you for clarifying the situation. Now it's really clear!
