### ISSUE TITLE
Sentences added with spaces at the start

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2131]
Cf. logs of the following sentences:
https://tatoeba.org/eng/sentences/show/8539416
https://tatoeba.org/eng/sentences/show/8539417
https://tatoeba.org/eng/sentences/show/8539418

Those spaces should be automatically removed before saving.

**Comment by AndiPersti** [comment]
The sentences are rather recent and not available in the weekly dump but I guess these all contain some sort of unicode white space characters. At least I can reproduce this on dev: https://dev.tatoeba.org/eng/sentences/show/7841128
The reason is that we use `trim()` for cleaning the sentence text, but this function just removes the code points 9, 10, 11, 13, 32 of all possible [Unicode whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character#Unicode).

I've looked at the current export and noticed that there are a few similar sentences included:

Space at the beginning:

    $ cut -f 1,3 sentences.csv | grep '  [[:space:]]'
    375562   قدمي ما زالت تؤلمني.
    375751   تتكلم ماريكو الإنجليزية جيداً.
    377093   كما يسبب استمرار هذا النزاع تكاليف باهظة ومصاعب سياسية جمة..
    2250282  لقد حصل على العلامة الكاملة.
    8185348  I'm so grateful to work here every day. It's so nice.
    8185349  I'm so grateful to work here every day.

With the 4 Arabic sentences, the punctuation looks strange, e.g. 377093:

    $ grep '     377093  ' contributions.csv
    saeb    2010-04-08 12:28:44     insert  sentence        377093  ara     \N      . كما يسبب استمرار هذا النزاع تكاليف باهظة ومصاعب سياسية جمة.
    saeb    2010-04-08 12:28:44     insert  link    377093  \N      377092
    saeb    2010-04-08 12:28:44     insert  link    377092  \N      377093
    $ grep '^377093      ' sentences.csv
    377093  ara      كما يسبب استمرار هذا النزاع تكاليف باهظة ومصاعب سياسية جمة..

The sentence was contributed with a period at the beginning and at the end, but is stored now with two periods at the end. Maybe related to #2075?

Both English sentences have a `LINE SEPARATOR` (U+2028 / e2 80 a8) at the beginning:

    $ grep '^8185348     ' sentences.csv | hexdump -C
    00000000  38 31 38 35 33 34 38 09  65 6e 67 09 e2 80 a8 49  |8185348.eng....I|
    00000010  27 6d 20 73 6f 20 67 72  61 74 65 66 75 6c 20 74  |'m so grateful t|
    00000020  6f 20 77 6f 72 6b 20 68  65 72 65 20 65 76 65 72  |o work here ever|
    00000030  79 20 64 61 79 2e 20 49  74 27 73 20 73 6f 20 6e  |y day. It's so n|
    00000040  69 63 65 2e 0a                                    |ice..|
    00000045
    $ grep '^8185349     ' sentences.csv | hexdump -C
    00000000  38 31 38 35 33 34 39 09  65 6e 67 09 e2 80 a8 49  |8185349.eng....I|
    00000010  27 6d 20 73 6f 20 67 72  61 74 65 66 75 6c 20 74  |'m so grateful t|
    00000020  6f 20 77 6f 72 6b 20 68  65 72 65 20 65 76 65 72  |o work here ever|
    00000030  79 20 64 61 79 2e 0a                              |y day..|
    00000037

Space at the end:

    $ cut -f 1,3 sentences.csv | grep '[[:space:]]$'
    774314  その俳優は、メディアが予想する平和賞の有力候補リストに入っていなかった。　
    776039  経営者は会社の代理として一週間に一回海外へ出張することになりました。　
    776041  我々の雄大な計画通りに、従業者を訓練されて、その効果を認められなかったんです。　
    941426  承知致しました。有難う御座います。　
    1859700 Die Zahl der Teilnehmer hat sich fast verdoppelt.  
    2573165 どれくらいの間離れていたんです？　
    2584973 普段は特に可もなく不可もなく、上司から言われたことだけをある程度こなしているような従業員も、アメとムチを使い分けてうまくモチベートすることで見違えるほ どの成果を出すこともあれば、逆に従業員の面子を潰すようなことをして、会社に敵対する行動を取り始めることもあるのです。 
    7864853 We allowed them no respite. 
    7864858 Мы им не давали передышки. 
    7864859 There was no respite from the cold. 
    7864862 Нельзя было никуда деться от холода. 
    7867936 A small boy stood champing gum. 
    7867937 Маленький мальчик стоял, жуя резинку. 
    8185351 It's really great to work here. 
    8185365 I wanted to not only give him what I owed him, but I wanted to give more because I thought: Wow, what kind of person is being so trustful. 
    8185371 In the name of Jesus Christ, Amen. 


`IDEOGRAPHIC SPACE` (U+3000 / e3 80 80), e.g. 776041:

    $ grep '^941426      ' sentences.csv | hexdump -C
    00000000  39 34 31 34 32 36 09 6a  70 6e 09 e6 89 bf e7 9f  |941426.jpn......|
    00000010  a5 e8 87 b4 e3 81 97 e3  81 be e3 81 97 e3 81 9f  |................|
    00000020  e3 80 82 e6 9c 89 e9 9b  a3 e3 81 86 e5 be a1 e5  |................|
    00000030  ba a7 e3 81 84 e3 81 be  e3 81 99 e3 80 82 e3 80  |................|
    00000040  80 0a                                             |..|
    00000042

And again `LINE SEPARATOR`:

    $ grep '^7864858     ' sentences.csv | hexdump -C
    00000000  37 38 36 34 38 35 38 09  72 75 73 09 d0 9c d1 8b  |7864858.rus.....|
    00000010  20 d0 b8 d0 bc 20 d0 bd  d0 b5 20 d0 b4 d0 b0 d0  | .... .... .....|
    00000020  b2 d0 b0 d0 bb d0 b8 20  d0 bf d0 b5 d1 80 d0 b5  |....... ........|
    00000030  d0 b4 d1 8b d1 88 d0 ba  d0 b8 2e e2 80 82 0a     |...............|

So we need a Unicode aware `trim()`.

**Comment by AndiPersti** [comment]
I took a closer look and with the following Python script I've found [198 problematic sentences](https://gist.github.com/AndiPersti/14d9a27680eed0b2b6ed13ce8ab2c8fb):

    import unicodedata
    
    with open('sentences.csv', 'r') as f:
        for line in f:
            id, lang, text = line[:-1].split('\t')
            first = unicodedata.category(text[0])
            if first.startswith(('Z', 'Cc')):
                print(id, text, unicodedata.name(text[0], 'NONE'), unicodedata.category(text[0]), ord(text[0]), 'first', sep='\t')
            last = unicodedata.category(text[-1])
            if last.startswith(('Z', 'Cc')):
                print(id, text, unicodedata.name(text[-1], 'NONE'), unicodedata.category(text[-1]), ord(text[-1]), 'last', sep='\t')

**Comment by AndiPersti** [comment]
I've just looked into the current `contributions.csv` and can confirm that all three sentences were originally added with spaces at the beginning (`c2 a0 20`):

    $ grep '^JGEN' contributions.csv | grep 'insert.*sentence.*8539416' | cut -b 55-65 | hexdump -C
    00000000  4e 09 c2 a0 20 46 69 63  6f 20 66 0a              |N... Fico f.|
    0000000c
    $ grep '^JGEN' contributions.csv | grep 'insert.*sentence.*8539417' | cut -b 55-65 | hexdump -C
    00000000  4e 09 c2 a0 20 46 69 63  6f 20 66 0a              |N... Fico f.|
    0000000c
    $ grep '^JGEN' contributions.csv | grep 'insert.*sentence.*8539418' | cut -b 55-65 | hexdump -C
    00000000  4e 09 c2 a0 20 49 73 73  6f 20 c3 0a              |N... Isso ..|
    0000000c

So this should be fixed with #2141 for future contributions.

@Trang For fixing the sentences which are already stored you would need to run my new version of the `fix_hashes` command and feed it the list of ids like `[sudo] cut -f 1 sentences_ws.tsv | bin/cake fix_hashes -i Sentences` (I'm not sure if the `sudo` is necessary). I have updated the list on my gist.

**Comment by trang** [comment]
I ran the command on prod.

Logs here: https://gist.github.com/trang/36fd50fc3c7b0df748a67a09e8146b2d

As always, thanks for this @AndiPersti :)
