### ISSUE TITLE
Rework the Stats block

### ISSUE THREAD

**Issue by agrodet** [Tatoeba/tatoeba2#2156]
See the discussion started on #2144. Extracting some information

One idea: 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/42261966/74811041-feb60280-5333-11ea-85e2-a45f27a36982.png">

trang said

> My only issue is that it feels a bit strange to have two stats (number of sentences + number of languages) associated to one page. It would feel less broken to have each stat followed by a link to some related page.
> 
> For the {x} sentences, I have two ideas of related page:
> 
>  the random sentence
>  or the advanced search

CK said
> Perhaps the following might be better.
> 468 sentences since 0:00 UTC
> 
> I still think it would be a good idea to add a "yesterday's" number on the main page, too. This gives both regular contributors and new contributors better idea of what's going on without needing to click to the timeline every day.
> 
> 468 sentences since 0:00 UTC
> 3,141 sentences yesterday.

@trang I don't think the random sentence would bring any benefit. The chance to find a useful sentence to you is unlikely. A search might be better, I'm not very sure... I like the idea that this block is entirely dedicated to stats. 

@CK I think "since 0:00 UTC" is kind of noisy. Most of people don't naturally refer to "0:00 UTC", some don't even know what it is, so it would make more sense from the human point of view to use "today". However, "today" can be adapted to the user, like it was suggested elsewhere.

**Comment by ckjpn** [comment]
[Additional Idea]

Instead of since 0:00 UTC, perhaps you could use the same relative time code you use on this page https://tatoeba.org/eng/contributions/latest so you would get "8 minutes ago, "an hour ago", etc.

**Comment by ckjpn** [comment]
I've mentioned this elsewhere, but I really wonder if the supported languages line is really necessary for this block.  It's not something that changes all that often, and members can easily find this information by clicking the "stats per language" page.

Eliminating that from the block might help minimize the text on the page and also solve what TRANG mentioned,  "My only issue is that it feels a bit strange to have two stats ...." 

However, this one line doesn't really clutter up the page, unless including it also means more text has to be added to accommodate it.

I do think, however, that this is a good stat to have on the non-logged in home page that new visitors to the website see, since it gives them an idea of the scope of the project.

**Comment by jiru** [comment]
Thank you agrodet for starting a new topic.

@trang I second CK that the first link allows to see the number of sentences for each language, so it's related to both "n sentences" and "n supported languages". If you really want to add a new link, you could use "Languages of members" (named e.g. "stats per level") for "n languages", and the current "stats per language" link for "n sentences".

**Comment by agrodet** [comment]
> I've mentioned this elsewhere, but I really wonder if the supported languages line is really necessary for this block. It's not something that changes all that often, and members can easily find this information by clicking the "stats per language" page.

I don't think it's easy to find this information on the "stats per language". Don't we have to scroll until the bottom line? 

Also, I think that because it doesn't change often, it's useful where it is. For example, when 350 will become 351, one can know that a new language was added, which is quite something, with so many languages already. One can then check or not check what that language was, either on the Stats page, or checking on the Wall. My point is simply that although the information is useless to most individuals, it is useful to the community, in my opinion.

**Comment by trang** [comment]
If we reworded the two stats into one line (like `{x} languages spread over {y} languages`), or if we would design the stats in way that more clearly encapsulates the two first stats together, it would feel better to me. Otherwise I get the feeling that there's a missing link. But that's maybe just me.

I created a ticket about the "Stats per language" page (#2157). I personally see this page as something that is more about languages than about sentences. That's also why I would be more inclined to link it only to "{n} supported languages" and not as much to "{n} sentences".

One more thing about reworking the stats block: we have to make sure it displays nicely on the homepage for non-authenticated users.

**Comment by jiru** [comment]
@trang To the contrary, I think that merging the first two lines makes it less easy to read because it breaks the `<number> <thing>` pattern that repeats three times.

**Comment by agrodet** [comment]
The fact that the link is named "Stats per language" implies that the page is about languages. 

In a [comment on #2157](https://github.com/Tatoeba/tatoeba2/issues/2157#issuecomment-602361609), I suggest to modify the title of the page to "{n} sentences in {m} languages". That way, it would perfectly echo what would be displayed in the stats block. 

On a personal level, the 2 lines - one link ; one line - link structure doesn't bother me because "stats **per** languages" implies a two-dimensional array, so, displayed as above, it's obvious that `i` would be sentences and that `j` would be languages. But I agree, that my math-wired brain is clearly biased.  
However, with a perfect one line - one link structure, what I would expect from the links would be totally different. 

- n sentences → see them all (or an excerpt)
- m languages → see information about them (not stats)
- k contributions → see information about them (the future activity timeline page).  

Since we're talking about a stats block and not a general information block, I think the structure displayed in the original post is better.
