### ISSUE TITLE
UI translations are not really updated on dev website

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2158]
The PO files are being properly fetched from Transifex, but the translations are cached (I think in the `/tmp/cache/persistent` folder), so for the translators, it's like they are not being updated.

We would need to either disable caching (which I'm not entirely sure how to), or clear the cache whenever the translations are fetched.

**Comment by AndiPersti** [comment]
Since the translations are cached in the `_cake_core_` cache which is used by CakePHP internally, I don't think disabling caching is a good idea.

For changing the cache duration time for `_cake_core_` which is currently [set to 1 year](https://github.com/Tatoeba/tatoeba2/blob/503acacdd7b0df4020e91580c3b29b6aff50dc54/config/app.php#L108) you could overwrite that time in `app_local.php` for dev.

Do you use `update-translations.py` for updating the translations? We could clear the cache at the end of the script.

**Comment by jiru** [comment]
I figured out it’s better to clear the cache manually (rather than changing the cache config in app_local.php) because we want dev.tatoeba.org to be as close as possible to tatoeba.org, so that it’s easy to reproduce bugs or compare things. Especially, the cache config _cake_core_ is used for other things like models etc.

**Comment by jiru** [comment]
Note that dev.tatoeba.org is still not being updated yet because Trang set it to use her branch instead of dev.
