### ISSUE TITLE
Search with "Owned by a self-identified native speaker" includes non-native speakers

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2178]
I was searching for [sentences in Japanese owned by a self-identified native speaker](https://tatoeba.org/eng/sentences/search?query=&from=jpn&to=none&user=&orphans=no&unapproved=no&has_audio=&tags=&list=&native=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance&sort_reverse=). I noticed that it gave the same result as just searching [sentences in Japanese](https://tatoeba.org/eng/sentences/search?query=&from=jpn&to=none&user=&orphans=no&unapproved=no&has_audio=&tags=&list=&native=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance&sort_reverse=).

**Comment by AndiPersti** [comment]
This bug is a little bit tricky. :-)

https://github.com/Tatoeba/tatoeba2/blob/c26b5dbbd9ca37128c769f222db48038fe92c754/src/Controller/SentencesController.php#L714-L716
Here we get the result as an array of `UsersLanguage` entities. `Hash::extract` then converts each of the array items internally using the `toArray()` method. But d0fac47f2b43407b513629d9013fc23ece24bdf0 adds `of_user_id` to the hidden fields which won't get included in the array and thus this field isn't visible for `extract`.
