### ISSUE TITLE
Tag Sorting Has the Wrong Default Sort, I think.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2186]
https://tatoeba.org/eng/tags/view_all

Instead of the tag with 0 sentences, shouldn't it, by default, be the tag with the most sentences, like it used to be?

I tried it with several browsers, so I don't think it's a cached preference on my computer.

Also, I wonder why "one" is a word, but the other numbers are digits (Arabic numbers).

**Comment by jiru** [comment]
Thank you for reporting the problem, CK. :+1:
It should be fixed on dev.tatoeba.org now.
About "one" as a word, it’s like this because the singular form has a dedicated translatable string while all plurals and zero share another string. I suppose it’s better to display "1 sentence" instead in the context of that page?
