### ISSUE TITLE
Expand/collapse translations not working correctly on the new design

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2194]
I compiled a list of related bugs:

A. Steps to reproduce:
1. Find a sentence with a total of exactly 6 translations (direct + indirect)
2. Problem: only 5 translations are displayed without expand/collapse button.

B. Steps to reproduce:
1. Find a sentence without an expand/collapse menu (5 translations or less).
2. Add several translations.
3. Problem: the new translations appear on top of the translation list while the lower translations disappear.

C. Steps to reproduce:
1. Find a sentence with an expand/collapse menu (6/7 translations or more).
2. Add one translation.
3. The expand/collapse menu says "show n more translations", but n is incorrect, it should be n+1 instead.

**Comment by trang** [comment]
I fixed (A) as well as another issue I found along the way.

(B) and (C) are a bit trickier because the label has to be updated properly. The string can be singular or plural, and plural can have complicated rules in some languages.

I'm thinking of adding a parameter `currentNumberOfTranslations` when calling `/sentences/save_translation/`. This number would be incremented if the translation is saved properly and in the response we can return the new label along with the saved translation.

Not sure if someone has a better idea.
