### ISSUE TITLE
"filter by language" often fails to work correctly for sentences with a given tag

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2205]
When displaying all the sentences with a given tag, "Filter by language" often fails to work correctly. Here's an instance where a Spanish sentence was displayed along with English ones:

![filter_by_lang](https://user-images.githubusercontent.com/1213027/76686964-1c564f00-65f6-11ea-9699-c3aa04b155d6.png)

When I chose a different language, then English again, I saw only English sentences.

This differs from #1764 in that the tag I was looking at ("@change") was not a new one.

**Comment by trang** [comment]
Just to clarify, it's not a problem with the filter returning wrong results, but with the filter not being triggered at all, right?

I suppose that when you select "English" in the language dropdown, sometimes, nothing happens?

But the expected behavior is that after selecting "English", you should be redirected to the URL https://tatoeba.org/eng/tags/show_sentences_with_tag/561/eng.

**Comment by alanfgh** [comment]
> Just to clarify, it's not a problem with the filter returning wrong results, but with the filter not being triggered at all, right?

I think so.

> I suppose that when you select "English" in the language dropdown, sometimes, nothing happens?

Again, I think so.

> But the expected behavior is that after selecting "English", you should be redirected to the URL...

I'll keep an eye on the URL to see whether or not it changes.

**Comment by AndiPersti** [comment]
@alanfgh Is this still a problem? I cannot reproduce it on my side. Since you have opened the issue, the [implementation of the language filter](https://github.com/Tatoeba/tatoeba2/pull/2532/commits/183b5be136d4897f5d3d7d5705230602dab47031) changed so maybe this was only a problem with the old version.

**Comment by alanfgh** [comment]
@AndiPersti  Indeed, I have not seen this problem in quite a while. I think we can consider it resolved.
