### ISSUE TITLE
Add "Send message" button on users' profiles

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2222]
Sometimes I want to contact so many users either to ask something about the same or different topics. For now, to do so, I have to

1. Go to the user's profile
2. Click on the box on the right and choose "Contact {user}"

It doesn't take too much if you have to send a message to one, two users, but might take so much time if you need to send messages to many users. Besides, for newcomers, it may be not intuitive, I guess.

I think we could add the button "Send message" on each user's profile. Maybe something like this:

![image](https://user-images.githubusercontent.com/7658430/77066260-96555200-69c1-11ea-9172-6776f50a5f17.png)

**Comment by jiru** [comment]
We could take the existing "Contact {user}" button out of the menu that is collapsed by default. In other words, keeping it at the same place but make it always visible.

**Comment by agrodet** [comment]
Maybe we could simply make sure that #2074 addresses this.

**Comment by RyckRichards** [comment]
Actually, I suggested like that just to follow the, let`s say, template we`re using on comments and Wall

**Comment by RyckRichards** [comment]
Actually, I sugessted like that since it ~follows the template~ we`re currently using on Tatoeba (Wall and comments have the same button in the same style)

**Comment by trang** [comment]
The pattern used on the comments and Wall posts is due to the limitation of space. We cannot display buttons with labels for each of the actions, it would make the UI too crowded. In the case of the profile, we have enough space so there's no real need to use an icon button with no label. I would recommend to keep the button "Contact {user}" with the label.

I'll definitely take care of this when I get to work on #2074, but in the meantime anyone could solve this issue already. The button can be placed pretty much anywhere as long as it's towards the top of the page, so that it's visible without having to scroll. Whether we place it in the sidebar or whether we place it in the top-right corner of the profile, it doesn't matter too much in my opinion. In both case it will be an improvement.
