### ISSUE TITLE
Create an easier way to users find what they're looking for

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2225]
Many users have reported that it's confusing to them how to translate sentences, for example, or create a list, post on the Wall.

I don't know if it's the best approach, but I think we could create a kind of "Google customized search" until they get familiar with Tatoeba.

**Comment by trang** [comment]
This issue is too broad and not very clear.

You have mentioned 3 different problems and they won't really be solved by creating a content search. From my understanding, you are simply saying that the UI is not friendly enough for many users. That's basically every software's problem and it's a never ending problem :)

To improve this, we have to understand each use case in more details: 
- What is the user trying to do? 
- Why are they trying to do it?
- What blocks them at figuring out how to do what they want to do?

I suggest to create a separate issue for each use case, or simply send me by email the things that users have reported to you and I will create the relevant issues in GitHub.

**Comment by trang** [comment]
By the way, have these users read the [Quick Start](https://en.wiki.tatoeba.org/articles/show/quick-start) guide? Or have they looked at the wiki in general?

In the wiki there is actually a small search box to find specific articles. Although the search results are not really optimal.

**Comment by RyckRichards** [comment]
Agreed. Thank you!

>

**Comment by RyckRichards** [comment]
@trang Well, some of them found very hard to find them. I have to point it to them like "Look at the bottom of the page. You may get all the info you need."

**Comment by trang** [comment]
For that we have #2112 where we can raise awareness about the wiki documentation.
