### ISSUE TITLE
one of my lists is not presented as an option in the drop-down

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2244]
I have a list "Sentences with errors marked as OK". It shows up on "My lists":

![my_lists](https://user-images.githubusercontent.com/1213027/78318135-07ecde80-7532-11ea-8f1d-2760ca037842.png)

and here are the details:

![list_details](https://user-images.githubusercontent.com/1213027/78318216-39fe4080-7532-11ea-9f37-2db6c81aa322.png)

But it doesn't show up as an option in the drop-down list:

![list_drop_down](https://user-images.githubusercontent.com/1213027/78318240-46829900-7532-11ea-8b29-17ed09ed0d8f.png)

**Comment by alanfgh** [comment]
I just figured out that the sentence already has been assigned to the list, so that must be why the list name doesn't appear in the drop-down list. Maybe it would be more clear if the list name appeared in the drop-down list, but was grayed out?

**Comment by trang** [comment]
This should no longer be an issue with the new sentence design. If a sentence has already been added to a list, the checkbox next to the list name will be checked (implemented in https://github.com/Tatoeba/tatoeba2/pull/2154/commits/b6ebbd94994f0a924c3d7ee519db5bb59a537447).

For instance, below is a sentence which already belongs to my list "Test". When I search for the list, I see that the checkbox is checked.

![Screenshot_2020-04-03 Na matou talanoa ai - Samoan example sentence - Tatoeba](https://user-images.githubusercontent.com/221850/78377404-d88caf00-75cf-11ea-9c3d-74473061fbb8.png)

@alanfgh If you confirm the behavior in the new design solves your issue, then I would suggest to close it. Otherwise, if there is still something to improve, then we should improve it directly in the new design and not fix it in the old design. At this stage it only makes sense to fix/improve the old design for very critical issues.

**Comment by alanfgh** [comment]
Yes, the behavior in the new design solves my issue. Thanks.
