### ISSUE TITLE
Possibility to have the audio contribution date below its author's name

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2275]
As suggested by mramosch on the wall:

> I would really like to see an additional field for creation/contribution/submission date of the Audio recording underneath the recording artist in the sentence pages. And in any other place where Audio is mentioned for that matter. Like with their prominent written counterparts ;-) 

https://tatoeba.org/ita/wall/show_message/34842#!#message_34842

**Comment by cblanken** [comment]
I'd like to take on this issue, but if someone could point me to documentation showing how to upload audio clips to the application when running locally in the TatoVM, it would be much appreciated :)

**Comment by jiru** [comment]
@cblanken https://github.com/Tatoeba/tatoeba2/tree/dev/webroot/files/audio_import

**Comment by jiru** [comment]
Welcome here, and you are welcome to take on this issue. 🙂

If I remember correctly the date field of audio database records is not always correct. We'd have to do some database cleanup/recovery to get the audio dates right.

In the past, we simply did not keep track of audio metadata (we only had a sentences.has_audio boolean field). So old audios likely all have the same date.

Additionally, at some point the functionality of "disabling an audio" was implemented in a way that removed the record from the audios table. So any audio that have been disabled during that time do not have a correct date.

I believe the last modification date of the audio file is probably more trustworthy, although it cannot be trusted 100% as CK sometimes reuploads some audio files.

Another useful source of information is the audio lists CK is maintaining. Since sentences in lists also have a "date of addition to the list", this should tell more or less when the audio was uploaded.

**Comment by cblanken** [comment]
@jiru 
> In the past, we simply did not keep track of audio metadata (we only had a sentences.has_audio boolean field). So old audios likely all have the same date.
Is there anyone with access to the database that could get me that date? I think a reasonable solution would be to just display `Unknown` for any audio recording with a `created` date prior to that point.

> I believe the last modification date of the audio file is probably more trustworthy, although it cannot be trusted 100% as CK sometimes reuploads some audio files.
I'm not sure I understand what you mean here. If the audio was re-uploaded won't the `modified` field also update when the old recording is replaced?

**Comment by jiru** [comment]
> Is there anyone with access to the database that could get me that date?

2017-02-13 (that is, Feb 13th) is the oldest value we have for the field `audios.created`.

> I'm not sure I understand what you mean here. If the audio was re-uploaded won't the modified field also update when the old recording is replaced?

No. With the old implementation, a reupload would reset both `created` and `modified` fields in the database. That’s why the last modification date of the audio file itself may be more accurate.

Anyway, I have deployed your pull request so the date now displayed, so I am closing this issue. As for the issue of recovering missing or inaccurate dates, I’ll open a new ticket.
