### ISSUE TITLE
Tonga (Zambezi) (toi)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2282]
* Language name: Tonga
* Language info: https://en.wikipedia.org/wiki/Tonga_language_(Zambia_and_Zimbabwe)
* ISO 639-3 code: TOI
* Public List: https://tatoeba.org/eng/sentences_lists/show/9953
* Icon: https://i.imgur.com/3zwrGaM.png
* Requested by: https://tatoeba.org/eng/user/profile/fj_nambala

**Comment by jiru** [comment]
Cool! Note that the sentences on list 9953 need to be fixed because they include both English and Tonga. The flags looks very... creative :smile:

The Wikipedia article says that TOI (Tonga) is an inclusive code that includes DOV (Dombe) as a dialect of TOI. However each [SIL](https://iso639-3.sil.org/code/toi) [page](https://iso639-3.sil.org/code/dov) list these languages scope as "individual". Compare with, for example, [Estonian](https://iso639-3.sil.org/code/est).

@RyckRichards Could you try clarifying the situation about Dombe and Tonga with fj_nambala?

**Comment by RyckRichards** [comment]
Sure

**Comment by soliloquist-tatoeba** [comment]
@RyckRichards
I had informed fj_nambala about the audio feature, and he became interested. Perhaps you could try to guide him on this matter.

He also told me about some sentence corpus he previously worked on. I don't know how its format and quality are, but he might send it to the admins and ask it to be imported to Tatoeba in the future.

**Comment by RyckRichards** [comment]
@soliloquist-tatoeba could you please ask him to contact me on ricardo14@tatoeba.org ? I'd be more than help to assist him but there are too much information which I might not be able to send on a Private Message

Thanks!

**Comment by soliloquist-tatoeba** [comment]
I did. Thanks.

**Comment by sabretou** [comment]
It should be noted that there are several languages named Tonga, and we should probably add a qualifier in parenthesis for clarification.

For (toi) we can probably use the following options:

- Tonga (Zambia)
- Tonga (Zambezi)
- Tonga (toi)

We should perhaps ask fj_nambala about which would be most identifiable to native speakers.

**Comment by RyckRichards** [comment]
I left him a message 3 days ago about the situation about Dombe and Tonga and now which qualifier would be the most identifiable to native speakers. Waiting for his reply.

**Comment by RyckRichards** [comment]
This is the message I got from him:

> Abou the toi or TOI code, I followed the instructions on Tatoeba to get to the ISO codes where it was clear that toi code is for the Tonga langauge of both Zambia and Zimbabwe (see https://en.wikipedia.org/wiki/Tonga_language and 
https://joshuaproject.net/people_groups/16082/ZI). I am Zambian Citizen and Tonga by tribe, as well as Tonga by speech, of Zambia (and basically Tonga by speech of Zimbabwe as I am not a Zimbabwean national). Zambia and Zimbabwe are neighbouring countries and the Tonga people in Zambia and Zimbabwe are divided in location by the Zambezi river position which is now expanded into a man-made Kariba Dam. See https://joshuaproject.net/countries/ZA, https://joshuaproject.net/people_groups/16082/ZA, https://joshuaproject.net/people_groups/15533/ZA (Toka being part of Tonga Language people in classification into a bigger group) and https://joshuaproject.net/people_groups/13048/ZA (Leya being part of Tonga Language people in classification into a bigger group).

> I have taken note of Dombe but be sure that it is not a quite well-known part of the bigger Tonga Language group of Zambia or Zimbabwe (see https://glottolog.org/resource/...id/id/domb1246 and https://glottolog.org/resource/.../id/domb1247). Dombe appears to be a small group of people's language spoken near Kazungula, Kalomo and/or Livingstone towns of Zambia where Tokas and Leyas are found under a classification called Toka-Leya people. Interesting enough, the Joshua Project (data) indicates that the Dombe are located in the northern parts of Zimbabwe near the Kariba Dam according to https://joshuaproject.net/people_groups/18979/ZI.
------

2nd email


> I hope my just earlier email to you has clarified on the Tonga Language concenrs that you have raised on this mail. Thing is we have a big river called Zambezi River where Zambia draws its name as a country. History indicates that Zambia was almost called Zambezi-land when we obtained independence from Britain in 1963/4 time. Hence we get Tonga (Zambezi) to mean the Tonga People/Language who live around the Zambezi River, now Kariba Dam area.

> Therefore, Tonga (Zambia) or rightly Tonga (Zambia [2 million people] and/or Zimbabwe [500,000 people]) coded as toi/TOI by the ISO... is same as Tonga (Zambezi). Zambia on its South(-East) and Zimbabwe on its North(-West) are countries separated by the Zambezi River at mainly a now man-made lake called Kariba Dam. The following two links should be able to aid: https://joshuaproject.net/people_groups/16082/ZA, https://joshuaproject.net/countries/ZI and https://en.wikipedia.org/wiki/Tonga_language.

> I now know that Toka (https://joshuaproject.net/people_groups/15533/ZA0 and Leya (https://joshuaproject.net/people_groups/13048/ZA) people are included in Tonga Language of Zambia while Dombe (https://joshuaproject.net/people_groups/18979/ZI) people are included into Tonga Language of Zimbabwe.

**Comment by soliloquist-tatoeba** [comment]
Dombe and Tonga (Zambezi) are listed separately as the languages of Zimbabwe on these pages.

http://www.muturzikin.com/cartesafrique/4.htm
https://www.ethnologue.com/country/ZW/languages

I guess we could use 'Zambezi' as the qualifier. It would be more inclusive than 'Zambia' and more descriptive than 'toi'. Besides, we won't have to edit the name or icon of the language even if Dombe is requested as an individual language on Tatoeba later.

**Comment by sabretou** [comment]
I agree, Tonga (Zambezi) seems best.

**Comment by RyckRichards** [comment]
Agreed. Going to change it.

**Comment by RyckRichards** [comment]
I've pushed a new commit - https://github.com/Tatoeba/tatoeba2/pull/2283/commits/1012778ad20014af8f86903a7a2793cf19ea3159

That changes the name of the language from Tonga to Tonga (Zambezi)

**Comment by fj-nambala** [comment]
Hi All, thanks for this work and discussion on Tonga (toi) language of Zambia, and of Zimbabwe. 
I have taken note of all your messages above. I have since responded to the emails by Ricardo14 and soliloquist on Tatoeba. However, for the sake of others who may not be privy my understanding after going through the Joshua Project website as well as looking at what Wikipedia has is that Dombe is a Zimbabwean dialect of Tonga (Zambia/Zimbabwe/Zambezi) (toi). See https://joshuaproject.net/people_groups/18979/ZI  and https://joshuaproject.net/languages/dov where Dombe is given a dov ISO... code. See also https://joshuaproject.net/languages/toi (Tonga (Zambia and/or Zimbabwe of the Zambezi (River) area of both countries), https://joshuaproject.net/people_groups/16082/ZA (Tonga (Zambia)) and https://joshuaproject.net/people_groups/16082/ZI (Tonga (Zimbabwe)).  
I hope these help even as you consider https://en.wikipedia.org/wiki/Tonga_language and https://en.wikipedia.org/wiki/Tonga_language_(Zambia_and_Zimbabwe).

**Comment by fj-nambala** [comment]
I agree with all of you (soliloquist-tatoeba, sabretou and RyckRichards) that Tonga (Zambezi) (toi) is best for the Tonga Language of both Zimbabwe and Zimbabwe. It seems that the same or a similar Tonga (Zambia/Zimbabwe/Zambezi) is also spoken somewhere in Mozambique obviously near the Zambezi River as the river goes all the way to the Indian Ocean. So, Tonga (Zambezi) might be more inclusive. 

This is fj_nambala on Tatoeba, here on Github (thread) as fj-nambala.
