### ISSUE TITLE
Show sentences as tooltips when the mouse is positioned on sentence numbers in the Logs block

### ISSUE THREAD

**Issue by soliloquist-tatoeba** [Tatoeba/tatoeba2#2293]
I mean this block.

![Logs_2](https://user-images.githubusercontent.com/47579687/79962765-2723bf80-8491-11ea-85ca-6da3f229b2f6.png)

This feature is already present on the Wall, in comments and private messages. If the Logs block had it too, it would be easier to see who linked/unlinked what, without leaving the page.

**Comment by jiru** [comment]
Did you know that you can click on the log entry to highlight the corresponding sentence?

**Comment by soliloquist-tatoeba** [comment]
Yes, it's very useful, but it naturally doesn't include unlinkings.

**Comment by agrodet** [comment]
I have wrote the requested improvement, extending it to users last contributions. I have tested several combinations. At first I only added the tooltip to "link" logs, since the sentence logs only display those. Besides, I argued with myself that "Since the sentence is displayed, there is no need for the tooltip."  
However, in the user contributions, it felt strange to have some "#nnn" with a tooltip and others without. Eventually, even if `sentence` type (`add` and `delete` action) logs display the text of the sentence, I think displaying the redundant tooltip is better than not at all. 

I mean that it becomes like this. 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/42261966/80505451-4ea5eb00-89af-11ea-8a26-aa946cd5b918.png">

That's a very small point. If it's okay with everybody, I'll open a PR.

**Comment by trang** [comment]
Having the tooltip would definitely be an improvement to the current situation but I don't think it will be the long term solution.

For the long term solution, we should explore the idea of showing the sentence's text when it's a log of type `link` (that's why I assigned this issue to myself).

I've been thinking for a while now on how to redesign the sentence's page to be responsive, which led me to think about how to redesign the logs. One of my ideas is to have several [tabs](https://material.angularjs.org/latest/demo/tabs) on the sentence's page and one of these tabs would be for the logs. This idea led me to ask myself what was need for highlighting a translation when clicking on a log entry because if the logs are displayed in a separate tab, then highlighting translations doesn't make sense anymore.

If the translation highlight mechanism was just for users to know what is the text corresponding to the ID in the logs, then why not just display that text right away? If we would just display the text, then there would be no need of having a tooltip. It would remove the need of solving #2252.

Anyway, feel free to open a pull request if you already have the code ready for the solution with the tooltip. I don't think it hurts to have a tooltip as an intermediate step :)

**Comment by agrodet** [comment]
There is quite a lot of information in what you wrote. Probably we can discuss all that another time, but I'd like to highlight that tabs can be, in my opinion, a huge obstacle to usability. For the simple reason that nobody wants to click a tab. It hides content and says "this functionality is not important or secondary". Taking only the example of the logs, it is useful to have it on the sentence page because we can see immediately what happens with a sentence. Probably only corpus maintainers and a few advanced contributors use the logs that way, but I think it's a very useful tool in some situations. However, if we had one additional click for the logs, I think the frequency of use would be close to zero.

Maybe we can discuss that again later ^^ I agree we should consider the case of displaying the text fully in the logs corner. However, I'm afraid that it will considerably clutter many (most of) sentences for a very small profit. So what if we consider the opposite reasoning? What if we have a consistent "#nnn" shows tooltip all over the website? On the wall, comment, logs, latest contributions, everywhere. If a user can imply that whenever he sees "#nnn" the text is in the tooltip, then they could infer that when the text is not displayed, it is in the tooltip. 

I admit that tooltip are not the best design in the world, especially if you need to move your mouse to see it. But I think that a) in this very specific case, that's a very practical choice, and b) the discovery of this behavior could be included in a future "beginner tutorial" #2112.

**Comment by AndiPersti** [comment]
> Taking only the example of the logs, it is useful to have it on the sentence page because we can see immediately what happens with a sentence. Probably only corpus maintainers and a few advanced contributors use the logs that way, but I think it's a very useful tool in some situations. However, if we had one additional click for the logs, I think the frequency of use would be close to zero.

But on the other hand, for big logs you need to scroll down a lot. Is there so much difference between one click and scrolling?
In addition, there would be more screen area available if the logs were on different tab and it would even be possible and easier to design some filtering/sorting options.

> I admit that tooltip are not the best design in the world, especially if you need to move your mouse to see it.

Tooltips are also rather unfit for touch screens, especially when the item is also clickable.

**Comment by agrodet** [comment]
Just to make it clear, of course I think that having the content of all sentences involved in the logs displayed directly is better than having only the #number. Now to answer Andi's questions, 

> Is there so much difference between one click and scrolling?

I think it depends what you click and what you scroll. If it's scrolling your page versus clicking a tab, scrolling might win. I think that tab is not a computer-oriented design. If someone shows me some websites making good use of tabs for **related content**, I'm open to change my mind, however. Note that **related content** is important here. A "Your progression" "Your general stats" "Leaderboards" structure is irrelevant because they are three different entities, whereas "Sentence and translations" "logs" "tags and lists" are information of the same entity (on the sentence page). 

> Tooltips are also rather unfit for touch screens, especially when the item is also clickable.

I think there are good reasons why it's called "responsive design", and not "smartphone design for every devices". Having tooltips is not an hindrance for small screen users, but relying on them only is a mistake, I think we all agree. Similarly, having the right menu as it is on the sentence page is, in my opinion, acceptable (preferable?) on larger screens (computers), while tabs are more convenient on smaller screens (smartphones). We can refer to how GitHub displays issues on smartphones, for example. 

> In addition, there would be more screen area available if the logs were on different tab and it would even be possible and easier to design some filtering/sorting options.

I absolutely agree ^^ (See my introductory note)

---
To go back to the original issue, I didn't see that @trang  assigned it to herself and I thought it would be good, for consistency mostly, to add this tooltip to all relevant #n logs. I still think it is a good idea, and that doing so would close this particular issue. I think that @trang's proposition falls under the "Rework of the sentence page" issue, which is a totally different, more complicated topic.

**Comment by agrodet** [comment]
Is there any reason why the sharp in `'This sentence was initially added as a translation of sentence #{n}.'` is not included in the placeholder for the link?

**Comment by trang** [comment]
Not that I know of. I agree it would be more consistent to have the `#` inside the link.

**Comment by jiru** [comment]
@agrodet Yes. It was taken out of the placeholder because not all languages use # to mean "number", so we need to allow that character to be translated too.

We could let translators translate # while keeping it inside the link text by creating a separate translation string "#{n}" that would be inserted in the sentence as `This sentence was initially added as a translation of sentence {numberWithNumberSign}.` or something like that, but it makes it harder for translators to figure out what the translation is going to look like.

**Comment by agrodet** [comment]
>  It was taken out of the placeholder because not all languages use # to mean "number", so we need to allow that character to be translated too.

I thought there could be something like that, but then, how does this currently go with #n in all other places, i.e. the log itself? Isn't it built as untranslatable `'#'.$sentenceID` (or similar)?

**Comment by jiru** [comment]
Yes, it hasn’t been taken care of in other places. The logs [used to have # out of the link](https://web.archive.org/web/20160221133411/http://tatoeba.org:80/eng/sentences/show/16440) before they were redesigned a few years ago. I guess I’m the only one picky about that :wink:

**Comment by jiru** [comment]
@agrodet By the way, CakePHP 3 provides something called [view cells](https://book.cakephp.org/3/en/views/cells.html) that you might want to use in your tooltip implementation. Sorry to tell you that now that you apparently more or less completed the implementation... Having it as a view cell would allow sentence text tooltips to be produced in other parts of the website, and we could get rid of [that hack](https://github.com/Tatoeba/tatoeba2/blob/70d6fc5200c9697d57f9f1db59096a3d78b44766/src/View/Helper/ClickableLinksHelper.php#L130) too.

**Comment by agrodet** [comment]
I've given more thoughts to 

> It was taken out of the placeholder because not all languages use # to mean "number", so we need to allow that character to be translated too.

Aren't you afraid that translating the # would create a discrepancy in the design that would confuse users?   
For illustration, suppose that my language, the dollarian, use $ for number: `This sentence was initially added as a translation of sentence $123`  
Similarly, logs could be displayed in dollarian as `$456 → $4444`, `$4444 Hello world`, etc.
If `$n` is clickable, speakers of dollorian could imply that if they want to link a sentence in a message, they can write `$n`. But it wouldn't work because only `#n` gets the "clickable" treatment. And we couldn't include all possible possibilities, anyway.

I do agree with `not all languages use # to mean "number", so we need to allow that character to be translated too.`. However, if we think of it not as "number" but as "shortcut for linking a sentence on this website", we don't need to allow that character to be translated. To be fully dishonest (^^), # does not actually designates the sentence "number", but the sentence "id", as written in `There is no sentence with id 444444444`. Since `id` is implementation specific, I don't think anybody would really complain that they cannot translate it into the symbol used in their language.

**Comment by jiru** [comment]
> If `$n` is clickable, speakers of dollorian could imply that if they want to link a sentence in a message, they can write `$n`. But it wouldn't work because only `#n` gets the "clickable" treatment. And we couldn't include all possible possibilities, anyway.

Not if the $ sticks outside of the hyperlink text. But even if we decide to include it in the hyperlink text, I don’t think that would be super confusing. Writing clickable links is more of a bonus feature; I can hardly imagine any new user *wanting create a sentence link in a comment*. And it will not be long before they inevitably stumble upon a message that includes a # link, and realize "oh, I can create links using #!". Really, users are smarter than this. If you see [n<sup>o</sup> 1234567](https://tatoeba.org/sentences/show/1234567), are you really going to write n<sup>o</sup> in your comments hoping that a link will get created?

We should use correct language and symbols. You will certainly understand if I write "Ça coûte $3", but it doesn’t mean we should put that kind of French on Tatoeba. Forcing # in the UI is imposing an English (actually American) way of writing to readers from other parts of the world. Instead, as a multilingual project that values diversity and equality among languages and cultures, I think that Tatoeba should set an example.

> if we think of it not as "number" but as "shortcut for linking a sentence on this website", we don't need to allow that character to be translated

I agree that we can think of it as a kind of [lightweight markup language](https://en.wikipedia.org/wiki/Lightweight_markup_language) (like the hashtags on social media), but in that case, this should only apply to comments, not other links in the UI. I understand that is it tempting to simplify/uniformize things, but proper use of language often goes against this temptation.

> To be fully dishonest (^^), [...]

Yes, you are being dishonest. :smile:
