### ISSUE TITLE
Duplicate sentence that was fixed by FixHashesCommand was not detected by Horus

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2340]
Reported by CK in a comment on [sentence #8185349](https://tatoeba.org/eng/sentences/show/8185349#comments):

> I'm so grateful to work here every day.
> edited by FixHashesCommand, February 23, 2020 at 6:42 PM
>
> Horus didn't find this. 

When the sentence was edited by FixHashesCommand, the `modified` field of the sentence was not updated so the sentence did not go under the radar.

```
+---------+---------------------+
| id      | modified            |
+---------+---------------------+
| 8185349 | 2019-09-13 22:46:49 |
+---------+---------------------+
```

**Comment by jiru** [comment]
https://github.com/Tatoeba/tatoeba2/blob/d54dd6fabacc199e314f42a9735d626e61bd6f2d/src/Command/FixHashesCommand.php#L81

**Comment by AndiPersti** [comment]
So I should change the `FixHashesCommand` shouldn't I?
(I'm pretty sure there was a reason why I've chosen to not update the column because otherwise I don't think I would have written the comment. But I can't remember the reason.)

I've found [33 duplicate pairs in the database](https://gist.github.com/AndiPersti/d06461a775d7bf2af8ba9c3fbf4085a1#file-duplicates-txt). From these 66 ids, 34 were processed by `FixHashesCommand` according to the contributions log (there is one pair (4173571, 6552479) where both sentences were processed).
I think it would be sufficient to set the modified date to the one from the contributions log and let Horus do its job, i.e. just running a [simple sql script](https://gist.github.com/AndiPersti/d06461a775d7bf2af8ba9c3fbf4085a1#file-updates-sql), isn't it?

**Comment by trang** [comment]
I don't think Horus will still catch these sentences now that we're a few months away from the modification date.

Horus runs every 30 minute and checks for the sentences modified in the past 3 hours, as far as I can tell.

https://github.com/Tatoeba/tatoeba2/blob/dev/docs/cron/dedup.sh#L5

I don't know if there's a way to run Horus for a specific range of sentence IDs?

**Comment by AndiPersti** [comment]
I see.
 
> I don't know if there's a way to run Horus for a specific range of sentence IDs?

There is the option to run a full table scan or an incremental scan (i.e. start at the given date):
https://github.com/Tatoeba/horus/blob/742d31384f71594abfb2352b832e49754be57f5c/dedup/management/commands/deduplicate.py#L434-L443

Running a full scan is not a good idea. 
There are about 233000 sentences added since `2020-02-23` so that's probably also a rather expensive scan (I've tried to run a dry run on dev but Horus is broken there.)

I think we have the following options:
1) Run the incremental scan
2) Update `modified` as described but use the current date. If we modify the sentence from the pair which will be deleted after the merge there shouldn't be a problem.
3) Update `modified` manually in the UI, e.g. change the language and then change it back to the original.
4) Modify the deduplication script so that there is also an option to set the end date of the scan.

Any other ideas?

**Comment by jiru** [comment]
Full scan is not impossible, it just takes a while (a few hours if I remember correctly). We can also run the incremental scan with a big enough timespan so that it includes the time FixHashesCommand did the edit (after updating the `modified` field of the sentences to the correct values). You’d be surprised how efficient Horus is. :wink: The 3h incremental pass only takes a few seconds.

@AndiPersti I repaired horus on dev if you wanna play around with it. (Needed to `git pull` from both `.` and `./src/tatoeba2/`.)

**Comment by trang** [comment]
The time it takes would be proportional to the amount of sentences that need to be scanned, wouldn't it?

If it takes 1 second to process 100 sentences, it would take 40 minutes for 250k sentences, and 22 hours for 8 million sentences.

**Comment by jiru** [comment]
I don’t think it’s proportional.

**Comment by AndiPersti** [comment]
@jiru Thanks for fixing Horus :+1: 

On dev it took Horus about 7 minutes for 243964 sentences:
````
root@envy:~# echo 'select count(*) from sentences where modified > "2019-01-01";' | mysql tatoeba
count(*)
243964
root@envy:~# python /srv/horus/manage.py deduplicate -l /tmp -a dedup.log -i '2019-01-01' -bHorus -c -e
Running incremental scan at 2020-05-27 03:44 PM UTC
Running filter on sentences added since 2019-01-01 12:00 AM
OK filtered 243964 sentences
Running filter on sentences to find duplicates
OK 16 duplicate sets found
Running deduplication transactions on duplicate sets
Deduplication: 100% done
OK 16 sentences merged into 16 sentences
Running verification step
All audio intact?
YES
All duplicates removed?
YES
All merged sentences intact?
YES
Sentences are free from links referring to deleted duplicates?
YES
Deduplication finished running successfully at 2020-05-27 03:51 PM UTC, see full log at:
http://downloads.tatoeba.org/dedup.log
````

**Comment by jiru** [comment]
So I think we could fix the `sentences.modified` field of affected sentences using the following command:
```sql
update contributions c
join sentences s on s.id = c.sentence_id
where c.user_id = 87998 and action = 'update' and type = 'sentence' and c.datetime > s.modified;
```

**Comment by AndiPersti** [comment]
Agreed, this would fix the sentences too.
But we still need to rerun Horus over these sentences, don't we?

**Comment by jiru** [comment]
Yes.

**Comment by jiru** [comment]
Yes.

**Comment by ckjpn** [comment]
Should I leave this in the database for testing purposes, or may I just delete it, so it doesn't show up in the exported data every week?

https://tatoeba.org/eng/sentences/show/8185349

**Comment by AndiPersti** [comment]
I've fixed this by rerunning Horus on the sentences created since February.
