### ISSUE TITLE
Offer "not directly translated into" option when translating random sentences

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#237]
cueyayotl writes:

"When you are browsing sentences by language, you have the option to select 'Not directly translated into' Would it be possible to implement this feature on the Translating Random Sentences section? A minor detail, but could be helpful :)"

**Comment by RyckRichards** [comment]
Requested once more by CK during the 1st Tatoeba day (2015-06-06)

https://tatoeba.org/eng/wall/show_message/22943#message_22943
Answer (by Trang): https://tatoeba.org/eng/wall/show_message/22982#message_22982

**Comment by ckjpn** [comment]
This is now possible with using the advanced search feature, so wouldn't it be better just to make it obvious that it can be done that way.

For example,  here is a random selection of Japanese sentences that are not yet directly translated into English.

https://tatoeba.org/sentences/search?query=&from=jpn&to=eng&trans_filter=exclude&trans_to=eng&sort=random

You can easily get various ways to translate by using the following set up.
Maybe tatoeba.org could offer something similar.

Russian to Spanish
http://a4esl.com/temporary/tatoeba/translate/links.php?f=rus&t=spa

Esperanto to French
http://a4esl.com/temporary/tatoeba/translate/links.php?f=epo&t=fra

**Comment by Guybrush88** [comment]
1000 sentences out of 4816, from Japanese to English, so I have almost 4000 sentences that I can't browse, and I can't really have random sentences that aren't translated in a given language, like i would have when searching for random sentences in any language, since it would search among the whole corpus of that language and show actual random sentences

**Comment by ckjpn** [comment]
Guybrush88,

After you translate the first 1,000 sentences, then you get 1,000 sentences out of 3,816, so eventually you will get them all.

Note that the current "random sentence" feature on this page (https://tatoeba.org/eng/activities/translate_sentences) only gives you a maximum of 15 at a time, rather than the 1,000 you get with the advanced search.

The advanced search version also allows you to limit the selection to only sentences that are not yet translated into your language, so I think it's a much better choice.

I assume Trang could easily set up a TO: and FROM: form for the advanced search form that could replace the existing form on the "translate_sentences" page.  She could also, perhaps, easily add the option to only search for sentences with audio.

**Comment by ckjpn** [comment]
Trang, 

Perhaps you could redo the https://tatoeba.org/eng/activities/translate_sentences page to include the 3 basic ways people can find sentences to translate.

See the types of URLs you need on the left side of this page.

For languages that don't have audio.
http://a4esl.com/temporary/tatoeba/translate/links.php?f=ind&t=fra

For languages that do have audio, you have 6 basic methods, since you could allow limiting to sentences with audio for each.
http://a4esl.com/temporary/tatoeba/translate/links.php?f=deu&t=fra

**Comment by ckjpn** [comment]
I think if my Nov 14, 2015 suggestion were implemented, then this issue could be closed.

**Comment by trang** [comment]
Closing this. 

The feature is available via the advanced search but requires people to have a bit more knowledge of how Tatoeba works.

I don't think it's really worth investing time into making this option more obvious.
