### ISSUE TITLE
Ancient Hebrew (hbo)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2421]
* Language name: Ancient Hebrew
* Language info: https://en.wikipedia.org/wiki/Ancient_Hebrew_language
* ISO 639-3 code: HBO 
* Public List: https://tatoeba.org/eng/sentences_lists/show/166705
* Icon: https://imgur.com/a/x92WUwi
* Requested by: https://tatoeba.org/eng/user/profile/alexmarcelo

**Comment by RyckRichards** [comment]
Note to myself: RTL Language

**Comment by conlangbecca** [comment]
Comment on the flag: why not use the Paleo-Hebrew alphabet? https://en.wikipedia.org/wiki/Paleo-Hebrew_alphabet

**Comment by conlangbecca** [comment]
I might also suggest a plain Magen David, since David was the king of both Judea and Samaria, and the evolutions leading to Modern Hebrew began as it came under the influence of Aramaic.

**Comment by RyckRichards** [comment]
Going to ask Alex Marcelo, the member who requested this language.

**Comment by RyckRichards** [comment]
Alex Marcelo is not against on having a different flag, but he did ask me that someone else design it since he'll have no time.
I truly believe that this flag is good for now. It represents Ancient Hebrew quite well.

**Comment by jiru** [comment]
I would like to merge the associated pull request today so that UI translators have time to translate the language name before the next update this Sunday. Since nobody pointed out anything wrong with the current flag, let’s keep it for now. Anyone may suggest a new flag in the future as long as they can provide the image file.
