### ISSUE TITLE
SVG files bigger than 3KB break building the test suite

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/tatoeba2#2438]
3fab7901058cc2bf7ec06303f77b06c8b8efdc79 added a flag file which is greater than 3KB and thus breaks building the test suite:
https://github.com/Tatoeba/tatoeba2/blob/7789beef99147589b5090f5f33f75101c33992bb/Jenkinsfile#L11-L12

But there is a way to reduce the file size. The coordinates in the `path` elements in that file use a pretty high precision which isn't really necessary. So if we multiply each coordinate with a factor `x` and round it to the next integer the file gets smaller because the numbers need less bytes when converted to strings.

Here is a comparison with factors 100 and 1000:
file | size in bytes | comment
-|-|-
http://tatoeba.forono.be/bal_orig.svg|8819|File from the commit but with `height` and `width` removed because we don't need them
http://tatoeba.forono.be/bal_1000.svg|3678|factor = 1000
http://tatoeba.forono.be/bal_100.svg|2838|factor = 100
http://tatoeba.forono.be/bal_new.svg|9074|New version by gillux from 81b41557e257dd5e8f261acd991790349cdad312
http://tatoeba.forono.be/bal_1000_new.svg|3890|New version, factor = 1000
http://tatoeba.forono.be/bal_100_new.svg|3060|New version, factor = 100

You can see that in full size, the image with factor 100 is a little bit sketchy compared to the other two, but scaled down to `30x20` there won't be any visible difference:
http://tatoeba.forono.be/comparison.html

@jiru I'll let you choose what precision you want.

**Comment by jiru** [comment]
Thanks for the detailed review. The 3KB limit is pretty arbitrary so we might as well higher it a bit as we gain more experience with SVG. I set it as a safeguard to force us to pay attention to the flag sizes when we were still using PNG files. In general I think we should strike to keep our images small.

@AndiPersti I uploaded a new version of the flag with simplified paths. The new version is a bit bigger because Inkscape wrote high-precision numbers, but it should result in a smaller file if we lower the precision. Could you perform the same trick on the new file?

**Comment by AndiPersti** [comment]
> @AndiPersti I uploaded a new version of the flag with simplified paths. The new version is a bit bigger because Inkscape wrote high-precision numbers, but it should result in a smaller file if we lower the precision. 

Actually your new version contains more floating point numbers and more additional text that won't be "compressed". So it won't be smaller after reducing the precision.
```
$ grep -Eo '[-]?([0-9]+)?\.[0-9]+(e-[0-9])?' bal_orig.svg | wc -l
896
$ grep -Eo '[-]?([0-9]+)?\.[0-9]+(e-[0-9])?' bal_new.svg | wc -l
911
```
I've uploaded the files and updated the table in the previous comment.

**Comment by jiru** [comment]
@AndiPersti My bad about the new flag. I saw a lot of what looks like unnecessary curve points, so I used Inkscape to merge shapes and do a "path simplification" pass. But it turns out that as soon as the shape is modified, Inkscape rewrites it using totally different commands in the `d` attribute, resulting in a bigger file, even if the path contains less points.

I think we should consider doing something to deliver compressed SVG when the browser sends the appropriate header like `Accept-Encoding: deflate, gzip`. At this point, that should save much more bandwidth than playing with the actual SVG markup.
