### ISSUE TITLE
Kurdish (Sorani) (ckb)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2528]
* Language name: Kurdish (Sorani) 
* Language info: https://en.wikipedia.org/wiki/Sorani
* ISO 639-3 code: CKB
* Public List: https://tatoeba.org/eng/sentences_lists/show/168673
* Icon: https://imgur.com/a/pIMJJW6
* Requested by: https://tatoeba.org/eng/user/profile/Sarchia

Note: We're waiting members to tell us if their sentences are in this language.

**Comment by RyckRichards** [comment]
Users who posted in Kurdish (Sorani):

Balamax
Kurd

**Comment by jiru** [comment]
This one is going to be difficult to deal with because we already have Kurdish (KUR) on Tatoeba, however it’s considered as a [macro-language](https://iso639-3.sil.org/code/kur) by the SIL. Should/can we change the language of the 1000+ existing Kurdish (KUR) sentences of Tatoeba into individual languages Kurmanji (KMR), Southern Kurdish (SDH) and Laki (LKI)?

**Comment by RyckRichards** [comment]
That's what we (the language team) are planning to do. I am just checking
in what "Kurdish version" they posted their sentences.

Sabretou is going to post an entry on the wiki about that, too.

**Comment by soliloquist-tatoeba** [comment]
These are the Kurdish sentences written in the Arabic script. 

https://tatoeba.org/eng/sentences/show/2850339
https://tatoeba.org/eng/sentences/show/2850341
https://tatoeba.org/eng/sentences/show/2851114
https://tatoeba.org/eng/sentences/show/2851117
https://tatoeba.org/eng/sentences/show/3081404
https://tatoeba.org/eng/sentences/show/4485592
https://tatoeba.org/eng/sentences/show/4485593
https://tatoeba.org/eng/sentences/show/4485594
https://tatoeba.org/eng/sentences/show/4485595
https://tatoeba.org/eng/sentences/show/4485598
https://tatoeba.org/eng/sentences/show/4485600
https://tatoeba.org/eng/sentences/show/4485601
https://tatoeba.org/eng/sentences/show/4485603
https://tatoeba.org/eng/sentences/show/4485604
https://tatoeba.org/eng/sentences/show/4485605
https://tatoeba.org/eng/sentences/show/4485607
https://tatoeba.org/eng/sentences/show/4485608
https://tatoeba.org/eng/sentences/show/5050741

The person (a native Sorani Kurdish speaker) who made the request said that they were all in Sorani. He also said that some of them had errors, but that's another issue. The rest of the sentences are in the Latin script so they are probably all in Kurmanji because it's the only Kurdish language written in the Latin script. There might be a few misflagged sentences though, just like for all the other languages.

**Comment by jiru** [comment]
Note for developers: if we add the above-mentioned sentences to a list and naively `call add_new_language('ckb', list_id);`, it works but the language stats for Kurdish (KUR) are not updated. That may not be a problem if we eventually remove Kurdish (KUR).

**Comment by trang** [comment]
Similar question as in #2529: why `Kurdish (Sorani)` instead of `Central Kurdish`?

**Comment by soliloquist-tatoeba** [comment]
Using *just* directions to define the sublanguages can be relative and confusing. I sometimes hear the Kurds in Turkey referring to Sorani (Central Kurdish) as 'southern'. If a sublanguage has a specific name used by the native speakers, I think it is better to include it. Directions can still be used additionally.
