### ISSUE TITLE
Kurdish (Xwarîn) (sdh)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2530]
* Language name: Kurdish (Xwarîn) 
* Language info: https://en.wikipedia.org/wiki/Southern_Kurdish
* ISO 639-3 code: SDH
* Public List: https://tatoeba.org/eng/sentences_lists/show/168674
* Icon: https://imgur.com/a/Z2v0vW4
* Requested by: https://tatoeba.org/eng/user/profile/Sarchia

We're checking which sentences on our corpus are in this language.

**Comment by jiru** [comment]
I’m concerned about the circumflex on the *i* of Xwarîn. It looks like it’s not consistent with the way you wrote Sorani and Kurmanji, which (I’m guessing) are some kind of romanization of [Soranî](https://ku.wikipedia.org/wiki/Soran%C3%AE) and [Kurmancî](https://ku.wikipedia.org/wiki/Kurmanc%C3%AE) in Kurdish.

**Comment by soliloquist-tatoeba** [comment]
It was requested as Xwarin, but I wanted to replace it with Xwarîn as on [Wikipedia](https://en.wikipedia.org/wiki/Southern_Kurdish) because 'xwarin' also means food in Kurmanji Kurdish. :)

https://en.wiktionary.org/wiki/xwarin

But you are right about the inconsistency. You could replace the others as 'Kurmancî‎' and 'Soranî'‎ if you want.

**Comment by RyckRichards** [comment]
I changed them. Thanks for noticing!

**Comment by trang** [comment]
Similar question as in #2529: why `Kurdish (Xwarîn)` instead of `Southern Kurdish`?
