### ISSUE TITLE
Mouseover to see the sentence number is more useful than a message that says "Show sentence's details."

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2543]
I'm fairly certain that I used to be able to mouseover and see what the sentence number was, and then I could find that sentence number in the logs to find out who linked it.

<img width="654" alt="Screen Shot 2020-09-04 at 13 51 35" src="https://user-images.githubusercontent.com/7934273/92200950-34789e00-eeb6-11ea-8285-e61716669ebe.png">

**Comment by ckjpn** [comment]
Another reason being able to see a sentence's ID number is that you can easily see which sentence is older just by mousing over.

**Comment by ckjpn** [comment]
I'm talking about the mouseover message.
Now the only way to see what the sentence number of one of the linked sentences is to click the link go to it, then look at the number, then return to the page and go down to the logs to find out who added the link.

The logs don't give the text of the sentences, so if you don't know the sentence's ID number, the logs don't mean much.

It was better the way it used to be.

**Comment by trang** [comment]
@ckjpn You may be confusing with something else, this tooltip has been saying "Show sentence's details" for years now.

According to the git history, the line of code corresponding to this tooltip was last modified 4 years ago (and it was due to some migration script so the string itself must have been there even before).

Cf. https://github.com/Tatoeba/tatoeba2/blame/8ac699d87c41c864046311b849121732599aef2b/src/View/Helper/SentenceButtonsHelper.php#L77

Note that you can see the sentence ID on hover by checking the URL that is displayed in the bottom-left corner of the browser. The sentence ID is the number at the end of the URL.

I'm closing this issue. In case you wish for a more practical way to figure out who linked a sentence, feel free to open an enhancement ticket.
