### ISSUE TITLE
Initial UI language does not honor browser settings properly

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2544]
1. Configure your browser preferred languages to "fr-FR".
2. Open a new private browsing session.
3. Go to https://tatoeba.org
4. Bug: Tatoeba displays in English.

Alternatively, using the command line:

```
$ curl -s -D - 'https://tatoeba.org/' -H 'Accept-Language: fr-FR' | grep -i ^location:
location: https://tatoeba.org/eng/
```

**Comment by jiru** [comment]
In a addition, if the user first arrives on Tatoeba on a page that contains a URL code (that is to say, anything but https://tatoeba.org/), then the browser language settings are not honored:

```shell
$ curl -s -D - 'https://tatoeba.org/eng/' -H 'Accept-Language: fr' | grep -i ^location:
# No redirection!
$ 
```

This explains why in [UX test 1](https://en.wiki.tatoeba.org/articles/show/ux-test-1#exploration) the user ended up using Tatoeba in English even though she had proper browser language settings. She looked up "Tatoeba" on Google and clicked on the first link, https://tatoeba.org/eng. She ended up on the English homepage. Then, she went on using the website in English because she understands it, however the test proven that using English introduced problems for her in understanding some words.

**Comment by AndiPersti** [comment]
I've noticed that ignoring the language code in the URL path has a side-effect on webcrawlers.

For example here are the number of responses with status code 200 and 301 for `Googlebot`:

date|200|301
-|-|-
27/Sep/2020| 68,710|  82,423
26/Sep/2020|  61,806 |  74,301
25/Sep/2020|  64,113|  85,712
24/Sep/2020| 76,429 | 89,408
23/Sep/2020| 63,881 | 76,820
22/Sep/2020| 82,687 | 84,816
21/Sep/2020| 98,305 | 67,047
20/Sep/2020| 96,138 | 9,090
19/Sep/2020|132,951| 7,403
18/Sep/2020|114,733| 2,269
17/Sep/2020| 76,451|1,922
16/Sep/2020|116,342| 4,223

As you can see the number of 301 responses have risen sharply since we introduced this change[*]. And I guess in the long term this will hurt the ranking for the localized pages in search results (see #507).

[*] `Googlebot`'s `Accept-Language` header seems to be set to `en` because all pages get redirected to the `eng` prefix. On the other hand `YandexBot` is obviously configured to act as a Russian client, because all its requests are redirected to the `rus` prefix.

**Comment by Yorwba** [comment]
I found [a blog post by Google](https://webmasters.googleblog.com/2015/01/crawling-and-indexing-of-locale.html) that says

> by default, Googlebot requests pages without setting an Accept-Language HTTP request header and uses IP addresses that appear to be located in the USA

and announces

> Language-dependent crawling where Googlebot would start to crawl with an Accept-Language HTTP header in the request.

So if Googlebot sends `Accept-Language: en`, that means they're explicitly requesting the version of the page an English-speaking user would see, and redirecting them to `eng` is correct. On the other hand, it's a bit weird if they never request any other version. Maybe they're just crawling English pages much more frequently?

**Comment by AndiPersti** [comment]
Most of the time `Googlebot` doesn't send a `Accept-Language` header but occasionally I've seen `en_US`. I've logged the header for about half an hour and 2420 requests had no header and 32 had `en_US`.
In that same period it requested 1197 times `eng`, 456 times `bre`, 90 times `cat`, 74 times `bel`, 65 times `ben`, ... All in all it requested about 50 different languages.

So I think the issue is the case where a client doesn't send the header and also doesn't have a cookie with the preferred language. With the current implementation, we will always response with the English version. But that also means that the language prefix in the URL is actually useless and we could get rid of it.

**Comment by Yorwba** [comment]
Including the language in the URL is [officially recommended by Google](https://support.google.com/webmasters/answer/182192?hl=en&ref_topic=2370587)

> Google recommends using different URLs for each language version of a page rather than using cookies or browser settings to adjust the content language on the page.

> If you use different URLs for different languages, use hreflang annotations to help Google search results link to the correct language version of a page.

> If you prefer to dynamically change content or reroute the user based on language settings, be aware that Google might not find and crawl all your variations. This is because the Googlebot crawler usually originates from the USA. In addition, the crawler sends HTTP requests without setting Accept-Language in the request header.

I think the way this is supposed to work is that the URL serves as a unique identifier of the content, and by default everyone accessing the same URL is served the same page. Redirecting the user if the current language is not their preferred one as indicated by the `Accept-Language` header makes sense, but redirecting to English even if English is not included in `Accept-Language` (e.g. because there's no such header) seems more like a bug to me.

This doesn't just negatively affect Googlebot, but also human users. E.g. if my system language is set to Kannada and I also speak some Hindi and find a link to `https://tatoeba.org/hin/` on a Hindi forum, then clicking on the link I'd be delighted to find a website in Kannada, but, since there's no translation into Kannada yet, seeing the Hindi version wouldn't be too unexpected. When I tested this just now with `curl -v -H 'Accept-Language: kn' https://tatoeba.org/hin/`, I was redirected to `https://tatoeba.org/eng/`, even though there's no indication I prefer English to Hindi. (I speak neither Kannada nor Hindi, so I don't know whether this situation is plausible for these particular languages, but I'm pretty sure there are languages where that would be the case.)

**Comment by AndiPersti** [comment]
> Redirecting the user if the current language is not their preferred one as indicated by the `Accept-Language` header makes sense, but redirecting to English even if English is not included in `Accept-Language` (e.g. because there's no such header) seems more like a bug to me.

Agreed.
I'd say the order for setting the language should be:
1. Cookie
2. `Accept-Language`
3. URL path
4. English

**Comment by jiru** [comment]
@AndiPersti Thanks for checking after me. :roll_eyes: 

In the case there is no `accept-language` header at all, I agree that it probably makes sense not to redirect at all because most (if not all) browsers set it, while many crawlers/scripts do not.

@Yorwba About your example of Kannada and Hindi. While these languages may be culturally and/or linguistically close enough, in reality the `accept-language` header is typically preset with "system locale + English" (as opposed to *only* "system locale"). Because of this, I think that your example almost never happens because it will almost always fall back to English anyway.
