### ISSUE TITLE
Can no longer use Enter key to navigate through search fields in right sidebar

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2561]
**To Reproduce**
Steps to reproduce the behavior, on Chrome on an Android device:
1. Do a search (ordinary or regular).
2. On the page with the search results, go to the search sidebar on the right, and put the cursor into the "Words" field at the top. 
3. Change the value in the "Words" field.
4. Press "Enter".

Prior to recent changes, this would take you to the Owner field. Three more presses of the Enter key would take you through Tags and Link Owner and finally your search would be submitted. Compared to the desktop browser, where a single press of the Enter key would submit your search, this was a pain. But at least it was workable.

Now that the UI has changed, hitting Enter wipes out whatever was in the Language field and makes it impossible to do anything until a language is selected. I often want to use the same language as before, so this is a huge step backward in usability for me. The fact that I often have my keyboard configured for Cyrillic while my UI is in English makes things even worse, since I can't type the language name into the field and am forced to scroll through the choices (difficult to do on my tablet). To make things still worse, the language list (which is very long) is mostly hidden by my on-screen keyboard. I have to choose between a bunch of time-consuming alternatives:  close the on-screen keyboard so I can choose a language, change the keyboard to English so I can type a language name, and so on. All this to change a language name which I generally don't even want to change!

This problem could be mitigated somewhat if the submit button (labeled "Search") were at the top rather than the bottom of the page. But I'm not sure whether there would be a key press that would take me from the "Words" field to the submit button, which is what I would really want.

What use case was the change in behavior meant to address, and how much demand was there for a change? If there are people who do want to change the language in search often, and don't mind the fact that Enter wipes out the current value, could there be some way (a configuration option?) that would let us choose the behavior?

**Comment by trang** [comment]
This change was not exactly planned but is the result of unifying the language selectors on every page (#2328).

When you press "Enter" (which is actually "Next"), the browser will jump to the next field that accepts keyboard input. Prior to the changes, the language fields were just regular dropdown lists so there was no keyboard interaction with them, therefore they were skipped. 

With the latest changes, the language fields are using the new language selector which has an autocomplete input. So when you press "Next" from the "Words" field, the next field that accepts keyboard input is no longer "Owner" but "Language".

Now the actual problem is that from the "Language" field, the "Next" key turns into "Search", which prevents you from jumping to the next input with the Enter key. That's because there's a `type="search"` on the autocomplete input. We did not put it there intentionally, it's part of the Angular component that we're using for the language selector.

On Firefox, the behavior is less disruptive because Firefox doesn't convert the Enter key into "Search" on inputs with `type="search"`. So from the "Language" field, it's possible to jump to "Show translations in" then to "Owner", etc.

I see two different problems:

1. If I want to navigate through the search fields with the keyboard, I can't. I'm stuck at the "Language" field.
2. If I want to submit a search after I changed the "Words" field (or even any of the fields at the top of the form), the search button is not easily reachable.

In your case, @alanfgh, it seems the bigger problem is (2). This could be solved with #1726 (adding `type="search"` on the query). It would not be the best solution as it would be a bit conflicting with (1) and it would not solve (2) for non-Chrome users, but it is quick to implement and can improve the situation until we figure out a final solution.

**Comment by alanfgh** [comment]
Thanks for the analysis, @trang . I'm glad you see a connection to #1726. I intended to link to it.

**Comment by alanfgh** [comment]
I had hoped that [jiru's changes to language dropdowns](https://github.com/Tatoeba/tatoeba2/pull/2615) might fix this problem on Android, but instead they've made things a little worse. Hitting Return from the "Words" field still takes you to the "Language" field, but now you're stuck there. You can't get out except by (1) clicking on a "dead" spot on the screen (somewhere that does not perform any action), or (2) choosing a language (even if you were fine with the previous value). You can't even scroll the screen. If you have another app (Multiling O Keyboard in my case) that blocks the dropdown, you need to jump through some hoops to get out of this situation.

![adv_search_Android](https://user-images.githubusercontent.com/1213027/107126816-1d344700-6880-11eb-8362-a7a0c454eb34.png)

**Comment by jiru** [comment]
We could try to update our AngularJS Material library to 1.1.21 or above. They changed the `type` attribute to `text` (angular/material@8c159aa43344cf464e544d0c23a03d3d9e001896). Last time I tried to update, it introduced issues (3caf2c4e593cbd37f5832e4323de652cd61be3b3) but we could try again.

**Comment by jiru** [comment]
I did not try to update AngularJS Material yet but I confirm changing the `type` attribute to `text` in md-autocomplete’s `<input>` allows to jump out of the language dropdown by pressing enter.

**Comment by jiru** [comment]
@alanfgh Could you try out the changes I've made on https://dev.tatoeba.org/ and tell us if it solves the problem for you?

**Comment by alanfgh** [comment]
@jiru It's definitely an improvement in that it brings the situation back to what it was before the change that prompted me to write this issue ticket. Now, once again, I can submit a new search request with the same values as before (except for the search string) by using a series of presses on the Enter key. The focus no longer gets stuck in any of those fields in such a way that the Enter key won't get me out again. I am quite happy about that. However, I still wish the situation were more like it is on my Windows desktop, where I only need to press the Enter key one time, not seven, in order to submit a new query. I don't know whether that is possible on Android, but at least this change makes things far better than they were. Thank you!

**Comment by jiru** [comment]
You’re welcome. As far as I understand, this behavior of having the Enter key stepping through the fields instead of submitting the form is up to the developers of Chrome (the Android browser), so there is not much we can do about it. You can try installing an alternative browser on your tablet such as Firefox.

**Comment by alanfgh** [comment]
This spurred me to install Firefox on my Android devices, which also lets me use custom keyword search ("search engines"), which I often run on my desktop. There are a couple of additional reasons that I prefer Firefox, so I'm happy to have made the change.
