### ISSUE TITLE
Pop-up menus don't scroll vertically on mobile

### ISSUE THREAD

**Issue by Yorwba** [Tatoeba/tatoeba2#2567]
**To Reproduce**
1. Perform a search using a mobile browser.
2. Click on "Narrow Search" to open the "Search critera" sidebar.
3. Attempt to scroll down.
4. Page doesn't move.

The same happens with the hamburger menu in the top-left corner. Horizontal scrolling appears unaffected.

**Expected behavior**
It should be possible to reach parts of the pop-up menus that are initially below the fold.

**Additional information**
- O.S.: Android 10
- Browsers: Firefox 81.1.1, Chrome 85.0.4183.127

**Comment by trang** [comment]
Thanks for creating this bug report, @Yorwba! I noticed this too the other day, when checking #2561.

I looked further into it and found out that this happens because of `height: auto` on the `body`, introduced in e66fafcf6a095ac32821e569f4d9ea7718603d54. This `height: auto` makes the height of the sidenav extend to the whole content of the page rather than just limit it to height of the browser, that's why there is no more scroll.

I guess one solution would be to add media query so that we set `height: auto` only for width>960px.
