### ISSUE TITLE
Some final adjustments for the Kurdish languages

### ISSUE THREAD

**Issue by soliloquist-tatoeba** [Tatoeba/tatoeba2#2570]
I'm creating this issue upon [the request](https://github.com/Tatoeba/tatoeba2/issues/2540#issuecomment-707509680) of Trang.

1- The qualifier could be removed from Southern Kurdish. The name of Xwarîn seems to be unknown to even some Kurds. Unlike Northern and Central Kurdish, Southern Kurdish probably doesn't have a standardized name. Other names like '[Feyli](https://www.youtube.com/watch?v=pFbF9E-3dIo)' or '[Pehlewani](https://tatoeba.org/eng/sentences/show/5050741#comment-824764)' are used, too. Perhaps it would be better to drop it to avoid confusion.

2- All Kurdish (KUR) sentences could be moved to Northern Kurdish (KMR). I've already moved the others. The rest are all in Northern Kurdish.

3- The writing direction of Central and Southern Kurdish should be RTL. Please see [this](https://tatoeba.org/eng/sentences/show/8996029) example. The Kurdish sentences aren't displayed correctly. They should be right-aligned like the indirectly-linked Persian sentence.

4- A Kurdish [user](https://tatoeba.org/eng/user/profile/Sarchia) suggested using the Persian font for Central and Southern Kurdish. Currently, they are in the Arabic font.

5- Another user insists on using [this flag](https://en.wikipedia.org/wiki/File:Flag_of_Rojava.svg) instead of [the current flag](https://commons.wikimedia.org/wiki/File:Flag_of_Kurdistan.svg) for Northern Kurdish, but I'm not sure if we should apply that change without informing other Kurdish contributors and discussing it. I leave the decision up to the admins.

**Comment by RyckRichards** [comment]
@trang How should I do # 2 ? 
>> All Kurdish (KUR) sentences could be moved to Northern Kurdish (KMR). I've already moved the others. The rest are all in Northern Kurdish.

**Comment by AndiPersti** [comment]
> All Kurdish (KUR) sentences could be moved to Northern Kurdish (KMR). I've already moved the others. The rest are all in Northern Kurdish.

I guess nobody wants to manually change the language for the remaining 1300 sentences, so my idea is to adapt/copy the existing Cake command for mass-editing the license.

> A Kurdish [user](https://tatoeba.org/eng/user/profile/Sarchia) suggested using the Persian font for Central and Southern Kurdish. Currently, they are in the Arabic font.

We currently use a single font (`Noto Sans`) for everything so I guess we would need to find a way to change the font depending on the sentence language.
But generally, what font is used by the browser also depends on the user's system. (E.g. I haven't installed `Noto Sans` so I get everything displayed in `DejaVu Sans`, my system's fallback sans-serif font.)

> If the admins are sure (by checking the IP logs etc.) that user is genuine and not some fake identity of an infamous Turkish polyglot (he has many), they could honor that request. I have my suspicion due to some reasons, but I can't prove it.

If you send me the username by PM I will investigate.

**Comment by soliloquist-tatoeba** [comment]
> We currently use a single font (Noto Sans) for everything so I guess we would need to find a way to change the font depending on the sentence language.
But generally, what font is used by the browser also depends on the user's system. (E.g. I haven't installed Noto Sans so I get everything displayed in DejaVu Sans, my system's fallback sans-serif font.)
 
This is how they are displayed on my PC - different on Firefox and Chrome, but same on IE. Is it possible to make Kurdish display same as Persian on Firefox and Chrome, too? I guess it should technically be possible as Persian displays same on all browsers.

<img width="519" alt="font" src="https://user-images.githubusercontent.com/47579687/95981288-16904880-0e27-11eb-8857-76f46e4645e2.png">

**Comment by CrowdsourceKurdish** [comment]
Hello,
First of all thank you for adding other Kurdish dialects. At the top, there is a demand for a change of flag, but a flag called the rojava flag is not officially recognized. The Kurdish flag(available), which is available in many other language / translation platforms, is used and the current Kurdish flag on Tatoeba represents all Kurdish and Kurdish dialects. No change is required.
Most well-known people use the same flag for kurmanji;
link: https://twitter.com/duolingokurdi/status/1313821607970902016?s=20
link: https://twitter.com/kurdishlessons/status/1277528415235604481?s=20
Translation platform Crowdin uses the same flag for Kurmanji;
![1](https://user-images.githubusercontent.com/72891963/96047333-96e19880-0e7d-11eb-8d44-b91a8a95ce16.JPG)


Thanks.

Kurdish Language Community

**Comment by jiru** [comment]
> We currently use a single font (`Noto Sans`) for everything so I guess we would need to find a way to change the font depending on the sentence language.

This kind of problem should be automatically handled by the browser from the `lang` attribute. I am guessing that Firefox and Chrome have some reasons to select a different font, while IE have reasons not to. But really this should be the browser’s job and we shouldn’t need to interfere in theory.

**Comment by Kadar111** [comment]
It is me who insists to use Rojava's flag instead of this three letter sided flag for northern and Kurdistan's flag for central and southern Kurdish. the fact is that we dont yet have a unified Kurdish flag that all political parties agreed on, 
 Rojava's flag is recognized as only official flag in social contract and all administrative departments, universities and schools are operating under that flag so since Tatoeba wants to stop supporting macrolanguages Rojava's flag is a better alternative to those three lettered one.

**Comment by Berevaji** [comment]
Hi,
Even though there is no unified Kurdish flag yet, the 4-colored flag with the sun at the center is the oldest one in use which was created and put into use first by Kurmanji speaking Kurds in early 20th century and it has actual international recognition today. The fact that it is ALSO the flag of the Kurdistan Region of Iraq doesn't take anything from it to represent all Kurdish dialects, there are many millions of Kurmanji speakers living in the KRI as well which in its many provinces and cities, Kurmanji (Northern Kurdish) is officially used as the primary language of government and education. 

As for Rojava, or today as it describes itself "Autonomous Administration of North and East Syria" doesn't have the three colored flag as its official flag, but another one with white background with a circle in the center colored blue and yellow and it has the name of the region in the four languages of the peoples living under the administration. This is the region's official flag and it doesn't primarily represent Kurds but all the peoples of the region. It isn't as internationally recognized nearly as the "Kurdish flag" internationally as the original century old flag with sun at the center is.

Other than this, the three-colored flag (unofficially) used by Syrian Kurds in the AANES is deemed illegal by some countries in the MidEast. So assigning it to an online platform could be problematic for some users and might lead them to be hesitant to contribute.

For these reasons I advise against adopting it for Kurmanji (Northern Kurdish) on Tatoeba. The four-colored flag with the sun at the center is accepted by many Kurds and it has even been hoisted by the AANES in many official events and ceremonies throughout the years. It is also used by most online platforms and services to represent all of the Kurdish dialects and it is identified by most users. Tatoeba wouldn't be in the best position by being an exception.

Flag of Kurdistan on Wikimedia Commons: [Flag of Kurdistan](https://en.m.wikipedia.org/wiki/Flag_of_Kurdistan#/media/File%3AFlag_of_Kurdistan.svg) 

Official flag of the AANES on Wikimedia Commons: [https://en.m.wikipedia.org/wiki/Autonomous_Administration_of_North_and_East_Syria#/media/File%3ADe_facto_SA-NES_Flag.svg](AANES)

**Comment by Kadar111** [comment]
Well tens of thousands of students from elementary schools up to universities study in Kurmanjî by LATIN SCRIPTS and hundreds of books get printed every year in Rojava under that three colored flag, where else in world does that happen? iin Kurdistan region all schools teach in ARABIC SCRIPTS and  you can even hardly find a single sign on roads written in Kurmanjî so how its flag could represent Kurmanjî? besides it is simply a trivial excuse that because Rojava´s flag is illegal in some countries so we cannot use it in tatoeba, even Kurdish language is forbidden in some countries so should we remove it from tatoeba?

I dont ask to remove Kurdistan flag, i just suggest to keep using it for central and southern Kurdish and Rojavas for northern Kurdish.
Rojava is de facto self administration now even though it is not yet internationally recognized and both Kurdistans and Rojavas flag are subjected to change at any time but right now it is that three colored flag represent majority Kurmanjî speaking Rojava whether you like it or not.

**Comment by Berevaji** [comment]
Hi again,

First of all this is not about who likes what or not. Like I said, the three colored flag is not even the official flag of the AANES (aka Rojava). I presented its official flag. If the three colored flag isn't even the official flag of the self-proclaimed autonomous region, how can it be regarded as official in anyway? 

And the reason that the flag of Kurdistan represents all Kurds and all Kurdish dialects has nothing to do with the KRI. This flag is almost a century old, as I mentioned earlier. It was created by Kurmanji speaking Kurds of Northern Kurdistan, which is predominantly Kurmanji speaking. Then later on, only many decades later the KRI adopted the four-colored flag with the sun at its center as its official flag. The KRI isn't even the tertiary beholder of this flag, it adopted it much later than many Kurdish organizations and regions, many of which were/are Kurmanji speaking. KRI only lead it to be internationally recognized, due to it being the contemporary internationally recognized Kurdish government. This could have been different and "Alaya Rengîn" would still be the most prevalent Kurdish flag. But it was KRI's choice of adopting the century old Kurdish flag as their own as well.

Its history and recognition is what makes this flag representative of all Kurdish dialects, including Kurmanji. Even especially Kurmanji, because Kurmanji speaking Kurds are the creators of this flag.

Also, the Kurdish language itself is not illegal in any countries. Believe me, if it was many platforms would exclude it by themselves. I also didn't say because it is illegal it shouldn't be anywhere, but like I said it can cause some users to not be as confident and comfortable to contribute in that case. Since Kurdish language isn't legally banned anywhere, no one has to worry about that. Thousands of people are already contributing to Kurdish projects without any issues. 

Something else Tatoeba should keep in mind is consistency, most platforms use the official Kurdistan flag to indicate Kurdish dialects, including Kurmanji. Like I said being an exception, wouldn't be the best position that Tatoeba would want to be in.

Another thing is, Rojava has one of the smallest portions of the Kurmanji speaking population, if not the smallest. It doesn't encompass all of the Northern Kurdish speaking people in anyway. Vast majority of Kurmanji speakers live in Turkey, next comes Iran and lastly either KRI or AANES. Since there isn't detailed census data we can't be exactly sure. 

Kurdish education using the Latin (Hawar) alphabet is given even in Turkey, although very limited. And Kurmanji is registered to be a language of Turkey with the locale code "ku_TR" on many standardisation platforms and services. So should the Turkish flag be used for Kurmanji if someone suggests that way? ABSOLUTELY NOT! Kurds are Kurds and they have their own national symbols, including a flag. Complicating things further isn't good for anyone.

So despite all this, how can the three-colored flag which isn't even the primary official flag of the AANES can be used to represent Kurmanji? It can not. And it's not about whatever I like or don't, this is the norm. Even Rojava hoists the Kurdistan flag at times. It is the most prevalent flag of the Kurdish people, respected in the both autonomous regions which are predominantly Kurdish.

We don't need further devisiveness. Not especially in these times which Kurds and their natioanl symbols are under attack. Hopefully no further is discussion needed.

**Comment by Kadar111** [comment]
Dude nobody questioned the history of Kurdistans flag so take it easy.
 But you are sadly misinformed and i reluctantly find it necessary to reply to some of your baseless claims.
The three colored flag IS official flag of Rojava and it is written in social contract.
Rojava and AANES are 2 different bodies.
Rojava consists of only three cantons (Cizîra, Efrîn, Kobanî) while AANES is a UNION between Rojava and some majority Arab dominating governorates (Dêrezor, Raqqa, Manbîj)
Same like YPG and YPJ, they are Rojavas defence forces but together with some other local ethnic groups and arab tribes they formed Syrias Democratic forces (SDF) and this doesnt mean YPG and YPJ dont exist any more.
European Union has it is known special flag, does it mean Germany has abandoned it is own national flag? 

You guys there know very well that northern Kurdish(Kurmanji) is almost invisible in Kurdistan region and badly marginalised and by enforcing it is flag for Kurmanji quite oppressive and it is somehow like enforcing Algerian flag for Egyptian arabic. Rojava is far more rightful than Kurdistan to represent Kurmanci.

Some of you reported me in Tatoeba claiming that im not Kurmanjis native speak. you are so bluntly adorable people.

**Comment by soliloquist-tatoeba** [comment]
After Berevaji's elaborate explanations, I'm convinced and personally consider the issue a done deal. We've also received objections from some non-Kurdish users against changing the flag of Northern Kurdish, but I'm glad that the discussion has remained between Kurds without foreign interventions. If the user Kadar wants to represent his/her contributions with a different flag, s/he's welcome to use it as his/her profile picture.

I also hope this flag issue doesn't affect the other adjustments and delay their implementation.

**Comment by Kadar111** [comment]
"you are convinced"? are you trying to say that it wasn't already a "done deal"? have you noticed that for Zaza they use another flag why you aren't you "convinced"to set Kurdistan flag for it too? isnt it also a Kurdish dialect ? and off course you ALL Kurds agreed on that flag.
any way. Tatoeba is just a website and you guys haven't landed on moon by denying Rojavas flag. 

congrats.

**Comment by soliloquist-tatoeba** [comment]
> have you noticed that for Zaza they use another flag why you aren't you "convinced"to set Kurdistan flag for it too? isnt it also a Kurdish dialect ?

Yes, I'm aware of that. It's a disputed issue among Zazas. I konw that many Kurds and some Zazas consider Zaza as a Kurdish dialect, and I respect that, but other Zazas don't. 

Here's [a comment of a Zaza user](
https://tatoeba.org/eng/sentences/show/5270493#comment-877796). (Many of the Zaza sentences on Tatoeba were added by him)


I also contacted [another Zaza user](https://tatoeba.org/eng/user/profile/Hatfanz) on Facebook some time ago to ask in which Zaza dialect the sentences on Tatoeba were and discussed these issues. He also considers the Zaza language as a separate Iranic language and not a dialect of Kurdish.

Tatoeba shouldn't be a battleground for such ideological conflicts. It's fruitless. Besides, Tatoeba follows SIL International's standards for adding and classifying languages. Kurdish and Zaza are classified as separate languages there. 

https://iso639-3.sil.org/code/kur

https://iso639-3.sil.org/code/zza

If a Zaza user wanted to represent their contributions with the flag of Kurdistan, my recommendation would be using it as their profile picture, just like my recommendation to you for the flag of Rojava.

**Comment by Kadar111** [comment]
Wow I have just got amazed now how tirelessly you contributing in turkish language. no wonder why Rojavas flag is being rejected.



what a failure for Tatoeba to let turks decide for Kurds.

Im just deleting my account,

**Comment by soliloquist-tatoeba** [comment]
> Im just deleting my account,

I hope you won't. No offense, but your reaction reminded me a bit of [this](https://www.youtube.com/watch?v=RXS1sJm7QEA).

**Comment by trang** [comment]
> 1- The qualifier could be removed from Southern Kurdish.

This is done.

> 2- All Kurdish (KUR) sentences could be moved to Northern Kurdish (KMR).

This will be done after #2576 is merged, so probably in a week or two.

> 3- The writing direction of Central and Southern Kurdish should be RTL.

This is done.

> 4- A Kurdish [user](https://tatoeba.org/eng/user/profile/Sarchia) suggested using the Persian font for Central and Southern Kurdish.

We could add CSS rules to specify the font-family for each language:
https://www.w3.org/International/questions/qa-css-lang

The user in question suggested using Noto Naskh Arabic, which is one of the fonts suggested when searching "Central Kurdish" or "Southern Kurdish" on the [Google Noto Fonts](https://www.google.com/get/noto/) page.

> 5- Another user insists on using [this flag](https://en.wikipedia.org/wiki/File:Flag_of_Rojava.svg) instead of [the current flag](https://commons.wikimedia.org/wiki/File:Flag_of_Kurdistan.svg) for Northern Kurdish

The suggestion for using the Rojava flag seems controversial and therefore we will not proceed to use it for the time being. I wouldn't consider this case entirely closed, but we need to do more research on the topic and that can take time.

@Kadar111 Please don't misinterpret this as "letting Turks decide for Kurds". The fact that solliloquist is Turkish is merely a coincidence. He was not at the origin of this flag.

We added Kurdish back in April 2012 (https://github.com/Tatoeba/tatoeba2/commit/618497c35d41d3d6be23677e81682094540abbbc), with a different flag (https://github.com/Tatoeba/tatoeba2/blob/6164448b9b5a4c5555d2d6364924d2445d2221a4/app/webroot/img/flags/kur.png).  I'm not able to trace back who suggested this intial flag but this flag was reported to us in March 2015 as being the flag of a terrorist organization PKK (cf. #159). We replaced it with the suggested flag of Kurdistan.

We've had people (including you, @Kadar111) who contributed Northern Kurdish (KMR) sentences in the Kurdish (KUR) corpus, with the flag of Kurdistan. I think this is a sign that this flag is at least not offensive to Northern Kurdish native speakers, otherwise we would have heard complaints about it before.

You could argue that using the flag of Rojava is better, but to establish this, we would need more time to do proper research. Until we have more evidence that the flag should be changed, we're keeping the flag of Kurdistan.

---

I think this ticket can be closed once we have moved the sentences from Kurdish to Northern Kurdish. We can handle the font and the flag issues separately.

**Comment by AndiPersti** [comment]
> > 2- All Kurdish (KUR) sentences could be moved to Northern Kurdish (KMR).
> 
> This will be done after #2576 is merged, so probably in a week or two.

I've merged #2576 and moved all Kurdish sentences to Northern Kurdish.

Before removing Kurdish we also need to deal with 44 Kurdish vocabulary items (see also https://tatoeba.org/eng/vocabulary/add_sentences/kur):

id|lang|text
-|-|-
46053|kur|bakûr
46054|kur|başûr
46055|kur|nerîn
46056|kur|mêzekirin
46057|kur|bahoz
46058|kur|bêkêr
46059|kur|bêxêr
46060|kur|kêrhatî
46061|kur|kêrnehatî
46062|kur|bazin
46063|kur|baz
46064|kur|ajal
46065|kur|kûçik
46066|kur|mamoste
46067|kur|bandor
46068|kur|xurifî
46069|kur|kalbûn
46070|kur|karker
46071|kur|karmend
46072|kur|hiş
46073|kur|hişmendî
46074|kur|bajarî
46075|kur|gundî
46076|kur|welatî
46077|kur|welatên yekbûy3i
46078|kur|welatên yekbûyî
46079|kur|zivistan
46080|kur|payîz
46081|kur|havîn
46082|kur|bihar
46083|kur|hevok
46084|kur|pismam
46085|kur|keçmam
46086|kur|keçxal
46087|kur|birazî
46088|kur|ziman
46089|kur|zimannas
46090|kur|peyv
46091|kur|peyvên kurdî
47269|kur|derfet
48649|kur|navgîn
48650|kur|aşti
48651|kur|amûr
48652|kur|alozî

@soliloquist-tatoeba I guess these are all in Northern Kurdish, aren't they?

**Comment by soliloquist-tatoeba** [comment]
Yes, I think so. And thanks for your efforts on #2576. It will be very useful for dealing with other macrolanguages.
