### ISSUE TITLE
Make it so if someone adds a sentence that is an orphan, the sentence automatically gets adopted by that username.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2581]
**Story** or **Context**
For the example, I'll just include the private message that I received.

*Example:*

When I add a sentence which is the same as an orphan sentence, the sentence still is an orphan, the sentence doesn't become mine.

(1) In the case added as a translation:
The added sentence is only linked, and the owner of the sentence doesn't become ourselves.

(2) In the case a new sentence is added:
The following message is displayed.
・Your sentence was not added because the following already exists.

If I remember correctly, I think it used to be as follows.

In case (1); The added sentence was linked and the owner of the sentence was automatically myself.

In case (2); The message wasn't displayed and the owner of the sentence was automatically myself.

What do you think about those?

Annotation: https://tatoeba.org/jpn/sentences/show/9207530

https://tatoeba.org/eng/sentences/show/9207530
アドプトされていない文（孤児の文）と同じ文を追加した時に、自動でアドプトされないような気がします。

この文は、
#9199907 Will Tom come today?
に追加した後、意図的に文を手放しました。その後、
#9207428 Is Tom going to come today?
の文にコピペで貼り付けましたが、small_snowでアドプトされませんでした。

テスト環境がうまく使えなかったので、こっちで試しちゃったごめんなさい。
昨日も、
#202714 ちょっと聞いてもいい？
で同様のことが起こりました。掲示板に書けばいいのだろうけど、不確かなのでまずは、こちらにメモ書き。

**Comment by HelioStrike** [comment]
@ckjpn I think the issue makes sense, but I think it was a conscious decision to make the change (from the earlier behavior to the present one). What do you think, @AndiPersti?

If the issue is valid, I'd like to work on this. I only discovered Tatoeba recently, and couldn't find a way to create orphan sentences. Could you please tell me how I could it, so I could try to replicate this behavior on my own system?

**Comment by AndiPersti** [comment]
I think this issue is valid and the suggested solution sounds reasonable to me.

I don't know anything about the old behavior but maybe @trang does.

As far as I can tell the current behavior was introduced by #1311 (fix for #577) and nobody probably thought about duplicates of orphan sentences.

**Comment by trang** [comment]
When the duplicate detection was implemented, I believe that indeed, no one thought about orphan sentences.

The suggestion is okay but we should limit it to only advanced contributors (who are allowed to adopt sentences) otherwise it creates a loophole.

Let's say I got banned and I'm not happy about it. I could just create a new account, open the list of orphan sentences, copy-paste them on the "Add sentences" page and they would belong to me. From that point, I can edit the sentence and change them anything else. It would not be much of a big deal for a sentence that is completely isolated, but it is a problem for orphan sentences that have translations, or have been tagged, or added to a list.

The automatic linking from the duplicate detection already created a loophole that we haven't solved. As a new contributor, I could for instance add "I love you" as a translation of "Let's try something!", and those two sentences would be linked even though I don't have permissions to link sentences. As far as I know, no one abused this but it wouldn't be a reason to introduce another loophole.

With that in mind, you're welcome to work on it, @HelioStrike :)

**Comment by ckjpn** [comment]
> The suggestion is okay but we should limit it to only advanced contributors (who are allowed to adopt sentences) ...

I'm pretty sure that you don't need advanced contributor status to adopt sentences.

Note that on the dev.tatoeba.org site, at least, you do not need to be an advanced contributor to adopt sentences.

I just tried it to verify this
https://dev.tatoeba.org/eng/activities/adopt_sentences/eng

**Comment by ckjpn** [comment]
Here is something that would be related that might not be too difficult to implement at the same time.

If someone adds a sentences as a translations or as a new sentence that ends up being a sentence that already exists, and that sentence is already owned, have an OK rating by that username assigned to the sentence.  If someone creates the same sentence, they obviously think it's OK.

**Comment by AndiPersti** [comment]
> > The suggestion is okay but we should limit it to only advanced contributors (who are allowed to adopt sentences) ...
> 
> I'm pretty sure that you don't need advanced contributor status to adopt sentences.

You're right: https://github.com/Tatoeba/tatoeba2/blob/afd9bdea47d794e967ed21570120ddcc820f0683/config/auth_actions.php#L77

But you need to be at least `advanced_contributor` if you want to adopt a sentence from a spammer or inactive user:
https://github.com/Tatoeba/tatoeba2/blob/afd9bdea47d794e967ed21570120ddcc820f0683/src/Model/Table/SentencesTable.php#L1038-L1040

**Comment by HelioStrike** [comment]
@trang @AndiPersti @ckjpn Thanks for all the info! I still have a couple' more questions... how are orphan sentences created? What's different between the sentences a contributor can adopt, and those that only advanced contributors (or higher) can adopt?

I've been having an issue that isn't exactly related to the topic. Since yesterday (well, night), starting up imouto and going to `http://127.0.0.1:8080/` on my browser forwards me to `http://127.0.0.1:8080/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/eng/` and the page crashes. I re-downloaded imouto, ran `vagrant destroy`, `vagrant halt`, and `vagrant up` several times (not in this exact order), restarting my pc once in a while. There were a couple times when I was able to see the homepage, but the next `vagrant up` destroyed it once again. Is this a perhaps a known issue, caused by me doing something I don't well?

**Comment by AndiPersti** [comment]
>  how are orphan sentences created?

At the beginning every sentence has an owner (the sentence creator). But users can give up their ownership by "unadopting" a sentence and so it becomes orphan. See also [our Quick Start Guide](https://en.wiki.tatoeba.org/articles/show/quick-start#adopt)

> What's different between the sentences a contributor can adopt, and those that only advanced contributors (or higher) can adopt?

Contributors can only adopt orphaned sentences. Other users can also adopt sentences that still belong to inactive users (or spammers).

>  Is this perhaps a known issue, caused by me entering a wrong command or something?

Sorry for the inconvenience but a few days ago I've updated the code that changed the configuration for the UI languages. So you either update your VM (see below) or copy the [UI language part from `config/app_local.php.template`](https://github.com/Tatoeba/tatoeba2/blob/afd9bdea47d794e967ed21570120ddcc820f0683/config/app_local.php.template#L139-L219) to `config/app_local.php`.

If you want to update the VM, you first need to run `vagrant box update`. Then you need to destroy your old box (`vagrant destroy`) and restart it (`vagrant up`). But updating will also destroy all your data inside the VM. So you should first commit all your changes and sync to GitHub. The destroy script also will also ask you whether you want to backup your database. In addition I would recommend to copy your git configuration (`.git/config`) to a place outside the VM on your local computer. After your new VM runs, just copy the configuration back to `.git/config` and run `git remote update`.

**Comment by HelioStrike** [comment]
@AndiPersti I think I've got all my answers. Thank you! :)

**Comment by trang** [comment]
> I'm pretty sure that you don't need advanced contributor status to adopt sentences.

Yes, my bad, I mixed it up with sentences from suspended users. 

Thanks @AndiPersti for clarifying it :)

**Comment by HelioStrike** [comment]
@ckjpn I'm somewhat new to Tatoeba, and can't find "OK rating" anywhere. Could you give me the steps on how I could do it via the interface?

Also, I finally got some code going! Do have a look at the description and review if I got everything.

**Comment by ckjpn** [comment]
Go to your settings.
https://tatoeba.org/eng/user/settings

Make sure that the following is selected.
Activate the feature to review sentences

Then go to any sentence and the 3 rating buttons appear.

Maybe you want to experiment safely on the "dev" site.
https://dev.tatoeba.org/eng/user/settings
