### ISSUE TITLE
Comments and private messages not working when email notifications fail to be sent

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2594]
**Story**

Gmail was experiencing issues in the past couple of hours or so. We use Gmail SMTP to send notifications and they could not be sent. As a result, features that required to send notifications (comments, private messages) would not work.

Related Wall thread: https://tatoeba.org/eng/wall/show_message/36302#message_36302

**Idea**

Ideally, users should still be able to post a comment or send a private message even if the email notification fails. When that happens, we could save somewhere that the email notification could not be sent for a certain comment or message and have some corn job that tries to re-send failed notification every hour or so.

**Comment by AndiPersti** [comment]
> When that happens, we could save somewhere that the email notification could not be sent for a certain comment or message and have some corn job that tries to re-send failed notification every hour or so.

Instead of building our own infrastructure for resending emails, an alternative would be to configure our local mail server (exim4) to forward outgoing mails to Gmail and in the code use exim4 instead of Gmail as the transport agent (i.e. email notification -> exim4 -> Gmail -> recipient). Exim4 will retry bounced messages for some time.

**Comment by trang** [comment]
I'm not at all familiar with exim4 but if it does the job then I have no objection. I'm happy with whatever is the easiest to implement and least demanding on maintenance.

**Comment by AndiPersti** [comment]
Fixed by #2600
