### ISSUE TITLE
Search word ‘sanoi’ results...

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#2639]
Why does searching for the Finnish word ‘sanoi’ bring up 7 words in Basque that are related to ‘San, Santua etc.’ when there is no form ‘sanoi’ in all 7 sentences (and googling sanoi/Basque doesn’t show any results either)?

**Comment by Yorwba** [comment]
Because the Snowball stemmer for Basque treats "sanoi" as a form of "san". You can [try it out on their demo page](https://snowballstem.org/demo.html#Basque). "oi" is [explicitly listed as one of the suffixes to be removed by the stemmer](https://github.com/snowballstem/snowball/blob/8b49140e5cb6675c58bd908dbd4c7e12146a4f72/algorithms/basque.sbl#L81)

If you had selected that you only want results in Finnish but still got Basque results, this would be a bug, but otherwise it's working as intended.

**Comment by mramosch** [comment]
Even if there is no word like ‘sanoi’ in Basque?

**Comment by jiru** [comment]
Yes, even if there is no word like "sanoi" in Basque.

This is because stemmers are "stupid". They are basically a bunch of rules to remove suffixes and prefixes. [Stemming](https://en.wikipedia.org/wiki/Stemming) is different from [lemmatisation](https://en.wikipedia.org/wiki/Lemmatisation).

Just to give you an example in a different language, consider the German word "Kondensator". Also, consider that -igkeit is a typical suffix in German. Now try to search for the word Kondensatorigkeit in German; you’ll that a sentence containing the word "Kondensator" shows up in the results, despite Kondensatorigkeit not being a word in German.
