### ISSUE TITLE
Old sentence block is confusing

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2670]
Let’s discuss here the issues raised by [githubshrek’s comment](https://github.com/Tatoeba/tatoeba2/issues/2611#issuecomment-808809743):

> Structurally, "the sentence" is shown as a single row in the same table as all the other sentences. This is actually somewhat confusing. For example, the sentence https://tatoeba.org/eng/sentences/show/9872646 is "Nie chcę z Panem mówić.", but when you look at the table, although it's the first row, and a bigger font, the table heading "Sentence #9872646" implies that all of the sentences in the table are simply versions of "Sentence #9872646", which is just not the case.
> 
> A second, related problem is the "menu" icons (Translate, Add to favourites, Add to list and the User profile link), which are separated from the table rows by a fine line. I guessed, wrongly, that these icons apply to all of the rows of the table. Not so. They only apply to the first row of the table.
> 
> I think therefore, the correct solution is to structurally separate the items which relate to the sentence itself, into a sentence details section:
> 
> * the sentence text, here "Nie chcę z Panem mówić."
> * the sentence id, here 9872646
> * **the sentence flag**, e.g. Polish
> * **the sentence language [new]**
> * the Translate icon
> * the Add to favourites icon
> * the Add to list icon
> *  the belongs to User link
> 
> from the sentence translations table, with multiple rows:
> 
> * sentence translation link arrow
> * sentence translation flag, e.g. Romanian
> * sentence translation text
> * sentence translation copy icon
> * sentence translation audio
> 
> 
> Basically, we should clearly separate the elements which are part of the sentence and things which are not.
> 
> Another deeply related issue is the main point about the page is _not_ the sentence id. As IT people, it is extremely important, but for the general user, it's the sentence itself which is the main thing, and other things (flag, id, etc.) are merely attributes of the sentence itself.
> 
> I'm not a designer (as you will see below), but structurally I think it should be more like the following:
> ![image](https://user-images.githubusercontent.com/7943077/112737243-380a6a00-8f59-11eb-8410-18527992a135.png)

**Comment by jiru** [comment]
I agree that the sentence block design is confusing, as mentioned in other tickets such as #2132. I very much wish this could be improved somehow, but it’s quite of a difficult task.

First, let me share some historical facts. The sentence block design you are referring to is actually something we call the "new design", which is part of an ongoing work mostly done by @Trang over the past years to make Tatoeba responsive, more modern looking and solve a number of bugs with the previous design. That previous design (aka "old design") can still be used by switching a setting in your preferences. We plan to get rid of the old design once the new design is mature enough. I think Trang could elaborate better on that, but she is not active these days, and this whole redesign work happens to be stalled at the moment. Trang wanted to make it easy for current members to switch to the new design, that’s why the structure is the same, and this structure has been around for [more than a decade](https://web.archive.org/web/20101205005334/http://tatoeba.org/eng/sentences/show/1). That was for the "how did we get there" part.

About the sentence id, as technical as it might look, it makes sense for members because this is how they refer to sentences in discussions. One can post a message like `Can you help me check if #1234567 is correct?` and `#1234567` turns into a link leading to the sentence page.

About your design suggestion, I think structurally separating the items is a good way to tackle the confusion. However, it looks like your design is tailored for the sentence page. What about other contexts, such as search results? If, say, I am searching for Polish sentences, there is little point displaying the word "Polish" underneath every result flag. Besides, it takes of lot of vertical space which is annoying when scrolling search through search results.

I’d like to see if we can make use of [Material’s bottom sheet](https://material.angularjs.org/latest/demo/bottomSheet) to make the sentence buttons pop-up over the sentence text from the bottom. I don’t have a precise design yet though.

**Comment by githubshrek** [comment]
In fact, I notice that **Random sentence** uses a much more clearly separated design than the **Sentence search** structure:

![image](https://user-images.githubusercontent.com/7943077/115468032-bee9f400-a232-11eb-8f61-8912528bb28d.png)

![image](https://user-images.githubusercontent.com/7943077/115468185-007a9f00-a233-11eb-8135-df83129c9631.png)

**Comment by jiru** [comment]
@githubshrek Your first screenshot shows the old design while the second screenshot shows the new design (see my previous comment for what I mean about "old" and "new"). I assumed that your initial comment was talking about the new design, but it seems not. Could you clarify?

**Comment by mramosch** [comment]
Gilles, I guess you meant it the other way round.

First screenshot is new design
Second screenshot is old design

I also saw shrek referring to the old design in other posts. I am not quite sure that he knows about those designs...

**Comment by jiru** [comment]
Yes, sorry I meant the other way round.

My point is that even though the new design is less confusing that the old, I think there is still room for improvement.

**Comment by githubshrek** [comment]
OK, let me clarify. If I understand correctly, we have:

OLD design:
![image](https://user-images.githubusercontent.com/7943077/117542166-d4736200-b017-11eb-9a0c-617d97273b50.png)

NEW design:
![image](https://user-images.githubusercontent.com/7943077/117542177-db01d980-b017-11eb-9caa-ed47e7cc0a8d.png)

When I created this "Sentence block is confusing" I was looking at the OLD design, which is still the most commonly displayed on the site.

The great news is that the NEW design addresses many of the issues which were confusing:

- the NEW design more clearly separates "the sentence" from the translations
- the NEW design more clearly displays the buttons for translation as related to the sentence rather than all of the translations

As I said "I think therefore, the correct solution is to structurally separate the items which relate to the sentence itself, into a sentence details section". The NEW design does this.

I still think there is an important issue that the sentence and sentence id is shown the wrong way round. Currently it is like the sentence id is the main entity and the sentence text is just an attribute of the sentence id. I think it is the other way round: the sentence itself is the main entity, and the sentence id is an attribute of the sentence. I think this is best separated into its own issue.

Regarding the OLD vs. NEW sentence block, I think the main thing is to get the NEW block being used everywhere, since it is much less confusing. I do have some other issues with the NEW block, but I will raise them as new tickets.

I think this ticket can be closed.

**Comment by githubshrek** [comment]
By the way, I see the new design has been stuck at pull request stage (https://github.com/Tatoeba/tatoeba2/pull/2351) for nearly a year now. Anybody know what the plans for getting that unstuck?

**Comment by jiru** [comment]
Closing as requested. About #2351, you want to ask @trang.
