### ISSUE TITLE
GET requests

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#2682]
Are Javascript GET request like in e.g.

• tatoeba2/webroot/js/services/list-data.srv.js

jQuery? Ajax?

——————————-

$http.get(rootUrl + '/sentences_lists/choices').then(function(result)

——————————-

Because in a WKWebkit webView environment on iOS it does not trigger a RESPONSE callback like all other request usually do.

That restricts you from investigating the response-headers like the ‘Set-Cookie’ header.

It also doesn’t trigger the’didChangeCookieStore’ callback although logging the content of the cookieStore shows that the cookies have been set properly.

Does that mean that (regarding their accessibility) GET requests issued from JS are treated differently by the Browser than the ones issued natively in application code?

**Comment by jiru** [comment]
There is not much we can do to help you on this. The GET request on `/sentences_lists/choices` is generated by Javascript code in `js/services/list-data.srv.js`. As such, it is an Ajax query. That code relies on AngularJS, but it doesn’t matter whether it’s AngularJS or jQuery, they are all just fancy wrappers over the very same browser feature called Ajax.

I can guarantee you that the response to a request to a .js file won’t contain any Set-Cookie header.

> Does that mean that (regarding their accessibility) GET requests issued from JS are treated differently by the Browser than the ones issued natively in application code?

While there are no differences between a Javascript-generated request and other requests not generated from Javascript, the way your browser expose them to you (with callbacks) could be different. Since your question is related to your browser (webview) and not Tatoeba, I will close this issue, but feel free to ask additional questions.
