### ISSUE TITLE
Paruni (prn)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2714]
* Language name: Paruni
* Language info: https://en.wikipedia.org/wiki/Wasi-wari
* ISO 639-3 code: prn
* Public List: https://tatoeba.org/eng/sentences_lists/show/169413
* Icon: 
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Since this requester is not following the procedures described on [the wiki](https://en.wiki.tatoeba.org/articles/show/new-language-request) and haven't contacted the [Tatoeba Language Team](https://tatoeba.org/eng/user/profile/TatoebaLanguageTeam), I'm closing this issue.

Related: #2719 #2720  #2718 #2717 #2716 #2715 #2714 #2713 and a couple of others.
