### ISSUE TITLE
Khughni (sgh)

### ISSUE THREAD

**Issue by Plkmoi** [Tatoeba/tatoeba2#2721]
* Language name: Khughni 
* Language info: https://en.wikipedia.org/wiki/Shughni_language
* ISO 639-3 code: sgh
* Public List: https://tatoeba.org/eng/sentences_lists/show/169420
* Icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Gorno-Badakhshan.svg
* Requested by: https://tatoeba.org/eng/user/profile/QAzaqQA

**Comment by RyckRichards** [comment]
Since this requester is not following the procedures described on [the wiki](https://en.wiki.tatoeba.org/articles/show/new-language-request) and haven't contacted the [Tatoeba Language Team](https://tatoeba.org/eng/user/profile/TatoebaLanguageTeam), I'm closing this issue.

Related: #2719 #2720  #2718 #2717 #2716 #2715 #2714 #2713 and a couple of others.

**Comment by Plkmoi** [comment]
I sent an email.

**Comment by Plkmoi** [comment]
Not adding these languages is not about the requester but about the language and the ethnic group who speak the language.

**Comment by Plkmoi** [comment]
I can only send 5 mails in private message in a day.
