### ISSUE TITLE
How can I see a Json view of a sentence? (attempt 2)

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/tatoeba2#2746]
I cannot see how I can reopen issues, and so I am asking this question again (https://github.com/Tatoeba/tatoeba2/issues/2699), because I don't yet have an answer.

I have looked at the suggested links:
- https://book.cakephp.org/3/en/views/json-and-xml-views.html
- ExportsController

However, I still do not know how I can see a Json view of a sentence.

Can somebody give me an example of how I can see a Json view of a sentence? For example, if I want to see the Json of https://tatoeba.org/eng/sentences/show/6257510 how would I do that? https://tatoeba.org/eng/sentences/show/6257510.json does not do it.

**Comment by jiru** [comment]
What did you try so far? What problems are you facing?

**Comment by githubshrek** [comment]
I tried to make guesses as to how this Json feature works. The problem is my guesses don't succeed.

Somebody, I suppose, implemented this Json feature, so that people who want to use it can do so, but it seems completely undocumented. Hence my request for any information. Writing an API (which I suppose is what the Json feature is partly) makes no real sense unless it can be used.

If you or nobody else knows how to use it, then OK, I'll just carry on with my own implementation (which is what I'm doing). If later it is found that the two implementations do the same thing, then we can always refactor.

**Comment by jiru** [comment]
> Somebody, I suppose, implemented this Json feature, so that people who want to use it can do so, but it seems completely undocumented

It is not undocumented. The json view is documented in the Cakebook, in the link you mentioned. Besides, the ExportsController is a working controller using the json view. At this point I am not sure how else I can help you except by writing the whole code for you. But I am reluctant to do this because I don’t think it will really help you learning and become independent. That’s why I am asking you more details. You probably feel frustrated because something is not working, but really, it is probably a matter of some detail or something you overlooked. I am much willing to help you solving your problem, but only if you share your current implementation with us and you explain what’s going on in a more detailed manner than "it doesn’t work".

When you start using with CakePHP (or any other framework for that matter), I think it is common to become puzzled and frustrated when something’s not working, because you are not used to all the common mistakes and others "gotchas". My advice is to take it easy. It will get more and more easy as you gain experience. Maybe try to solve one of the [good first issues](https://github.com/Tatoeba/tatoeba2/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) for a change of air.

**Comment by jiru** [comment]
You can also look at the commit history of ExportsController:
* f63c61a665db8f7d5bdd6b2dcc67769bab377868 is the very first commit that creates ExportsController.php with the one HTML action "index"
* 1622fc6c73e999c47a14647d6c69e9a11d177ec7 is the second commit that adds the json action "add"

**Comment by githubshrek** [comment]
When I was talking about documentation, I was not talking about general Cake documentation, but rather documentation of the features available to technical users of Tatoeba, for example, if it were possible to get the Json of a sentence by going to say:

* sentence/3.json
* sentence/json/3

I would think that would be documented somewhere in the Tatoeba documentation.

I certainly am not asking you or anybody to write code for me. I've now written my own code to get a Json view of a sentence (https://github.com/Tatoeba/tatoeba2/issues/2771) which was pretty straightforward. If there _is_ already some way to see the same thing in another way, fine, I guess I'll figure out how later.

The link https://book.cakephp.org/3/en/views/json-and-xml-views.html certainly looks useful.

Thanks for your help.
