### ISSUE TITLE
278 sentences free floating...

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#2770]
Sorting the sentences_detailed download file by language shows that there are 278 sentences that have no language assigned and about 90 of them belong to nobody.

I checked a few of them and they were reported as e.g. Arabic (google translate).

How could we sanitize them? Is there a way to give the automatic language recognition script another go?

———

[Missing Language.csv](https://github.com/Tatoeba/tatoeba2/files/6394857/Missing.Language.csv)

**Comment by Plkmoi** [comment]
Can some of these be new Languages not assigned?

**Comment by trang** [comment]
I'm not convinced automatic language detection would be the answer to this problem. It's only a few hundred sentences after all, we can process them on a human level :)

- For sentences that have an owner, I think best is to simply contact the owner to ask if they forgot to set the language.
- For sentences that don't belong to anyone, this could be mentioned on the Wall and people could help identify what language it is.

Note that our process to request new languages requires that the requester creates a list with a few sentences in the requested language. So it is normal to have, temporarily, some sentences with unassigned language, because they simply cannot be assigned to any language that Tatoeba support at the moment.

**Comment by mramosch** [comment]
But being of temporary nature, do they make any sense in the weekly download files?

And similarly,  what good are the unknown languages in some user profiles?

They also show up as EMPTY fields with an additional skill level 0 field in the weekly download files...


That makes no sense, or does it?


———



![IMG_2951](https://user-images.githubusercontent.com/725445/118191692-4519e480-b445-11eb-8a9c-b432ba324914.png)


![IMG_2952](https://user-images.githubusercontent.com/725445/118191764-68449400-b445-11eb-9482-195a6444915b.jpeg)

**Comment by mramosch** [comment]
From the first 10.000.000 sentences:

              199 - (no language)
       178.214 - (no owner)
                90 - (no owner - no language)

**Comment by jiru** [comment]
> But being of temporary nature, do they make any sense in the weekly download files?

Yes it does. As Trang explained, these sentences are yet to be assigned to a new language. Since new languages are being added regularly, it is expected to have such sentences in the database. Since we export all of our sentences, it is expected to have them in the CSVs. If you don’t want them, you can simply filter them out or download per-language CSVs instead.

It seems to me that you are seeing a problem where we don’t. If this is true, please describe your problem and your use-case with more details.

> And similarly, what good are the unknown languages in some user profiles?

This looks like a different issue. Please open a new issue if it is still relevant.
