### ISSUE TITLE
git push --set-upstream-to unknown option error

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/tatoeba2#2773]
I'm trying to follow the instructions on https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-pull-requests
![image](https://user-images.githubusercontent.com/7943077/116823347-4a914800-ab84-11eb-8998-8aa130ccb51e.png)

I'm initially getting the following error on the push:
error: unknown option 'set-upstream-to'
![image](https://user-images.githubusercontent.com/7943077/116823391-89bf9900-ab84-11eb-8341-d11731b6d518.png)

I tried to get further. I don't see my branch listed as a remote branch and I don't see to have permission to do the push I am trying:
![image](https://user-images.githubusercontent.com/7943077/116823460-e58a2200-ab84-11eb-8969-5a950c8114f3.png)

Suggestions? Thanks.

**Comment by jiru** [comment]
You are right about the incorrect option `--set-upstream-to`, it should be `--set-upstream`.

About the permission error, it happens because you did not create a fork and you are trying to push your code to the main repository Tatoeba/tatoeba2. This is not how it works on Github. The right way to do this is to first fork the Tatoeba/tatoeba2 repository, then run `git clone` to create a local copy of your fork, then make your edits, then push your code to your fork repository, and from there you can create the pull request. For a more complete guide, [see this article](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo).

Since you did all your changes locally already, it would be easier for you at this point to just change the remote. First of all, create the fork of the tatoeba2 repository on Github. This will create your own repository at https://github.com/githubshrek/tatoeba2 on which you have full write access. Then, run this command:
```
git remote set-url origin https://github.com/githubshrek/tatoeba2
```

This will change what `origin` means in the commands in your screenshots. Right now it means `https://github.com/Tatoeba/tatoeba2` but you need to change it to `https://github.com/githubshrek/tatoeba2`. You can check the current URL of `origin` any time by running `git remote -v`.

**Comment by githubshrek** [comment]
OK, sorted. Thanks for your help.
