### ISSUE TITLE
Help getting Visual Studio debugging working with Tatoeba

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/tatoeba2#2783]
Up until now I've not been doing any "proper" debugging with Tatoeba; just a bit of educated guesswork and the occasional "echo". I'd now like to make my Tatoeba development life easier.

I am able to get debugging working with a different PHP application:
![image](https://user-images.githubusercontent.com/7943077/117891610-7cf32180-b2b7-11eb-9c02-1dcb803656a4.png)

For that I'm using Xampp
![image](https://user-images.githubusercontent.com/7943077/117891850-ef640180-b2b7-11eb-920f-37e6310875b8.png)

However, when I try and debug my localhost version of Tatoeba the "Listen for Xdebug" doesn't break when I run like http://localhost:8080/eng/sentences/show/7 in the browser:
![image](https://user-images.githubusercontent.com/7943077/117891725-b75cbe80-b2b7-11eb-805a-fc81ce3eb1d4.png)

I've tried changing my launch.json to set the port to 8080 since my local URL is http://localhost:8080/eng
![image](https://user-images.githubusercontent.com/7943077/117892200-9183e980-b2b8-11eb-88f6-fc562989aabc.png)

I can also "Launch currently open script" (with launch.json port set to 9000), not that I can do much with that.
![image](https://user-images.githubusercontent.com/7943077/117892820-add45600-b2b9-11eb-9bb3-e0cc0ad8cb84.png)

I'm not sure what I'm doing wrong. Thanks for any pointers!

**Comment by jiru** [comment]
I did some research since I am not familiar with xdebug.

Since the web server is running in a VM, the setup is a bit unusual and it does not work out of the box. The XAMPP instance you mentioned is not running Tatoeba, so it won’t help.

The first step is to install the xdebug PHP extension in the VM. From Git Bash, run:
```sh
vagrant ssh
sudo apt-get install php-xdebug
sudo systemctl reload php7.3-fpm
```

With this, you should already have xdebug development aids such as stack traces showing as a table.

If you want to do step debugging, you need to add a line `xdebug.remote_enable=1` by editing PHP’s INI files:
```sh
vagrant ssh
sudo nano /etc/php/7.3/fpm/conf.d/20-xdebug.ini
sudo systemctl reload php7.3-fpm
```

I am using `nano` here but you can use whatever editor suits you. The resulting INI file should look like this:
```ini
zend_extension=xdebug.so
xdebug.remote_enable=1
```

You can add any other xdebug config there. Remember to reload php7.3-fpm every time.

About step-debugging, xdebug documentation says xdebug initiates the connection to your IDE, so we need to allow the VM to connect to your host. Note that the existing port 8080 redirection works the other way around (host connects to guest), so we can’t use that mechanism. The only way I found to do this is to setup an SSH tunnel, like this:

```sh
vagrant ssh -- -R 9000:localhost:9000
```

And then leave that vagrant shell opened. This assumes xdebug uses port 9000, which is the default for xdebug 2. Since I am not using an IDE, this is as far as I went. I can only see an incoming connection from xdebug on the host whenever I load a page.

**Comment by githubshrek** [comment]
OK, thanks for the ideas. It makes logical sense to treat the vagrant host as a remote system. Anyway, I'll give it a try and let you know.

**Comment by githubshrek** [comment]
I haven't tried the ideas yet, but I'm going to close this issue since I have some new pointers. Thanks!
