### ISSUE TITLE
Unjustified log-in request...

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#2792]
https://tatoeba.org/en/users/all

Why is it that tapping on the search field on iOS/Safari always closes the keyboard and asks me to log in? From there, opening the keyboard manually proceeds normally without complaining again about having to log in.

https://user-images.githubusercontent.com/725445/118723656-f944b200-b82d-11eb-8e04-f1ac4820a6d2.mp4

**Comment by jiru** [comment]
It looks like this is an issue with Safari, not Tatoeba.

* Maybe this is the same problem: https://discussions.apple.com/thread/1849643
* Maybe this can help: https://collegefactual.uservoice.com/knowledgebase/articles/666268-site-keeps-asking-for-login-safari
* Maybe this can help, too: https://www.macworld.com/article/234462/does-safari-always-request-fresh-logins-to-sites-heres-why.html

I will close this issue because there is not much we can do about it. If you still think the problem comes from Tatoeba, feel free to reopen or comment back.
