### ISSUE TITLE
Migrate from Cakephp to Drupal?!

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/tatoeba2#2797]
I throw this out here, although I don't think it's likely to have much support, but I'm interested in at least a "what if?" chat.  I don't suppose a migration from Cakephp to Drupal is realistic unless everybody:

- who is involved in the development was enthusiastic and familiar with Drupal
- this was a project run by full-time staff who had the time needed to take on such a big task (which of course it doesn't)

Why would you want to do that? Basically Drupal is a much more robust, enterprise-level PHP framework, and so would have many technical advantages.

One of the reasons I'm interested in the project is that I knew nothing about Cakephp so it's interesting for me to learn a little about another PHP framework. I have to say that for me looking at CakePHP compared to Drupal is a bit scary. Let me put it like this: Drupal is kind of like to CakePHP what CakePHP is to pure PHP. Imagine you were an expert in CakePHP and you saw someone had built Tatoeba in raw PHP. It would be impressive and interesting, but you'd run a mile and want to get back into your cosy CakePHP universe. The pure PHP folk would not really understand what the issue was. I kind of feel a bit like that; Drupal is an order of magnitude "better" than CakePHP, in the same way that CakePHP is an order of magnitude "better" than raw PHP. 

You might think this is simply because I know Drupal extremely well and CakePHP not very well. It's true I know Drupal extremely well and CakePHP not very well at all. Nonetheless, I think I have already a good enough view of CakePHP that even if I were to use it full time for a few years, my view would not change at all.

CakePHP may have been the right choice by @trang in 2006 and has served Tatoeba very well for 15 years. Perhaps for the next 15 years it's worth stepping up a level.

**If there was any interest at all, I could probably do a little proof of concept of some of the Tatoeba functionality built with Drupal.**

(The main reason I've started to get a little involved in this project is because I think my own site, https://lingopolo.org/ could perhaps be the language learning tool which the original 2010 video https://www.youtube.com/watch?v=ac9SmJuwHqk&t=210s hints at in the "Language Learning App" circle.)

One thing which I think is interesting is that CakePHP seems much bigger in Japan than anywhere else according to https://trends.google.com/trends/explore?q=drupal,cakephp .

**Comment by trang** [comment]
Not to discourage new ideas, but I have to say that there's been a few attempts to migrate Tatoeba to something else than CakePHP and none of them came to life because it is indeed a lot of work and requires people who would want to commit to this migration for a long term (several years, not just a few months).

I understand the issue with CakePHP being not very popular and perhaps difficult to grasp for the less experienced developers, but it has been working for Tatoeba so far, it does the job. And while perhaps some of the features we implemented might have been easier to implement with Drupal, I suspect that many things would be much more of a headache in Drupal too, and we would have less flexibility than with CakePHP (just like we have less flexibility with CakePHP than with raw PHP). I however don't know Drupal enough to back up that last statement 🙂 It's just that my understanding is that Drupal is a CMS, and I don't feel that Tatoeba doesn't completely fit in a CMS.

That being said, Drupal or not, unless one day it is announced that CakePHP will no longer be maintained, I doubt we will ever migrate to something else. I also don't think it would be a good strategy to attempt a migration to a new framework when it's such a high effort and we could put all this energy into improving the current codebase instead.

**Comment by githubshrek** [comment]
I agree, that realistically, the only time that a volunteer project like this is going to migrate to another platform is if CakePHP ceases to be usable.

I don't think CakePHP is any easier or harder than Drupal or any other platform to grasp; it's just a platform with its own way or doing things, and just like any platform, the more a developer knows it, the more efficient they will become.

If we were here discussing from scratch what platform to build Tatoeba with, I think Drupal would be an excellent candidate. Tatoeba is in fact very much a CMS type of application: 

- languages, sentences and users would be 3 of the entities perfect to model with Drupal. 
- display of a single entity (in particular sentence and user) are extremely classic CMS functionalities
- display of a paged list of entities (e.g. all the different sentence lists, by language, by user etc.) are classic CMS functionalities

Regarding flexibility, I think Drupal is as flexible as you want it to be; although you probably get more out-of-the-box than you do with CakePHP (just like you get more out of the box with CakePHP than raw PHP), it does not restrict you from building what you want.

In the end, I fully agree that a migration is really not viable given the extremely high effort, for relatively small reward given that CakePHP is already doing a pretty good job.

Anyway, it's interesting to hear your perspective on it. Thanks!
