### ISSUE TITLE
"Help" link is not visible enough

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#28]
Recently, Ticket 384 was addressed, which was nice to see. However, I think an additional change needs to be made.
The subject of the ticket was "Place 'Help' and 'FAQ' links at top of page, not at bottom". The problem was that "Help" and "FAQ" links are extremely important but had very low visibility (at the bottom of the page). A change was made to put them at the top of the page. However, now they're underneath a "More" link. They were not obvious at all to me there, and I'm sure they would be less so to someone who is unfamiliar with the site.

There is plenty of room for another item on the top bar. I would suggest that a "Help" link be added between "Wall" and "More". Then under "Help" you could have "FAQ", "Quick Start Guide", "Tatoeba Wiki" and "Help" itself, though perhaps there should be some way to distinguish between top-level "Help" and the actual "Help" link itself. Maybe that lower-level link should be named something like "General Help"?

Meanwhile, I think that "Downloads" and "Tools" should remain under "More".

**Comment by trang** [comment]
I'm closing this issue because we've reorganized the menu and the footer (#947), and the help section is now placed in the footer.

@alanfgh, you've posted a comment on this topic in the homepage issue: https://github.com/Tatoeba/tatoeba2/issues/947#issuecomment-195111588. I'll reply to it here since it also replies to this issue.

> I agree with most of Trang's points, but wanted to comment on this one:
>
> "Clicking on a help link should be ideally be the last resort for users, which is why it is fine to have help links at the bottom."
>
> [...]
>
> I agree that the site should be designed so as to minimize any user's need to go to a help link, but if they end up needing it, it should be put in a place that can be found easily.

I completely agree that users should be able to easily find help whenever they need it but I prefer to focus on the approach of having more targeted/contextual help, rather than focusing on a help center.

A concrete example would be the help for the search. If a user has problem with the search, instead of having them click on "Help" in the menu (or footer), then search in our help documentation if there's an answer to their problem, we have a link right there in the search bar that leads directly to the page that explains all the search features. And maybe that article can link to other related articles that the user might want to read if they still can't find the answer to their question.

We would need this kind of help for various other features. It doesn't always have to be a link to the wiki. It could be just a tooltip, or a message that users can close once they've read it and it won't appear again. But the help would be provided based on a certain context rather than in the form of a help center.

This doesn't mean we should get rid of the help center. I think it is very important to have good, complete, up-to-date help documentation. In fact, if our help was very well designed, and organized in a way that new users can easily find information, I think it would be fine having a help link in the menu. But our help is quite messy and is in the end helpful only for advanced users.

> I speak from personal experience. When I was new to the site, I didn't know about the content at the bottom of the page until someone told me.

I can understand that the old footer was pretty small and barely noticeable but the new footer is a lot bigger and has a whole section entitled "Need some help?".

Obviously if as your very first visit on Tatoeba, you land on the Wall while there is an intense debate, then you probably won't see the footer because you won't scroll down. But I would guess that you would at some point click on the logo and be redirected to the homepage or other shorter pages, where you have more chance to notice the footer and the help section.

But anyway as I've said, I prefer to focus on contextual help. If you can remember what problems you had when you were a new user, if these problems are still relevant today but are not documented in our issues, please feel free to create issues for them.
