### ISSUE TITLE
Add language: Tigrinya (tir, 3545)

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#280]
Requested by guybrush88 on behalf of danieljtah, whose profile says that he is a native Norwegian speaker, but continues:

"I am currently learning Tigrinya. I have Eritrean friends who are helping me with the language. All sentences I add in Tigrinya have either been given to me by them or are from another reliable source."

http://tatoeba.org/ita/sentences_lists/show/3545

Flag: Eritrea, where it is the official language: https://en.wikipedia.org/wiki/Flag_of_Eritrea

**TODO**
`CALL add_new_language('tir', 3545);`

**Comment by oyd11** [comment]
How come this is still open ? (year and a half) the alphabet and all is already supported throught Amharic (which is listed) 
flag selection - Tigray or Eritean?  [ https://en.wikipedia.org/wiki/Tigray_Region ] 
there's a big list [ http://tatoeba.org/eng/sentences_lists/show/3544 ] 
please this would be so helpful as people will be able to contribute in an orderly manner when it's a language the system, I've been waiting for that before introducing the site to some native speakers.
cheers

**Comment by trang** [comment]
@oyd11, thanks for letting us know.

Adding new languages is actually rather low priority which is why this language still hasn't been added. 
We also don't monitor very closely how much a not-yet-supported language grows in popularity. We just count on users to remind us or notify us about it (like what you did here).

Knowing that you've been waiting for this language to be added and that you will bring native speakers is definitely going to make it higher priority.

**Comment by oyd11** [comment]
That's great to hear, I hope the informants will be collaborative.
Thanks @trang !
Btw::  Regarding the alphabet (ge'ez script, on both Amharic and Tigrinya)
I've seen in Georgian - there's already automatic transliteration of their alphabet [ eg: http://tatoeba.org/eng/sentences/show/459552 ] - which is real useful for 'phrasebook' like usage.

I already wrote a transliteration script for Ge'ez to a Romanization, could you guys direct me of how to possibly integrate this into the code base? I think that'll be a real big plus,

**Comment by oyd11** [comment]
[I'd base the Romanization on almost official rules 
 http://www.loc.gov/catdir/cpso/romanization/tigrinya.pdf
http://www.loc.gov/catdir/cpso/romanization/amharic.pdf ] 
With the exception of Ayin [ which in non-phonemic in Amharic but phonemic in Tigrinya, I think that's why it's left out ] I'm add Ayin

**Comment by trang** [comment]
@oyd11,

> I already wrote a transliteration script for Ge'ez to a Romanization, could you guys direct me of  how to possibly integrate this into the code base? I think that'll be a real big plus,

If you are available this Sunday (Sept 27), we can meet on IRC (server: freenode, channel: #tatoeba) so that I can guide you on that.

Otherwise, I'm not sure how much direction you'll need, but a starting point is:
https://github.com/Tatoeba/tatoeba2/blob/dev/app/vendors/autotranscription.php
This is where we have the code that takes care of transliteration/transcription.

If you need more information, just send me an email: trang@tatoeba.org.

**Comment by oyd11** [comment]
Thanks i ll look into it now; and possibly join sunday!

**Comment by tommy-3** [comment]
I think this should be discussed on the Wall first.

See this thread: https://tatoeba.org/wall/show_message/21405.

**Comment by oyd11** [comment]
what exactly should be discussed on the wall?

**Comment by oyd11** [comment]
Well, it's been a long night, I've managed to hack the transliteration
coded into php,
there it is as a stand-alone, note most of the effort was due to Unicode
stuff (which is not handled so gracefully in php)

https://ideone.com/eizWUV

The technical adding of Tigrinya as a language (no relation to
transliteration ) is attached, I *think* this is it..
So:
Added: to the ISO 639-3 -> 639-1 map : Tigrinya "tir" -> "ti"
Added : to the language-code list : Tigrinya, Tigre, Ge'ez ( iso 639-3
codes: 'tir', 'tig', 'gez' )

I've also integrated the transliteration code for the Ge'ez script,
covering Amharic,Tigrinya, Tigre and Ge'ez.
I'll try to test it and then attach.
Note - I could not yet construct the system locally - so I'm asking for one
of you guys to actually integrate and do the finial testing, I hope this
helps, it would certainly help me alot as a user. (availability of these
languages and transliterations)

I've seen some discussions about the concept of transliterations and it's
usefulness -  and whether it's possible to make automatic "quality"
transliterations, it certainly is , it might not be so obvious for an
English speaker, which is both a language with highly inconsistent
orthography, and a language with no languages close enough to provide a
reasonable amount of mutual intelligibility.

I'll address these points separately:
1. Is a quality transliteration possible?
 - Yes, the case of Georgian - the language orthography is totally
phonemic, and it's possible using a 1-1 map to produce the official
transliteration, it's better than doing it manually and flawless. It's the
same case with many (most?) languages.

2. why is transliteration needed? users of the language already know the
script don't they?
 - One very needed case is the case of close sister languages, a Pole,
might not read Cyrillic, but otherwise understand alot of written (and
spoken) Ukrainian, many such cases within the Slavonic family. Same within
Turkic, Semitic and probably many more.

Note this is not related the "phrasebook like" "anglophone" ad-hoc
transliterations.
This is a dictionary project and it's a common user story to look for
cognates and related and less related languages

**Comment by oyd11** [comment]
actually - it might make more sense for the translitaration to be
Client-side code, it should be both - simpler , lighter to run, and not be
an issue for people not interested in it, ie, part of a user configuration,
but as is, I think it's really useful

**Comment by tommy-3** [comment]
> what exactly should be discussed on the wall?

There are two points.

1. Do we really want transcriptions of Amharic and Tigrinya sentences on Tatoeba? How about Russian and Marathi? How about French and English?

2. What script should we use for transcriptions? Is there a convincing reason to use the Latin alphabet? Many Japanese, for example, would prefer transcriptions in katakana.

**Comment by oyd11** [comment]
Ok.
1. I'm not sure I understood, I thought we want all languages in Tatoeba,
at least all significant languages. French and English are already on
Tatoeba AFAIK, so is Russian.

2. This is an important point. I think this is a reason another reason to
move transliteration code into the Client possibly. I agree there should be
many-to-many transliterations (ie, not only a Latinisation of Russian, but
also a Cyrillisation of Polish for example). However, one point regarding
Latinisation - is that alot of languages have official latinisations, often
used in street signs, maps and so on. Certainly some close alphabets need
direct transliterations between them, for example, Arabic, Syrian and
Hebrew - are three Abjads, from the same language family, automatic
Latinisation - is hard - since they do not transcribe vowels,  but
cross-transliteration between them is common, standardised and useful.

**Comment by oyd11** [comment]
Ok, I miss-read point number 1.

So yes, I don't know about we, but for sure I want latin transliterations
of Tigrinya and Amharic, I wouldn't mind Russian as well, but it's not as
important. English and French already have a latinisation, which is good.
So out of my familiarity with big diaspora communities of Ethiopians and
Eritreans - I know most children immigrants and second-generation - speak
these languages but are not literate in them, I work with some of these
people, and having accessible online dictionaries for them is a thing.
Another point, for learners - learning the Ge'ez script is a longer process
than learning an alphabet (comparing to Russian for example) , since the
Ge'ez script is a syllabary (like Katakana) and not an alphabet (I've could
more or less read Cyrillic after a day of introduction, whereas reading
Ge'ez took me a few month of practice)

**Comment by ckjpn** [comment]
I think what tommy_san thinks needs to be discussed is partially whether we really even want to have transliterations on the website with the exception, perhaps, of languages that are just very, very hard to read.

The following is somewhat my feeling on the topic, omitting lots of details.

I have a feeling that we don't need to add transliteration for any language that is written phonetically, assuming that the number of "letters" is not so great.  Even then, I wonder if it's really necessary.  We should expect people who are going to contribute by translating from certain languages to have some basic fluency.  As I understand it, the Tatoeba Project's primary aim is to collect sentences and translations in various languages, of a high enough quality that other developers can take the data that is exported and use it in other projects.

Of course, the Tatoeba website can be used by students of languages, but that's not the primary aim.  At this time, at least for the English and the Japanese data, there are really too many poor sentence examples for tatoeba.org to be considered a safe and efficient way to study those languages. If we make the website too accessible to low level students, we may actually be doing them a disservice since they may assume that what they are studying is accurate.  It's bad enough to learn something that is accurate and then forget it.  However, it's worse to spend time learning something that isn't accurate, thinking that it is.

** This is related, but maybe slightly off topic. **

Ideally, all sentences would be contributed by native speakers, but that will probably never happen and is likely not the way some people involved with the project feel.  However, if this were the case, then contributors could feel confident that what they were reading in their non-native language was good.  They could be accurately learning a lot about that language as they are translating.  Not only would they be learning as they translate, they would not be embarrassed by translating a sentence that wasn't correct. It's very easy, often, to translate the intended meaning of an inaccurate sentence, but it can be a bit embarrassing to do so since it implies that you don't understand the language well enough to know that the sentence wasn't good.  When you translate a bad sentence, it sort of implies that you consider it a good sentence, which is sort of like adding your "stamp of approval."

**Comment by oyd11** [comment]
Ok @ckjpn and @tommy-3 , I have reviewed the Project Goals (which I haven't re-read since 2011 till now, I assumed it is "just" a sentence dictionary catering for people who want to use a sentence dictionary, not only for people who are interested to build the corpora), if you can redirect me the the project goal, I'll gladly review them, the "closests thing I found is the statement video, from 2010, Goals might have changed without my awareness [ https://www.youtube.com/watch?v=ac9SmJuwHqk ], so please do update if I'm to be more active now in the project.

As a dear friend once said - if there's anything worth debating, it's gotta be Language-Policies and Football. Here we go.

Firstly, I think transliterations really help the "interconnectivity" of languages being "complete graph" connectivity. There seems to be an ambiguity here by what I and I think other people who implemented transliteration functionality have in mind (suggested by the "English-French" transliteration mentioned above) - Eg. no "ad-hoc" translitarations such as  "Excusez-moi  -> "eck-SKEW-zay MWAH" [taken from http://wikitravel.org/en/French_phrasebook]  - Such *transcription* systems might be implemented in a "phrase-book" application built above the Tatoeba corpora (if any wishes to), I'm guessing some English speakers are used to such transcriptions, hence the ambiguity. 
but rather transliterations between different alphabets - representing the *same-symbolic information* in *different scripts*, favourably - not a *phonetic* but a-grapho-morphemic one (where each graphic symbol on one-system corresponds to one graphic symbol in the other system)

 > "Tatoeba website can be used by students of languages, but that's not the primary aim. "

 What is the main aim then? I think excluding the actual use of Tatoeba as a look-up dictionary - would be counter-productive.
 Ie. such a layer/user-interface - where the Tatoeba corpora are being used as dictionaries (for learners or otherwise curious people)  -  is needed. Are you suggesting such a use-case would be a separate layer/site to the "sentence contribution" site? What would be left as a design goal for the "main" Tatoeba site?
 That's like, if to take an analogy with Wikipedia - to have a different user-site for "reading" Wikipedia and for "contributing" to Wikipedia, which would slow people down and prevent many people from intuitively contributing/editing/commenting.
 
Back to the actual usefulness of transliterations (again not "tourist transcriptions"), I think it's best to turn to actual use-cases rather than features, let's start with "User Stories":
See whether firstly - do my stories make sense, secondly - I think the addressed population should comment about the usefulness or necessity of that.

Please present any user-story or aspect where having transliteration code is a minus.

Story 1: Curiosity: 

Especially for related languages:
A Hebrew speaker wonders "how close is Amharic to Hebrew" (two Semitic languages), in some random (or not) list, sees the phrase "I'm hungry" -
"ራበኝ" - looks like random noise to them, while a transliterated "rabäñ" rings a bell, like Hebrew (ra'ev, "רעב"), and vice-versa, gradually the speaker becomes aware of some cognate distance to the language. This is valid whether or not language are related, "how is this said in lang X" should be easy, regardless of their choice of transcription.

 Story 2: Sister-languages should be accessible:

 Some native-like-speakers of Spanish - might be interested to see the French or Italian translations for sentences they're looking for (in whichever other language they might be learning, or looking for a more idiomatic translation for something). They might not actively be "learners" of French or Italian, but they like seeing and getting a feel of what's similar and what's dis-similar. They might occasionally translate some sentence *into Spanish*  from another language, their certainty of the meaning of the sentence (from the Other language, let's say they're learning Finnish, so from Finnish) - is re-enforced by seeing the Italian / French translation (let's say their's already an English translation which they speak) 
 
 Now: Languages and Alphabets are separate , while all the Latin language are written in the Latin script (AFAIK), this is not the case with Turkic or Slavonic, and surely with more language families. 
 A Turkish speaker might be interested to see the Kazakh and  Tatar translations  [see: alot of sentences are close by https://tatoeba.org/eng/sentences/search?query=&from=tur&to=kaz] ; the user might not read Cyrillic, and might not wish to actively learn these languages or alphabet; Yet, situations such as described with the Spanish speaker is desired.
 Some Turkic languages switched from Cyrillic to Latin in the early 1990s (Turkmen, Uzbek), some are considering a transition (Tatar), there might even be a situation in a few years where one of these languages officially has switched, and native speakers would prefer to use read  transliteration .

 A Czech speaker might be interested to see Bulgarian and Ukrainian  (Latin) transliterations for the same reason.
 
 Yiddish - should be accessible for  Dutch/Danish/German speakers; again, the accessibility and exposure of data - can both help the project spread to more speech-communities  (hearsay through these users), help the speakers get familiar with a sister language, thus enable *more-connectivity* between language nodes. It's also quite reasonable for a user to want to see a list of sentences in "All-Germanic-Languages" for example.  (And be able to read it). This shouldn't require a 'sister project', and if it will - I suspect that sister project will become the main interface to Tatoeba eventually. This is only one "feature", but the trend you suggest - making Tatoeba not optimal as a daily use (phrase) dictionary, will extend to other usuability issues.

Berber languages  (Tamazight) )- and Berber literacy ::  Berber language communities are currently divide between Latin script and Tifinagh (official in Morocco), which Berber language is currently presented in Tatoeba is unclear to me (codified "ber" a "collective" iso code) - there's communities with millions of speakers (codes "kab", "rif" , "tmh").
Tifinagh in now encoded in Unicode, and is real alphabet, transcribable to Latin and vice-versa. As Berber is one of the populations currently being more and more represented online (via mobile connectivity, social factors and emigrations) - these communities should have accessibility to each-other's dictionary.
 
 Hopefully - this should not encourage someone to *contribute* in a language they don't speak, and I don't see how transliteration promotes that.; that's a social issue and should be delt with socially, eg, a French speaker who's far from fluent in Spanish - shouldn't con
 
 Story 3: Non-literacy of Native-Speakers
 
 Example: There are over 120,000 "Ethiopians" living now in Israel, about 40,000 are "born in Israel", alot of them are fluent in either Tigrinya or Amharic, as in speak it at home and in some social context, however, most of them, especially the ones born in Israel and the ones who emmigrated under the age of 6, cannot read the Ge'ez script.
 [ https://en.wikipedia.org/wiki/Ethiopian_Jews_in_Israel ],  alot of them - are both: 1. able to validate Amharic sentences in the dictionary, 2. are quite interested to read especially proverbs and expressions in their language 3. some start learning the alphabet in their 20s. 
 Some of them are my personal friends, and they were helping me to learn the language - however - when they saw I'm learning how to read - their common reaction was "are you nuts? that's so hard! whatever for? I'll teach you more conversation, you don't need that stuff, that's only for reading Bible"
 
 Story 4: Various "literary" needs :
 
 A Polish speaker, who's also a Yoga practitioner, notices similarities between Polish and Sanskrit used in practice, from counting, to names of poses,
 While not really bothering to learn the Davanagari script - while "" जीवाति , वृत् ,  कोण , त्रिकोणासन " - looks to them like line noise, the translitaration "Jīvāti, vr̥t, kōṇa, trikōṇāsana" are pretty clear!

**Comment by tommy-3** [comment]
I created a thread on the Wall for this topic.
https://tatoeba.org/wall/show_message/24290

**Comment by ckjpn** [comment]
> What is the main aim then?

So the concept is : we gather a lot of data, try to organize it, ensure it is of good quality and make it freely accessible, downloadable and redistributable, so that anyone who has a great idea for a language learning application (or a language tool) can just focus on coding the application and rely on us to provide data of excellent quality.

Trang, 2009-11-28:

**Comment by oyd11** [comment]
@ckjpn : What is this random quote? Does it have to do with the aim of the project (it sounds to me like a strategy not a goal)
Does it contradict catering to "the students of languages" or does it support it? And what are the best means to "gather a lot of data", "organize it" and "make it accessible"?
Again, all public presentations of Tatoeba present it as a project for learners 
[ WP article starts "Tatoeba.org is a free collaborative online database of example sentences geared towards *foreign language learners.* " , the getting on board video [ https://www.youtube.com/watch?v=ac9SmJuwHqk ] , the application to Mozilla Drumbeat " it’s easier for amateurs to translate sentences rather than words, and thus makes building a database accessible for more people. (Alan Simon)" ]
 
Again, how is having *transliterations* interfering with gathering data, organising it and ensuring the quality, I argue it helps in most cases. 

To phrase things clearly - are you trying to stress out this is a *data-oriented* project? This is clear. The project needs some technological background and policies to support this data collection and quality assurance. It also needs a community, and by the original project statements I understand the attracted community is the general population of users who use Tatoeba as a phrase dictionary. The vast majority of the of them - language learners. For the feedback loop to be effective - contribution, correction, cross-linking - we need a large community, and we need that language learning community to be on the same site and interface as contributors of sentences (the "wikipedia" model). If having language learners around is secondary, I suggest  forking the project into project where language learners are "first class" users (ie, not users of some post-processed phrasebook app without direct review manipulation of the data).

This seems to me like a "Wikipedia" vs "Nupedia" like policy, which @ckjpn and @tommy-3 seem to hold. If this is the majority view on Tateoba - please update the public info on it (main page, introduction, faq, video), since this is a big shift and not just an issue of whether Transliteration's considered harmful.

**Comment by ckjpn** [comment]
I'm not really trying to debate anything. I was just answering questions.

**Comment by trang** [comment]
I've created this issue for the question of having or not transcriptions in Tatoeba: #784.

**Comment by trang** [comment]
@oyd11, Tigrinya is now added:
https://tatoeba.org/eng/sentences/show_all_in/tir/none/none/indifferent

The sentences are not indexed yet so you won't be able to find results if you try to search them from the search bar. They should be indexed on Sunday.

**Comment by oyd11** [comment]
hura!!1
