### ISSUE TITLE
Rohingya (rhg)

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2932]
* Language name: Rohingya
* Language info: https://en.wikipedia.org/wiki/Rohingya_language
* ISO 639-3 code: rhg
* Public List: https://tatoeba.org/en/sentences_lists/show/170261
* Icon: ![rhg](https://user-images.githubusercontent.com/221850/168808694-fd1bd941-2136-4594-afcf-0fe09b2bf4aa.png)
* Requested by: https://tatoeba.org/en/user/profile/lbdx, https://tatoeba.org/en/user/profile/TWB

**Comment by soliloquist-tatoeba** [comment]
The Rohingya people have an ethnic flag. 

https://en.wikipedia.org/wiki/Rohingya_flag
https://www.facebook.com/RohingyaFC/photos/1187833701386024
https://www.youtube.com/watch?v=70cf704mFNw

As they have also recently suffered from [ethnic cleansing](https://en.wikipedia.org/wiki/Rohingya_genocide), I suggest adopting a similar policy as that of Uyghur and using it instead of a blank icon.

Also, if the text direction were set to auto, sentences written in [different scripts](https://en.wikipedia.org/wiki/Rohingya_language#Writing_systems) would all display correctly.
