### ISSUE TITLE
The "Browse audio" page takes very long to load

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2946]
**Story**

We're displaying the full list of sentences with audio and we have over 1 million audio recordings.

From my attempt to open just now the [Sentences with audio](https://tatoeba.org/en/audio/index), it took 43 seconds.

![image](https://user-images.githubusercontent.com/221850/171013679-be218735-721b-47a4-92ea-85a3d1bce1d4.png)

**Idea**

We limited the number of results to 1000 items on some other pages (Browse by language, contributions logs...). This was a decision we made in https://github.com/Tatoeba/tatoeba2/issues/1353#issuecomment-476564743. We should do the same for the audio page.

**Comment by ckjpn** [comment]
Occasionally, I get the "under maintenance" error message that we get for time-out errors, which I think means it sometimes takes over 60 seconds. I'm not sure what the time-out setting is.

I suspect this may be related to the newly-implemented "multiple audio" feature.

https://tatoeba.org/en/audio/index
This took 43 seconds to load the last time I loaded it.

https://tatoeba.org/en/audio/of/CK
This took 57 seconds to load the last time I loaded it.

**Comment by ckjpn** [comment]
Since this problem didn't exist before the new way of handling audio files was implemented, I still would assume that it has something to do with that, unless some other change was made at about the same time.

Today, I noticed this, perhaps it's related to the problem.

<img width="379" alt="Screen Shot 2022-06-06 at 8 47 22" src="https://user-images.githubusercontent.com/7934273/172075699-ba36cc8b-0a61-4b50-a881-e9a7316f4c4d.png">

**Comment by trang** [comment]
@ckjpn The new feature for multiple audio definitely made it worse, but it was already very slow before.

The call to raw.githubusercontent.com is unrelated to this. Might be some add-on on your side?

**Comment by ckjpn** [comment]
I know it was slow before, but often it loaded in much less than 30 seconds, and I don't remember it getting the time-out error before.  I could be wrong, of course.
