### ISSUE TITLE
Sentence language is stuck and audio returns 404

### ISSUE THREAD

**Issue by PineappleSnackz** [Tatoeba/tatoeba2#2962]
**To Reproduce**
1. Go to sentence [#8095084](https://tatoeba.org/sv/sentences/show/8095084)
2. Click on the flag icon.
3. Attempt to change the language. (given you have the permissions to do so)
4. Action fails.
(5. Attempting to listen to the audio returns 404)

**Expected behavior**
The language of the sentence should change when changed.

Attempting to listen to the audio should not return 404.

**Screenshots**
![screenshot](https://i.imgur.com/rXJUl9I.gif)
![screenshot2](https://i.imgur.com/RerFtH4.gif)

**Comment by trang** [comment]
The audio on this sentence can probably be deleted. It's one of the sentences for which audio was not properly migrated, and was skipped. Just for reference, this is the full list of sentences for which the audio migration was skipped:

> Only 998880 of 998888 audio files were successfully migrated:
>  - Skipped sentence 5507673: missing audio file: /var/www-audio/sentences/kab/5507673.mp3
>  - Skipped sentence 7193075: missing audio file: /var/www-audio/sentences/ber/7193075.mp3
>  - Skipped sentence 7193076: missing audio file: /var/www-audio/sentences/ber/7193076.mp3
>  - Skipped sentence 8172048: missing audio file: /var/www-audio/sentences/kab/8172048.mp3
>  - Skipped sentence 8271732: missing audio file: /var/www-audio/sentences/kab/8271732.mp3
>  - Skipped sentence 8095084: missing audio file: /var/www-audio/sentences/kab/8095084.mp3
>  - Skipped sentence 8101865: missing audio file: /var/www-audio/sentences/kab/8101865.mp3
>  - Skipped sentence 8103843: missing audio file: /var/www-audio/sentences/kab/8103843.mp3

I had sent this list for @ckjpn to check, but perhaps he forgot. I will ping him again.

Once the audio is removed, you should be able to change the language. The fact that you cannot change the language is (probably) due to the restriction that we have, where sentences with audio cannot be edited.

**Comment by ckjpn** [comment]
I've deleted the audio link on this sentence.

When I uploaded the original audio file for it, even though it was in English, I assume that it must have been placed in the /kab/ directory for the uploading script.

Skipped sentence 8095084: missing audio file: /var/www-audio/sentences/kab/8095084.mp3

**Comment by trang** [comment]
The sentence was switched to English and the audio was removed so I'll close this issue :)
