### ISSUE TITLE
Experimental options >> Display sentences with the new design has been set as the default for new accounts.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2972]
The Experimental option "Display sentences with the new design" has (accidentally?) been set as the default for new accounts.

This means that new members may not realize that they aren't getting the fully-functioning version, and may find it confusing when existing members try to help by explaining things about the UI.

I think it would be better to revert this to the way it was. That is, unless the displayed message is no longer true, in which case that option should be moved out of the experimental options.

"Display sentences with the new design. Note that some features are not yet implemented in this new design but are coming soon."

**Comment by Yorwba** [comment]
This change was deliberate: f08e0bbf3fa77663490ac89b4154e01b34eb5203

If new users don't notice anything wrong with the new design, that's mission accomplished, I guess. The confusing parts of the old design should be fixed in the new design, so fewer explanations should be necessary. Did you actually encounter a situation where you had to explain the UI to a new user and they didn't understand your explanation because you were using the old design?

**Comment by trang** [comment]
We should move the "Display sentences with the new design" option out of the "Experimental" section, or at least remove the part that says "Note that some features are not yet implemented in this new design...". That part is indeed no longer true.
