### ISSUE TITLE
Quotes aren't escaped in TSV exports

### ISSUE THREAD

**Issue by Sobsz** [Tatoeba/tatoeba2#2973]
As part of maintaining my [CC0](https://tatoeba.org/en/sentences_lists/show/169276) list, I downloaded a tab-separated export of it. It contains [sentence #10883689](https://tatoeba.org/en/sentences/show/10883689), which has an ASCII quotation mark at the beginning and a fancy Unicode one at the end. The Python CSV parser interpreted the former as the start of a multi-line quote, causing it to fail to parse all the sentences between it and [sentence #10903586](https://tatoeba.org/en/sentences/show/10903586). The same issue happens with the `Sentences (CC0)` file from [the Downloads page](https://tatoeba.org/en/downloads).

[According to Wikipedia](https://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules):
> Fields with embedded commas *{tabs in our case}* or double-quote characters must be quoted.
> `1997,Ford,E350,"Super, luxurious truck"`
> Each of the embedded double-quote characters must be represented by a pair of double-quote characters.
> `1997,Ford,E350,"Super, ""luxurious"" truck"`

**Comment by jiru** [comment]
Thank you for letting us know about that.

I think we'd rather not change the file format of our exports because it could break current implementations that rely on it.

Since there is no standard definition of the file format TSV/CSV, it is hard to know who gets it "right". That's why most CSV readers allow tweaking the field separator character, quote character (if any) etc. I suggest you try changing your implementation so that it can read the file correctly. We don't use quotes in our exports, only tabs as field separator. There should be no tabs in the fields, so no need to use quotes.

By the way, there is an [existing implementation in Python](https://github.com/LBeaudoux/tatoebatools), it might help you achieve what you're trying to do.

**Comment by Sobsz** [comment]
Alright, that's fair enough. I'll copy the `quoting=csv.QUOTE_NONE` from the repository you linked.

Would it be possible to add a note about this quirk on the download pages?

**Comment by jiru** [comment]
Good idea. We could add a message telling about the specifics of our CSV format. Pull requests are welcome. 😉

I'll close this issue then.
