### ISSUE TITLE
Ability to filter sentences in lists by language

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2977]
**Story** or **Context**
Currently, when users want to browse a list with sentences in different languages, they have to open an advanced search to apply a filter and search for sentences in a specific language, and this might take longer than expected to see only a given language. I came up with this thought while browsing this list: https://tatoeba.org/it/sentences_lists/show/170280

**Idea**
To improve this page, there could be a dropdown menu above or below the "show translations" one, so users could be able to filter sentences by language directly from the page of the list.

**Comment by ckjpn** [comment]
An additional advantage would be that advanced searches are limited to 1,000 results.  There are no such limits on lists.

@Guybrush88
You could do this kind of filtering offline using the weekly exported files if you know how.

**Comment by vinkaks** [comment]
Implementing the language filter seems very straightforward and non-invasive. It will however require implementing some minor interface changes and creating related translation for the "action". I tucked away the filter by language option under "actions" since the title bar is already full of other buttons and the list title itself. Still need to add some margin between the two actions.

![tatoeba list filter 1](https://user-images.githubusercontent.com/21044267/183522335-389ce479-69da-4c50-8581-8a8a0d901492.png)

@jiru can I do a PR on this enhancement?  

BTW: If a language that does not exist in the list is chosen as a filter, this results in an empty result. In such a case maybe the default "List is empty" notice may be a little confusing? 

![tatoeba list filter 2](https://user-images.githubusercontent.com/21044267/183523879-3b31da94-875b-4d4d-af0e-388f61a09b30.png)

**Comment by ckjpn** [comment]
Perhaps a message that says that the selected "filter by language" request gets no results would work better than "This list is empty."

**Comment by Yorwba** [comment]
I think we should try to keep the interface consistent across different parts of the website.

Filtering sentences by language and choosing which translations to show is already possible on the page listing all sentences in a given language (e.g. [all sentences in Vietnamese](https://tatoeba.org/en/sentences/show_all_in/vie/none))
![sentences in Vietnamese](https://user-images.githubusercontent.com/6555947/183746079-155cced7-46d6-414c-8f38-2f78d3412699.png)

The page listing a user's sentences in a given language displays a message "`$user` does not own any sentences in `$lang`" when there are no results. (e.g. [I don't have any Bengali sentences](https://tatoeba.org/en/sentences/of_user/Yorwba/ben))
![Yorwba does not own any sentences in Bengali](https://user-images.githubusercontent.com/6555947/183747030-5c1ca806-f0fd-48b2-acb5-9e8d8460330a.png)

@vinkaks Maybe you could make your implementation work similarly to those two pages.

In general, when you've written some code and would like some feedback, opening a PR is never wrong.

**Comment by vinkaks** [comment]
@Yorwba thank you for the style and layout pointers. I'll do a PR

**Comment by vinkaks** [comment]
Managed to find a "Only sentences in" key in the translation files.

![tatoeba](https://user-images.githubusercontent.com/21044267/183990718-247058c8-58f8-499b-9ea3-51fc6dff9dd4.png)

@Yorwba I think the grammar will be off if we try to use "$user does not own any sentences in $lang" because in many languages including English only people can "own" things.

If the current screen is judged to be worth changing, a separate PR can be done.

**Comment by jiru** [comment]
> Managed to find a "Only sentences in" key in the translation files.

I am not sure I understand what you mean, but feel free to create new translatable strings! 😸
