### ISSUE TITLE
Strange formatting when displaying Aiji's LIst 170670

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2994]
https://tatoeba.org/en/sentences_lists/show/170670
This doesn't seem to be happening in other lists.

I wonder if we need to filter certain allowed characters in the titles.  Perhaps that's the cause.

<img width="1021" alt="Screen Shot 2022-09-23 at 15 44 26" src="https://user-images.githubusercontent.com/7934273/191906099-d8257cc7-9088-4985-bb5c-4b9e065805bf.png">

**Comment by Yorwba** [comment]
This happens because the `edit-list-name` element [is displayed even when you only have permission to add sentences](https://github.com/Tatoeba/tatoeba2/blob/51060d800dcd36e5c45669dad077e302e3dba741/src/Template/SentencesLists/show.ctp#L156), but the contents are undefined if you don't actually have permission to edit the list.

So it's not related to special characters in the title (which would've been a security issue).

**Comment by ckjpn** [comment]
This seems to be a problem with all collaborative lists.
I don't think this was the case before, so I think perhaps some code needs to be reverted.

https://tatoeba.org/en/sentences_lists/collaborative

Why does that character indicated by the "cause?" in the above image appear?

**Comment by Yorwba** [comment]
This is now fixed.
