### ISSUE TITLE
Free abandoned sentences

### ISSUE THREAD

**Issue by CangarejoAsul** [Tatoeba/tatoeba2#3022]
Would it be possible to make orphaned all sentences owned by users that have been inactive for more than 365 consecutive days? The original owner and sentence would be listed in the sentence history, so there’s no licencing problem. That way anyone would be able to improve those sentences.

**Comment by alanfgh** [comment]
I'm having trouble understanding what existing problem this would solve, but I can think of many new problems it would create.

### What problem is this trying to solve?

Sentences with errors can already be corrected by corpus maintainers. Advanced contributors can leave tags on them indicating that they think the sentence should be checked or deleted. And any member can leave comments on them requesting corrections. So I don't see what is prompting this suggestion.

### What problems will this create?

(1) Sentences have always been contributed with the implicit understanding that they would be credited to their author forever unless that author chose to abandon them or violated a rule (for instance, copying copyrighted sentences onto the site) on a scale that made all of their sentences untrustworthy. Changing that rule arbitrarily at a later date is a breach of contract that would make the community furious and probably cause many to leave it for good. So it seems to me like a really problematic idea for both ethical and pragmatic reasons.

(2) Ownership of a sentence indicates some level of trustability because it was written or adopted by someone who thought it was worthwhile. Suddenly erasing that marker of trust for every contributor who had not visited the site within a year would dump large quantities of sentences into the "untrusted" bucket even though they once had been trusted.

(3) People should stay active at Tatoeba because they want to, not because they feel coerced to do so in order to defend ownership of the sentences they wrote or adopted.

(4) Orphaning great masses of sentences leaves them open to vandalism by any contributor.

Could you please tell us more about what prompted your suggestion?

**Comment by CangarejoAsul** [comment]
I made this suggestion because I’m used to Wikipedia, where everyone can edit everybody else’s contributions.
