### ISSUE TITLE
Add Ho (code: hoc) language as UI language

### ISSUE THREAD

**Issue by Prasanta-Hembram** [Tatoeba/tatoeba2#3024]
Hello, Me and my friends wants to translate tatoeba UI in [Ho language (code: hoc)](https://en.wikipedia.org/wiki/Ho_language), but the language as an option for request isn't available in Transifex, what needs to be done in order to contribute for Ho .

Thanks

**Comment by jiru** [comment]
Hello, thank you for willing to help translating Tatoeba’s UI.
It looks like Transifex does not support the Ho language.
Here is the [list of languages available on Transifex](https://explore.transifex.com/languages/).
I think you need [ask Transifex to add](https://help.transifex.com/en/articles/6208588-how-do-i-add-a-new-language) that language.
In the meantime, if you wanna start translating already, we could repurpose another existing language to be used as Ho language.

**Comment by Prasanta-Hembram** [comment]
Thank you so much @jiru .
>I think you need [ask Transifex to add](https://help.transifex.com/en/articles/6208588-how-do-i-add-a-new-language) that language.

I think It will take time to add language, will apply soon. Translators already completed a significant portion of translation.
>In the meantime, if you wanna start translating already, we could repurpose another existing language to be used as Ho language.

Can we use Erzya (myv)

**Comment by jiru** [comment]
@Prasanta-Hembram I set things up so that you can use Erzya (myv) and it will appear as Ho in https://dev.tatoeba.org. I sent you an invitation on Transifex, so you should be able to start translating already.

As for the Ho language name in the UI language dialog, I copied `𑢹𑣉𑣉 𑣎𑣋𑣜` from Wikipedia, please confirm this is fine. I don’t have fonts for the script so I can’t even see what this looks like. Could you recommend a font by the way?

Note that you could run into issues with pluralized strings. Every language has its own plural rule that is used to translate pluralized strings. For example, "{n} result" and "{n} results" are two versions of a string depending on the value of **n**. English has two versions, one for n=1 (singular) and one for n≠1 (plural). Some languages have only one version (no plural), while some others have three versions or more (multiple plurals). So each language has a rule (a formula) to find the correction version depending on **n**. I can see Transifex set the language plural formula for Erzya as `(n != 1)`, which is the same as English. I don’t know what is the correct formula for Ho, but if it is different, we might wanna use a different temporary language whose plural formula matches Ho’s.

**Comment by Prasanta-Hembram** [comment]
>I set things up so that you can use Erzya (myv) and it will appear as Ho in https://dev.tatoeba.org/. I sent you an invitation on Transifex, so you should be able to start translating already.

Thanks alot @jiru for adding Ho language to dev. My Ho friend Ganesh was very happy. :-) (Unfortunately, he is not in Github)

>As for the Ho language name in the UI language dialog, I copied 𑢹𑣉𑣉 𑣎𑣋𑣜 from Wikipedia

Needs some corrections, Ganesh told me it should be  𑢹𑣉𑣉 𑣎𑣁𑣋𑣁𑣜

> Could you recommend a font by the way?

Noto Sans Warang Citi -- Use this google font (https://fonts.google.com/noto/specimen/Noto+Sans+Warang+Citi)

> I don’t know what is the correct formula for Ho

Santali and Ho are very similar in language and grammar rules, I discussed with Ganesh and he confirmed. So, the plural rules for Ho are same as Santali : Plural-Forms: nplurals=3; plural=n==1 ? 0 : n==2 ? 1 : 2 

> but if it is different, we might wanna use a different temporary language whose plural formula matches Ho’s.

If there are languages having same plural rule as Ho, that would be fantastic (Still searching for a match ). But, though we are using this for temporary purpose, we can stick to Erzya (Ganesh told it would be ok, if their plural form is incorrect temporarily). If we don't get a match then, it is totally ok. Translating plural forms later is not that hard and Ganesh is ok with it.

**Comment by Yorwba** [comment]
> Noto Sans Warang Citi

This font is included in the [`fonts-noto-core`](https://packages.debian.org/bookworm/fonts-noto-core) package on Debian, and most other Linux distros have similar packages bundling most or all Noto fonts. (For the space-constrained, Unifont also has Warang Citi coverage IIRC, but it looks rather ugly.)

> Plural-Forms: nplurals=3; plural=n==1 ? 0 : n==2 ? 1 : 2

We have one other UI language with this plural rule, Northern Sami (`se`). Transifex also supports Southern Sami (`sma`), which based on a quick look at Wikipedia I think should have the same plurals.

**Comment by jiru** [comment]
Thank you @Yorwba! Since you did not start translating yet, I moved from using Erzya (myv) to Southern Sami (sma).

@Prasanta-Hembram I have invited you to the (fake) Southern Sami team on Transifex. As team coordinator, I think you can freely add members to that team.

Please confirm that adding Ho translations on Transifex make them appear correctly on https://dev.tatoeba.org and I will close this ticket.

**Comment by Prasanta-Hembram** [comment]
Thank you @Yorwba and @jiru, I will soon notify Ganesh and other translators to start the work soon. I have translated some strings, but still they are not live, will update here after they will show in dev.

**Comment by Prasanta-Hembram** [comment]
@jiru It's more than 8 hour, still translations not showing in dev.

**Comment by jiru** [comment]
@Prasanta-Hembram There was a problem indeed, sorry. It should be fixed now. :+1:

**Comment by Prasanta-Hembram** [comment]
Thanks @jiru It is working now. Warang Citi script is being displayed as expected.

**Comment by jiru** [comment]
Awesome. I will close this ticket now, good luck with the Ho translation! When it will be more or less complete, you can open a new ticket to ask for enabling Ho on tatoeba.org.

By the way, I installed the font and I can see Warang Citi now. It looks beautiful! ✨
