### ISSUE TITLE
Tumbuka (tum)

### ISSUE THREAD

**Issue by DJ-Saidez** [Tatoeba/tatoeba2#3045]
* Language name: Tumbuka
* Language info: https://en.wikipedia.org/wiki/Tumbuka_language
* ISO 639-3 code: tum
* Public List: https://tatoeba.org/en/sentences_lists/show/171249
* Icon: ![image](https://user-images.githubusercontent.com/70669145/226407310-d44b7a7d-50d4-44d5-b491-c977d445b4b3.png)
* Requested by: https://tatoeba.org/en/user/profile/Tumbuka_Arch

**Comment by Yorwba** [comment]
The flag of Malawi is already used for Chichewa (as you can see e.g. on Tumbuka_Arch's profile) so we'll need to distinguish Tumbuka somehow, e.g. using a regional flag, or using the ISO code if there is none.

**Comment by DJ-Saidez** [comment]
Requester let me know that the Malawi flag should be used for both languages and that there is no regional flag. I'll add ISO codes to the flags for both languages, unless you have another idea.

**Comment by Tumbuka-Arch** [comment]
There are no regional flags in Malawi, instead only the national flag is being used. Adding ISO codes to the flags will be helpful to distinguish the two languages.

**Comment by trang** [comment]
I've opened a pull request for this since this has been stalling for long enough.

For the language icon, I've used the default design (black-on-white ISO code) as it was just quicker to craft, to not drag this language request longer. We may update the icon some time later to use the flat of Malawi.

@Yorwba, if you won't have time to do a Tatoeba update next week (July 25), I will take care of it. 

@Tumbuka-Arch, sorry for the long wait. Thanks for your patience 🙂
