### ISSUE TITLE
Display recommended tags in the sidebar

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#306]
Consider displaying recommended tags (e.g., "@delete") in the sidebar. It may make sense to display them only for advanced contributors.

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on the 1st Tatoeba day
► https://tatoeba.org/eng/wall/show_message/22968#message_22968

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on Tatoeba Day #3 (2015-07-11 06:27):
https://tatoeba.org/eng/wall/show_message/23393#message_23393

**Comment by ckjpn** [comment]
Perhaps, instead of "recommended tags" such as @delete or @change you could have just one button called "report" or "problem item" or something like that.  I've seen this kind of button on other websites, so members might be accustomed to this idea. 

You could then have a page similar http://en.wiki.tatoeba.org/articles/show/special-links-for-corpus-maintainers or instead of this page.

You have already created a substitute for the OK tag, so this type of button might fit in well with the user interface.

**Comment by RyckRichards** [comment]
I'd like all tags being showed in the sidbar - numbers, present, 1st Person, etc... I think we would have to "teach" Tatoeba how to recognize them, i guess...

**Comment by trang** [comment]
@RyckRichards, I've set this back to "pending" because it needs more specifications.

The fact of adding tags in the sidebar may not be the best solution for the problem you want to solve.

**Comment by RyckRichards** [comment]
I see! =)

**Comment by ckjpn** [comment]
Perhaps this isn't needed since we already have autocomplete for tags.
All someone has to do is start typing the desired tag.
For "@delete", it shows up on the list after typing "@" which isn't much effort.

Note that if some of the @ tags were deleted, then most, if not all, the @ tags people needed would be shown by just typing this one character.

Here are @ tags that are likely unneeded.

@check translation  (covered by @check)
@wrong translation (covered by @check, since this requires looking at comments to know which language pair don't match)

@wrong transliteration  (perhaps obsolete, now that these can be edited)
@duplicate (obsolete since we have a duplicate-merging script always running)
@check copyright (covered by @possible copyright infringement)
@change punctuation (covered by @change)

![screen shot 2016-01-03 at 10 08 32](https://cloud.githubusercontent.com/assets/7934273/12076862/b2498b64-b202-11e5-86c8-c695aabb4f9e.png)

**Comment by trang** [comment]
I'm planning to close this issue because it doesn't describe any problem and it is unclear what criteria we would use to consider that a tag is recommended.
