### ISSUE TITLE
It's taking a long time to submit comments.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#3066]
It's taking a long time to submit comments.

See the wall.

https://tatoeba.org/en/wall/show_message/39986#!#message_39986

**Comment by jiru** [comment]
I had a look at the server logs, there are no related slow SQL queries logged. I think it’s related to the delivery of email notification. I noticed that some comment posting queries are not affected while some other are very slow, like 30 secs or timeout after 60 secs. It looks like unaffected queries did not involve sending a notification email, so it’s likely related.

A possible long term solution is to move email notifying code into a background job.

**Comment by jiru** [comment]
It turns out the reason of the delay is that the server completely lost IPv6 connectivity. When sending out emails, Tatoeba first tries to connect to the SMTP server using IPv6, time outs after 30 secs, and only then falls back to IPv4. So the delay is like 30 secs multiplied by the number of emails to send, but capped to 60 seconds by nginx.

As a temporary fix, I added an ip6tables output rule to immediately reset the IPv6 connection.

**Comment by jiru** [comment]
Our host solved the problem of IPv6 connectivity. I removed the ip6tables rule.
