### ISSUE TITLE
Clean up unknown language inconsistency in the database/export

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#308]
It seems like currently, languages that aren't identified, for some reason either get a null value or an empty string. I'm not sure which part of the codebase is causing this inconsistency (maybe the call to tatodetect?) but at least for now we need a procedure that sets the empty strings to null as well before/during the run of the export script as this can break scripts working on the data in unexpected ways. Also the default value for null in the export is \N which is fairly ugly, maybe we should change that to something more sane like 'und' (undefined) or something.

List of sentences with empty strings:
http://sprunge.us/BWeF

List of sentences with null
http://sprunge.us/dVZW

**Comment by trang** [comment]
It seems that these empty strings in the lang field are due to users who edit sentences which language is null.
From what I have tested though, the edited sentence is currently not even saved when you try to edit a sentence which language is null. I've commited a fix for that.

I've also set to null the languages that were an empty string. For the record, these were the sentences:

<pre>
mysql> select id, text, created, modified from sentences where lang = '';
+---------+---------------------------------------------------------------+---------------------+---------------------+
| id      | text                                                          | created             | modified            |
+---------+---------------------------------------------------------------+---------------------+---------------------+
| 3158526 | /ʔɛˈmɛh cəmɛh maiɲ/                                           | 2014-04-08 03:58:12 | 2015-03-09 14:33:04 |
| 3158546 | /maj juːʔ ʔaj muː/                                            | 2014-04-08 04:16:36 | 2015-03-09 14:10:13 |
| 3189925 | မဂၤလာပါ။ ေနေကာင္းလား။                                         | 2014-04-19 13:56:14 | 2015-03-23 02:21:32 |
| 3189927 | မဂၤလာပါ၊ ေနေကာင္းလား။                                         | 2014-04-19 13:56:47 | 2015-03-23 02:23:04 |
+---------+---------------------------------------------------------------+---------------------+---------------------+
</pre>
