### ISSUE TITLE
Tigrinya (tir)

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#312]
- Language name: Tigrinya 
- Language info: http://en.wikipedia.org/wiki/Tigrinya_language
- ISO 639-3 code: tir
- Public List: http://tatoeba.org/eng/sentences_lists/show/3544
- Icon: TODO
- Requested by: http://tatoeba.org/eng/user/profile/danieljtah

Email sent to team@tatoeba.org:

> Hello, I've created a list with sentences, and then noticed a list already exists, so I've added my sentences into the existing list ::
> 
> List "Tigrinya" - created (and possibly requested before) by the User: danieljtah
> 
> http://tatoeba.org/eng/user/profile/danieljtah
> 
> the list:
> http://tatoeba.org/eng/sentences_lists/show/3544/
> 
> Spelling in English Tigrinya, older spelling: Tigrigna 
> 
> Iso code: 'tir'
> http://www-01.sil.org/iso639-3/documentation.asp?id=tir
> 
> Icon - I don't know - the language is official in both Eritrea and Tigray region in ethiopia, which are at war with each other, (hence I would not chose one or the others flag, millions of speakers on both sides), and on the Ethiopian side, different groups are burning each others flags [  arguing on what the 'true flag' should be :: http://mereja.com/forum/viewtopic.php?t=61484&p=373879 ]
> 
> Can we postpone the icon, or ask native speakers what they would use?
> 
> I would suggest adding a Latin transcription to the Ge'ez script - similar to what has been done with Georgian on Tatoeba (that's so cool!)
> I've coded for my own needs such a procedure in Javascript, I would gladly contribute myself this transliteration unit if you would guide me where/how.
> 
> my own code's here:
> [ http://jsfiddle.net/oyd11/Z5Wws/embedded/result/
> http://jsfiddle.net/oyd11/Z5Wws/embedded/
> 
> or as tool-tip for reading Ge'ez sentences in latinazation: 
> https://googledrive.com/host/0B35t4kCYWXP1ZnNUeExTbDB2ZE0/tst.html ]
> 
> thanks!

**Comment by oyd11** [comment]
Note about the flag choice: The current Flag on Tatoeba, is the Eritrean flag, while Tigrinya is one of the official and local languages in Ertirea, it's also the official language of the Tigray region in Ethiopia [ https://en.wikipedia.org/wiki/Tigray_Region ] where actually most native Tigrinya speakers are located (about 6 million in Tigray, plus about 3 million speakers in Eritrea, close to a million in 'diaspora').
I do recommend that somehow the flag reflects that, again, the usage of national flags for languages, is problematic, especially in Africa. cheers.

**Comment by RyckRichards** [comment]
Alright, going to work on it. I'll open a PR requesting to change its flag.

**Comment by oyd11** [comment]
ahh...  I didn't mean change it completely to the flag of Tigray, I'm pretty sure that might create some 'holy war' (or edit-war) somewhere...
Listen, what happens in other cases to languages which are used by two nations? An almost good analogy would be... hmmmm...  which flag does Swahili get? I mean, analogies could theoretically be Spanish, Portuguese or English, spoken in several countries, the issue that Tigrinya dialects are not so divided by the state-border, and the areas are adjacent.
Probably some divided Tigray-Eritrea flag is needed...
In Wikipedia - there's a divided Eritrea-Ethiopia flag for Tigrinya btw: https://commons.wikimedia.org/wiki/File:Flag_of_Tigrinya_language_(ET-ER).png 
(note that while it's official in Tigray, obviously there's lots of Tigrinya speakers elsewhere in Ethiopia)
Some divided Eritrea-Tigray-or-Ethiopia version is needed I guess.

> Alright, going to work on it. I'll open a PR requesting to change its flag.

**Comment by yosiasz** [comment]
Tigrinya is a language not a country. Analogy: Russian. Spoken both in Ukraine and Russia. You would not put one flag over the other, you would put both?

**Comment by oyd11** [comment]
@yosiasz , agreed, that was my point, Russian btw, is an official language in over 10 countries.
What do you suggest then?

I would personally advice generally disconnecting flags from languages, but somehow a lot of people seem to like that.

This is how this situation is different than the Russian language:

All Eritreans speak Tigrinya; on the other hand most Tigrinya speakers live in Ethiopia (which has population about x20 larger than Eritrea).

The situation is more obvious in Africa, where languages and nation-states rarely coincide (probably only in a few cases, like Rwanda, and in some sense Somalia).

Anyhow, @yosiasz, I didn't get what is the hinted solution (if any) in your analogy?

Tigrinya, is official in two countries, Ethiopia (also on a state/government level since 2020: 
https://unpo.org/article/21787 )  and Eritrea, both countries, are multi-cultural and multi-lingual, and were in a long war till 2019.

**Comment by yosiasz** [comment]
So what is the main purpose of this whole effort? "Tatoeba is a free collaborative online database of example sentences geared towards foreign language learners." Not sure what flag has anything to do with this mission statement. just a distraction imho.
If people want it, then put both.

**Comment by yosiasz** [comment]
also the flag wiki is so odd https://commons.wikimedia.org/wiki/File:Flag_of_Tigrinya_language_(ET-ER).png.

File:Flag of Tigrinya language (ET-ER).png

Then the description says
English: overlapped flags of Portugal and Brazil.
Português: bandeiras de Portugal e do Brasil sobrepostas.
አማርኛ: የኢትዮጵያ ሰንደቅ ዓላማ
Čeština: Vlajka Etiopie
English: Flag of Ethiopia
Italiano: Bandiera dell'Etiopia
Oromoo: Alaabaa Itoophiyaa
Soomaaliga: Calanka Itoobiya

👀

**Comment by oyd11** [comment]
The main purpose of the whole effort, is not to present national flags that might hurt native speakers and prevent them from extending the language corpus.
I'm only presenting the data as I am closely familiar with the speech community.

If you want to doubt the whole effort of assigning flags in Tatoeba, open a specific issue about it, otherwise do not troll.

**Comment by alanfgh** [comment]
We use images to represent languages because even at a small size, they can be linked mentally with a language. By contrast, language names vary in length and can be quite long. In addition, they're often displayed next to the text of a sentence, and it could be confusing to determine where the language name ended and the sentence began. Sentence abbreviations (such as "eng" for "English") are not widely known and are often hard to distinguish from each other, though in some cases, we do use them, either in conjunction with a flag or without.

Among the easiest images to find to represent languages are flags, usually national ones. It's true that the mapping of nations to languages is not one-to-one, but in some cases, speakers of a language do not have a problem with using the flag of a different nation. For instance, I'm a native English speaker from the US, but I have no problem with the fact that the UK flag is used to represent English. In fact, I would prefer it to a flag composed of a hybrid of the flags from, say, the UK, US, Canada, and Australia. For one thing, even that's not an exhaustive list of the countries where English is predominant/official, so we might as well stop at an icon that contains one flag rather than four. But it's worth noting that predominantly English-language countries have not been at war for a long time. By contrast, (1) the Ethiopian-Eritrean conflict is fresh, and (2) there are only two countries where the Tigrinya language is widely spoken.

@oyd11 asked above which flag we use for Swahili. The answer is that we use the flag of Tanzania, one of four countries where it is an official language. As far as I know, this hasn't caused a dispute.

So again, the e-mail that @trang quoted said "Can we postpone the icon, or ask native speakers what they would use?" As far as I'm aware, there are no native speakers participating in this thread. So we have the following options:

(1) use a bland icon, but one that we think will be uncontroversial, such as one that just consists of the three-letter abbreviation for the language
(2) use a composite icon, such as the Ethiopian/Eritrean hybrid suggested above
(3) continue to use whichever flag we're already using, and see whether any native speakers complain [the option that we are currently following, by default]
(4) ask native speakers on the Wall

It's quite possible that none of these choices is perfect. A flag composed of a three-letter abbreviation is uninviting. A composite flag looks odd. A single flag **might** alienate some speakers, possibly without our knowing about it. Asking people for opinions might draw attention and cause dissatisfaction (some of it not coming from native speakers) that wouldn't have been present before.

Having said that, I would probably go with (3), but none of the options strikes me as particularly bad.

**Comment by yosiasz** [comment]
I am a native speaker and  got a private message from someone in the tatoeba2community to give my 2 cents. I did. But @oyd11 thinks I am trolling. So not sure how I can contribute?

**Comment by trang** [comment]
@yosiasz Could be all a misunderstanding, so let's just start from the beginning :)

Currently in Tatoeba we are using the Eritrean flag to represent the Tigrinya language, as you can see for instance if you go to the page for this sentence: https://tatoeba.org/en/sentences/show/3305166

@oyd11 reported that this might be inappropriate because Tigrinya is not spoken only in Ertirea, it is also spoken in Tigray. Therefore, it could be more appropriate to use a combination of the Eritrean and Tigray flag.

How you can contribute is simply to let us know if you find anything confusing, inappropriate or offensive about the new version. And if so, why?

![image](https://user-images.githubusercontent.com/221850/131898776-38b03fcf-616b-4106-84ba-aa3389d3b6e9.png)

**Comment by yosiasz** [comment]
I doubt "otherwise do not troll" is a misunderstanding. Anyways, the following might help
1. Eritrea is a country
2. Ethiopia is a country
3. Tigray is a region in Ethiopia
3. Tigrinya is a language 
4. Tigrinya language is spoken both in the country of Eritrea and in the Tigray region of Ethiopia (with some slight differences)

The second option has the flag of Eritrea and Ethiopia which I would say is appropriate.

**Comment by oyd11** [comment]
So @yosiasz , firstly I totally apologise, my fingers were probably too fast on the Trolling claim, I meant let's focus on the current issue, and that's it.

Secondly, we all agree about your claims 1 through 5. 

Third, personally I have no opinion, my main concern, is not to drive away possible contributors. 

If to explain about the my trolling comment, it was specifically about not diverging the discussion towards a general discussion about the connection between Languages and National-Flag-Icons. A due discussion, but probably elsewhere, I simply meant let's focus about the current discussion. Which of the three or more flags should be selected.

(I  also happen to be a Russophone, so your discussion about Russian hit close to home, but I cannot guess yet what was your suggested about the Russian language icon if any)

**Comment by oyd11** [comment]
Note that my suggestion of the combined flag - was after someone's opened a PR suggesting the flag of Tigray only: https://github.com/Tatoeba/tatoeba2/pull/2836
If there's going to be PR's switching back and forth between the flag of Eritrea and Tigray, that makes little sense. (btw: in 2020, Tigrinya has finally received global level status in Ethiopia as well).

Anyhow, @yosiasz , from reading your comments, I'm pretty sure now my "otherwise do not troll" - _is_ a misunderstanding , I was assuming you're not related to the Tigrinya speech community, and that you're somehow diverging the discussion, which is obviously not that case.

 Even if it is, note that I'm not significant (yet) in the Tatoeba community at all, @trang is.
 
 I care about the Tigrinya language, and online presence of Tigrinya, which is both why I applied for Tigrinya to be officially listed in Tatoeba in 2014, and the reason I've commented about the icon, which might be excluding some parts of the speech community.
I personally do not care much for Flag icons, and the rate of change of National-flags is about 10 or more times faster than language change so far....
But I personally know _some_ Tigrinya speakers, who might stay away from interfaces if presented with the wrong flag.

**Comment by yosiasz** [comment]
I think people will complain either way. they will complain if you put a combined flag, they will complain if you use only one, they will complain if you put one above the other, they will complain one is wider than the other, etc. And they might have legitimate historical, ethnic and political reasons. We cannot be arbitrators of these. I would recommend another option: use a neutral flag that has a silhouette of a man and a woman 😃

**Comment by trang** [comment]
@yosiasz 

> I would recommend another option: use a neutral flag that has a silhouette of a man and a woman 😃

When it comes to neutral flag, we already have a design pattern, which is to put the ISO code of the language in black on a white background.

Is there anything about a silhouette of a man and a woman that is symbolic for Tigrinya native speakers? In other words, if we were to show an icon like that to a native speaker, could they somehow see the connection to their language? Because if not, then there would be no reason to deviate from our design pattern for neutral language icons.

But in the present case, we may not need to resort to a neutral icon. Our goal is not to shield ourselves from any possible complaint. It is just figure out a language icon that is acceptable within the majority of the native speakers that we can reach out to.

-----

@oyd11 

> But I personally know some Tigrinya speakers, who might stay away from interfaces if presented with the wrong flag.

Could you ask them what they think of the flag combining the Eritrean and Tigray flag to represent the Tigrinya language? If they confirm they see no issue with it and would not stay away from Tatoeba when presented with it, then I think we can go ahead and use it as the new language icon for Tigrinya.

**Comment by oyd11** [comment]
I know some people who wear such pins on your tshirts (the combined flag or two flags).
My main opinion here was to stop the first commit on https://github.com/Tatoeba/tatoeba2/pull/2836 , (to the flag of Tigray, from the flag of Eritrean) so that there will not start a loop of switches between these two flags.
I think the ISO code suggestion is better, at least in most African context right now, unless there's an obvious flag for the language community. I think both options suggested by @trang now are fine.
