### ISSUE TITLE
Directionality of original lang. for sentence remains after lang. is changed

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#33]
If a newly created sentence is assigned a language with one directionality, then it will continue to be displayed with the same directionality even after the language is changed. For instance, say that I add an English translation "The sky is blue." to a Hebrew sentence, but I mistakenly mark my translation as Hebrew. I see my mistake immediately because the final period clings to the beginning of the sentence (the left) rather than the end (the right). Now I click on the flag to change it to English. Even though I've changed it, it will still be displayed on my current page with right-to-left directionality (with the period clinging to the beginning rather than the end). If I actually go to the URL of the sentence, it is displayed correctly, however. Thus, this is a transient annoyance rather than a permanent problem. It would still be nice to fix the problem, though.

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/407

**Comment by ckjpn** [comment]
This is a "feature" of the fact the the full page isn't reloaded, I think.
If you reload the page, then you are likely to see what you expect to see.
My guess it that it saves resources by doing it this way, rather than forcing a complete reload of the page each time a change is made.

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on [Tatoeba Day 14](https://tatoeba.org/eng/wall/show_message/25169#message_25169).

**Comment by jiru** [comment]
Note that not only the directionality needs to be updated (HTML attribute `dir="..."`), but also the language (`lang="..."`), so that appropriate fonts, spell check dictionary etc. are selected by the browser for the sentence text. If the language is changed to a language that has multiple scripts, autodetection should find the script and append it to the `lang` attribute (for example `lang="zh-Hans"` for simplified Chinese). Finally, if the language is changed to a language that has transcriptions, the autogenerated transcriptions should show up too.
