### ISSUE TITLE
Add a way to delete tags from the set of possible tags through the UI

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#330]
Currently, we can only add new tags, not delete existing ones, through the UI. Most tags are deleted automatically when the number of sentences with which they are associated drops to zero, but not the ones that start with "@". Currently, those need to be deleted manually by an SQL DELETE command. It would be good for users of a certain level (probably admins) to be able to do this from the UI.

**Comment by RyckRichards** [comment]
@allan-simon do you know a script which could delete the tag Cebuano - https://tatoeba.org/eng/tags/show_sentences_with_tag/6363? Actually 203 sentences have been tagged. This tag was created by cueyayotl while Cebuano wasn't implemented on Tatoeba.

**Comment by trang** [comment]
@RyckRichards You pinged the wrong person. Also there is no official script to remove a tag from all sentences.

**Comment by allan-simon** [comment]
I was also wondering if it was about a old script for which only I had the knowledge :P

**Comment by ckjpn** [comment]
Here's a message I sent to Trang.  She said that she wanted to wait until this issue was taken care of.   This is just to let people know that they would have my permission to delete this tag.

**Comment by ckjpn** [comment]
Here's a message that I sent to TRANG a while back.  She said she wanted to wait until this issue was taken care of first.  I've included the message here, so that someone can remember to take care of this in the future.

## The message
Subject line: You may remove all the List 907 tags if you like.
Date: July 11, 2019

You may remove all the List 907 tags if you like.
You mentioned that you didn't like them

I started tagging sentences with "List 907" before the advanced search allowed limiting searches to a list, but did allow limiting searches by tag.

However, now that we can do that by limiting to a list, the tags aren't really necessary.

I assume that you can easily and safely delete all of those tag directly in the database.

**Comment by agrodet** [comment]
What would be the use cases of a need for an admin to "delete" a tag from the database? 

- Malicious mass-tagging. Someone adds "Gotcha" tag, we block him, we remove all the garbage tags. 
- Erroneous @-tags, like `@chang` that appears as auto-suggestion although there is 0 sentence.

Do we have other cases? Do we have to be careful of something in particular (I mean: can we simply and safely remove the tag and the operation is over?)

**Comment by jiru** [comment]
Note that, in addition to the removal of the the tag in the database, we also need to remove the tag in suggestd, so that it doesn’t show up in the autocompletion box too. However, there is currently no way to do that as far as I can tell from reading the [source](https://github.com/Tatoeba/suggestd/blob/master/src/http.c) (other that restarting the daemon of course). So one needs to implement the proper API endpoint in suggestd (or replace suggestd with some other implementation).

**Comment by AndiPersti** [comment]
> (or replace suggestd with some other implementation).

A little bit OT but for some time now I've planned to play around with `Manticore` as a replacement for `suggestd`. (see https://github.com/AndiPersti/tatoeba2/issues/6 for the reasons).

**Comment by jiru** [comment]
I am closing this issue because it mostly contains misleading, outdated of otherwise off-topic information. Feel free to open a new one if you want.

Just to clarify. I think there was a confusion between *removing a tag from the suggestion list* and *removing a tag from Tatoeba* because the suggestions used to be generated by a separate piece of software (suggestd) which could get out of sync. We removed suggestd at some point so there can be no confusion any more: what you see in the suggestion list now always reflects what's on Tatoeba.

At the moment, tags reaching zero sentence count are automatically removed from Tatoeba, regardless of starting with an @.
