### ISSUE TITLE
Keep search query settings across sessions

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#350]
Currently, we keep the search query settings "From" and "To" throughout a session, but drop them when the session ends. I think it makes sense to save them across sessions, as we do for the settings in "Browse by language" (show_all_in).

**Comment by trang** [comment]
I'm planning to close this issue because I don't think it will be beneficial for users. If we implement this, most of the time users will have to clear their search when coming back to Tatoeba. It rarely happens that someone wants to re-do the exact same search that they did before they left Tatoeba.

**Comment by alanfgh** [comment]
That's fine. In the meantime, I've discovered that I switch search directions often, and that saving bookmarks/keyword searches is best when I need to do a "canned search".
