### ISSUE TITLE
Offer an online method to search one's Tatoeba mailbox for a string

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#37]
Offer an online method to search one's Tatoeba mailbox for a string.
[AlanF_US, Wall](http://tatoeba.org/eng/wall/show_message/16971#message_16971)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/403

**Comment by trang** [comment]
I will close this issue. Implementing a full text search for private message would too high effort and too low impact for what we can afford.

Since we have email notifications for private messages, users can search from their email clients. This definitely doesn't cover every case. For instance:
- if a user has email notification disabled, that won't work at all for them
- if the notifications are not working for some time, the user won't be able to find the private messages that were not sent

For such situations, we could compromise by providing some filters (filter by recipient as suggested in #967, or filter by date) so that the user can narrow the scope of messages that they have to check manually.
