### ISSUE TITLE
Improve handling of sentences to which an OK tag cannot be added

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#43]
Improve handling of sentences to which an OK tag currently cannot be added. For instance, modify the current message to explain that you cannot add an OK tag to your own sentence.

[AlanF_US, Wall](http://tatoeba.org/eng/wall/show_message/16885#message_16885)

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/397

**Comment by trang** [comment]
**Clarification of the problem**

The tag feature has been modified so the initial description of this issue is not accurate anymore. The current behavior is the following (note that it requires to be advanced contributor or corpus maintainer):

- I go to the page of one of my sentences.
- In the sidebar, I enter "OK" in the textinput in the "Tags" section.
- I press "enter" and I see a loader.
- After a short time the loader disappears, but no tag is added.
- I try to add another random tag on the same sentence, for instance "dsdf".
- That tag does appear.
- I try to go to another sentence that doesn't belong to me, and try to add "OK".
- The tag does appear.

There should be a message that says `You cannot tag your own sentences with "OK"` when I try to tag my own sentences with "OK".

**Why can't users tag their own sentences with OK?**

The tag feature was not implemented with the idea that several people can tag the same sentence with the same tag. Tags are supposed to be meta data that gives extra information about a sentence. If a sentence is for instance tagged "slang" there is no need for 10 other people to add again a "slang" tag on it.

​The "OK" tag was introduced after we realized we needed some mechanism for users to validate sentences. We figured we could use the tags for that. We agreed on a tag that would mean "this sentence has been verified and considered as correct​". That's the "OK" tag.​

​Since only one same tag can be applied on a same sentence, ​we made a restriction that you cannot tag your own sentences, because it brings more value if somebody else tags your sentence "OK" (because you can easily be biased and not see your own mistakes).

**Comment by trang** [comment]
I'll close this. The fact that the tag `OK` simply doesn't appear when being added to your own sentences is good enough. I haven't heard from anyone being confused about this.

Additionally, this `OK` tag is very likely going to disappear one day because it was just a workaround for a need which we wanted to address in a quick and cheap way. People needed a way to mark that a sentence has been reviewed and is correct.

So overall, it would be an improvement but it's not really worth implementing.
