### ISSUE TITLE
Sentence link generation fails before non space character

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#482]
Noted [here](http://tatoeba.org/jpn/sentences/show/3585262#comment-410335).
MySQL dump of the comment:
```sql
INSERT INTO `sentence_comments` VALUES (410335,3585262,NULL,'否定疑問文はすごく難しくて、言語による違いも大きいと思います。\r\n\r\n参考：#3030014\r\n\r\nこの文の場合、「いる？」と「いない？」では意味はほとんど同じで、個人的には「いない？」の方が若干丁寧な感じがするというくらいです。\r\n\r\nフランス語ではどのような違いでしょうか？',51111,'2014-10-28 13:14:44','2014-10-28 13:14:44',0);
```

**Comment by trang** [comment]
We can't make the pattern match no matter what the preceding character is because of  #461. If the `#123` is part of a URL, it messes up the URL.

I've used the \p{P} class, thanks for the suggestion. It doesn't take into account the Japanese punctuation though, so I added also the Japanese colon in the list.

I also had to change the pattern for the number to make sure it starts with something else than 0 because `htmlentities()` converts single quotes to `&#039;`, and `#039` was converted to a link.
