### ISSUE TITLE
Scroll pages of results using Ctrl+→ and Ctrl+←

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#483]
[Original post](http://tatoeba.org/jpn/wall/show_message/20717#message_20717).

Feature request. Scroll pages of results using Ctrl + -> and Ctrl + <- (or Cmd + -> ) like search engines like Google do.
By pages with results I mean moving between such pages:
http://tatoeba.org/eng/sentences/search/page:1...
http://tatoeba.org/eng/sentences/search/page:2...
http://tatoeba.org/eng/sentences/search/page:3...
...

**Comment by kwikadi** [comment]
I was looking at this issue, and while I can make a JS only solution, I don't know if it will be considered a legitimate solution. On the other hand, a solution that involves cake has certain problems that I can't seem to overcome (and the solution involves some JS too). Can anybody help?

**Comment by jiru** [comment]
A Javascript-based solution seems fine to me, but

> a solution that involves cake has certain problems

What problems?

**Comment by kwikadi** [comment]
I've solved the issue with JS only. The issue I had with Cake involved how to inject JS only to those views which had pagination, and how to send to cake both the current url as well as whether the page requested was previous or next (so that cake could process and spit out the correct page).

Do I need to be assigned this issue for me to send a pull? (Trang said he would assign it to me, but I guess he forgot). If you want to see the code change, its available here: https://github.com/kwikadi/tatoeba2/commit/dbf5d7ebe9a49c6e1072135e7da39a10806285c0

**Comment by trang** [comment]
I'm reopening this because [gillux mentioned](http://tatoeba.org/eng/wall/show_message/21838#message_21838) that he had issues with the shortcut bringing him to the next or previous page when he's writing a comment.

Some users indeed use `Ctrl + arrow key` to quickly move their cursor to the next/previous word.

The solutions I see:

* Keep `Ctrl`, but use other keys than the arrow keys. Maybe `Ctrl + b` and `Ctrl + n`.
* Use `Alt + →` and `Alt + ←`.

**Comment by Ppjet6** [comment]
What about deactivating the functionality when in an input/textarea?

**Comment by kwikadi** [comment]
Neither of the two mentioned solutions (Ctrl+b/n and Alt+<-/->) will work because they are both mapped to different stuff in browsers already.
I think deactivating the functionality when inside a textbox is the best solution in this case (and the code change involves just a
 document.activeElement.type != "text" && document.activeElement.type != "textarea" 
in the if condition).
If the selective deactivation is an acceptable solution, let me know, I will send a pull request ASAP.

**Comment by trang** [comment]
Sounds good for me.
