### ISSUE TITLE
Linking a sentence shows translations in more languages than I asked for

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#510]
I'm translating from Hebrew to English. The page ( http://tatoeba.org/eng/sentences/show_all_in/heb/eng/eng/indifferent ) has the following settings:

Sentences in: Hebrew
Show translations in: English
Not directly translated into: English

When I first land on the page, the only translations shown are in English. But as soon as I link a translation, all direct and indirect translations of the main sentence are shown, not only the ones in English (or Hebrew). This is at odds with the fact that I asked to show translations only in English.

**Comment by trang** [comment]
As reported by Pfirsichbauemchen [here](http://tatoeba.org/eng/wall/show_message/21446#message_21446), the translations disappear in some situation, after linking or unlinking.

That's because the `_renderTranslationsOf()` is used everywhere and not just on the show_all_in page. A possible fix would be to check on which page the user is currently at, and only use the language stored in the cookies when they are on the show_all_in page.

**Comment by alanfgh** [comment]
Could you tell me how I could detect when one is on the show_all_in page?

**Comment by trang** [comment]
You should be able to do that with `$this->params['controller']` and `$this->params['action']`.

**Comment by jiru** [comment]
If I understand the problem, you want to use the referer instead, because the problem happens within an ajax call.

**Comment by jiru** [comment]
However, using the referer isn’t a very good way to handle the problem since you’d have to parse the URL yourself etc. How about sending the current language restriction as a parameter of the link/unlink ajax call?

**Comment by trang** [comment]
> If I understand the problem, you want to use the referer instead, because the problem happens within an ajax call.

Indeed.

> However, using the referer isn’t a very good way to handle the problem since you’d have to parse the URL yourself etc. How about sending the current language restriction as a parameter of the link/unlink ajax call?

Yes, sounds better.

**Comment by alanfgh** [comment]
Could you give me more details about how to do that? Are we talking about code in webroot/js/sentences.link.js, or somewhere else?

**Comment by jiru** [comment]
@alanfgh yes, that code. We currently only send one parameter: `'returnTranslations': true`. You could pass the language restriction as an additional parameter to the `linkToSentence()` function (and/or read the cookie value from the Javascript code), and the controller would receive that parameter and filter the returned list of translations.

**Comment by jiru** [comment]
@alanfgh This should be fixed now. It’s up on the development website. Can you try it out?

**Comment by jiru** [comment]
Note that there is still an edge case I’ve been unable to solve. While on the show_all_in page, if you add a translation to one of the sentences, it will be displayed regardless of the filtering settings (it was the case before as well). From there, if you click on the scissors icon of that newly created sentence, it will reload the list of translations without filtering.

**Comment by alanfgh** [comment]
gillux, thanks very much for addressing this. However, I see an issue when
I test out the dev. When I search for a word (in this case "stars") and
choose "To: " = "Hebrew", the search matches every sentence in the corpus.

**Comment by trang** [comment]
@alanfgh, the search is not functional on the dev. The config has Search.enabled = false.

**Comment by alanfgh** [comment]
@gillux, in some cases, when I break the link, I am taken to a sentence page that shows all the translations. For instance, that happened when I broke a link for sentence #2486856. I was taken to that sentence page. Oddly, the logs don't show record of my having broken a link. I'll have to try to reproduce it again.

**Comment by jiru** [comment]
@alanfgh the behaviour you’re describing sounds like the Javascript code broke (the 'onclick' code stops and do not `return false`, and the browser follows the href link normally). Maybe this happened because the .js file and the page contents were out of sync regarding my update? Either you clicked on the scissors of an 'old' page while having browsed new pages on other tabs that would’ve refreshed the .js, or you clicked on a new page while the .js were still not updated.

You said the logs didn’t show record of the link break, but did you actually broke the link?

**Comment by alanfgh** [comment]
I did break the link. However, I cannot reproduce the problem. Perhaps it was indeed caused by an out-of-sync situation that no longer exists.
