### ISSUE TITLE
duplicates in need of normalization

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#557]
CK posted these on the mailing list, they either have a bom(\xef\xbb\xbf) or a mismatched apostrophe character and should be edited manually or with a script or the dedup script won't merge them:

1809371	eng	I'm going to my grandmother's.	pne
3601982	eng	I'm going to my grandmother's.	karloelkebekio
1540664	eng	It is too expensive.	CM
http://dev.tatoeba.org/eng/sentences/show/1540664
925077	eng	﻿It is too expensive.	zvaigzne
http://dev.tatoeba.org/eng/sentences/show/925077
1522520	eng	It isn't over yet.	Spamster
3728104	eng	It isn't over yet.	CM
1808077	eng	Money doesn't grow on trees.	pne
3501287	eng	Money doesn't grow on trees.	CK
1737426	eng	Price isn't an issue.	Spamster
3147954	eng	Price isn't an issue.	CK
895935	eng	That's interesting.	pauldhunt
1897793	eng	That's interesting.	CK
2967925	eng	This is only the beginning.	CM
2680594	eng	This is only﻿ the beginning.	Balamax
2236214	eng	Tom didn't hesitate.	CK
2471834	eng	Tom didn't hesitate.	arnxy20
1886675	eng	What's wrong with that?	CK
2367526	eng	What's wrong with that?	eastasiastudent
50984	eng	Who's there?	CK
2176373	eng	Who's there?	dafp
2191867	eng	Why'd you do that?	Snark
2631832	eng	Why'd you do that?	Joseph
2542709	eng	You won't get away with this.	CK
3727170	eng	You won't get away with this.	CM

**Comment by alanfgh** [comment]
In my fix for #619, I added code to strip any byte-order mark when the sentence is added, and then I made a pass to remove existing byte-order marks. That fix was made several months ago (March 2015). The script did indeed merge sentences 1540664 and 925077, so the fix worked as planned. However, I see that there are 41 sentences that contain a byte-order mark somewhere other than the beginning. See #643.

As for merging sentences that differ only in punctuation (in which I am including apostrophes) and spacing (ordinary vs. non-breaking), I've written a separate issue ticket for that: #642. 

I'm going to close this ticket because it's covered by the other three. It will still be possible to read the list after the ticket is closed.
