### ISSUE TITLE
Hover text for "no audio" icon is unintuitive

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#561]
When you hover over a "no audio" icon next to a sentence, you get a tooltip that says "Audio unavailable. Click to learn more." Clicking takes you to the "Contribute audio" page on the wiki, which begins "Contribute audio for Tatoeba... If you want to record, you must have a good microphone because sound quality is important." A mental leap is required to figure out that what you're saying is "There is no audio for this sentence, but you can contribute it." Also, the hover text is ambiguous: is the audio unavailable because the site is broken, or because no audio was ever recorded for that sentence?

Thus, I think the hover text should say something like: "No audio has been recorded for this sentence. Click to learn how to contribute audio." (With the upcoming fixes to #524 and #560, note that it is also possible that an admin has turned off the audio because it doesn't match the sentence. But I wouldn't confuse users by mentioning this.) That message might be a bit long, but it's probably okay. However, we can think about coming up with something more concise. Maybe "No audio recorded. Click to learn how to contribute audio." would be okay, if people think it's clear that "No audio recorded" pertains to that particular sentence.

**Comment by jiru** [comment]
How about removing that icon altogether, and only show the icon when a sentence has audio? It just bloats the interface and screams all around the obvious fact that most sentences lack audio, which most visitors don’t care. Maybe it’s just me, but I don’t think that kind of thing attract much audio contributors, because I think only people who are really interested into audio recordings will make the effort to find the relevant information.

**Comment by trang** [comment]
>  I think the hover text should say something like: "No audio has been recorded for this sentence. Click to learn how to contribute audio."

I would be fine with this.

There is this issue by the way, that groups issues with UI strings: https://github.com/Tatoeba/tatoeba2/issues/528
To avoid creating too many issues just to deal with the change of a string, you can simply post a comment on that issue.

> How about removing that icon altogether, and only show the icon when a sentence has audio?

I would also be fine with this, but it requires a bit more work.
* Change the position of the audio button to be displayed before the language icon (otherwise there can be a blank column when no sentence has audio, and it looks weird).
* Add a category "Contribute" > "Contribute audio" in the menu. It could just display the same page as "Browse" > "Browse audio".
* Add some info text on the side bar of the Browse audio page, to link to the Wiki page that explains how to contribute audio.

**Comment by tommy-3** [comment]
Sorry for a late response, but I'd suggest removing the link and the alt text (while keeping the icon).
Most people would be more interested in listening to audio of a language they're studying, so it now looks as if we were encouraging them to contribute audio in their non-native language.

**Comment by alanfgh** [comment]
The instructions on the landing page now tell them that they should only contribute in their strongest (native) language.
