### ISSUE TITLE
Detect if a sentence is a duplicate and don't add it if it is

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#577]
We have a script that eliminates/merges duplicates from the database but it would be good to detect if a sentence is a duplicate before it gets added, and simply not add it if it's a duplicate.

Note that we need to distinguish 2 situations:
1. The duplicate sentence is detected while adding a **new sentence**. In this case we just don't add it.
2. The duplicate sentence is detected while adding a **translation**. In this case still don't add the sentence itself, but we probably want to add the links.

**Comment by ckjpn** [comment]
Perhaps this is no longer needed now that the duplicate-merging script is being run so often.

**Comment by trang** [comment]
@zachleigh, here's some more details about this issue.

There is currently no mechanism in Tatoeba to prevent users from adding a sentence that already exist. This has been the case since the beginning of Tatoeba. This is a problem because:

* It generates unnecessary work for contributors. Let's say I add a sentence today, and it gets translated into a bunch of languages. Someday you add the exact same sentence. People might translate it again into languages for which translations already exist.
* It generates unnecessary data to download and process for people who are using our [CSV files](https://tatoeba.org/eng/downloads).
* And it probably generates a bunch of other problems which don't cross my mind right now.

Over the years, the database accumulated a significant amount of duplicate sentences. To clean up the database from existing duplicates, a couple years ago, [a script has been developed](https://github.com/Tatoeba/tatoeba2/milestone/33?closed=1). It currently runs every 15 minutes, if I remember correctly. The actions performed by the script are stored via the user account [Horus](https://tatoeba.org/eng/users/show/63758) (all the comments and logs of this account were created by the deduplication script).

This script did solve the problem of having tons of duplicates in the database, but it's not the optimal way to handle duplicates. It generates additional data (comments and logs) which would not be there if the duplicate sentence was not added in the first place. It can create confusion for users who are unaware of the deduplication process: they contribute a lot of sentences, a significant amount of their contributions are duplicates, they get removed, they wonder why they lost sentences. And it has other problems which I won't detail here.

----

Possible scenarios and desired behaviors

**1) I'm adding a sentence that already exists.**

==> The sentence appears in the list of added sentence (just like the vocabulary feature), but with a warning that it already exists so that the user knows their sentence was not added, and who added it before them.

```
	(!) The sentence you tried to add already exists.
	
	(menu icons)				belogns to SomeUser
	------------------------------------------------
	# Duplicate sentence text
```

**2) I want to translate sentences.** Let's say I want to translate an English sentence into French. The French sentence already exists but is not directly linked to the English.

==> The translation becomes a direct translation and appears in the list of translations, as if I was the one who added it. In the logs however, it doesn't record that I have created the sentence. It only records that I added a link between the English and French sentence.

**3) I want to edit a sentence, and by editing it, it becomes a duplicate of an existing sentence.**

==> This case is trickier to handle and should be part of another issue. The problem is that we have to consider the case where a user is trolling and replaces is a perfectly good sentence by an existing sentence that has a completely different meaning.

----

For the scope of this issue we only want to focus on exact duplicates. Near duplicates are another issue.

Technically, we can reuse the same concept as for the vocabulary (cf. #1218, murmur3 hash of lang+text stored in a column with unique constraint). As far as I know, it's the fastest way. If you can think of a better solution, feel free to suggest.

**Comment by trang** [comment]
Suggestion from bill: http://tatoeba.org/eng/wall/show_message/27372#message_27372

Not for the scope of this issue, but good to remember for whenever we rework again the "Add sentences" page.

**Comment by sabretou** [comment]
I did some testing on TatoebaDev and found that it is possible to 'bypass' this feature by adding whitespace before or after the sentence.

To test, I took CK's sentence: https://dev.tatoeba.org/eng/sentences/show/3843299
Then, I tried adding it by copy/pasting, it did not add because duplicate.
Then, I tried adding it with one space after the sentence. It was added: https://dev.tatoeba.org/eng/sentences/show/3843303
Twice, I tried adding an extra space within the sentence (added to an existing space, for eg. "Tom wore  a dark sweater." or "Tom  wore a dark sweater."). They were not added.
Then, I tried adding the sentence with one space before the sentence. It was added: https://dev.tatoeba.org/eng/sentences/show/3843304

**Comment by zachleigh** [comment]
@sabretou Thanks for the report. Ill test this out and submit a fix tomorrow.

**Comment by trang** [comment]
@zachleigh there is a function that takes care of [cleaning extra spaces](https://github.com/Tatoeba/tatoeba2/blob/dev/app/models/sentence.php#L135), but currently it is called **after** you create the hash and try to check if the sentence is a duplicate.

**Comment by trang** [comment]
@zachleigh another thing to fix: the warning message when the user is adding a duplicate.

`The sentence you tried to add already exists.` 
--> `Your sentence was not added because it already exists. Below is the existing sentence.`

[Guybrush](https://tatoeba.org/eng/wall/show_message/27406#message_27406) mentioned that the current message was not clear enough.

**Comment by ckjpn** [comment]
Perhaps a shorter message would be more effective.

Here are some ideas.

## If adding a duplicate as a new sentence.

Your sentence was not added because the following already exists.

This sentence already exists.

This sentence was already in the corpus.


## If adding a duplicate as a translation.

Instead of adding your duplicate sentence, this has been linked to the following existing sentence.

The following existing sentence has been linked.



Maybe some other members can look at these and suggest better, more concise messages.

**Comment by ckjpn** [comment]
This is related.

https://github.com/Tatoeba/tatoeba2/pull/1311#issuecomment-251015524

Re: https://cloud.githubusercontent.com/assets/221850/19021407/bf5c8b9a-88c0-11e6-9c80-249e853d15ed.png

Perhaps a simpler message could be something shorter and similar to the following.

"An existing duplicate has been linked instead of adding yours as a new sentence."

Maybe Alan can suggest a better wording.
I imagine we can come up with something better, but more concise like this.

**Comment by alanfgh** [comment]
Using CK's suggestions as a starting point:

**When attempting to add a duplicate as a new sentence:**
This sentence already exists.
That sentence already exists.
The sentence you are trying to add already exists.

I favor "That sentence already exists."

**If attempting to add a duplicate as a translation:**
An existing duplicate has been linked instead of adding yours as a new sentence.
\#1234 has been linked instead of adding yours as a new sentence.
An existing duplicate has been linked instead of adding yours.
\#1234 has been linked instead of adding yours.
The following existing sentence has been linked.
An existing duplicate has been linked.
\#1234, which is identical to your sentence, has been linked.
\#1234, which matches your sentence, has been linked.
Sentence \#1234, which is a duplicate of yours, has been linked.

Of these, I favor "\#1234, which matches your sentence, has been linked."

**Comment by ckjpn** [comment]
## When attempting to add a duplicate as a new sentence:

I prefer "This sentence already exists." since we are talking about the current sentence.
However, I can live live with "That sentence already exists." that alanfgh favors.

## If attempting to add a duplicate as a translation:

I like the idea of just showing the sentence number.  It's more concise and also gives regular contributors an idea of how long the existing sentence has been in the database.

I can live with the version alanfgh favors.
"#1234, which matches your sentence, has been linked."

I somehow feel it might be better if the message didn't have the grammatical structure with the 2 commas, but I can't think of anything better right now.

Including the word "sentence" may make it clearer to new contributors, but short and concise is good, too.

"Sentence #1234, which is a duplicate of yours, has been linked."

## One Other Thought

It might be nice if the messages could be more similar to each other.  Perhaps someone can suggest something.

**Comment by zachleigh** [comment]
@trang I now pass $text through the clean() method before creating the hash.

**Comment by zachleigh** [comment]
@ckjpn You sent me a link to a gist regarding this issue the other day, but I cant for the life of me remember where it is or how you sent it to me. Could you send it again when you have time?

**Comment by trang** [comment]
I merge the branch. I will take care of changing the warning message.

I think CK's first suggestion is best: `Your sentence was not added because the following already exists.`. We need more emphasis on the fact that the sentence was not added. It may be very clear for regular users that duplicate sentences are not added, but not for new users, so we need to explicitly say it.

**Comment by trang** [comment]
This is now deployed on the main website.

For reference, some stats regarding the number of sentences deleted by Horus each day since October 1st until today.

```
mysql> select date_format(datetime, '%Y %m %d') as day, count(*) from contributions where user_id = 63758 and action = 'delete' and type = 'sentence' and datetime > '2016-10' group by day;
+------------+----------+
| day        | count(*) |
+------------+----------+
| 2016 10 01 |      127 |
| 2016 10 02 |      182 |
| 2016 10 03 |      226 |
| 2016 10 04 |      212 |
| 2016 10 05 |      175 |
| 2016 10 06 |      201 |
| 2016 10 07 |      223 |
| 2016 10 08 |      208 |
| 2016 10 09 |      145 |
+------------+----------+
9 rows in set, 2 warnings (7.20 sec)
```

**Comment by trang** [comment]
Also just for the record, the update script took 2 hours to finish (one hour more than I initially expected).

```
mysql> \. docs/database/updates/2016-09-11.sql
Query OK, 5175908 rows affected (58 min 28.54 sec)
Records: 5175908  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (1 min 20.34 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected, 1 warning (0.01 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 5175485 rows affected, 423 warnings (55 min 3.93 sec)
Rows matched: 5175908  Changed: 5175485  Warnings: 423

Query OK, 0 rows affected (0.40 sec)
Rows matched: 6682  Changed: 0  Warnings: 0

Query OK, 0 rows affected (0.53 sec)
Rows matched: 7819  Changed: 0  Warnings: 0
```
