### ISSUE TITLE
Message about noneditability of sentences with audio

### ISSUE THREAD

**Issue by liori** [Tatoeba/tatoeba2#578]
The recently introduced blocking of editing sentences with audio is presented in a non-discoverable way: clicking on a sentence on a sentence details page just does nothing, instead of showing a text field. This made me think it's a bug and I started looking in the source code etc.

I propose to display a small message like "You cannot edit a sentence that has audio. Please contact admins if your intended edit will not change pronunciation of the sentece." instead, right below the sentence.

**Comment by trang** [comment]
@kwikadi, I've assigned you this issue but we need to take care of #580 first because we want to remove the edit-in-place mechanism.

We can't solve this issue here simply by adding a warning message on click on the sentence because we cannot assume that the user clicked necessarily to edit. 
They could have clicked simply to copy-paste and it be confusing/annoying for the user to see a warning every time.

Once you've solved #580, we can discuss how we will display the information "You cannot edit a sentence that has audio...". It could be on click on the edit button, it could be on rollover.
Note that there's already something for the delete button: http://prntscr.com/62siwx. If we decide to implement it differently than how it's done for the delete button, we should also change the behavior on the delete button.

**Comment by kwikadi** [comment]
I have, as of right now, added tooltips to the edit button that work identically to the Delete button ('Edit' when editing is possible, and 'You cannot edit this sentence because it has audio' in case of audio. The button is missing altogether if the user does not have permissions to edit the sentence)
Do you think a more visible form of communication is needed?

**Comment by trang** [comment]
It's fine for now. I'm leaving this issue open until after the release though, in case users have some feedback on this. I've updated the dev website so that they can test the new features.
