### ISSUE TITLE
Adopting or unadopting a sentence shows more translations than asked for.

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#581]
Bug similar to #510.

Steps to reproduce:
1a. Go to the show_all_in page and restrict the displayed translations
1b. Or, search for a word and select a target language
2. Adopt or unadopt a sentence that has translations in other languages than the one selected in 1.
3. The translation list reloads and shows all the translations without restriction.

**Comment by trang** [comment]
Note that when adopting there's actually no need to reload the whole sentences group. It's enough to just update the user icon and username.
Adoption is one of these features that were implemented a long long time ago, in a non-optimal way, and never got improved. That's why it currently reloads the whole sentences group.

Solving this issue should not be about restricting the languages displayed, but restricting the content  to update to only the icon+username (insted of the whole sentences group).

**Comment by trang** [comment]
The behavior is a bit confusing when you are clicking on your username for sentences that belong to you. It redirects to your profile, and at the same time unadopts the sentence.
I don't think users will want their sentences to be unadopted when they clicking on their username.
Or at least, if it's going to unadopt, then clicking on the username shouldn't redirect to the profile. The user should stay on the same page, so that they can clearly see that the sentence was unadopted.

**Comment by jiru** [comment]
Woops, that wasn’t intended.

**Comment by jiru** [comment]
It should be fixed now.
