### ISSUE TITLE
Export users languages into CSV file

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#624]

**Comment by alanfgh** [comment]
The solution involves adding something like the following to database/scripts/weekly_exports.sql:

```
-- User skill level per language
SELECT ul.language_code, ul.level, u.username, ul.details
FROM users_languages ul LEFT JOIN users u ON ul.of_user_id = u.id
ORDER BY ul.language_code ASC, ul.level DESC
INTO OUTFILE '/var/tmp/user_languages.csv';

```
This works, but if anyone has any comments regarding selection or ordering of fields, please let me know.

**Comment by alanfgh** [comment]
CK and tommy_san both expressed interest in such an exported file. In e-mail, CK suggested this format:

username, language code, level, details

He said "Personally, I'm really only interested in each members strongest language, so that would be enough for me." But sorting by language, then skill level, is closest to what the "Languages of members" page does, and would give CK the information he needs anyway.

tommy_san didn't mention any preferences regarding fields or ordering.

**Comment by trang** [comment]
The "order by" is not really necessary. People who are using the data will filter it according to their needs so it won't matter how it's ordered. I would limit it to:

<pre>
SELECT ul.language_code, ul.level, u.username, ul.details
FROM users_languages ul LEFT JOIN users u ON ul.of_user_id = u.id
INTO OUTFILE '/var/tmp/user_languages.csv';
</pre>

**Comment by alanfgh** [comment]
Considering that all the other output files are either explicitly ordered or are implicitly ordered in a way that makes sense (for example, by sentence id). I'd rather keep things consistent in that regard. I'd also like to have them in an initial order that makes sense so it's immediately "readable" by the person who downloads it.

**Comment by jiru** [comment]
For the record, I just updated the crontab script to take this new export file into account.

**Comment by lagleki** [comment]
+1 for such a thing

**Comment by trang** [comment]
@lagleki, I'm not sure what your +1 refers to, but if it refers to a CSV export of users languages, it's already available.

Cf. http://tatoeba.org/eng/downloads > "User skill level per language"
http://downloads.tatoeba.org/exports/user_languages.tar.bz2

**Comment by lagleki** [comment]
sorry, it was a misplaced comment.
