### ISSUE TITLE
Allow rich text in messages

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#651]
[Requested by 123xyz](https://tatoeba.org/wall/show_message/22583#message_22583).

Allow bold and italic in messages (wall and sentences), in order to empathize words.

**Comment by trang** [comment]
And quotes.
http://tatoeba.org/eng/wall/show_message/22618#message_22618

And probably other things will be requested, like underline, stroke text, color...

**Comment by RyckRichards** [comment]
Requested by Lazovic on [Tatoeba Day #9](https://tatoeba.org/eng/wall/show_message/24496#message_24496).

**Comment by ckjpn** [comment]
I think this is an unnecessary enhancement.
It seems like it would take a lot of work for something that is primarily just cosmetic.
I think people manage to use Facebook pretty efficiently without needing this for posting messages.

**Comment by RyckRichards** [comment]
It would be great to have such a feature since we'd have less problems about sentences, I think. Example: people that write "every day" by "everyday" , "have" instead of "has", people that don't care about capitalization, etc. I'll contact [123xyz](https://tatoeba.org/eng/user/profile/123xyz) and ask him about that.

@ckjpn  - I half agree to you. On Facebook, nobody really cares about grammar but on Tatoeba we do. Also, I think that it would be good even for learners that visit Tatoeba since they would read why that sentence is 100% correct or not.

**Comment by trang** [comment]
For similar reasons to #1915, I'm marking this `out of scope`. The communication tools implemented within Tatoeba will mostly remain as they are. We don't have the resources to develop them further.

**Comment by trang** [comment]
Closing since there hasn't been any objection for almost a month.
