### ISSUE TITLE
use xml interface for sphinx

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#69]
http://jetpackweb.com/blog/2009/08/16/sphinx-xmlpipe2-in-php-part-ii/moreover it can be usefull to have this if we move from something else than mysql

**Comment by trang** [comment]
The link mentioned in the description is broken.

@jiru, since you've worked more with Sphinx than I did, do you know if this is something we should still consider, or should we just close this issue?

**Comment by jiru** [comment]
As the description says, it can be useful if we move from something else that mysql.

Other than that, I think there is a potential for optimizing the indexation process by using this, because the indexation query currently builds json data by wrapping the “real” query with another query that does a `group_concat`, which I think is rather suboptimal. Using xmlpipe2 should allow us to generate json in a more efficient way.

That said, we have no plans to move from mysql and the indexation is efficient enough, so I’m closing this.
