### ISSUE TITLE
Change the personal drop-down menu under a member's username.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#714]
**** Insert "Translate my sentences."

- This makes it easy for members to add sentences to lists, and see what translations have been added to their sentences.  Both of these are things you can't do by just viewing "My sentences."  My guess is that more members frequently go here than to "My favorites".

****  Resolve the problem that neither of the links at the bottom of the menu go to where a member can change his "known languages."

- Perhaps eliminating both of these and just having a link that says "My profile" would solve the problem.  Once people are on that page, they can change all the settings related to their profile. I know that clicking the username in the menubar goes there, too, but that may not be so obvious to new members.

![screen shot 2015-07-12 at 09 40 15](https://cloud.githubusercontent.com/assets/7934273/8635908/0451f948-287c-11e5-9a59-8759bf6a7624.png)

**Comment by trang** [comment]
I have added a "My profile" link and removed the "Edit profile" one.

I didn't add the "Translate my sentences" link because I think this is a bit confusing. If the goal is to be able to view your sentences with the "full box" (menu + translations), then the solution is not to add "Translate my sentences" but to change the way sentences are displayed on the sentences page of a user.
