### ISSUE TITLE
"More" dropdown menu is missing on the homepage with the Italian interface

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#735]
On the homepage with the Italian localization, the "More" menu is missing. On all the other pages it's present. From what I saw, English and other localized interfaces don't have this issue.

This is how I see the localized homepage menus with Firefox 39.0 on Ubuntu 15.04: http://i.imgur.com/6L5FNzA.png

It started recently (like a couple of weeks ago)

**Comment by trang** [comment]
The problem exists in Polish too.

That's more of a problem for users with a longer username and/or who are viewing Tatoeba with a font in which the characters are larger in width.

The "More" item gets pushed to the next line, but since the menu was made to have a fixed height of 30px, the items that are below are hidden.

**Comment by jiru** [comment]
It’s not a problem anymore with the new homepage since the menu properly spans on two lines:
![two-lines-menu](https://cloud.githubusercontent.com/assets/5107734/13679538/7f706e66-e6f4-11e5-9816-aeb1fdbbcc05.png)
