### ISSUE TITLE
"Unknown language" string in dropdown doesn't render properly in Finnish

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#737]
http://tatoeba.org/eng/wall/show_message/23674#message_23674

**Comment by jiru** [comment]
I think there is a better way to solve this problem. Why did the Finnish translator put a sublist as translation for the string “unknown language”? Because it’s used in sentences such as “Orphan sentences in {language}”. However, such strings would be better special-cased when {language} is “unknown language”, for instance: “Orphan sentences whose language is unknown”. This allows more natural sentences in French too (Phrases dont la langue est inconnue.) and I bet in many other languages too. In addition, this solution allows to change “unknown language” into “Unknown language” (because it won’t be used inside sentences any more) so that the case is consistent within the dropdown.
