### ISSUE TITLE
Remove suspended users from "Languages of members" and "Native speakers"

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#741]

**Comment by trang** [comment]
**Clarification of this issue**

* The "Languages of members" page can be accessed from the menu "Community" > "Languages of members"
* The "Native speakers" page can be access from Community" > "Native speakers".

These pages display information about the languages of the members in Tatoeba.

At the moment, these pages include as well members who have been suspended (they can no longer log in with their account). It would be preferable not to display these members, because they are no longer part of the community and they may also have false information about the languages that they know.

The original issue was also mentioning to remove "blocked users", i.e. users who can still log into Tatoeba but are temporarily blocked from adding new sentences or translations. Since it's possible that these members become normal contributors again, I think there is no need to exclude them from these pages (hence I changed the title).
