### ISSUE TITLE
Add "daily average" to the https://tatoeba.org/eng/contributions/activity_timeline/

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#751]
As I was doing a screenshot for "Daily Contribution Stats for 2014 & 2015 at a Glance" (http://goo.gl/3PUMKG), I thought it would be very easy for you to add in a "daily average" on each of the pages.

It would be a simple formula, calculated on all "complete days."

I'm referring to these pages.
https://tatoeba.org/eng/contributions/activity_timeline/

**Comment by RyckRichards** [comment]
I'm pretty sure that it would help people (new members) see how important and "being used" is Tatoeba. It's not a "static" page, but a page that everyone add;correct, tag, link sentences everytime. Is it too hard to implement, @Tatoeba/tatoeba-team ?
I'm going to post it on the Wall since some members complain that they haven't been notified and so, Tatoeba is not "democratic"...

**Comment by jiru** [comment]
> It's not a "static" page, but a page that everyone add;correct, tag, link sentences everytime.

I don’t understand this sentence.

**Comment by RyckRichards** [comment]
It's not like many pages such as Duolingo that always displays the same thing all the time or LingQ, Memrise, etc

**Comment by trang** [comment]
This is low severity, but if someone wants to implement it: the daily average can be displayed at the bottom, below the chart.

The string would be:
- `Daily average: {number} sentences` (if more than 1)
- `Daily average: {number} sentence` (if less or equal to 1)

**Comment by theblindspring** [comment]
I have to confess, I don't use Tatoeba myself, so I am not sure what is being asked for. Do we want the daily average of sentences added by anyone to Tatoeba? Or just sentences added by the user? If we want the users daily average, do we count only days they logged in or do we count every day since they have been a member?

**Comment by trang** [comment]
We want the daily average of sentences added by anyone in Tatoeba. You already have all data from the activity timeline page. You just have to make the sum of everything, divided by the number of days.

**Comment by ckjpn** [comment]
To make it more clear, what I was suggesting is an average of contributions each month, similar to what's on this page each month on the gray line.

http://a4esl.org/temporary/tatoeba/stats/timeline/

I've included a partial screenshot since sometimes the above website is overloaded with traffic and is slow.

![screen shot 2016-05-10 at 22 53 56](https://cloud.githubusercontent.com/assets/7934273/15148872/56d044e8-1702-11e6-9776-6f3d171c2be5.png)
