### ISSUE TITLE
Tags for moderators -> Tags for corpus maintainers

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#765]
I suggest to reword Transifex's string #862 in default.pot, since it's been a while since "moderators" have been changed in Tatoeba's glossary, so maybe it's time to update also the sting used in this page: https://tatoeba.org/ita/tags/for_moderators/561/
Maybe also the url could be updated.

**Comment by ckjpn** [comment]
There are several other places on tatoeba.org that are using old names for things.

moderator
trusted user
etc.

Perhaps these should be updated at the same time.

**Comment by trang** [comment]
As I've explained [on the Wall](https://tatoeba.org/eng/wall/show_message/26330#message_26330):

> This page is actually more of a hidden page and is likely to be removed one day, to be replaced by something else. It's not accessible anywhere from the menu and new users wouldn't know about it unless veteran users tell them about it.

> I'm actually going to mark the issue as rejected because I don't think it's worth fixing the text of a page that is meant to be replaced. It'll just generate unnecessary work for UI translators.

**Comment by ckjpn** [comment]
Some of the blog entries about things might be less confusing to new members if the blog entries, at least, were updated to use the current terms.

**Comment by trang** [comment]
Yes, but that's not code related. It's a task that doesn't need to be tracked in GitHub. Ideally, there shouldn't be any guides or guidelines that refers to the blog. Guides and guidelines ideally should be all copied into the wiki.

Besides the blog, normally there shouldn't be other pages on tatoeba.org itself, where the terms "moderator" and "trusted user" are used. This is only the case for some admin pages, but that is because the values come from the database, they are not translatable strings.
