### ISSUE TITLE
In the advanced search, the "Limit to sentences with translations" with the "Link: Any" option doesn't work.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#777]
In the advanced search, the "Limit to sentences with translations" with the "Link: Any" option doesn't work.

*** Link: Any
This doesn't work.  -- It displays sentences with no links even though  "Limit to sentences with translations"  is set.

*** Link: Direct
*** Link: Indirect

These both work.

This is the "Link: Any" URL shown in the screenshot below.

https://tatoeba.org/eng/sentences/search?query=&from=und&to=und&orphans=no&unapproved=no&user=CK&tags=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created

See the 3 screen shots.

1. Link: Any
![any](https://cloud.githubusercontent.com/assets/7934273/9998259/4f597a24-60cb-11e5-9200-53c425d17dc9.png)

2, Link: Direct
![direct](https://cloud.githubusercontent.com/assets/7934273/9998260/4f60a164-60cb-11e5-9a02-26b9f761d106.png)

3. Link: Indirect
![indirect](https://cloud.githubusercontent.com/assets/7934273/9998261/4f62109e-60cb-11e5-8cca-4d1cbe1f7c79.png)

**Comment by jiru** [comment]
Sorry, this is by design. The default options ("limit to" + everything in the "translations" fieldset set to "any") currently equals to "don’t do any sort of filtering regarding translations", which is, I admit, kinda wrong. If we want this to mean "only keep sentences having translations", then we need to fit yet another option that actually means "don’t do any sort of filtering regarding translations" which would be the default. I’m all ears for form design ideas.

**Comment by ckjpn** [comment]
I think this can be closed.

The second one of these does what I was expecting the other to do.  

Show all sentences by Gillux that have direct translations.
https://tatoeba.org/eng/sentences/search?user=gillux&trans_filter=limit&trans_link=direct&sort=created

Show all sentences by CK that have either indirect of direct translations.
https://tatoeba.org/eng/sentences/search?user=CK&trans_filter=limit&trans_link=any&sort=created
