### ISSUE TITLE
The number sentences shown on the index of lists and the number showing on the actual list aren't the same.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#783]
** The Index of Lists **
https://tatoeba.org/eng/sentences_lists/of_user/CK/manythings

![index of list](https://cloud.githubusercontent.com/assets/7934273/10117624/815a5b12-6498-11e5-9819-d18022b54203.png)

** The List **
https://tatoeba.org/eng/sentences_lists/show/4000

![list](https://cloud.githubusercontent.com/assets/7934273/10117626/88bbf1b8-6498-11e5-86b9-15f0681914f3.png)

**Comment by trang** [comment]
The number that is displayed in "About this list" is the correct one because it really counts all the sentences.

The number displayed in the index of lists comes from a value that is incremented or decremented whenever a sentence is added or removed.

I assume that the difference comes from when duplicates are deleted by Horus. The number of sentences is not updated accordingly so the number of sentences in the index page ends up being higher than the one on the list page.

I've updated the values on the index page with this:
https://github.com/Tatoeba/tatoeba2/blob/dev/docs/database/procedures/create_nbr_sentences_of_list.sql

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on [Tatoeba Day 14](https://tatoeba.org/eng/wall/show_message/25168#message_25168).

**Comment by trang** [comment]
I'm closing this issue.

The rest should be handled in #966.
