### ISSUE TITLE
Make the "Tags" button link to the list of tags.

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#786]
By Hybrid:
> When I'm looking at a sentence, I would like to be able to click on "Tags" to look at this list 
> "http://tatoeba.org/eng/tags/view_all"

**Comment by RyckRichards** [comment]
Requested by Hybrid on [Tatoeba Day 8](https://tatoeba.org/eng/wall/show_message/24346#message_24346)

**Comment by ckjpn** [comment]
There is a "browse by tag" option in the top navigation bar that has this link, so it's already on every page.

I think this issue can be closed.

**Comment by kamillel** [comment]
If this is still required, I think it would be better to have a link 'view all tags' in the tag block instead of making the title as a link, that would be more consistent with the other blocks.

![viewalltags](https://cloud.githubusercontent.com/assets/6699709/14770198/8e2fd788-0a63-11e6-94af-89bfc4805e54.jpg)

**Comment by trang** [comment]
@kamillel, yes. This is actually how it was initially implemented. 

Back then [I removed the link](https://github.com/Tatoeba/tatoeba2/commit/6ae35b84171f80c915a95602122ba5366423daeb#diff-173dbc5353b0f630fadb6e4e0cc27f4dL95) while implementing #674 because I felt the link was redundant with the link in the menu. But it wasn't causing problem or anything, so I think it's fine if we re-introduce the link.

**Comment by ckjpn** [comment]
Here is another possible location for the link.
I'm not sure it's better, but it's something to consider.

![screen shot 2016-04-25 at 09 05 20](https://cloud.githubusercontent.com/assets/7934273/14771407/27f9007c-0ac5-11e6-87d7-e4c2352bc22f.png)

**Comment by trang** [comment]
@ckjpn, I think it's better to have it inside the block content rather than next to the title. There is usually little space in the right-side column, and maybe the translation of "Tags" in some languages is very long, so we wouldn't have space to add a "View all" link and have it all fit in one line.
As far as I know, we online have links in the title in the "main" column, not in the right-side column.

@fadhelafif, to clarify the problem for you, we have a page that lists all the tags: http://tatoeba.org/eng/tags/view_all. This page is accessible from the menu: `Browse` > `Browse by tag`.
One user mentioned it would be more intuitive for him to be able to click on the "Tags" title, on the sentence's details page.
The solution we're opting for is not to have the "Tags" title itself as a link, but rather to add a link "View all tags", like in @kamillel's mockup.
Is this clear enough?

**Comment by ckjpn** [comment]
Perhaps, another option would be to change the name of the menu item from "Browse by Tag" to "View All Tags."

Doing so would mean less clutter on the web page.

**Comment by trang** [comment]
Renaming the menu item doesn't solve the initial problem. 
The `Browse by tag` item is hidden until the user hovers over `Browse`. Users would need to be aware of this item and it may not be intuitive for them. 
The `View all tags` link is always visible on the sentence's page and is placed in a area that is more intuitive for users to navigate to the tags page.

I don't think we need to worry too much about cluttering the page. It's only a small link.
