### ISSUE TITLE
Unicode symbols not working for Choctaw

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#791]
As reported by Choctaw_Irish on the wall:

"I am contributing sentences and translations in Choctaw (Chahta anumpa), but the standard orthography of putting a macron below nasal vowels is not working. I have not found any Unicode characters for vowels with macron or line below. When I try to use a combining character (U+0320, U+0331, U+0332), the line extends beyond the vowel and looks bad:
a+0320 = a̠
a+0331 = a̱
a+0332 = a̲
These vowel+unicode combinations look good in other webpages & Unicode-compliant apps like Notepad, Word, etc. But for some reason they don't display properly on any of the Tatoeba pages. I have taken to using a non-standard macron "above" the vowel (ā) to indicate nasalization until this issue can be resolved."

https://tatoeba.org/ita/wall/show_message/24368#message_24368

**Comment by Rajzin** [comment]
Copying my comment from the wall, because I think it has relevant information for finding the problem.

"I'm afraid this problem is not specific to Tatoeba. I have had the same problem when combining IPA diacritic characters with normal letters on another site.

If it does work on some other sites, maybe it has something to do with fonts or something? I thought at first maybe it was a problem with the browser, but Chrome, Firefox, and Internet Explorer all display it the same for me."

**Comment by jiru** [comment]
> the line extends beyond the vowel and looks bad
> These vowel+unicode combinations look good in other webpages

Could you define “good” and “bad” by attaching some screenshots?

**Comment by jiru** [comment]
Sorry, I’m gonna ask on the Wall.

**Comment by sven-oly** [comment]
I wonder if the problem is just the font(s) you are using. Some do not handle unusual combinations of base letters and diacritics, or display them with poor positioning.

Tatoeba may just be using fonts that don't work well with these combos. It might be worth using a browser inspector to figure out the font being used for display.

**Comment by trang** [comment]
For the record this is what Choctaw_Irish was seeing:

![5487643c5e90515c9934f356d4a4fc6d](https://user-images.githubusercontent.com/221850/43372846-9d74dfae-93a5-11e8-97bb-fc41235babd4.png)

I confirm it displays that way with the font Trebuchet MS, which was our default font back then. We changed the font a while ago (#1245), I don't think this is a problem anymore.
