### ISSUE TITLE
Trusted users ( "friend list" )

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#794]
https://tatoeba.org/eng/wall/show_message/24381#message_24381

Tatoeba is not a social network such as Facebook or Twitter but people work there, not machines. I mean, we do have friends there which we can trust and so, it would be good if each user has a "friend list" (or trusted user list). That way everyone would add people there that them would like to translate sentences and correct eventual mistakes, if necessary. It would so make Tatoeba even more trustable and we would have even more good sentences.

**Comment by ckjpn** [comment]
What you want could likely easily be accomplished by just changing the advanced search to allow searching for sentences by more than one username at the same time.

For example instead of just being about to search of Japanese sentences not yet translated into English that are owned by "bunbuku, like this:
https://tatoeba.org/eng/sentences/search?query=&from=jpn&to=und&orphans=no&unapproved=no&user=bunbuku&tags=&has_audio=&trans_filter=exclude&trans_to=eng&trans_link=direct&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random
... I could search for Japanese sentences not yet translated into English by more than one Japanese native speaker, like this:

bunbuku, mookeee, tommy_san, arnab

I think there is already an issue that asks for this.

**Comment by RyckRichards** [comment]
Sure:

let's picture this situation first

Imagine that I'm User1 and for some reasons, I really like User2, User59, User 9002 and User15003.

So as far as I consider them as my "friends" (or "best coworkers", coworkers I trust in), I would

1st - "add" them on my friend list (that would be my trusted list also once they are my "friends", so I can trust them. 

2nd - I would check (a page that would be created, maybe) everyday (or always I  log in on Tatoeba) and read User2, User59, User 9002 and User15003's sentences.

3rd - Then, I will translate User2, User59, User 9002 and User15003's sentences first or that would be my priority. It doesn't mean that I won't translate anyone else sentences, but that I'd feel more comfortable if I translate "my friends'" sentences.

On this way we
--> Would have more natural sentences (once I'd be even more careful when translating my friend's sentences);
--> Would have an even more "friendly atmosphere" for ourselves once we know we have friends or people we can trust in and that we feel even more confortable to ask something, for example (explanation about a specific word, grammar, links, etc)

**Comment by ckjpn** [comment]
Even though this one has been accepted, I wonder if it is necessary.
I would at least suggest listing this as a low priority issue.

**Comment by trang** [comment]
I removed the status accepted. All the "status:accepted" issues were part of a somewhat experimental process. The label "status:accepted" is therefore currently not reliable to say that an issue really has been accepted.

**Comment by trang** [comment]
I'm planning to close this issue.

A similar idea has been considered several years ago. There was a beginning of implementation but it has been abandoned.
https://github.com/Tatoeba/tatoeba2/commit/dfc4af1768e5ed3d434ff4f127cfb2cb232cc585#diff-6e47989cc4220f3476fb940934024107
​
There was no motivation to finish this feature because we have no real need to implement social network features.

If users want to establish friendship with other users, they can exchange Facebook, Twitter or other social network information via private message, and use these other platforms for socializing.

If contributors want to translate sentences from other contributors that they trust, they can visit each profile manually and use the "Translate sentences of {user}" page.​

**Comment by RyckRichards** [comment]
Actually, it wouldn't be a "social feature" on Tatoeba but a(nother) way to translate sentences from without having to visit each member's page which we trust every single time we want to translate their sentences.

1st - We would have to go to this member's page and check the "check this member as reliable" or something like this in order to "collect members we trust and we would like to translate sentences from";

![001](https://cloud.githubusercontent.com/assets/7658430/13886980/4ce12786-ed18-11e5-8a3a-25ecc9d17b87.PNG)

Then we could have

![002](https://cloud.githubusercontent.com/assets/7658430/13887200/31cf14b6-ed19-11e5-9025-427a5208ad10.PNG)

and /or 

https://tatoeba.org/eng/sentences/search?query=&

![003](https://cloud.githubusercontent.com/assets/7658430/13887524/dbc5010a-ed1a-11e5-8211-2a40b973e241.PNG)

**Comment by RyckRichards** [comment]
Selena [suggested something pretty similar to this](https://tatoeba.org/eng/wall/show_message/24056#message_24056):

> I suggest to make it possible for every user to create their own private lists of contributors and display the sentences, added only by the contributors from the certain list (now we can only browse the sentences, added by one single contributor, but not by the group of contributors). For example, "Native British English contributors", "The German contributors, I like the most", and so on. Also it would be possible to display all the sentences in the language, excluding those, added by contributors from the certain "black" list (like "Chinese contributors, which style I don't like"). I suppose those lists only for private personal usage, so it's not any kinds of ratings, but the feature for user's commodity.

**Comment by trang** [comment]
As are reminder, our guidelines about submitting issues say to [focus on describing the problem](https://github.com/Tatoeba/tatoeba2/wiki/Guidelines-for-submitting-issues#focus-on-describing-the-problem). So I'm going to write what I believe is the problem, and I'll write it as if I was you. You can tell me if I'm correct or not, and if I'm missing something.

**Problem**
There are several people on Tatoeba that I consider to be good contributors and I like to browse their sentences when I'm looking for sentences to translate. Most of the sentences I translate are sentences from these contributors.
It is however not very practical to go through each profile one by one in order to check if they have added any new sentence that haven't been translated into Portuguese yet. It would save me time if all their sentences were displayed in one same page.

**Comment by ckjpn** [comment]
This problem could be solved by making it so the advanced search could search for sentences by more than one member at a time.

As mentioned above.
https://github.com/Tatoeba/tatoeba2/issues/794#issuecomment-144334191

Once someone like RyckRichards entered all his favorite member's usernames and did a search, he'd only have to bookmark the URL and access the bookmark anytime he wanted to see those sentences.  

Related issue: https://github.com/Tatoeba/tatoeba2/issues/797

**Comment by RyckRichards** [comment]
Selena left this message:

> I don't have an account there, so I can't comment there, but I read the discussion, and I think it would be much better for an user to create the lists once and use those prepared lists every
time he or she needs, than make such lists every time, like CK suggested.

**Comment by trang** [comment]
Closing this issue, to avoid having issues lingering too long. I'll keep the suggestions in mind and will create new issues when the use cases become clearer.
