### ISSUE TITLE
Welcoming new users

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#796]
Why not welcome them? We usually dont do it unless this user comits a typo, for example. Actually, there are on the home page

- Random sentences
- latest sentences
- latest contributions
- latest comments

Why not add "latest users" or something like that? All of us would welcome him/her easily on that way.

**Comment by ckjpn** [comment]
You can easily see new members with this link.
https://tatoeba.org/eng/users/all/page:1/sort:since/direction:desc

I'm not sure if it would really be useful to make a big deal out of welcoming all new registered members, since we get a lot of people registering who never contribute anything.

If, somehow, we made if clear to visitors that they didn't need to register unless they were planning to contribute, then this might be something useful to do.  Or, perhaps, create a list of new members who have actually contributed at least one or two sentences.

**Comment by RyckRichards** [comment]
That would avoid it, @ckjpn  since they may fell that many people can help them and it's easier also to ask for help.

**Comment by ckjpn** [comment]
The way I notice new contributors is that I use Stylish to change link colors.  I use the old standard blue for links and purple for visited links.  If I see a blue link to a username on the list of incoming visitors, I know that I haven't seen that visitor's profile page yet (... actually "not recently.")  I can then welcome that visitor.  I used to do so via private message, but since private messages sometimes don't display links correctly (another issue), I find it's better to post the message on one of their sentences.

Perhaps, doing something as simple as making the link and visited link color different would solve this problem for those who pay attention to this kind of thing and frequently look at members' profile pages.  (With CSS, it would be possible to limit this to just usernames, or even just usernames appearing on the "recent contributions."

**Comment by trang** [comment]
I'm planning to close this issue because it is too unclear.
