### ISSUE TITLE
Autodetection of languages not working properly

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#805]
When adding a sentence in a foreign language, it gets autodetected as Italian, even if words are clearly not Italian. An example: https://tatoeba.org/ita/sentences/show/4586714
I changed the flag manually, but initially it was in Italian.
Another issue is with very short sentences, which get autodetected in another language. For example, these sentences were recognized as Latin, even if they're in Italian:
https://tatoeba.org/ita/sentences/show/4586875
https://tatoeba.org/ita/sentences/show/4586827
https://tatoeba.org/ita/sentences/show/4586756
https://tatoeba.org/ita/sentences/show/4586755

**Comment by Guybrush88** [comment]
A thing I noticed, also for other users, is that the auto detection uses mostly the language in which the user mostly contributes, and not the proper language. For example: I contribute mostly in Italian, and, when adding a sentence in French or in English, this sentence is recognized as Italian, even if it clearly isn't

**Comment by RyckRichards** [comment]
Requested by Guybrush88 on [Tatoeba Day #9](https://tatoeba.org/eng/wall/show_message/24478#message_24478)

**Comment by sacredceltic** [comment]
J'ai signalé auparavant que les apostrophes ne semblent pas prises en compte dans la détection, alors que la position des apostrophes et leur fréquence est très caractéristique d'un language. Je remarque donc que les phrases très courtes comportant des apostrophes sont très souvent mal identifiées.

**Comment by trang** [comment]
The language detection tool takes 2 parameters: the text and the user.
I've removed the "user" parameter so that the result of the auto-detection doesn't get influenced by the quantity of sentences that a user has contributed in a certain language.

The other issue, about very short sentences not being recognized in the correct language, is not something that can be fixed in Tatoeba itself. It needs to be fixed in [Tatodetect](https://github.com/Tatoeba/Tatodetect).
