### ISSUE TITLE
Create an "Annotation:" field in addition to the "Comments", many of which are aimed at correcting errors.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#808]
It would be useful to have comments that are annotations separated from comments that are aimed at correcting sentences.

** Possible approaches to doing this **

- have more than one comment form
-- corrections
-- annotations

- have one comment form, but include an SELECT dropdown menu to choose what kind of comment it is.  This would allow the possibility of have more types of comments without cluttering the page.
-- corrections
-- clarifying the meaning
-- annotations
-- related
-- etc.

The following is something I put together to show sysko a long time ago.
It doesn't look that good because the CSS files on tatoeba.org have changed since I create the demo.
However, you can sort of get one idea how this might be done, even though this probably isn't the approach I would try now.

http://a4esl.com/temporary/tatoeba/ideas/comment-radio-buttons.html

**Comment by RyckRichards** [comment]
@ckjpn  Awesome

[1] Isn't a checkbox better than a Select dropdown list once we might, for example, correct and include  an anottation on sentence? and [2] if we're going to add two different kind of comments, wouldn't be better to open two different "fields" to do so - maybe opening a new tab?

**Comment by ckjpn** [comment]
Radio buttons are better than checkboxes, since they are limited to one choice.
I like the radio button idea, too, which is why my original demo had it that way.
The advantage of a dropdown select menu, is that it makes it possible to have more choices without cluttering up the page. Perhaps we don't need this possibility.

**Comment by RyckRichards** [comment]
I see!

**Comment by RyckRichards** [comment]
+1,000 Would it be too hard to implement, @Tatoeba/tatoeba-team ?

**Comment by jiru** [comment]
> Would it be too hard to implement?

I think it’s not particularly difficult, though it can easily take some time. The main difficulty I can see is that what needs to be done is still not clearly defined. We need to come with a precise idea of how it would be done and used by members so that it’s convenient, efficient etc. *before* starting an implementation.

**Comment by ckjpn** [comment]
Briefly, I think we need at least 2 types of comments.

1. Temporary
- Things that wouldn't really be useful for students that use the sentences for study.

- Discussions and clarification on meaning before translations are made.
- Things aimed at corrections.
- Discussions that have nothing to do with the sentences, and people complaining about things.


2. Permanent and worth exporting for possible use with projects that use our data.
- Annotations that help students of the language understand things.

-- Annotations:
-- Related:
-- Contrast with:
-- Same pattern:


I think Trang originally thought of comments as only number 1 above, but I think we could easily expand this to be more useful.

**Comment by trang** [comment]
​​
I've never thought of comments as temporary.

Comments were implemented simply to make it easier for users to communicate
around sentences (to ask a question, to write explanations, to report
mistakes, etc) and every comment may be useful in a way or another to more
or less people.

> Things that wouldn't really be useful for students that use the sentences
for study.
>
> -- Discussions and clarification on meaning before translations are made.
> -- Things aimed at corrections.

I actually consider those two things to be useful or interesting for people
who study languages.

> -- Related:
> -- Contrast with:
> -- Same pattern:
> -- Similar:

What you are suggesting here are not comments but new types of link. At the
moment we have only one type of link, which is "is translation of".

Anyway as @jiru said, the difficulty here is to define what really needs to
be done. I understand the idea that we need to categorize comments so that
users can more easily filter out a certain type of comment that may not be
useful for them.

But how do we do it so that users will understand how and when to use each
category? How do we deal with comments that were not properly categorized?
What categories do we really need to handle?
​​
The topic of this issue is
​specifically ​
to separate comments that are aimed to suggest corrections from other
comments.
​For this particular case, the question is, does it often happen that users
need
​/want​
to filter out suggestions of corrections?
​ Can it happen​ that users will actually feel bothered by this separation?

**Comment by trang** [comment]
I'm planning to close this issue because it suggests a solution for a problem that is not clearly identified.

It would be good to find concrete examples of sentences that have comments that illustrate the problem(s) with our current comment system.

**Comment by ckjpn** [comment]
The problem is that for those of us with lots of sentences, the comments suggesting corrections get mixed in with a lot of general comments and unrelated discussions, so they get overlooked.

I thought this might be a way that would help ensure that needed corrections would get made.

**Comment by trang** [comment]
I've added your problem to #1046.
Closing this issue. We can discuss solutions in #1046 instead of here.
