### ISSUE TITLE
Add a button to message someone while commenting on his/her sentence

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#812]
It might be be good and useful to have this once we would be able to

--> Talk about things unrelated to the sentence;
--> Allow us to talk about a grammar mistake, for example (something that may hurt the user if exposed publicly) 

![add button to message someone on](https://cloud.githubusercontent.com/assets/7658430/10414455/456bacd6-6fac-11e5-9860-76d03ac9c03f.PNG)

**Comment by trang** [comment]
I'm planning to close this issue because I consider that for this case, it is not worth to burden the sentences menu with yet another button.

Adding this button will only save one click, for something that is not done so frequently. Currently, users can:
1. Click on the username. They will be redirected to the owner's profile.
2. From the profile, click on "Contact {user}" in the side bar.​
