### ISSUE TITLE
Send an automatic message to inactive users.

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#813]
There are too many inactive users on Tatoeba. It means that many sentences haven't been corrected and they don't "belong" to anyone once those sentences are still "linked" to those users' profiles.

Maybe we could send an automatic email to him/her when "Logs of user's contributions" > 45 days. So s/he would have 15 days to log in again and contribute or reply to the admins asking to delete his account (we count set it as "inactive). In case s/he doesn't reply 15 days after this automatic email, we'd set this account as inactive.

**Comment by trang** [comment]
​I'm closing this because it mixes two different problems and both problems need more analysis.

The first problem (the fact that some users become inactive and don't correct their mistake) can be discussed in #1046.

The second problem, which is about setting certain users as inactive based on when they last contributed, would need more clarification and should probably be discussed on the Wall first, to come up with a clear problem description.
