### ISSUE TITLE
Bodo (brx)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#865]
* Language name: Bodo
* Language info: https://en.wikipedia.org/wiki/Bodo_language
* ISO 639-3 code: brx
* Public List: https://tatoeba.org/eng/sentences_lists/show/4830
* Icon: https://drive.google.com/file/d/0B5_jtoG7OkkpVm1kcDd6aVFxR00/view?usp=sharing
* Requested by: https://tatoeba.org/eng/user/profile/ramenro96

**Comment by sabretou** [comment]
I don't think that flag is appropriate. For one, it is the emblem of Assam, and Bodo is only a minority language spoken there. Secondly, because the letters are illegible, it looks like the Emblem of India, which is even more generic. And finally, it's not a very attractive flag.

Luckily then, I've created a more colourful flag: https://drive.google.com/file/d/0B5_jtoG7OkkpVm1kcDd6aVFxR00/view?usp=sharing

**Comment by RyckRichards** [comment]
Thanks a lot, @sabretou !!!!  You're the best!!!

**Comment by lagleki** [comment]
Can we clarify the name of this language to separate it from the language with ISO 639-3 code ''boy'' (Bodo (Central African Republic))?

**Comment by sabretou** [comment]
We can perhaps name the languages as:
Bodo (India)
Bodo (CAR)
