### ISSUE TITLE
Advanced Search - Counts of Results Are Not Correct

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#901]
https://tatoeba.org/eng/sentences/search?user=catmint&trans_filter=limit&trans_link=direct&sort=created

3 results shown - the heading says 8.
![screen shot 2015-11-03 at 08 37 57](https://cloud.githubusercontent.com/assets/7934273/10897641/7c78a668-8206-11e5-9501-d686cc1a40fd.png)

This user seemed to have 6 sentences, in all languages.
![screen shot 2015-11-03 at 08 38 32](https://cloud.githubusercontent.com/assets/7934273/10897644/84f6900c-8206-11e5-8d36-fb3fc587363b.png)

**Comment by trang** [comment]
I can't reproduce the problem. The number of sentences has increased to 27, and it's the correct count.

**Comment by ckjpn** [comment]
Perhaps it only occurs when the counts are less than 10.
It's not really a big bug, so it can possibly just be ignored, especially if it doesn't occur most times the page is accessed.

**Comment by jiru** [comment]
Such inconsistencies may appear during a limited period of time after a sentence is deleted or its language is changed (or maybe some other action I havn’t figured out yet). The problem is that the data indexed for search purposes (result count) differs from the real data (actual results). Weekly main reindexation fixes the problem, which is why the problem is not visible any more. I tentatively improved things a bit so that delta reindexation (which is currently performed every 20 minutes) should fixes the problem as well.
