### ISSUE TITLE
Have the auto-detect for languages only choose from languages listed in a member's profile and then default to the member's declared native language when it can't figure out what the language is.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#905]
Have the auto-detect for languages only choose from languages listed in a member's profile.
If the script still can't figure out the language, then default to the member's declared native language.

I think Sysko wrote the auto-detect script before Trang added the "register languages" feature, so he wasn't able to take advantage of this extra information at that time.

This should help make the detection more accurate.

Related Wall thread:
https://tatoeba.org/eng/wall/show_message/24789#message_24789

**Comment by trang** [comment]
I'm planning to close this issue. Improvements regarding the language detection should rather be submitted in the Tatodetect repository: https://github.com/allan-simon/Tatodetect

I don't think we should restrict the auto-detection to a user's profile because we have no certainty that a contributor will contribute only in the languages listed in their profile. There is a higher possibility that they do, but they could contribute in any language.

I don't think either that we should set the language to the user's native language by default. If the language detection tool cannot detect the language, then it just can't, and there needs to be a human intervention to set the proper language.

**Comment by sacredceltic** [comment]
I disagree. Since the detection scheme is based on statistics, I think we could at least, in the detection algorithm, weigh up the probability that the language is within the profile languages. You could, for instance, double the probabilities for these languages. If the stat was zero, then 2 x 0 = 0, so if won't affect the detection.

**Comment by trang** [comment]
I didn't mean to say we shouldn't take the user's languages into account. I was saying we shouldn't make it strictly restricted to the users languages.

CK's suggestion is "Have the auto-detect for languages only choose from languages listed in a member's profile". It's the *only* that I don't agree with.

I completely agree with adapting the probabilities based on the user's languages.

**Comment by sacredceltic** [comment]
Remember that wrong detection is a strong deterrent to newcomers, who think the service doesn't work properly.
Everything that can improve detection is a must. To start with, I don't think the ngram stats are up to date, because I don't see it improving along with the size of the corpus, as it should.

**Comment by trang** [comment]
> To start with, I don't think the ngram stats are up to date

Yes, I confirm. As far as I know, the last time the ngrams were updated was back in November 2014.
https://groups.google.com/forum/#!msg/tatoebaproject/cL2_mI3kty8/M6SrXgbj3UMJ

**Comment by halfdan** [comment]
> I think we could at least, in the detection algorithm, weigh up the probability that the language is within the profile languages. You could, for instance, double the probabilities for these languages. If the stat was zero, then 2 x 0 = 0, so if won't affect the detection.

Tatodetect does already do this. The factor is 100.

The ngrams.db can easily be regenerated.

I wonder however whether we should simply replace Tatodetect with https://github.com/crodas/LanguageDetector. We could run a comparison between the two and compare the detection reliability.

**Comment by trang** [comment]
Closing this since we won't implement it.

Taking notes on alternative for language detection. We'll see about that when users start to complain about the accuracy of our current language detection.
