### ISSUE TITLE
Increase the limit of sentences downloaded from a list

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#927]
By [PaulP](https://tatoeba.org/eng/user/profile/PaulP) - https://tatoeba.org/eng/wall/show_message/24895#message_24895

> The download feature has been disabled for this list because it contains X sentences. Only lists containing 100 or fewer sentences can be downloaded. If you can edit the list, you may want to split it into multiple lists.
> 
> Is there an easy way to do this, other than deleting the sentences one by one?

**Comment by RyckRichards** [comment]
+1
It would help a lot - even more students.

**Comment by ckjpn** [comment]
If the main reason this is limited to 100 sentences is to lower the load, then perhaps you could allow downloading the whole list if it's just the sentences without linked translations, but only limit the download if it requires linking to another language.

Also, perhaps create the option to allow people to download the complete list as numbers only without translations.  I have found there are times I wish I could do this rather than wait for the weekly exports to get this information.  Maybe this wouldn't put too much load on the system.

**Comment by ckjpn** [comment]
Another possibility is to allow downloading the complete list incrementally, sort of like you get it if you browse the pages.

Download the first 100.
Download the second 100.  (201-300)
Download the third 100. (301-400)
etc.

**Comment by RyckRichards** [comment]
Paul says that he use the lists he create to study. After creating a list, he exports them to his phone which he can easily study and as far that it's only possible to download lists which have 100 entries, he have to chop them into many other lists which demand too much time and effort.

**Comment by trang** [comment]
How many sentences does Paul have in his lists?

**Comment by RyckRichards** [comment]
3-5,000 of sentences .

**Comment by jiru** [comment]
For the record, I think it’s possible increase the limit tremendously without significantly increasing the server load, by using the following approach:
* In the controller method:
 * Increase the PHP script timeout
 * Get sentences using successive paged queries (to avoid filling up RAM)
 * Output the CSV already, instead of passing data to the view (necessary because of paged results)
