### ISSUE TITLE
@username can produce multiple notification emails

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#932]
[Reported by tommy_san](https://tatoeba.org/jpn/wall/show_message/24958#message_24958).

> When someone writes my username in a comment to my sentence or a sentence where I also posted a comment, I get two email notifications. When someone mentions me there twice, I even get one more notification. This needs to be changed.

**Comment by wellsyw** [comment]
I think this patch (untested) might fix it.
 
http://pastebin.com/9CqALHEW

**Comment by jiru** [comment]
wellsyw, thank you for your patch but it would be better if you test it before sending. Another problem that comes to my mind is that we’re using different email templates for each notification type. With you approach, only the first notification would get through and the email template wouldn’t convey correct information about the origin of the notification.

Looking at how Github handles this, it just has one very simple email template with the title of the issue as subject, the comment as content and a link to it as footer. We should use a similar approach.

**Comment by wellsyw** [comment]
I fail to see the problem about templates.

There are two notification templates. One goes to people who either own the sentence or have commented on it. One goes to people who have been @mentioned

This is suppressing the latter e-mail if the former has been sent. Which is the whole point of this bug, is it not?

**Comment by wellsyw** [comment]
Or did you mean that the "why was this e-mail sent" should be stripped out of the templates? Or should an e-mail list all the reasons it was sent?

**Comment by jiru** [comment]
> Or did you mean that the "why was this e-mail sent" should be stripped out of the templates? Or should an e-mail list all the reasons it was sent?

Yes. If someone mentions me in a comment of a sentence of my own, what is the reason of the notification? Is it because I have been mentioned, or is it because someone commented my sentence? It’s both, so neither of the current email templates fit.

Having said that, it’s not a serious problem if we just use the “commented a sentence” template in that case, like you did.

Having a unique wordless template would also work around the problem that notifications are not localized.

That said, we have private messages while Github doesn’t. A unique template may add confusion between private and non-private messages. It is often that people exchange private messages along with a public discussion.

**Comment by wellsyw** [comment]
There are two or three templates used.

a) you own the sentence -- you get an e-mail
`"xyz has posted a comment on one of your sentences."`
b) you commented on the sentence -- you get an e-mail
`"xyz has posted a comment on a sentence where you also posted a comment."`
c) you were mentioned -- you get an e-mail
`"xyz has mentioned you in a comment."`

First hit supersedes the following ones, as it was before the mentions system existed. I don't really see why that should be changed. You did not get an e-mail that lists "you own this sentence and you commented on it" before either. As such, I don't even consider the proposed change to have the "wrong template" -- it certainly is *a* correct template.

It can be argued though that because there was a mention happening, it should be somehow highlighted, but the comments tend to be so short that adding such a highlight (whether in the subject or body) would not really add anything for the receiver.

Or it could be argued that the mentions should be pushed upwards in priority, which is doable but the code needs much more massaging.

**Comment by jiru** [comment]
Yes, you’re right.

**Comment by trang** [comment]
@wellsyw, thank you very much for tackling this issue. Is this just a punctual intervention or do you have plans to contribute more code for Tatoeba in the future?
I'm asking because if you do have plans to contribute more code, it will be better that you make a pull request here, as well as installing Tatoeba on your machine so that you can test (and if you need assistance for that, simply let me know).
But if it's just a one-time contribution it might be too much overhead.

> Looking at how Github handles this, it just has one very simple email template with the title of the issue as subject, the comment as content and a link to it as footer. We should use a similar approach.

Yes, I​'m in favor of simplifying our templates and do something similar to what GitHub does. Instead of having 3 templates we could just have something like:
​`​xyz has posted a comment on sentence "Some sentence" (#123).`
I don't think it would confuse too much our users if we don't indicate exactly why the notification was sent.

**Comment by wellsyw** [comment]
I do not have plans to contribute more, though I may tackle an issue once in a while if one affects me and it looks easy enough to solve.

**Comment by theblindspring** [comment]
I will try to work on this.

**Comment by theblindspring** [comment]
Should we internationalize the strings in the email template? Like in app/views/elements/email/html/comment_on_sentence.ctp:
`echo $html->tag('p', sprintf('%s has posted a comment on one of your sentences.', $author));`

**Comment by trang** [comment]
That would be the scope of another issue. We can't internationalize the strings in the email the same way we do for the UI. In the case of email notifications, we need to retrieve the language of the recipient. If we use the `__()` function, the notifications would be written in the author's UI language.
