### ISSUE TITLE
An app to record audio

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#940]
By [markpalmer](https://tatoeba.org/eng/user/profile/markpalmer) on ]Tatoeba Day #12](https://tatoeba.org/eng/wall/show_message/24988#message_24988)

>I'm a new contributor and I'd like to know if there is an app for recording. I use my tablet 100%. This is a fantastic web page for learning other languages, so I'd love to contribute for this amazing tool.

It would help everybody to add even more sentences (correct, comment, etc) since we'd be able to do it everywhere and we use devices so much nowadays.

**Comment by trang** [comment]
@RyckRichards, I've changed the title of the issue because from my understanding, what markpalmer was asking for is an app for recording audio. Not an app for Tatoeba.

I'm hesitating to leave this issue open or not because the scope is too large.

* I wouldn't call this an enhancement. It's a project on its own, to code a separate app, for mobile/tablets.
* Having this app also depends on whether or not we decide to accept audio with lower sound quality.
* And of course it depends if we can set up the proper infrastructure for users to contribute audio seamlessly, i.e. they record audio from their app and it goes right away into Tatoeba. This is something we don't have for people who use computers, and there is a huge amount of work there, for this to be possible.

**Comment by RyckRichards** [comment]
I see your point. Maybe the admins can divide members (after listening) in

► Members allowed to record
► Members not allowed to record

And point on Tatoeba in

"HD" audio
"good audio"

or even let members to rate them.

On 11/28/15, Trang <notifications@github.com> wrote:
> @RyckRichards, I've changed the title of the issue because from my
> understanding, what markpalmer was asking for is an app for recording audio.
> Not an app for Tatoeba.
>
> I'm hesitating to leave this issue open or not because the scope is too
> large.
>
> * I wouldn't call this an enhancement. It's a project on its own, to code a
> separate app, for mobile/tablets.
> * Having this app also depends on whether or not we decide to accept audio
> with lower sound quality.
> * And of course it depends if we can set up the proper infrastructure for
> users to contribute audio seamlessly, i.e. they record audio from their app
> and it goes right away into Tatoeba. This is something we don't have for
> people who use computers, and there is a huge amount of work there, for this
> to be possible.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tatoeba/tatoeba2/issues/940#issuecomment-160288447


-- 

Ricardo Vernaut Jr

Mobile // Celular: (5521) 967-640-668
Email: rvernautjr@gmail.com
<https://www.linkedin.com/in/vernautjr>

**Comment by trang** [comment]
I'm planning to close this issue for the reasons I mentioned in my previous comments. If anyone feels this should not be closed, please let me know before the next Tatoeba Day (March 20).

**Comment by RyckRichards** [comment]
As far this would be a different project, I think it can be closed and added into another folder, maybe.
