### ISSUE TITLE
Lists don't show audio icons like other similar pages do.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#948]
Perhaps it would be a good idea to add the audio icons in.

https://tatoeba.org/eng/sentences_lists/show/996/und
![screen shot 2015-12-06 at 09 59 26](https://cloud.githubusercontent.com/assets/7934273/11611115/2c877698-9c00-11e5-9891-097ffc19a1ac.png)

**Comment by jiru** [comment]
Hiding the audio icons is not a bug, it’s a feature. I know it’s deliberate, but I don’t know the reason it’s like this.

I think, too, that audio icons should be displayed in lists as well because [some lists](https://tatoeba.org/sentences_lists/show/4023) gather sentences with audio.

**Comment by trang** [comment]
As far as I can remember, lists were implemented before we had audio. When audio was introduced, it didn't make sense to display an audio icon in the lists because 99% of the time, there would be no audio. I believe that's the main reason why the icon was not displayed in the lists initially (basically to not pollute the lists with a useless icon).

Things have changed now, so yes, we should consider adding this icon in the lists.
