### ISSUE TITLE
Khitan (zkt)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#962]
- Language name: Khitan
- Language info: https://en.wikipedia.org/wiki/Khitan_language
- ISO 639-3 code: zkt
- Public List: https://tatoeba.org/eng/sentences_lists/show/5052
- Icon: http://i.imgur.com/zw6PptJ.png
- Requested by: https://tatoeba.org/eng/user/profile/SevernayaPustota
# 

[for dev.tatoeba.org]
CALL add_new_language('kek', 4210);

[for tatoeba.org]
CALL add_new_language('kek', 5052);

http://dev.tatoeba.org/eng/sentences_lists/show/4210

**Comment by RyckRichards** [comment]
**Personal note**: To wait

https://tatoeba.org/eng/sentences/show/4749471#comment-767836 
![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/12170211/68377636-b526-11e5-9949-7d5b63d055fc.png)

**Comment by RyckRichards** [comment]
SevernayaPustota's reply



![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/12171836/26691b16-b534-11e5-887c-e8a7a6a2d450.png)

**Comment by RyckRichards** [comment]
@SevernayaPustota 's suggestion:

> ISO 639-3 - zkt
> https://en.wikipedia.org/wiki/Khitan_language
> no official or used flag, but a few people have suggested http://i.imgur.com/zw6PptJ.png

He says that this language hasn't been recognized both by linguistics and Russians and so, it hasn't any standard caligraphy. As cueyayotl suggested, I'll wait he posts more sentences before adding it.

**Comment by cueyayotl** [comment]
This user SevernayaPustota's posts sound suspiciously like user UmNui's posts, in which they claimed that they spoke a Japanese dialect from Inner Mongolia. Much to our disappointment, tommy_san and I debunked their claims. Now we have this user claiming that they speak a direct descendant of the Khitan language, which has somehow eluded both national and international linguists all these years. We know what happened to the Khitan people and we know what languages their descendants speak nowadays. The sentences this user has contributed DO have somewhat of a Mongolic feel to them, so we have left them alone, at least for now.
I post them here, just in case:
1) "Орҭографія қюўз бул." - "Орфография очень важна." (Orthography/Spelling is very important.)
2) "Ңа эннэндь ба җэўшаб." - "Я этим недоволен." (I am displeased/dissatisfied by this/that.)
3) "Жуўң алағынд қэўнрід чішт!" - "Don't mistreat small animals!"
4) "Сайң!" - "Hello!"

Analyses and thoughts:
1) I question the number of special Cyrillic characters used here. Also is the "ҭ" representing an aspirated /tʰ/ ? It seems strange, given that a vowel follows. The syntax does seem Mongolic, with "бул" a possible copula. I suppose "қюўз" would mean "очень важно" (very important).
2) We don't know the pronouns of Khitan, though "Ңа" /ŋa/ has been reconstructed as a Proto-Altaic first-person singular pronoun, but at the time Khitan split from Proto-Mongolic, I believe it would more likely have been "nam" or "nad". "эннэндь" is plausible for "this" in the dative case.
3) "Жуўң" reminds me of Mongolian "ᠥᠴᠦᠬᠡᠨ" [өчүүхэн] (small) or even "ᠴᠥᠭᠡᠨ" [цөөн] (few), though I read in a couple of research papers by Shirō Hattori (服部四郎) and Masayoshi Nomura that Proto-Mongolian would not have had long vowels. I wonder why "алағынд" appears to be in dative case, as "mistreat" usually takes the accusative case in Mongolic languages.
4) This is the weirdest one. "Сайң" is clearly the word for "good". It is used as a greeting in various Mongolic languages, but usually as a question, and of course, with an interrogative particle.

Khitan was written in two distinct scripts: Small and Large Scripts. We could allow this language to be written in Cyrillic only because we do not yet have the native scripts added to Unicode. This person clearly did some research, and may actually speak a Mongolic language natively (which I wish they would have added instead), but I do not believe they are being sincere about this language. It may even be a troll testing to see how gullible the Tatoeba community is.

If no one has anything more to add, or if anyone objects, I will delete these four sentences soon (maybe in a month or so, if no one else deletes them before me).

**Comment by bashbashy** [comment]
These sentences puzzle me. The Mongolic-Turkic continuum in Xinjiang is sometimes collectively called Khitan but these sentences are not enough to tell if it's some of that, and there are issues even ignoring that Cyrillic is usually not used.
1) The word for "orthography" is "имла" using Cyrillic - I have never heard the word "қюўз" - "бул" means "to be" in any person but is used only for emphasis or questions.
2) Normally "би" or "мэн" is used - "ңа" is super formal, it's the pronoun that was probably used by khans - I've never heard the word "җэўшаб".
3) This sentence makes no sense to me at all.
4) Cueyayotl is right, it means "good" - it can be used as "hello" but more often "bye".

**Comment by sabretou** [comment]
This issue can be safely closed now as we do not even have any relevant sentences from the requesting user in the corpus anymore. The language will not be added at this point.
