### ISSUE TITLE
Shortened links are sometimes incorrect

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#963]
The function to make links display in less space doesn't always work correctly in email messages.

This may be limited to php links with a ? mark. I'm not sure.

![screen shot 2015-12-31 at 09 11 04](https://cloud.githubusercontent.com/assets/7934273/12059454/bd6412f0-af9e-11e5-97dc-00e4a8491aa9.png)

**Comment by ckjpn** [comment]
The same kind of link works OK in comments.

![screen shot 2015-12-31 at 09 26 27](https://cloud.githubusercontent.com/assets/7934273/12059548/addad1aa-afa0-11e5-9ae0-074fdab3f858.png)

**Comment by ckjpn** [comment]
Note that for this kind of shortening of the clickable part of the URL, you could first eliminate the "http://" or "https://" part at the beginning.  It's not necessary for it to be displayed on the surface of the page.

**Comment by ckjpn** [comment]
This isn't exactly the same, but it may be related.

Long link texts are cut inside HTML entities #698

**Comment by ckjpn** [comment]
This same bug appears on the Wall, too.

https://tatoeba.org/eng/wall/index#message_25519
![screen shot 2016-02-16 at 19 37 34](https://cloud.githubusercontent.com/assets/7934273/13073976/134bdc8c-d4e5-11e5-905b-5a875ffdac79.png)

**Comment by ckjpn** [comment]
Perhaps this will help you figure out the problem.

There are 2 similar GitHub links, one works and the other doesn't on the Wall.

![screen shot 2016-02-16 at 19 46 18](https://cloud.githubusercontent.com/assets/7934273/13074169/4ab6bef2-d4e6-11e5-917a-d4084a36d204.png)

**Comment by trang** [comment]
Since I've edited my message on the Wall to minify the link, I'm copying below the paragraph with the original link:

> Each issue on GitHub is basically like a forum thread. We create issues even for small problems though, not just "serious" ones. But we can label issues with "priority:high" for important topics. We have a few issues that were labeled this way, but it was somewhat arbitrary:
https://github.com/Tatoeba/tatoeba2/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%3Ahigh
Only a handful of people can label issues and you can see who exactly set the label.

@ckjpn, along with the screenshot it would be good if you could also copy the strings themselves in your comment. This way we can easily copy-paste to try it out on the dev website or on our local machines.

**Comment by ckjpn** [comment]
I've deleted my message. I wasn't really necessary, I should've tried in on dev.tatoeba.org instead.

This was the link:
https://github.com/Tatoeba/tatoeba2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug


I posted both linked on ...

https://dev.tatoeba.org/eng/wall/show_message/21753#message_21753

... and they both work there.

**Comment by ckjpn** [comment]
This same thing happened in a comment, too.

https://tatoeba.org/eng/sentences/show/3824550#comment-789103

Here the link:  https://www.google.co.jp/search?q="Most%20of%20it%27s%20in%20(French%7CGerman%7CSpanish%7CRussian%7CEnglish%7CDutch%7CJapanese%7CChinese%7CKorean)"

![screen shot 2016-02-17 at 12 25 07](https://cloud.githubusercontent.com/assets/7934273/13099038/c00700f0-d571-11e5-989e-0aeae55fec4e.png)

**Comment by trang** [comment]
This issue is fixed and can be tested on the dev website.

Note that the problem wasn't specific to private messages. It applies to all messages (comments on sentences, on the Wall, and private messages). The problem happened when 2 URL's had the same beginning. Example:

![url-issue](https://cloud.githubusercontent.com/assets/221850/14942242/f6e8ff7c-0fb6-11e6-9460-9ec821ce4ce3.png)

**Comment by ckjpn** [comment]
https://dev.tatoeba.org/eng/sentences/show/3841528#comment-562378

![screen shot 2016-05-02 at 02 34 04](https://cloud.githubusercontent.com/assets/7934273/14943246/7b2c094e-100e-11e6-8f5a-eb5acabc61d9.png)


https://tatoeba.org/eng/sentences/show/5098210#comment-835873
(It seems the comment has already been deleted, but I did take this screenshot before it was.)

![screen shot 2016-05-02 at 02 30 17](https://cloud.githubusercontent.com/assets/7934273/14943260/ce5905b8-100e-11e6-8c45-5ef5b4aa9d9e.png)

**Comment by trang** [comment]
@ckjpn thanks for testing. It should be fixed.
