### ISSUE TITLE
Possibility to reverse order of sentences in page that lists sentences of user

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#981]
By [maaster](https://tatoeba.org/eng/user/profile/maaster) on the [Wall](https://tatoeba.org/eng/wall/show_message/25237#message_25237):

> Pagination
It would be nice if the pagination was just inversely.
What I mean exactly: when I write the "book of my sentences", I always write on the page 1.
That's totally unlogical. The sentences locate always on a different page and a certain page contains always different sentences. If I want to look for something in a book, I know about where to search. The orderliness and permanence are pretty good things in many aspects.

**Comment by trang** [comment]
To clarify this issue, maaster is talking about this page: https://tatoeba.org/eng/sentences/of_user/maaster

The sentences in there are currently listed by date of modification:
Cf. https://github.com/Tatoeba/tatoeba2/blob/0582092c97c3bd471423f2cc9a15165e6225c9d0/app/controllers/sentences_controller.php#L1104-L1104

What we'll want to do here is give to the user the option to change the order of the sentences, so that they can order sentences:
- by date of creation
- by date of modification

Something similar to what we can find on the [lists](https://tatoeba.org/eng/sentences_lists/index) where we can order by name, by date created or by count.

By default, we can probably keep the current order, with the first sentence being the latest modified.

**Comment by ckjpn** [comment]
Another idea is to leave that page the way it is and change this page instead. 
Or, change both.

https://tatoeba.org/eng/activities/translate_sentences_of/maaster

This one is already sorted with the newest additions at the top.
You could possibly give people the option to reverse this order.

**Comment by theblindspring** [comment]
I will work on this
