### ISSUE TITLE
Import CK’s native speakers list

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#983]
I think we should import [CK’s native speakers list](http://a4esl.org/temporary/tatoeba/native.html) into tatoeba.org. It feels like something that should’ve been done long ago so I was wondering if it’s just that nobody took care of it already, or that there are objections. I don’t feel like editing everyone’s profile without their consent is very great, but there is huge benefit for the community (it becomes easier to know who speaks what language, the advanced search option “only from self-proclaimed natives” becomes useful…).

**Comment by trang** [comment]
This wasn't done yet because it requires to extend the user languages feature.

I personally think we should be transparent and let users to know when a language level was defined by the user themselves, or by another user (in this case CK). As you've mentioned it wouldn't be great to edit users profiles without their consent.

There is a field called `by_user_id` in the `users_languages` table. This field is currently not used (or well, it is, but it is set to be equal to `of_user_id`). But this is meant for situation like we have here, where a user (CK) is evaluating the language level of another user.

When we import CK's native speakers list, we should use this `by_user_id` field and set it to CK's user_id.

This means that for some users, there may be 2 evaluations for the same language. So we would need to figure out how to display this on the profile page.

**Comment by ckjpn** [comment]
Note that I don't evaluate a member's level on my list at http://bit.ly/nativespeakers.
This list is only focused on identifying native speakers.

I've only added names to that list as people have told me what their native languages are, or if they have had it listed in their profiles.  

I do, however, choose to only list one language per user, so if a member claims more than one native language, I write back to clarify which is their dominate language.  I omit members from my list who can't decide which their stronger language is or won't tell me which one is.  For my purposes, I'd rather lose a few good sentences than pollute my projects with sentences by trolls or people who think their level is better than it is. The main purpose of my list is to help me choose sentences that are less likely to have errors.

I've been maintaining my list for a long time, so my list includes members who have not come back to the Tatoeba Project. I used to often write new members and specifically ask them what their native languages were.  However, now I just harvest that data from user_languages.tar.bz2.  Before I add new members to my list, I do filter out all the members claiming more than one native language on this list, unless one is a constructed language.

http://bit.ly/nativespeakers
Usernames Identified as Native Speakers = 3923
Last Update: 01/16/2016 22:53:54

On the last update with sentence counts, about 30% of these native speakers had never contributed a sentence.  In the future, I may start deleting such names from my list, since they aren't really necessary for me.  Up until I started harvesting names from user_languages.tar.bz2, 100% of the names on my list had contributed sentences in their own native languages.

**Comment by ckjpn** [comment]
BTW, if you are going to harvest my list, it would be easy to do.
Just list the source of the page and you'll find a tab-delimited list.
All you would need it the first 2 items in each JavaScript data statement.

**Comment by ckjpn** [comment]
I made this list that compares "users_languages" with "bit.ly/nativespeakers".

http://bit.ly/tatoebacontributions

I primarily did this to help someone who posted something on the Wall, but then realized it also might be helpful for this discussion.

**Comment by ckjpn** [comment]
I can easily understand why you may not want to do the following, since it may not be considered a good idea to link to offsite URLs.

Perhaps you would consider adding a link to http://a4esl.org/temporary/tatoeba/native.html on the right side of https://tatoeba.org/eng/stats/native_speakers.  It would likely be something that would be useful to many people who don't already know about it.

The link:
http://a4esl.org/temporary/tatoeba/native.html
The clickable text:
Tatoeba.org Native Speakers

![screen shot 2016-02-10 at 16 06 03](https://cloud.githubusercontent.com/assets/7934273/12940950/38611286-d011-11e5-86b3-fd405aae590f.png)

**Comment by jiru** [comment]
So since CK’s list is not about CK evaluating others’ native language, but natives self-proclaiming their mother tongue, I suggest we just import the list as “self-proclaimed native level”.

I think we should as well notify the concerned users about the change, but I’m afraid some of them will not understand the message if it’s in English. If we decide to translate it systematically, that would require translating into 60 languages according to CK’s page, which likely include languages we don’t have translators for. @ckjpn How did you deal with this problem? Did you always asked users in English, or have you been helped by interprets?

**Comment by ckjpn** [comment]
I write them a message in English.

The following is what I usually send, unless they have 2 languages they claim as native languages. In that case, I ask which one is their stronger language.

>What is your native language?
>
>I want to put your username on the following page.
>
>Tatoeba.org Native Speakers 
>http://bit.ly/nativespeakers
>
>Maybe you want to add this information your profile page, too.  

I haven't yet uploaded the most recent version of my page, so before you import the data, if you are planning to, let me know.  I can also email the list to you, if you like as tab-delimited data.  (Username + Tab + Native Language)

**Comment by ckjpn** [comment]
updated:
http://a4esl.org/temporary/tatoeba/native.html

Make sure that the updated message is after this, so you're not getting a cached version.

Last Update: 03/12/2016 22:07:18

You can list the source.
(native languge + username + total native contributions + status + new since last updated)

"ara	alanood	741	user	0",
"ara	Safa_Alfulaij	657	user	107",

**Comment by ckjpn** [comment]
To make things clear, this is an example of replies that I get.

This came from a new member who has both Spanish and German listed as native languages.

==== the reply ====

My native language is Spanish but I can read and write in German.

CK escribió:
> What is your native language? (Which is your stronger
> language?)
> 
> I want to put your username on the following page.
> 
> Tatoeba.org Native Speakers 
> http://bit.ly/nativespeakers
> 
> Maybe you want to add this information your profile page,
> too.

**Comment by ckjpn** [comment]
I can send you my complete list if you want it.

It includes ...
* the native languages for some previous members who haven't yet added it into the field TRANG created.
* a person's "real" native language, when they have declared more than one, if they sent me back a message with this information when I asked for it.
* many members who haven't actually made any sentence contributions yet. (Most of these are already in the database, I think.)

It would likely help with the advanced search "native speaker" option.

An additional comment...

At this time, the 5-star native language setting is described something like "native-speaker level" and not "native speaker."  People who self-access themselves at such a level are perhaps over-confident.  Maybe something could be done about this, too.

**Comment by trang** [comment]
I think this issue can be closed actually.

The proper solution, in my opinion, would be to simply contact these users to ask if they could add the languages to their profile. If they don't do, then so be it. There could be reasons why they don't want to publish this information in Tatoeba and we shouldn't force this upon them.

From the private message sample, it seems it was already suggested to the users that they add the language to their Tatoeba profile. We could be more pushy about it and contact them again, but I think it's fine to just let it be.

Currently, around 88% of our sentences are owned by a user who has added languages to their profile. This looks good enough to me.

Below is the number of sentences that are orphan or owned by someone who has not added any language in their profile.
```
MariaDB [tatoeba]> select count(*) from sentences s where s.user_id not in (select by_user_id from users_languages) or s.user_id is null;
+----------+
| count(*) |
+----------+
|   887837 |
+----------+
1 row in set (4.91 sec)
````

**Comment by ckjpn** [comment]
It only matters if you want to get the native speakers who were early members of the project listed.

It's useful for me, since I filter-out non-native speakers of languages other than English.

I just thought that perhaps other developers who use the data might also want these names.

I have the usernames already myself, so it doesn't really matter much to me other than the fact we could be helping others.

**Comment by ckjpn** [comment]
I just did a count...

cks-native-speaker-list-not-on-tatoeba 2019-03-26.csv
= 1,149 usernames

cks-native-speaker-list-real-native-language-of-people-claiming-more-than-one-native-langauge 2019-03-26.csv
= 308 usernames

I didn't compare this with actual contributors, but when I was creating this list originally, I visited profile pages of the most prolific contributors first. If their native language wasn't listed in their profiles, I wrote them a private message asking them what their native language was.  This means that likely a high percentage of these usernames are also contributors.

**Comment by ckjpn** [comment]
Here is a list.  You can click to each member's profile to either verify or write them a PM.

http://tatoeba.byethost3.com/native-speaker-data-not-on-tatoeba.html

**Comment by jiru** [comment]
I agree with trang’s comment. Besides, I think we should focus on providing better ways than the nativeness to evaluate the quality of sentences.

**Comment by ckjpn** [comment]
I'm all for coming up with additional ways to easily be able to filter out bad sentences.  But in the meantime, this seems like the best way to do it.  If you have any suggestions of other methods I could possibly use, please write me an email.

For an educational website, it's better to eliminate as many errors as possible, even if it means losing a few good sentences.

**Comment by ckjpn** [comment]
If you are interested, these are the members on the first list, cks-native-speaker-list-not-on-tatoeba 2019-03-26.csv.

Sorted by the number of contributions in their native languages.

http://tatoeba.byethost3.com/stats-190323-additional-native-speakers.html

**Comment by trang** [comment]
Closing since we won't be importing the list.
