### ISSUE TITLE
Copy to clipboard ignores immediate changes to a sentence

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#988]
As I reported on the wall here https://tatoeba.org/ita/wall/show_message/25276#message_25276 ,
I think I found a bug related to the feature that allows you to copy a sentence into the clipboard: I add a sentence that i want to copy into the clipboard in order to add variants more quickly, I realize that I make a mistake and I fix it a few seconds after I added the sentence (like: I translate "hello" with "cioa" instead of "ciao", and I click on my translation to edit it right away without opening the translation as the main sentence and clicking on the edit button), I copy the sentence into the the clipboard, I paste it and I can see that the feature totally ignored my changes, since it copied the original sentence without any change

**Comment by trang** [comment]
@Guybrush88, since the copy to clipboard feature is still a beta feature and there is no plan on my side to move it out of beta, I personally  won't put much priority on fixing this. Anyone else is free to work on it though. But for me, it will be something I would fix when we decide that the feature needs to become stable.

Just for the record, I'm adding here your additional [comment on the Wall](https://tatoeba.org/eng/wall/show_message/25682#message_25682):

> If any kind of mistake is corrected, it totally eliminates any advantage one could get to add multiple translations to a single sentence from a smartphone or a tablet, since alternative versions might differ for just one word, so the "copy to clipboard" feature is really necessary for this purpose
