### ISSUE TITLE
Split "Random sentence" into two localization strings

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#990]
The same English string is reused in

https://github.com/Tatoeba/tatoeba2/tree/dev/app/views/elements/random_sentence_header.ctp#L39
https://github.com/Tatoeba/tatoeba2/tree/dev/app/views/elements/top_menu.ctp#L61

The point of such split is that the first string in some languages could be better translated as "Random sentence in language " since #randomLangChoice element follows it.

**Comment by achaitanyasai** [comment]
Can you please elaborate the issue, as far as I understand, the string in <pre><?php __('Random sentence'); ?></pre> is translated to <pre>"Random sentence in language"</pre> in some languages, is that correct ? <br>By the way I am sorry for the late (I was busy in my coarse project and I ended up installing tatoeba on my machine today.)

**Comment by lagleki** [comment]
One of the strings is used on the main page and is followed by  #randomLangChoice element. Thus it means "random sentence in [language]".

however, the string in the menu is really just "Random sentence" without any further specifications.

So I'd split it into two localization strings.

**Comment by achaitanyasai** [comment]
So you mean "Random sentence" in
https://github.com/Tatoeba/tatoeba2/tree/dev/app/views/elements/top_menu.ctp#L61 <br>
should be splitted into two localized strings by taking selected language into consideration ?

**Comment by lagleki** [comment]
2016-02-25 8:29 GMT+03:00 Chaitanya Sai Alaparthi <notifications@github.com>
:

> So you mean "Random sentence" in
>
> https://github.com/Tatoeba/tatoeba2/tree/dev/app/views/elements/top_menu.ctp#L61
>
> should be splitted into two localized strings by taking selected language
> into consideration ?
>

Split - yes.
And I suggest doing that for all languages. For Transifex one could just
translate the new string once again.
If for a given language the two strings have the same translation it's no
problem. Many strings are like that.

**Comment by achaitanyasai** [comment]
Yeah got it, thanks.

**Comment by jiru** [comment]
> Thus it means "random sentence in [language]".

I can see some problems with this.

We can’t just split into two different translatable strings "Random sentences in" and "[language]", because the language name needs to be [declined](https://en.wiki.tatoeba.org/articles/show/interface-translation#declensions) in some languages. Instead, we’re having strings like "[All sentences in {language}](https://www.transifex.com/tatoeba/tatoeba_website/translate/#fr/tatoebaResource/84377275)" that can be declined.

So we want to turn the translatable string "Random sentence" into "Random sentence in {language}"  with "{language}" being a placeholder for the dropdown. However, it’s not possible to decline a word if it’s inside a drop down.

Another problem is that it makes title to split into two lines in the English interface:
![screenshot-2018-6-19 tatoeba collection of sentences and translations](https://user-images.githubusercontent.com/5107734/41615106-fbf0cabc-73bf-11e8-984f-fba7ca6f590c.png)

**Comment by trang** [comment]
We'll keep the title of the random sentence block as it is for now. We can consider changing it when we decide to redesign the random sentence block.

**Comment by lagleki** [comment]
and i think i was misunderstood. i dont ask to change the english string. i ask to have 2 localization strings that for english might have the same value

**Comment by trang** [comment]
You were misunderstood indeed. Can you explain in which language the translation is different?

**Comment by trang** [comment]
Actually re-reading your initial comment, you said in some languages it could be better translated as "Random sentence in" because it is followed by the language dropdown.

The change you're requesting puts an implicit UI restriction: the dropdown *has to be* next to "Random sentence". If we ever decide to move this dropdown elsewhere, the title will just look weird in languages where the string is translated as "Random sentence in".

Unless there is a language where there is different translation, and this translation makes sense as a standalone (that is, without taking into account the position of the language dropdown), then we can split it. Otherwise, we shouldn't split it.

**Comment by lagleki** [comment]
> The change you're requesting puts an implicit UI restriction: the dropdown has to be next to "Random sentence".

Yes, like it's done now.
> If we ever decide to move this dropdown elsewhere, the title will just look weird in languages where the string is translated as "Random sentence in".

And it already looks weird in one language.

After all changing UI often leads to losing context and therefore a need in new localization strings arises.

**Comment by trang** [comment]
We're actually now in a situation where the dropdown is separated from the "Random sentence" string by a larger space and I don't think it would make sense to have the string translated as "Random sentence in", nor would it make sense in terms of UI pattern to move the dropdown next to the title.

I will close this.
