### ISSUE TITLE
Sometimes it would be useful to have exact dates and times rather than times listed as "6 hours ago".

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#993]
I wonder if it would be possible to include exact times in places like this, since there are often cases where people reading comments and comparing them to the logs, tags, or ratings may find it useful to know which came first.    This is not the first time that I've wished I knew the exact time sometime was added.

Would it add too much clutter to the page to include something like this?

6 hours ago (2016-02-02 09:33:58)

.... or maybe this way.

2016-02-02 09:33:58 (6 hours ago)

... or maybe this way.

2016-02-02 09:33:58 GMT

... or maybe this way.

2016-02-02 09:33:58 GMT (6 hours ago)

My assumption is that this could be labeled "effort: low", but I'm not sure.

The question is this, I think.
Would the added benefit outweigh the clutter such text adds to the page?

Possibly the part in parentheses could also be a mouseover.  This way it wouldn't really clutter the surface of the page.

2016-02-02 09:33:58 GMT (6 hours ago)

![screen shot 2016-02-02 at 22 59 45](https://cloud.githubusercontent.com/assets/7934273/12751683/eef543d4-ca01-11e5-9888-ca7858d0cbae.png)

**Comment by jiru** [comment]
If you look at how labels, milestones and assignations are displayed in Github issues, you’ll see that just don’t need to compare dates in the first place because the information is already displayed on a timeline. I think that’s be the proper way to solve this problem.

**Comment by ckjpn** [comment]
> If you look at how labels, milestones and assignations are displayed in Github issues, ....

I'm not sure what you mean by this. Could you include a URL?

Does this mean you think comments, tagging, etc. should be added to the log on the right side of the page?

**Comment by jiru** [comment]
> I'm not sure what you mean by this. Could you include a URL?

#993. You have a timeline that mixes comments, adding of a label, adding/removing of a milestone, and assignation.

> Does this mean you think comments, tagging, etc. should be added to the log on the right side of the page?

Currently there are two timelines on sentence pages. The comments on the left and the sentence log on the right. As a result, you need to go back and forth if you want to know what links the sentence had at the time a particular comment was posted, which is troublesome and unpractical, especially if the date is formatted like “X ago”. This would be much easier if there was a unique timeline combining comments and sentence log.

Your initial problem is that you’re unable to see whether the rating was added before of after what comment. You’re suggesting to solve it by displaying the date in canonical format, but it doesn’t solve the problem entirely. If a given rating was, say, added and removed multiple times, the date only gives you the last time it has been added, so you can’t go far into the past and compare with older comments. Which is why we need proper logging of ratings and proper display of this information that allow comparing with other events (a unique timeline). The same reasoning can be applied for tags, flag changes etc.

**Comment by ckjpn** [comment]
I was just trying to think of a way that it could be done perhaps quickly and easily without needing to change drastically how users are accustomed to using the website.

**Comment by thorn0** [comment]
The standard solution is to show the exact time in a tooltip:
![image](https://cloud.githubusercontent.com/assets/94334/12868260/7a129b72-cd0b-11e5-89cb-4801bb98e49b.png)

**Comment by trang** [comment]
> The standard solution is to show the exact time in a tooltip

Yes :)  You were faster than me in suggesting this. I wanted to give Reddit as an example ,but indeed GitHug does it too.
